src/http/Server.cpp

The header file for QMessageBox has been moved from "QtGui" to "QtWidgets"

update header file for Qt5

---

src/autotype/AutoTypeSelectDialog.cpp
src/autotype/AutoTypeSelectDialog.h
src/gui/entry/EditEntryWidget.cpp

This is rebased to a slightly newer point in history in upstream than this repo it seems. I can rebase it to your master if that's more convenient.
The point is simply to quit and save entry editing when hitting ctrl+return on the text area for notes.

Save with ctrl return

---

src/gui/EditWidgetIcons.cpp
src/gui/EditWidgetIcons.h

* Replace favicon fetching using Google with fetching from the root of the website
* Follow up to 3 http redirects for the favicon
* Add download favicon from Google as fallback
#32

Fetch favicon from the root of the website and use Google as a fallback

---

src/main.cpp

for each database listed as a parameter read a line from stdin as the password.
the original KeePass could accept database passwords from stdin which mitigates exposing password via environment.
i originally submitted a version this change in https://github.com/keepassx/keepassx/pull/167, 02 Jun 16, after using it personally for a few months prior.  i use this daily with a frontend script that pulls passwords from kwallet.
my environment is openSUSE Leap 42.1 using KDE.
the scope of the change is very limited and the default behavior is preserved.  nowhere else do i find reference to stdin or cin so it should not affect other areas of the code.
- [x ] New feature (non-breaking change which adds functionality)
- [x ] My code follows the code style of this project.
- [x ] My change requires …

add command line option --pw-stdin to accept password from stdin

---

CMakeLists.txt
src/autotype/CMakeLists.txt
src/gui/MainWindow.cpp
src/http/Server.cpp

When compiling on Windows, the build fails for 2 motive:
* Autotype on Windows isn't implemented yet but Cmake tries to build its tests anyway
* keepassxhttp uses **netinet/in.h** header file for **sockaddr_in** struct. <br/>This file is not available on Windows, where instead the struct is defined in the **winsock2.h** header
on Windows:
* Building KeePassXR was broken due to keepassxhttp.
* Tests were broken due to Autotype.

Fix winsock and autotype error when compiling on Windows

---

utils/keepassx-kwallet

default an environment variable to provide search path
canonicalize database paths
requested in https://github.com/keepassxreboot/keepassx/pull/55
not much, really, but enough to discover the need to canonicalize.
openSUSE Linux Leap 42.1
since this is external to keepassx i cannot imagine it affects too much of anything
use absolute path to database file

search directory configured via environment

---

src/gui/SettingsWidget.cpp
src/http/HttpSettings.cpp
src/http/OptionDialog.cpp

Fixes some advanced HTTP settings not being remembered.
Fixes #34 
Manually tested whether the settings are remembered.
- :white_check_mark: Bug fix (non-breaking change which fixes an issue)
- …

Fix advanced HTTP settings (close #34)

---

src/core/Config.cpp
src/gui/MainWindow.cpp
src/gui/SettingsWidget.cpp
src/gui/SettingsWidgetSecurity.ui

This PR adds two security-related options: _Lock databases after minimizing to system tray_ and _Lock databases after minimizing to taskbar_.
The autolocking is suspended when GUI/MinimizeOnStartup is true (or to be more precise, _MainWindow::configuredMinimizeWindow()_ is left intact), as it wouldn't make much sense to lock the DB right after unlocking it.
It enables additional workflows for using this program, and is implemented in the original KeePass as well.
Manually tested all possible combinations of the following settings:
_GUI/MinimizeOnClose
GUI/MinimizeOnStartup
GUI/MinimizeToTray
security/lockdatabasetray
security/lockdatabaseminimize_
- New feature (non-breaking change which adds functionality)
- :white_check_mark: My code follows the code style of this project.
- …

Implement automatic locking when minimizing

---

CMakeLists.txt
src/CMakeLists.txt
src/autotype/AutoType.cpp
src/gui/DatabaseWidget.cpp
src/gui/DatabaseWidget.h
src/gui/DatabaseWidgetStateSync.cpp
src/gui/MainWindow.cpp
src/gui/MainWindow.h
src/gui/MainWindow.ui
src/gui/SearchWidget.cpp
src/gui/SearchWidget.h
src/gui/SearchWidget.ui
src/gui/group/GroupView.cpp
tests/gui/TestGui.cpp
tests/gui/TestGui.h

Moves the search bar from the database entry view to the toolbar. It is always visible and capable of making searches without an extra button click. The search options were moved into a drop down list on the search icon button. Pressing escape while focused on the search text clears the search. Closes #15.
Moving the search out of the database widget required some replumbing work in the way searches are conducted.
I also enabled the use of QT keywords like "emit", "slots", etc which make the code easier to read.
This was requested by the community and it also cleans up the UI significantly.
The testgui.cpp file was completely retooled to accomplish the following:
- Test the new search bar functionality
- Properly segregate test cases instead of them relying on the state left over from the …

Make search always visible (#15)

---

snapcraft.yaml

Add the packaging metadata to build the keepassxc snap
This allows the project to be installed and auto-updated in all the linux distributions that support snaps.
It is secure, simple, self-contained, and allows to have our own release schedule independent from the one of the distributions. It also provides four different channels, from edge to stable, so early adopters can easily help testing the recent changes, leading to a better release. 
I build it and ran it in an ubuntu xenial kvm.
I created a new database and added some secrets to it.
I've been using daily a similar snap for keepassx for a couple of months.
- :white_check_mark: : New feature (non-breaking change which adds functionality)
- …

Add the packaging metadata to build the keepassxc snap

---

src/gui/DatabaseOpenWidget.cpp
src/gui/MainWindow.cpp
src/gui/MainWindow.h
src/gui/SettingsWidget.cpp
src/gui/SettingsWidget.h
src/gui/SettingsWidgetGeneral.ui
src/main.cpp

This pull request resolves issues #105 and #64.
When the option to minimize KeePassXC at startup is enabled, the unlock dialog is no longer shown. Instead, the application is directly minimized to the tray or task bar (depending on whether _"Hide window to system tray when minimized"_ is enabled or not). In accordance with the new behavior, the setting _"Open previous databases on startup"_ was reworded to _"**Load** previous databases on startup"_.
The window also doesn't inadvertently hide anymore every time after unlocking a database when _"Minimize window at application startup"_ is enabled. This setting now only applies at application startup.
Furthermore, the four different settings concerning minimization and the system tray were decoupled. _"Minimize window at application …

Fix minimize at startup and decouple various tray and minimization options

---

src/autotype/test/CMakeLists.txt
src/autotype/xcb/CMakeLists.txt

When building KeePassXC for openSUSE in the open build service the build fails because of missing  with  undefined reference to AutoTypeExecutor::execDelay similar to https://dev.keepassx.org/issues/389 
Add the keepassx_core to the autotype plugin and its testcase.
Build a package for openSUSE 
https://build.opensuse.org/package/show/home:greenbasilisk:keepassxc/keepassxc
See build log, for example, 
https://build.opensuse.org/build/home:greenbasilisk:keepassxc/openSUSE_Leap_42.2/x86_64/keepassxc/_log
- :white_check_mark: Bug fix (non-breaking change which fixes an issue)
- …

Fix build issue for openSuse

---

utils/entropy-meter.cpp

Building on 64-bit Windows gets to 99% and fails on this particular file due to the `stdafx.h` inclusion.
The macro in `entropy-meter.cpp` is different than `src/zxcvbn/zxcvbn.cpp`.
After copying the macro from `zxcvbn.cpp` and rebuilding, the Windows build succeeded.

Fix build for 64-bit Windows

---

src/gui/DatabaseWidget.cpp
src/gui/DatabaseWidget.h
src/gui/SearchWidget.cpp
src/gui/SearchWidget.h
tests/gui/TestGui.cpp

Just a fix to #131, originally by @knu 
This improves the UI of the search edit.
It was originally submitted as https://github.com/keepassx/keepassx/pull/74 and successfully merged, but the functionality got lost as the search UI was revamped in KeePassXC.
I want the Search UI to work without bothering with the focus.
- The copy action (Control+C) when no text is selected copies the password of the current entry.  This should be reasonable when Control+B copies the username.
- Down at EOL moves the focus to the entry view.  Enter and Tab should do that, but it would be handy for user to be able to get to the third entry by hitting Down three times.
Test case is included in this PR.
- :white_check_mark: New …

Improve UI of the search edit (resurrecting 5c7c7f54) 

---

src/zxcvbn/zxcvbn.cpp
src/zxcvbn/zxcvbn.h

Entropy estimator, zxcvbn, is written in C and conversions are somewhat "obsolete".
When compiling some warnings about old-style C conversions shows up. 
While these warnings are not symptoms of wrongness, better overall quality is obtained switching to a C++-style to avoid such messages
Manual tests have been performed through GUI password generator.
- …

Replace old-style C conversions in entropy estimator

---

src/gui/DatabaseWidget.cpp

There is a missing space is those error messages.
Open 2 times the same database. Make a change in one tab, do not save. Lock from the other tab, and choose to save anyway. The error message should appear.
:white_check_mark: Bug fix

Add missing space in messages.

---

CMakeLists.txt
src/autotype/test/AutoTypeTest.cpp
src/autotype/test/AutoTypeTest.h
src/autotype/xcb/AutoTypeXCB.cpp
src/autotype/xcb/AutoTypeXCB.h
src/core/Entry.cpp
src/crypto/Crypto.cpp
src/format/KeePass2XmlWriter.cpp
src/gui/DatabaseWidget.cpp
src/keys/FileKey.cpp
src/streams/qtiocompressor.cpp
tests/TestEntryModel.cpp

This is a rebase of the trivial changes in keepassx/keepassx#191 by @jsoref
The patch does not fix any bugs or adds any features. It only corrects a lot of spelling mistakes in variable names and code comments.
Code still compiles and runs.
- :negative_squared_cross_mark: My change …

KeePassX PR Migration: #191 Spelling

---

.github/ISSUE_TEMPLATE.md
.github/PULL_REQUEST_TEMPLATE.md

Changes the PR template so users are asked to remove non-applicable lines instead of having to change long emoji codes.
The previous PR template was quite cumbersome for authors of pull requests.
- :negative_squared_cross_mark: I have added tests to cover my changes.

Ask PR authors to remove lines that don't apply instead of changing emoji

---

src/keys/CompositeKey.cpp
src/keys/CompositeKey.h
tests/TestKeys.cpp
tests/TestKeys.h
utils/CMakeLists.txt
utils/kdbx-extract.cpp
utils/kdbx-merge.cpp

Update kdbx-extract to use :
* QCommandLineParser
* stdin to read the password/keyfile path
* Functions moved out of the utils directory.
After writing kdbx-merge, some required changes in kdbx-extract became apparent.
Locally for the kdbx-extract code, + added unit tests for the new function.
```bash
louib@Desktop $ utils/kdbx-extract 
Usage: utils/kdbx-extract [options] database
Extract and print a KeePassXC database file.
Options:
-h, --help  Displays this help.
Arguments:
database    path of the database to extract.
```
- ✅ I have read the **CONTRIBUTING** document. 
- ✅ My code follows the code style of this project. 
I had trouble when troubleshooting why my unit tests were failing. I tried using …

Fixes #156 : update kdbx-extract

---

src/gui/SearchWidget.ui

Switched to using the placeholder for the search widget instead of a label just beside it.
Make the searchWidget more compact, and makes its size not dependent on the local. Also added a margin to be consistent with the rest of the UI / toolbar.
Tested locally, with different locales to make sure the translation still occurs.
Before:
After:
- :white_check_mark: UI improvement
- :negative_squared_cross_mark: I have …

Use placeholder for search widget.

---

src/core/FilePath.cpp
src/gui/SearchWidget.cpp
src/gui/SearchWidget.h
src/gui/SearchWidget.ui
tests/gui/TestGui.cpp

* Pressing down arrow will always focus on entry view
* Pressing enter opens currently selected entry
* Pressing CTRL+F focuses and selects search text
Also fixes #163 
Originally inspired by @knu
While the PR #67 was a great improvement, my "Control+F and type a word" workflow had stopped working since then.
Most popular browsers and editors do this so you can always do a fresh search every time you invoke the "Find" action, so I think KeePassXC should, too.
The new behavior is covered by the new assertions added to the GUI test.
- :white_check_mark: New feature (non-breaking change which adds functionality)
- :negative_squared_cross_mark: Breaking change (fix or feature that would cause existing …

Enhanced search ui keypress actions

---

src/gui/MainWindow.ui

Changes context menu entry order so that commonly used actions are at the top.
Reordered the context menu.
The mostly commonly used actions should be at the top.
Built on a Ubuntu 16.04 workstation and hand tested the context menu

Adjusted order of entry's context menu

---

CMakeLists.txt
README.md
src/http/HttpSettings.cpp
src/http/HttpSettings.h
src/http/OptionDialog.cpp
src/http/OptionDialog.ui
src/http/Server.cpp

This pull request resolves #147. Although KeePassHTTP is still a weak protocol and its main flaws remain, this implementation should be safe enough for releasing it as part of KeePassXC.
KeePassXC strictly limits communication to the local loopback interface at 127.0.0.1. This address is hardcoded and cannot be changed. The plugin is now also disabled by default at runtime and needs to be explicitly enabled before KeePassXC listens to any requests from PassIFox or chromeIPass.
**Additional changes in this PR:**
- Warn user when trying to bind to a port below 1024 and fall back to default port
- Update heavily outdated README.md and add security notice about KeePassHTTP
- Only require libmicrohttpd build-time dependency when compiling with HTTP support.
There are still no unit tests for …

KeePassHTTP hotfix, resolves #147

---

src/gui/DatabaseWidget.cpp
src/gui/DatabaseWidget.h

The group and entry focus was lost when saving a new entry because of the autoreload feature.
I added the `restoreGroupEntryFocus`. While testing, I realized the entry focus was also lost when locking / unlocking the db (the group focus was preserved though), so I added that to the locking / unlocking also.
Fixes #144 
Unit tests + tested manually that the bug was fixed on MacOS.
I did **not** test with linux yet (I will!)

Preserve group/entry focus when replacing db.

---

src/gui/Application.cpp
src/gui/Application.h
src/gui/MainWindow.h

The database wasn't saved properly and lockfiles were not removed when receiving the signals SIGINT, SIGTERM, SIGQUIT or SIGHUP. This patch implements signal handling and performs a clean shutdown after receiving SIGINT SIGTERM or SIGQUIT and ignores SIGHUP.
Since this uses POSIX syscalls for signal and socket handling, there is no Windows implementation at the moment.
This resolves issue #169.
This patch makes sure the database is properly saved when closing KeePassXC using Ctrl+C on the terminal or when logging out of the desktop session. It also removes the lock file and therefore prevents cluttering the file system.
For testing a clean shutdown, a SIGINT was sent to the application via Ctrl+C and killall -INT keepassxc. When there were unsaved changes, KeePassXC asked the user whether …

Implement clean shutdown after receiving Unix signals, resolves #169

---

src/gui/SearchWidget.cpp
tests/gui/TestGui.cpp

This allows for quitting search by pressing escape in the main window.
Everybody loves keyboard shortcuts, but there's no equivalent for the clear icon.
The updated GUI test case.

Pressing escape quits search

---

src/format/KeePass2XmlReader.cpp

This is cherry-pick of commit https://github.com/keepassx/keepassx/commit/8cd0c8555413a6bdf4b6603211cf3b930a1036a0 in KeePassX which fixes a compilation error with Qt 5.8.
This pull request resolves #195.
All tests pass, code still compiles.

Fix compilation error with Qt 5.8, resolves #195

---

src/core/Entry.cpp
src/core/Entry.h
src/gui/DatabaseWidget.cpp
src/gui/MainWindow.cpp
tests/gui/TestGui.cpp

When in search mode you can now clone entries! This fixes #214. Thank you to @datamaan for the suggestion.
Cloned entries also now get " - Clone" appended to their title. This does not occur when cloning a group.
Tested manually and via unit tests.

Clone an entry when in search mode

---

src/autotype/mac/AutoTypeMac.cpp

Global Autotype on MacOS doesn't work in Google Chrome, because the frontmost window title is empty.
Fixes: https://github.com/keepassxreboot/keepassxc/issues/212

MacOS: Fix Global Autotype in Google Chrome.

---

src/gui/PasswordGeneratorWidget.cpp

The presence of at least 1 character class was not verified before generating a new password, resulting in the following line https://github.com/keepassxreboot/keepassxc/blob/develop/src/core/PasswordGenerator.cpp#L52 crashing the program.
Note that the validity was checked when calling `PasswordGeneratorWidget::regeneratePassword`, but was not checked when calling `PasswordGeneratorWidget::generatePassword`. The `Generate` button is now disabled if the generator is in an invalid state.
Even though now we should never call `PasswordGeneratorWidget::generatePassword` with an invalid password generator, I added the `isValid()` verification for robustness and for consistency with `regeneratePassword`.
Fixes #199
Unit tests + manual tests (on MacOs).
Generate button is enabled when at least 1 …

Fixes #199 : Disable buttonGenerate when no classes.

---

src/gui/entry/EditEntryWidget.cpp
src/gui/entry/EditEntryWidgetMain.ui

Small change to reuse the `password-generator` button in the edit view.
Unit tests + manual tests.
Before:
After:
- ✅ UI improvement

Reuse password generator icon.

---

src/gui/PasswordGeneratorWidget.cpp
src/gui/PasswordGeneratorWidget.ui

This resolves issue #228.
The password entropy and strength labels below the password generator field are sized dynamically to be 80% of the default font size. On some platforms this lead to illegibly small text. This patch limits the minimum font size to 8pt. If the resulting font size would be smaller, no font size changes are applied.
Tested on KDE: no visible change.
Tested on Windows: labels have a readable font size now.
Before:
After:

Don't make font size of password strength labels smaller than 8pt, resolves #228

---

src/gui/PasswordGeneratorWidget.ui

Resolves issue #192.
On KDE, there was never a visible difference, but tested it on Windows and buttons have the same size now.
Before:
After:

Use consistent button min-heights, resolves #192

---

src/gui/DatabaseWidget.cpp

When the user selects to open a `cmd://` URL, prompt them to ask, "Do you really want to execute the following command?"
(Does not have a "don't ask me anymore" option.)
Fixes #51.
Not having worked with Qt (ever) or C++ (much) in the past, I copied the code from the `DatabaseWidget::deleteEntries` method to prompt the user and adjusted it appropriately. Looking at an example on the Qt website, I realized you could insert HTML into the text for message boxes. I wasn't sure whether to use `<br><br>`, `<br /><br />`, or `<p>` to produce the linebreak effect, or whether I should just not attempt that at all and instead should embed it into the question (e.g. `"Are you sure you want to run the command '%1'?"`). I couldn't see any other instances of `<br/?>` or `<p>` in the code.
I created two …

Prompt the user before executing a command in a cmd:// URL

---

src/core/Entry.cpp
src/core/EntryAttributes.cpp
src/core/EntryAttributes.h
src/gui/DatabaseWidget.cpp
src/gui/entry/EditEntryWidget.cpp

Allow user to store preference when asked whether to execute command, resolves #51.
This patch adds the missing checkbox to store the user's decision whether to execute a command or not.
The preference is stored in the form of an extended attribute. When the URL of an entry changes, the attribute gets removed, so the user will be asked again next time.
I performed many manual runs in different configuration contexts: creating a new entry, editing an entry, storing yes editing the entry, storing no, editing again and so on.
Considering that we have …

Add 'Remember my choice' checkbox, resolves #51

---

src/core/EntrySearcher.cpp
src/core/EntrySearcher.h
src/gui/DatabaseWidget.cpp

This is a rebased version of KeePassX pull request keepassx/keepassx#190 by @jsoref.
It allows to not only search for entries in the database, but also for their group names.
Additionally, I removed two assertions which lead to crashes when the search result was empty and KeePassXC was compiled in Debug mode.
Searching for group names of entries works as expected. All existing unit tests pass.

KeePassX PR Migration: #190 Search for Group Names

---

src/crypto/SymmetricCipher.cpp
src/crypto/SymmetricCipher.h
src/format/KeePass2.h
src/format/KeePass2Reader.cpp
src/format/KeePass2Writer.cpp
src/gui/DatabaseSettingsWidget.cpp
src/gui/DatabaseSettingsWidget.ui
tests/TestSymmetricCipher.cpp
tests/TestSymmetricCipher.h

This is a rebased version of KeePassX pull request keepassx/keepassx#122 by @drizzt which adds Twofish cipher support for encrypting the password database. Additionally to what was already in the original pull request, I also added unit tests.
- Code compiles and runs
- Encrypting and decrypting databases with Twofish works as expected
- Existing unit tests pass
- New unit tests which compare encryption/decryption results with a small subset of the published NIST MCT KAT pass as well

KeePassX PR Migration: #122 Twofish

---

src/gui/DatabaseTabWidget.cpp

When choosing to lock the database after it was modified but before is was saved, the `*` would remain indicating that changes were still pending. Calling `databaseSaved` clears the asterisk.
Unit tests + manual testing.
- ✅ Bug fix
- ✅ I have read the **CONTRIBUTING** document. 
- ✅ My code follows the code style of this project. 

Fixes database modified after discard

---

src/gui/DatabaseTabWidget.cpp
src/gui/DatabaseWidget.cpp
src/gui/entry/EditEntryWidget.cpp
src/http/Service.cpp

This PR resolves #236
Although not a security issue, unescaped HTML contents in user-defined strings can have funny effects when displayed inside a MessageBox. This PR properly escapes HTML where necessary.
.toHtmlEscaped() was added to all user-defined strings which are shown in MessageBoxes.
Tested to move groups and entries with HTML inside the title to the trash and then delete them "for good". As intended, HTML tags are now displayed as raw text and not interpreted anymore.

Properly HTML-escape strings with user-defined contents in message boxes

---

src/autotype/AutoType.cpp
src/autotype/xcb/AutoTypeXCB.cpp

Fixes #256 
Manually with autotype.

Allow space keyword in autotype sequence

---

src/core/Entry.cpp
tests/TestAutoType.cpp

Edit `resolvePlaceholder` to load custom-attribute in the `{S:Custom}` format
Fix #218 
In the autotype sequence you can call custom attribute with `{S:Custom}` like stated in the [KeePass](http://keepass.info/help/base/placeholders.html) interface. 
The new tests for Custom attribute autotype are 100% pass

Fix autotype custom-attribute placeholder

---

AppImage-Recipe.sh
src/core/FilePath.cpp

This PR resolves #194.
Qt also looks in the program's working directory for icons, but apparently, the Ubuntu Unity system tray doesn't, resulting in missing tray icons
Tested on Ubuntu 16.04 with Unity, tray icon now shows up.

Don't try to use theme icons for the system tray, resolves #194

---

AppImage-Recipe.sh
src/core/FilePath.cpp

This PR provides an alternative fix to #194 and reverts the previous solution in #273.
After some more research, I found that unsetting the `XDG_DATA_DIRS` environment variable in our AppImage startup script also resolves the tray icon issue (see https://github.com/probonopd/AppImageKit/issues/351). This allows us to continue using relative icon paths within the application.
Tested on Arch Linux (KDE Plasma 5.9) and Ubuntu 16.04 (Unity). Works fine in both.

Unset XDG_DATA_DIRS env as an alternative fix to #194

---

CMakeLists.txt
src/CMakeLists.txt
src/gui/MainWindow.cpp

This resolves issue #271
Ubuntu Unity unregisters global menus when the connected window is hidden. This leaves KeePassXC without a working menu bar when the the window is restored from the system tray.
This patch manually sends a D-Bus call to re-register the window. Unfortunately, it adds D-Bus as a direct dependency on Linux, but I couldn't find another working solution except for disabling native menus altogether.
I compiled an AppImage with Qt 5.8 and tested it in an Ubuntu 16.04 virtual machine and on Arch with KDE Plasma 5.9. Plasma 5.9 has never had issues to begin with (because windows weren't automatically unregistered), but it also doesn't show duplicate menus or any other weird behavior after this patch.
- ✅ I have read …

Re-register global D-Bus menu when restoring window from tray

---

share/CMakeLists.txt

This patch resolves #281 by excluding the `share/icons/application/*/{status,actions}` directories from `make install`.
Before this patch, those directories were always installed, although empty.
I ran `make install`, directories are properly excluded now.

Don't install empty icon directories, resolves #281

---

src/gui/SettingsWidget.cpp

Not all the systray settings were hidden on MacOs.
Unit tests.
Before
After
- ✅ Bug fix

Fix : systray option visible mac

---

src/gui/MainWindow.cpp
src/gui/MainWindow.h
src/gui/MainWindow.ui
src/gui/WelcomeWidget.cpp
src/gui/WelcomeWidget.h
src/gui/WelcomeWidget.ui

Welcome Screen redesign
A nicer welcome screen for new users
Manually on Linux (should work no problem on other platforms)

Welcome screen redesign

---

src/gui/DatabaseTabWidget.cpp
src/gui/MainWindow.cpp
src/main.cpp

This PR resolves #304.
When _"Hide window to system tray when minimized"_ and _"Minimize window at application startup"_ are enabled, restoring the window from the tray causes compositing problems on Ubuntu Unity/Compiz.
Most of those glitches have already been solved as a result of #276 which properly sets the minimize flag on the window before hiding it, but that didn't apply at startup time.
With this fix, KeePassXC doesn't try to show the main window anymore, only to minimize it right after if both options are set. This not only gets rid of artifacts on Ubuntu, but also prevents the window from flashing up for a split second after starting KeePassXC.
I also smuggled another small fix into this PR which solves a timing issues which sometimes causes the window to not be shown properly …

Hotfix #304: Compositing glitches when restoring from tray

---

.gitattributes

Adding github-linguist language hints so that the main language displayed is C++ instead of C.
Stats before
```
74.62%  C
23.69%  C++
1.12%   CMake
0.45%   Shell
0.05%   Objective-C++
0.05%   Python
0.02%   Objective-C
```
Stats now
```
98.33%  C++
1.12%   CMake
0.45%   Shell
0.05%   Objective-C++
0.05%   Python
```

Add github-linguist language hints.

---

src/gui/DatabaseTabWidget.cpp

This PR resolves #285.
When the user clicks the button to create a new database, they are asked immediately where to save the database. This resolves issues with the autosave feature in combination with unnamed databases. It also avoids general confusion when users are not aware that their database exists solely in memory until they explicitly save it.
When saving to a location fails, the save dialog is shown again, so the user can choose a different location. When the user clicks the "Cancel" button, the whole database creation process is canceled.
I also changed the default database file name to "Passwords.kdbx" to make it easier to understand for novice users.
I tested to save to multiple different locations (writable and non-writable) on Arch Linux.
- ✅ Bug fix (non-breaking change …

Ask for save location when creating new database

---

src/gui/AboutDialog.ui
src/gui/ChangeMasterKeyWidget.ui
src/gui/DatabaseOpenWidget.cpp
src/gui/DatabaseOpenWidget.ui
src/gui/DatabaseSettingsWidget.ui
src/gui/EditWidget.ui
src/gui/EditWidgetIcons.ui
src/gui/EditWidgetProperties.ui
src/gui/PasswordGeneratorWidget.ui
src/gui/entry/EditEntryWidget.cpp
src/gui/entry/EditEntryWidgetAdvanced.ui
src/gui/entry/EditEntryWidgetAutoType.ui
src/gui/entry/EditEntryWidgetHistory.ui
src/gui/entry/EditEntryWidgetMain.ui
src/http/OptionDialog.ui

This PR fixes major visual glitches, most of them occurring on OS X (but partly also on other platforms). It therefore fixes almost all issues described in #295. The error message bug, however, has not been fixed, because inline messages have not been merged into the current release branch.
The KeePassXC interface contains many minor layout inaccuracies and some major visual bugs. Most of these issues appear on OS X, because Qt apparently cannot emulate native Mac widgets too well.
All changes have been tested on Mac OS X 10.12 Sierra. Some of the fixes require adding arbitrary paddings to widgets and layouts. **It would therefore be good if someone could test this on other OS X versions before this patch gets merged.**
The changes were also verified on Arch Linux with KDE Plasma 5.9 …

Fix major visual glitches

---

src/gui/ChangeMasterKeyWidget.cpp
src/gui/ChangeMasterKeyWidget.h
src/gui/DatabaseTabWidget.cpp
src/gui/DatabaseWidget.cpp
src/gui/DatabaseWidget.h

This is a follow-up pull request to #302 in order to fix the last remaining point of criticism about that PR.
This patch disables the *Cancel* button on the ChangeMasterKeyWidget when setting an initial password on a new database.

Follow-up to #302: Disable 'Cancel' button when setting initial database password

---

src/main.cpp

This PR resolves #221
This PR enables automatic HiDPI scaling when compiled with Qt >= 5.6.0. This fixes or at least mitigates #221. We couldn't find a perfect solution for Windows 10 yet, but this fix at least resolves the biggest problems. It also appears to fix HiDPI problems on Fedora.
I can't test it myself due to the lack of a HiDPI monitor, so I can only rely on reports by affected users.

Enable High DPI scaling, resolves #221

---

.gitignore
src/gui/EditWidgetIcons.cpp
src/gui/EditWidgetIcons.h
src/http/Service.cpp

This PR resolves #306.
I replaced the former favicon download code with a new implementation based on our patched version of the QHttp library (see #317).
QNetworkAccessManager causes unnecessary Wifi network scans every 10 seconds (see https://bugreports.qt.io/browse/QTBUG-40332). This results in very poor network performance (and probably also increased battery drain) on some platforms (e.g. OS X) when using a PC or laptop with a Wifi connection.
I tested the changes myself manually to make sure favicons can still be downloaded
- over plain HTTP
- over HTTPS
- with up to 3 redirects
- from Google as fallback if no favicon.ico file could be found (e.g. when there is a favicon.png like on keepassxc.org)
If the server cannot be found, the download button is re-enabled after a timeout of 5 …

Hotfix #306: wifi network polling

---

src/gui/entry/EntryView.cpp

This PR resolves #319
When searching for entries, a QSortFilterProxyModel is used for showing and hiding the *Group* column. However, sorting was still done on the original model which resulted in arbitrary sort order. This patch sorts the proxy model instead of the data model and only does one extra sort on the data afterwards to update the column headers.
Tested it on a large database with lots of passwords and groups. Sort order before, while and after searching is as intended now.

Fix sort order when searching

---

src/core/Config.cpp

This PR let KeePassXC load a different configuration file when loaded from a Debug build
This is useful if you need to change KeePassXC configuration for testing some feature when developing.
You don't want to mess up your own KeePassXC configuration or revert your configuration back after the tests.
When KeePassXC is compiled with Debug option it will load keepassxc_debug.ini configuration, if it's a Release instead it will load keepassxc.ini
Manually by opening 2 different KeePassXC build (one Release and one Debug) and setting 2 different configuration. …

Load a different config when debug option enabled

---

release-tool

This is a little fix to the release script to make sure the DIGEST file always contains only the file name of the hashed file, not any other path prefixes.
DIGEST files are delivered together with the binary releases in the same directory. No path names should be added when `release-tool sign` was called from a parent directory.

Only use relative path in DIGEST file

---

src/main.cpp

This reverts commit 188cac34ce6366ec37fea4c5c0a138cd6bfb1215.
Resolves #323 
HiDPI scaling remains an issue, but setting `Qt::AA_EnableHighDpiScaling` only fixes it on some platforms while creating new issues on others. It is therefore a non-fix. 

Revert "Enable High DPI scaling", resolves #323

---

share/translations/keepassx_en.ts
src/http/OptionDialog.ui
src/main.cpp

Improve the clarity of various strings in the HTTP menu and a command-line parameter.
This modifies the text in various strings in the HTTP settings dialog, for the purposes of clarity (and grammar), and also in one of the command-line positional arguments.
As discussed in IRC, "filename(s)" and "database(s)" means Transifex requires a certain number of parentheses in any translations, which makes it hard to translate for Italian where (I think) "database" and "databases" are the same word. In addition there was a typo in one of the HTTP setting strings ("only, if you know") which led me to go check the clarity of a bunch of strings in that dialog (and rewrite them).
I built the executable with the updated translations (after running the commands from the `share/translations/update.sh` …

Update text in HTTP settings and a hard-to-translate command line hint

---

src/gui/DatabaseWidget.cpp

This patch removes an unnecessary error message when trying to reload a locked database.
This was especially annoying when syncing a database across multiple machines, because every time the file was updated, this error popped up.
However, this fix is merely a band-aid as it only removes the error message. When we are refactoring the database open/tab widgets, we should avoid monitoring locked databases in the first place. There is no point in watching for changes in a locked database. However, that is out of scope for this fix. Implementing that with the current code base is a non-trivial task, since we don't have a well encapsulated and self-contained database object which keeps track of the current status of the database. Instead, responsibilities are scattered all over the placed …

Don't show error message when trying to reload a locked database

---

src/gui/DatabaseTabWidget.cpp

Change role of "Open read-only" button so Qt doesn't place it between the "Yes" and "No" button.
On Windows and Linux/KDE, the "Open read-only" button is correctly placed to the right of the "Yes" and "No" buttons. On OS X, it's to the left.

Assign role 'NoRole' instead of 'Accept' to not mess with button order

---

src/gui/EditWidgetIcons.cpp

Fixes #356 
All entries using the deleted custom icon are reset to the default entry or group icon. Also fixes the case when only the current entry has the icon, the default icon is selected after deletion instead of the first custom icon.
Fixes an annoying aspect of having many custom icons.
Tested manually.

Delete a custom icon with multiple entries using it

---

src/gui/MainWindow.cpp

This patch enables the unified toolbar on Mac OS X for better visual integration.
I've run the patch on OS X 10.12 Sierra, looks good.
Before:
After:

Use unified toolbar on OS X

---

src/gui/MainWindow.cpp
src/gui/MainWindow.h

This fixes an issue on X11 where Alt-F4 would not close the window, due
to toggleWindow() believing the window is inactive and trying to raise
it.  Avoid the problem by closing the window unconditionally.

closeEvent() should always hide the window, never raise it.

---

src/core/Tools.cpp
src/core/Tools.h

Use a discretionary access control list to deny PROCESS_QUERY_INFORMATION and PROCESS_VM_READ access rights without admin privileges.
Prevent memory dumps on windows
Windows 7 and Process Explorer
**Needs more testing**

Prevent memory dumps on windows.

---

CMakeLists.txt
src/CMakeLists.txt
src/gui/EditWidgetIcons.cpp
src/gui/EditWidgetIcons.h

* WITH_XC_AUTOTYPE defaults to ON
* WITH_XC_HTTP now wraps custom icon download code
* No networking libraries are included when WITH_XC_HTTP=OFF
Documentation on the wiki will be updated once merged.
Allows us to easily distribute an "OFFLINE" version of KeePassXC
Manually and running existing tests

Compile auto-type by default and encapsulate all networking code using WITH_XC_HTTP

---

src/gui/DatabaseWidget.cpp
src/gui/DatabaseWidget.h

Fixes crash when deleting in search mode.
The `EntryView` was trying to refresh itself after we deleted the entry from the recycle bin. The `EntryModel` was never removed from the `EntryView` used by the search. Now, after deleting an entry permanently, we refresh the `EntryView` used by the search so that it does not try to access the deallocated memory of a deleted database entry.
This also fixes a bug that we had where deleting an entry in search mode while the recycle bin was disabled would not update the `Search Results (x)` label of the search widget.
Fixes #369
Manual tests + tested locally.
- ✅ Bug fix

Fixes crash when deleting in search mode.

---

src/CMakeLists.txt
src/autotype/AutoType.cpp
src/core/Entry.cpp
src/core/Entry.h
src/core/EntrySearcher.cpp
src/gui/CloneDialog.cpp
src/gui/CloneDialog.h
src/gui/CloneDialog.ui
src/gui/DatabaseWidget.cpp
src/gui/DatabaseWidget.h
src/http/Service.cpp
tests/gui/TestGui.cpp

- Create popup for clone options
- Add ability to resolve references for title, username, password, url, notes, and uuid fields when using autotype, http, and/or copying
Allows references to be used across all fields for autotype, http, and copying
Resolves #75 
Created multiple clones of different entries
Tested http by removing the url from the original and having chromeIPass fill the appropriate data
Tested inline copy/paste by manually editing all supported fields and using the context menu to copy the values
Tested autotype similar to http by cloning a working entry and removing the association from the original
May/or may not be helpful but this shows the different states of the clone process …

Add feature to handle field references, resolves #75

---

src/core/Entry.cpp
src/core/Entry.h
src/core/EntryAttributes.cpp
src/core/EntryAttributes.h
src/gui/entry/EntryModel.cpp

Highlight reference field in Database view instead of printing the full reference string
Printing the full reference field (`{REF:U@I:<UUID>`) in the database view it's not very user friendly.
Searching also will show reference string instead of the searched content.
This PR shows reference field clearly without hiding the referenced content. 
Manually

Highlight reference field in Database view

---

src/gui/entry/EditEntryWidget.cpp
src/gui/entry/EditEntryWidget.h
src/gui/entry/EditEntryWidgetAdvanced.ui
tests/TestEntryModel.cpp
tests/gui/TestGui.cpp

* Allow protected attributes to be hidden
* Entry area is resizable
Fixes #111 and fixes #45 
Attribute entry area was ugly and boring. It is now awesome (or at least slightly better)! The protected view is powered by the already existing protected attributes in the entry class.
Manual testing

Enhance attribute entry

---

tests/gui/TestGui.cpp

GUI tests were failing on my system due to some events not being processed in time. This patch adds `QApplication::processEvents()` after adding test entries and before trying to move them to the trash.

Force event processing after adding entries to prevent test failure

---

src/core/Config.cpp
src/core/Config.h
src/gui/MainWindow.cpp
src/gui/SettingsWidget.cpp
src/gui/SettingsWidgetGeneral.ui

This is related to https://github.com/keepassxreboot/keepassxc/issues/269, so that we are able to rule out config file permissions problems when troubleshooting settings issues.
Tested locally with a valid (sufficient permissions) and an invalid (insufficient permissions) default config file.

Adding warning messages when config access error.

---

src/gui/DatabaseTabWidget.cpp
src/gui/DatabaseTabWidget.h
src/gui/MainWindow.cpp

Add support for proxy icons in OSX, according to [OSX human interface guidelines](https://developer.apple.com/library/content/documentation/UserExperience/Conceptual/OSXHIGuidelines/WindowAppearanceBehavior.html#//apple_ref/doc/uid/20000957-CH33-SW1).

Add proxy icon to title bar in OSX

---

src/format/KeePass2XmlReader.cpp

When reading kdbx files generated by libkeepass-unicode, the `<Expires>` field for `<Entry><Times>...</Times></Entry>` can be short closed without a value as `<Expires/>`. This is properly treated as false on other implementations including original KeePass but KeePassX(C) only accepted the string values `True` and `False`.
Treat empty boolean strings as false in XML.
Not fail when encountering a simple XML formatting difference.
Tested using offending .kdbx file provided on IRC.

Treat empty booleans in XML as false

---

src/gui/MainWindow.cpp
src/gui/MainWindow.h

Instead of using hardcoded index, use clearer enum label 
Requested by @droidmonkey in https://github.com/keepassxreboot/keepassxc/pull/437#discussion_r108081959
Manually + Test + Travis

Clearer stackedWidget index using enum

---

src/http/Service.cpp

Fixed a couple of compiler warnings due to the lack of default statement on switch statements. 
```
keepassxreboot/keepassxc/src/http/Service.cpp:79:16: warning: 
enumeration value 'ImportMode' not handled in switch [-Wswitch]
switch(dbWidget->currentMode()) {
^
keepassxreboot/keepassxc/src/http/Service.cpp:96:16: warning: 
enumeration value 'ImportMode' not handled in switch [-Wswitch]
switch(dbWidget->currentMode()) {
^
```

Fix compiler warnings

---

src/gui/SearchWidget.cpp
src/gui/SearchWidget.ui
tests/gui/TestGui.cpp

* Move the search icon (with popup menu) and clear icon inside the line edit
* Move the search widget to the right-side of toolbar
This makes the toolbar less clutered, and the search widget has a more usual look.

More compact search widget

---

src/http/AccessControlDialog.cpp

closes #460 
Bring KeepassHTTP confirmation window to the foreground when the browser makes a request.

Bring KeepassHTTP confirmation window to the front

---

src/main.cpp

Fixes #468 
Tested with the "Load previous databases" option enabled and with/without databases passed as argument to `keepassxc`.
The issue when opening directly a `.kdbx` was not reproducible on Mac, since that use case is handled by the `QFileOpenEvent` at https://github.com/keepassxreboot/keepassxc/blob/develop/src/gui/Application.cpp#L104.

Prioritize explicitly specified databases.

---

src/autotype/AutoType.cpp

Implement support for braces in auto-type using {{} and {}}

Implement support for auto-type {{} and {}}

---

src/gui/MainWindow.cpp

closes #481, closes #482 
Set menu roles for application menu on macOS

Set menu roles for application menu on macOS

---

src/autotype/AutoTypeAction.cpp
src/autotype/mac/AutoTypeMac.cpp
src/autotype/mac/AutoTypeMac.h
src/autotype/windows/AutoTypeWindows.cpp
src/autotype/windows/AutoTypeWindows.h
src/autotype/xcb/AutoTypeXCB.cpp
src/autotype/xcb/AutoTypeXCB.h

closes #426 
This PR add support for the auto-type `{CLEARFIELD}` command.

Add auto-type {CLEARFIELD}

---

CMakeLists.txt

print_enabled_features() and print_disabled_features() are deprecated using last cmake (3.8.0)
This PR avoid the warning messages displayed when running cmake >= 3.8.0
Clean build of entire project with different options seems fine.

Substitute deprecated commands with feature_summary

---

share/translations/keepassx_en.ts
share/translations/keepassx_ru.ts
src/gui/MainWindow.cpp

Using the Russian localization of KeepassXC I noticed that the menu item "Database > Recent databases > **Clear history**" is not translated to Russian. I couldn't find that string nontranslated on Transiflex, it was just missing. I took a look at the code and found out that the string was just hardcoded (there was no call to `tr(...)`). So I added the call and added the string to keepassx_en.ts and keepassx_ru.ts.
Note, a new string was required to be added to keepassx_en.ts, therefore I couldn't just translate it on Transiflex. I believe I don't have the permission to upload a new base file for translations on Transiflex and I don't see the option to create a new string in the Transiflex web interface. So please make the appropriate arrangements with Transiflex using the TS files …

Moved a hardcoded English menu string to the string resources

---

src/core/Config.cpp
src/core/Group.cpp
src/gui/SettingsWidget.cpp
src/gui/SettingsWidgetGeneral.ui

Allow user to ignore group expansion.
https://github.com/keepassxreboot/keepassxc/issues/446
Locally + unit tests.

Ignore group expansion and other minor changes when marking database as dirty

---

src/gui/MainWindow.cpp

In #316 the shortcut for "New database" may be unchanged on some platforms. Specificially, if a platform has ```QKeySequence::New```, Ctrl+N will still be used. My patch fixes this by dropping the ```QKeySequence::New``` part.
See #513
Build and check the menu.
- My change requires a change to the documentation and I have updated it accordingly. (GUI changes only)
- I have added tests to cover my changes. (GUI changes only)

:bug: Really set the shortcut for "New database" to Ctrl+Shift+N

---

src/gui/csvImport/CsvImportWidget.cpp
src/gui/csvImport/CsvImportWidget.h
src/gui/csvImport/CsvImportWidget.ui

A checkbox let user choose field names from CSV first row, instead of an aseptic "Column n"
This should also close #458
A more cohesive fit with CSV column meaning was needed in order to make the right mapping between CSV fields and KXC DB fields
Manual tests

[CSV import window] add option to choose dropdown menu field names from CSV

---

src/core/PasswordGenerator.cpp
src/core/PasswordGenerator.h
src/gui/PasswordGeneratorWidget.cpp
src/gui/PasswordGeneratorWidget.ui

Resolve #343 
This adds support for extended ASCII character in the password generator, like KeePass.
Manually and with Travis

Add support for extended ASCII in password generator

---

share/translations/keepassx_en.ts
src/CMakeLists.txt
src/autotype/AutoType.cpp
src/core/Entry.cpp
src/core/Entry.h
src/gui/DatabaseWidget.cpp
src/gui/DatabaseWidget.h
src/gui/MainWindow.cpp
src/gui/MainWindow.ui
src/gui/SetupTotpDialog.cpp
src/gui/SetupTotpDialog.h
src/gui/SetupTotpDialog.ui
src/gui/TotpDialog.cpp
src/gui/TotpDialog.h
src/gui/TotpDialog.ui
src/totp/base32.cpp
src/totp/base32.h
src/totp/totp.cpp
src/totp/totp.h
tests/CMakeLists.txt
tests/TestTotp.cpp
tests/TestTotp.h
tests/gui/TestGui.cpp
tests/gui/TestGui.h

resolves #80
This PR add support for TOTP code generation (as described by [rfc6238](https://tools.ietf.org/html/rfc6238)) using KeepassXC.
This is a rework from the ground up of my [previous TOTP PR](https://github.com/keepassxreboot/keepassxc/pull/380). It has more features, tests and the code is a lot cleaner than before.
* GUI for easily setting up the TOTP of an entry
* Auto-Type with the `{TOTP}` tag
* Support for codes with 6 and 8 digits
* Custom time period support
* It supports reading and updating the format used by the 2 TOTP plugins listed on [Keepass plugins page](keepass.info/plugins.html) ([KeeOtp](http://keepass.info/plugins.html#keeotp) and [Tray TOTP](http://keepass.info/plugins.html#traytotp)) plus the [URI format](https://github.com/google/google-authenticator/wiki/Key …

Add TOTP support

---

src/autotype/xcb/AutoTypeXCB.cpp

Fixes #379. Adds the same minor delay behavior seen in autotype on Windows (25ms delay between char and key presses).

Added small delays to autotype on Linux

---

src/core/ScreenLockListenerMac.cpp
src/core/ScreenLockListenerMac.h
src/core/ScreenLockListenerWin.cpp
src/core/ScreenLockListenerWin.h

I was having a hard time compiling this on Mac. Looked at the doc and realized that the function's signature for `CFNotificationCenterAddObserver` was actually using `CFStringRef` instead of `CFNotificationName`. What I'm not  sure of is how others were able to compile this on Mac and not me...
This is the doc I used https://developer.apple.com/reference/corefoundation/1543316-cfnotificationcenteraddobserver?language=objc

Styling + CFNotificationName -> CFStringRef

---

.clang-format
src/gui/SearchWidget.cpp
src/gui/SearchWidget.h

Adding a `clang-format` file corresponding to the coding style of the project. Right now it's not hooked to anything, but it could be at some point (I think it can be integrated with `cmake`).
I don't think it would be a good idea to format the whole codebase, as it might cause some problems, for example when porting some keepassx changes to keepassxc, or when browsing the git history, but the style used for new code could be easily enforced with `clang-format`
I ran it on 2 files to show an example of the coding style being enforced.
```
clang-format -i -style=file src/gui/SearchWidget.*
```
@TheZ3ro @droidmonkey what do you guys think?
I feel like this would allow reviewers to concentrate on the feature instead of reviewing the coding style of the new code. …

Adding .clang-format file.

---

src/gui/MainWindow.cpp

Add the quit submenu to macOS tray icon and disable redundant toggle window action when clicking on the icon.
Local tests

Fix quit submenu on macOS tray icon

---

src/cli/List.cpp
src/core/Group.cpp
src/core/Group.h
tests/TestGroup.cpp
tests/TestGroup.h

Moved code from the List command to the Group class. Also removed the printing of the Root group, since it doesn't add any value to the listing.
It's easier to unit test this way.
CLI interface + new unit tests
```
$ ./src/cli/keepassxc-cli list ~/1.kdbx
SubGroup1/
[empty]
SubGroup2/
entry4
entry5
Recycle Bin/
entry1
entry2
```
```
$ ./src/cli/keepassxc-cli list ~/1.kdbx -u
SubGroup1/ e05b75cc7875a7b708f4aa38a247e42f
[empty]
SubGroup2/ f8bbae53ddb5148864a10b5b498db1b3
entry4 7cac7da624ede2a1294ce1808f204dcc
entry5 3ec4a60fa4858c1b5bc4525f5c884463
Recycle Bin/ 0a06b7d21db94d7be916f5d6946ac313
entry1 7b0fe7b1d0ce0cdd3ee90ba921fdc68b
entry2 4b9520590aff6c11ccda4b9fe1ce48a6
```
- …

Moving print group in Group class.

---

src/cli/Clip.cpp
src/cli/keepassxc-cli.cpp
src/core/Database.cpp
src/core/Database.h
src/gui/UnlockDatabaseDialog.cpp
src/gui/UnlockDatabaseDialog.h

This PR adds a GUI password prompt for the CLI commands. Some logic is now needed to determine which type of QApplication to instantiate (QCoreApplication or QApplication), since we need a GUI type application to display the GUI prompt. Also, creating 2 QApplications will result in a seg fault when the program terminates, so the instantiation of the QApplication is done at the last moment.
I will add the option to use the GUI to the other commands at some point.
Tested that the Clip command was still working.
- ✅ I have read the **CONTRIBUTING** document. 
- ✅ My code follows the code style of this project. 

Adding a GUI prompt for password.

---

src/gui/AboutDialog.ui

About dialog "Report bugs at" link to GitHub did not have "openExternalLinks" property in the ui definition and the link did not work.

Fix about dialog report bugs link functionality

---

src/gui/DatabaseWidget.cpp
src/gui/MainWindow.cpp
src/gui/SearchWidget.h

When databases are locked, end search mode if it was activated and clear the visible input field for search term.
The `DatabaseWidget::endSearch()` call on `DatabaseWidget::lock()` clears the search term from memory regardless if search mode was active or not.
Adding a default argument for `SearchWidget::databaseChanged()` allows using the existing method for lock signaling.
A user on IRC pointed out that the search field is not cleared when locking databases and it could be perceived as unintentional information leak.
@TheZ3ro said the maintainers are considering this but no issue was ever opened.
Locking/unlocking databases multiple databases, switching databases.
- ✅ My …

:lock: Fix search information leak

---

tests/modeltest.cpp

Qt's QCOMPARE() is never well-defined. In some Qt versions it requires RHS and LHS to have exactly the same type while some versions just ask for comparable types. In Qt 5.9, there's a new breakage here.
Homebrew has updated to Qt 5.9 (https://github.com/Homebrew/homebrew-core/pull/14109). Arch Linux is on the way (https://www.archlinux.org/todo/qt-59-rebuild/). Fixing this simplifies packaging.
* Building KeepassXC with the following command on macOS:
```
$ cmake -DCMAKE_OSX_ARCHITECTURES=x86_64 -DCMAKE_BUILD_TYPE=Debug -DWITH_GUI_TESTS=ON -DWITH_DEV_BUILD=ON -DWITH_XC_AUTOTYPE=ON -DWITH_XC_HTTP=ON -DWITH_XC_YUBIKEY=ON -DCMAKE_PREFIX_PATH=/usr/local/opt/qt/lib/cmake -DWITH_APP_BUNDLE=OFF ..
```
And then run ```make test```
* Smoke tests: open my database, use KeepassHTTP to automatically …

:bug: Fix building with Qt 5.9 (closes #528)

---

src/gui/PasswordGeneratorWidget.cpp
src/gui/PasswordGeneratorWidget.h
src/gui/PasswordGeneratorWidget.ui

Add copy button to password generator. Uses the standard KeePassXC clipboard functionality so it is also cleared after a timeout if configured to do so.
Issue #595
Copied password from the generator directly and while editing an entry. Clipboard was also cleared after my configured timeout.

Add copy button to password generator (#595)

---

src/gui/PasswordGeneratorWidget.cpp
src/gui/PasswordGeneratorWidget.h

In the password generator:
If the password field is empty, disable the Copy button and the Apply button. 
The Close button should instead be always enabled 
Manually

Fix password generator button's enable behavior

---

share/macosx/Info.plist.cmake

Add the `CFBundleAllowMixedLocalizations` key to the embedded Info.plist to allow Cocoa to localize its strings in the open and save file dialogs.
closes #554 

Fix macOS file dialog localization

---

src/gui/EditWidget.cpp
src/gui/EditWidget.h
src/gui/EditWidget.ui
src/gui/entry/EditEntryWidget.cpp
src/gui/entry/EditEntryWidget.h
src/gui/group/EditGroupWidget.cpp
src/gui/group/EditGroupWidget.h
tests/gui/TestGui.cpp

Add's an "Apply" buttons to both the entry and group edit windows. Implements #509.
Often times you want to save your changes without exiting the edit windows.
Manually and with updated GUI tests.

Add "Apply" button to entry and group edit windows

---

src/cli/Merge.cpp
src/core/Database.cpp
src/core/Database.h
src/gui/DatabaseTabWidget.cpp
src/gui/DatabaseTabWidget.h
src/gui/csvImport/CsvImportWidget.cpp
src/gui/csvImport/CsvImportWidget.h

This adds a `saveToFile` function to the `Database` class, allowing for a better encapsulation of the saving code. The main reason I do this is that this code will be reused in the future CLI commands that will need to write the database to file (it's already the case in the `Merge` command, so I made the switch).
* Unit tests
* Tested the merge command, with and without a writing error. The writing error was produced by removing the writing permission on the file for the current user. The error message is still correctly displayed.
* Tested saving the file through the UI also, with the same error as above.
Note that the auto reloading is disabled for the whole `saveToFile`, instead of just during the actual writing to disk. I don't think this has much of an impact, but if you have any …

Adding saveToFile function to Database.

---

src/core/Config.cpp

Implements #231. Config class checks for presence of keepassxc.ini in the run directory prior to checking the user's folder. If no ini file was found, the app proceeds as before with the user's stored config.
When deploying keepassxc as a portable app (.zip or .tar.gz) we will pre-package a keepassxc.ini config such that one is never created in the user's directory on first run. All other distribution methods will use the original behavior prior to this PR.
Manually
- ✅ …

Add support for portable config settings

---

src/cli/keepassxc-cli.cpp

Fixes #649 
As mentioned in the issue, the `showHelp` exits the application right after printing the help message. I wasn't aware of that before, and thought using the `exitCode` was fine.
Also, the `argv` is only modified once the `commandName` is known to be valid, otherwise the invalid command message will display an incorrect application name.
I'd like at some point to convert the `argv` to a `QStringList` once, and then only use a `QStringList` in the different commands, but for some reason there's no way to instantiate a `QApplication` without passing the `argv` and `argc` (unless maybe we hardcode some values for it).
```
$ ./src/cli/keepassxc-cli
Usage: ./src/cli/keepassxc-cli [options] command
KeePassXC command line interface.
Available commands:
clip		Copy a password to the …
```

Fix CLI help and version options.

---

src/CMakeLists.txt
src/cli/Extract.cpp
src/cli/PasswordInput.cpp
src/cli/PasswordInput.h
src/cli/Show.cpp
src/core/Database.cpp

Disable echoing the `stdin` input back to `stdout` on cli password prompts to avoid leaving the password visible at the terminal buffer during and after the program execution.
https://github.com/keepassxreboot/keepassxc/pull/652#issuecomment-309787721
Tested on macOS, Linux and Windows (with cmd.exe and Power Shell).

Disable stdin echo when entering passwords on cli

---

src/core/Config.cpp
src/gui/DatabaseWidget.cpp
src/gui/DatabaseWidget.h
src/gui/SearchWidget.cpp
src/gui/SearchWidget.h
tests/gui/TestGui.cpp

Partially revert #16 and add an option at the search field icon to limit the search to the current group, as suggested by @TheZ3ro in this comment with alternative n. 4: https://github.com/keepassxreboot/keepassxc/issues/296#issuecomment-288720610
This option is remembered and defaults to allow global search.
Closes #296

Add option to limit search to current group

---

src/cli/List.cpp
src/core/Group.cpp
src/core/Group.h
tests/TestGroup.cpp
tests/TestGroup.h

Add support for listing a single group. The `findGroupByPath` function will also be reused in some other CLI commands I'm working on right now.
- Manually with the cli
- added unit tests.

Adding support for listing a group.

---

src/cli/PasswordInput.cpp

The next line would be displayed on the same line as the password prompt.
before
```
$ ./src/cli/keepassxc-cli list ~/test1.kdbx 
Insert password to unlock /Users/louib/test1.kdbx
> Group1/
[empty]
Group2/
Entry1
```
after
```
$ ./src/cli/keepassxc-cli list ~/test1.kdbx 
Insert password to unlock /Users/louib/test1.kdbx
> 
Group1/
[empty]
Group2/
Entry1
```
- Manually
- ✅ Bug fix

Outputing newline after password prompt.

---

src/gui/UnlockDatabaseDialog.cpp

Closes #662 
Bring unlock database dialog to the foreground when trying use auto-type with a locked database.

Bring unlock database dialog to the front

---

AppImage-Recipe.sh

Resolves Qt library loading issue when starting the AppImage (#666).
New AppImage build now also works on systems which don't ship with Qt 5.9.

Use correct Qt library path, resolves #666

---

src/gui/csvImport/CsvParserModel.cpp

During localization of the version 2.2.0 to Russian I've noticed that the file info published by the CSV Importer doesn't really follow the pluralization rules of Qt, described [here](http://doc.qt.io/qt-5/i18n-source-translation.html). Therefore even in English the info will not look good enough, for example it will say "1323 byte, 1 rows, 1 columns" instead of "1323 bytes, 1 row, 1 column".
This change just makes the stuff more human-friendly.
Your standard tests.

Added proper plural processing in CSV importer (localization)

---

src/CMakeLists.txt
src/cli/CMakeLists.txt
src/cli/EntropyMeter.cpp
src/core/PasswordGenerator.cpp

detect a system version in case it is available.
this approach should be retro-compatible and safe for Debian builds
(we don't like embedded libraries).
maybe you could also update zxcvbn to get rid of that useless file like debian zxcvbn-c did

detect system zxcvbn library

---

src/core/Config.cpp
src/gui/EditWidgetIcons.cpp
src/gui/SettingsWidget.cpp
src/gui/SettingsWidgetSecurity.ui

This patch makes the Google fallback for downloading website favicons optional and off by default.
Privacy concerns have been raised.
Tried to download favicon for example.com. Without the option ticked, download fails and an error message is shown. With the option ticked, the Google default favicon is downloaded.

Make favicon Google fallback optional and off by default

---

src/autotype/AutoType.cpp
src/core/Config.cpp
src/gui/SettingsWidget.cpp
src/gui/SettingsWidgetGeneral.ui

A user requested KeePassXC to have separate options to match the title and URL of an entry like in KeePass.
Created second checkbox for URL matching, new configuration option with default on, changed auto-type window matching logic to test them separately.
Release note: the new checkbox is checked by default like the old one was so if one has title matching disabled URL matching will become enabled anyway until unchecked.
Issue #638.
Two entries where one has matching title only and one which has matching URL only.

Split auto-type title and URL matching into separate options (fixes #638)

---

src/autotype/AutoType.cpp
src/autotype/mac/AutoTypeMac.cpp
src/autotype/windows/AutoTypeWindows.cpp
src/autotype/xcb/AutoTypeXCB.cpp
src/core/Config.cpp
src/gui/SettingsWidget.cpp
src/gui/SettingsWidgetGeneral.ui

Adds both solutions presented in issue #699.
All platform dependant hardcoded auto-type delays were removed in favor of a configurable default. UI was added to configure the delay which defaults to 25ms as specified.
Issue #699.
Only on Linux with three different auto-type entries:
1. Default, no custom delay (will use the configured default)
2. Sequence with {DELAY=0} -> will override the default
3. Sequence with {DELAY=200} -> will override the default
Tested the default at 0 ms, 25 ms and 500 ms. All work and are overridable by the sequence {DELAY=X} option. …

Implement configurable default auto-type delay (fixes #699)

---

src/autotype/xcb/AutoTypeXCB.cpp
src/autotype/xcb/AutoTypeXCB.h

Fix auto-type implementation on Linux. The previous implementation would mess modifiers handling, resulting in invalid output and sometimes stuck modifiers.
The code was also simplified a little: I removed left-overs from what looks like a previous implementation that was not using `XTestFakeKeyEvent`.
This might fix #414 and #474.
I tested both with entries containing a mix of characters available with my layout, and special accented characters that are not. Those tests were run with a combination of:
* `NumLock` on/off
* non-qwerty layouts (I use a custom modified colemak layout, but also tried with `setxbmap es` and `setxkbmap dvorak`)
I also checked `{CLEARFIELD}` support was working. …

fix X11 auto-type

---

src/gui/MainWindow.cpp

This patch correctly adds a "[*]" placeholder to the window title to indicate whether the database was modified as described in the QWidget documentation.
The placeholder ensures that the visible modification indicator adheres to the platform standards and it gets rid of the following Qt warning:
QWidget::setWindowModified: The window title does not contain a '[*]' placeholder
No visual difference to the previous implementation exists on Linux (and I suppose Windows).
Opened and modified databases. All existing unit tests pass.
- ✅ I have compiled and …

Use [*] placeholder in window title to get rid of Qt warning

---

AppImage-Recipe.sh

* the url for script functions.sh was changed, see [functions.sh](https://github.com/AppImage/AppImages/raw/master/functions.sh)
* add 32bits architecture  for release-tool
* for information, **bug** on appImage: functions.sh don't build on debian, see [pull request](https://github.com/AppImage/AppImages/pull/252) then release-tool don't work.   
the PR was accepted, and it is **important** for debian platforms
* release-tool don't work on 32bits architecture
* before PR 252 (on AppImage), I can't build with release-tool, on Stretch or Sid
after Pull Request, I can
* I make a build, with success and use the image builded
* add /usr/lib/i386-linux-gnu in 
- ✅ My code follows the …

Kyodev patch 2

---

src/gui/PasswordGeneratorWidget.ui
src/gui/entry/EditEntryWidgetMain.ui

This patch fixes minimum widget sizes and size policies for components of the PasswordGeneratorWidget.
With certain "large-padding" themes such as KDE Breeze, the alphabet selection buttons appeared squished inside the inline password generator.
Before:
After:
Visuals are fine now on KDE with Breeze.

Fix PasswordGeneratorWidget sizes and size policies

---

src/cli/CMakeLists.txt
src/cli/Clip.cpp
src/cli/Command.cpp
src/cli/Command.h
src/cli/EntropyMeter.cpp
src/cli/EntropyMeter.h
src/cli/Extract.cpp
src/cli/Extract.h
src/cli/List.cpp
src/cli/List.h
src/cli/Merge.cpp
src/cli/Merge.h
src/cli/Show.cpp
src/cli/Show.h
src/cli/keepassxc-cli.cpp
src/core/Group.cpp
src/core/Group.h
tests/TestGroup.cpp

This PR introduces a `Command` class, from which all the CLI commands inherit. This makes it easy to programmatically get the names of all the available commands, using the factory-like static functions in the `Command` class.
Also took this opportunity to add most of the information on an entry to the `show` command, and renamed the `list` command to `ls`, to fit the unix name.
This will make it easier to add new cli commands (there will be more in the future...)
* unit tests are passing
* Tested manually that all the commands were still working.
- ✅ Breaking change
- ✅ Refactoring
- ✅ I have compiled and …

Refactoring : Command base class for CLI commands

---

src/gui/MainWindow.ui

When a help menu exists, its access key is supposed to be "H" unless there's a very good reason not to use that.
Consistency with standard windows programs.
No testing

change help accesskey to h

---

src/gui/MainWindow.ui

Correct "set up" from "setup" (split from #782)
"Setup" is a noun
"Set up" is a verb phrase
A program is often called "setup", but the action it's taking is to "set up" the program.
The "Set up TOPT" action falls in the latter category.
UI consistency
None

Set up is used as a verb phrase not a noun

---

src/core/Entry.cpp
src/core/Entry.h
src/gui/EditWidgetIcons.cpp
src/gui/entry/EditEntryWidget.cpp
src/http/Service.cpp
tests/CMakeLists.txt

The user provided URL field can contain various protocol URL other than `http` and `https` (like `cmd`, `ftp`, `sftp`, etc)
This PR adds an entry method called `webUrl` that takes the url field, checks if it's web-friendly (check if the protocol is `http` or `https`, adds `https` by default if the protocol is missing, tries to extract the url from `cmd` protocol, ...)
The `webUrl` is then used for downloadingFavicon and for the KeePassHTTP protocol.
If the website don't support `https`, the request will timeout so we need to retry under `http`
This fixes #238 and #240 
Writing tests for this is pretty painful.
I've tested this manually with the following url:
- `www.google.com` *url without protocol* -> fetch icon for `https://www.google.com`
- `www.stealmylogin.com` *url without …

Fix correct favicon downloading

---

LICENSE.APACHE-2.0
src/core/Config.cpp
src/gui/Application.cpp
src/gui/SettingsWidget.cpp
src/gui/SettingsWidgetGeneral.ui
src/main.cpp

This PR fix the current "Single instance" behavior in Debug mode that conflicts with the Release instances of KeePassXC.
After this PR:
- You can run unlimited Debug-compiled instances
- If you are running a Release instances you can disable the "single instance" mode in the settings
This PR also revert the old patch that isn't required anymore and add the APACHE2 license that was missing in 2.2.0 (for the Base32 library copyright)
Using Debug instances along with Release one was pretty annoying
Manual testing …

Fix single instance behavior in debug mode

---

src/gui/CloneDialog.ui

The clone dialog in the ui says `Append ' - Copy' to title.'`
The actual code creates an entry with added '- Clone'.
Fixed the string in the CloneDialog.ui file and in the translation files.
Makes UI consistent with the actual behavior of the code.
Have not built the application. It should be a simple string change. 
Notice how the cloned entries have a '- Clone' suffix and not '- Copy'.
Simple text string change

Fix clone dialog text

---

src/CMakeLists.txt
src/cli/Clip.cpp
src/cli/Clip.h
src/cli/Extract.cpp
src/cli/Utils.cpp
src/cli/Utils.h
src/core/Database.cpp

Clip command using native programs.
Summary of changes:
* Using native programs for the `Clip` command.
* Adding a timeout option for clearing the clipboard
* Renamed PasswordInput -> Utils, since we now use it for other CLI functions.
Interacting with the `QClipboard` is not possible for a `QCoreApplication`, and instantiating a `QApplication` does not play nicely with the CLI. The goal is to remove usages of `QApplication` (GUI applications) in the CLI, so that we can instantiate 1 `QCoreApplication` in `keepassxc-cli.cpp`, and that's it. No more branching to know what type of application to instantiate.
The next step is to remove the GUI prompt in favor of a `--key-file` option, supported in all of the commands. 
Unit tests + tested on Mac and Linux.
@droidmonkey could you test this on …

Feature : Clip command using native programs.

---

src/cli/Clip.cpp
src/cli/Clip.h
src/cli/Command.cpp
src/cli/Command.h
src/cli/EntropyMeter.cpp
src/cli/EntropyMeter.h
src/cli/Extract.cpp
src/cli/Extract.h
src/cli/List.cpp
src/cli/List.h
src/cli/Merge.cpp
src/cli/Merge.h
src/cli/Show.cpp
src/cli/Show.h
src/cli/keepassxc-cli.cpp
src/core/Database.cpp
src/core/Database.h
src/gui/UnlockDatabaseDialog.cpp
src/gui/UnlockDatabaseDialog.h
src/keys/CompositeKey.cpp
src/keys/CompositeKey.h
tests/TestKeys.cpp
tests/TestKeys.h

* Introduced the `--key-file` option for CLI commands
* Removed support for `--gui-prompt` and related code.
* Moved `QCoreApplication` instantiation to `keepassxc-cli.cpp`
* Removed `CompositeKey::readFromLine`, which was assuming a password entered at the password prompt was possibly a key file path. We do not need that anymore now that there's an option for that.
Overall, removing the use of a `QApplication` in the CLI. We only use a `QCoreApplication` now, which removes the need to branch on the application type, and allows to move some duplicated logic to `keepassxc-cli`.
* Unit tests
* Tested all the commands with / without key files
* Tested the merge command with all `key-file`, `key-file-from` and `-s` combination.
New documentation for the `key-file` option:
```
$ …
```

Feature : --key-file option for CLI

---

src/main.cpp

In LastOpenedDatabases, the most recently opened file is listed first and the
least recently opened one is listed last. If the databases are re-opened in this
order, LastOpenedDatabases is reversed afterwards. To avoid this, load the files
in reverse order, so LastOpenedDatabases is not modified.
Currently, with each start of KeePassXC, the order of the tabs which represent previously opened databases gets reversed. This can be easily reproduced:
1. Open at least two databases
2. Close and open KeePassXC repeatedly, observe order of tabs
The change is rather minimal and easy to review. Testing was done in two ways:
* `make test` was run and 100% tests passed
* fix of the behavior described above was tested manually by repeatedly opening the application and looking at values stored in …

Open previously opened databases in correct order

---

src/core/Database.cpp

While reviewing #824 , I realized we were not handling errors when loading the keyfile.
Locally, with the clip command
```
$ ./src/cli/keepassxc-cli clip ~/test.kdbx --key-file fadsfdsaf entry1
Failed to load key file fadsfdsaf : No such file or directory
```

Handle FileKey::load errors (--key-file)

---

src/gui/entry/EditEntryWidget.cpp
src/gui/entry/EntryHistoryModel.cpp
src/gui/entry/EntryHistoryModel.h

Fixes #812
We were trying to delete the same history items multiple times. The bug would also occur when deleting an history item an hitting multiple times the `apply` button.
Manually.
- ✅ Bug fix

Clearing deleted entries on applying.

---

src/core/Database.cpp

Looks like we must add the key file after the password, otherwise the composite key will not be the same.
- Tested locally with the CLI.

Moving keyFile after password.

---

CMakeLists.txt

Fixes #801
If a non-default (ex: MacPorts' /opt/local/include) include path provides a new enough zlib and an old zlib.h resides in default include paths (ex: on OS X 10.9 Mavericks), the version check fails. 
I don't actually have a Mavericks box, so I changed the bottomline of ZLIB_VERNUM to 0x1290. MacPorts provides zlib 1.2.11 (ZLIB_VERNUM = 0x12b0), and macOS Sierra provides 1.2.8 (ZLIB_VERNUM = 0x1280). With the newly added line, KeePassXC compiles fine.
The command I used is:
```
cmake .. -DCMAKE_SYSTEM_PREFIX_PATH="/opt/local;/usr"
```
N/A build fix only
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to change) …

:bug: Use correct ZLib include path

---

src/gui/MainWindow.cpp
src/gui/SearchWidget.cpp
src/gui/SearchWidget.h

Signed-off-by: Ettore Dreucci <ettore.dreucci@gmail.com>
At startup and when the database is open and no action is being carried out the keyboard focus is automatically given to the search widget so that it's possible to search an entry without using the ctrl+f shortcut or clicking on the search field.
Fixed issue #847 
Manually tested:
1. Created a new database
2. Added some random entries
3. Started typing to search

Solve issue #847: Keyboard autofocus on search field at startup

---

src/gui/MainWindow.cpp

Use the `delete` key to delete selected records, ontop of the original `CTRL+D` record. 
Add a key bind for delete key to delete an entry
Using the delete key to delete a record just makes sense, That's what the key is for 👍 
Locally. Select record, see if delete dialog appears.

Bind delete key to delete entry

---

src/cli/Add.cpp
src/cli/Add.h
src/cli/CMakeLists.txt
src/cli/Command.cpp
src/cli/Edit.cpp
src/cli/Edit.h
src/cli/Remove.cpp
src/cli/Remove.h
src/cli/keepassxc-cli.1
src/core/Group.cpp
src/core/Group.h
src/core/PasswordGenerator.h
src/gui/PasswordGeneratorWidget.cpp
src/http/HttpPasswordGeneratorWidget.cpp
tests/TestGroup.cpp

* adding basic entry manipulation commands for the CLI. (add, edit and remove).
* extracted a `DefaultLength` for the password generation since `16` was hardcoded at multiple places
* added sub-sections to the `OPTIONS` section of the man page, to avoid mixing command specific and general options
Adresses #681
* Tested locally the new commands
* Added unit tests where possible
```
$ ./src/cli/keepassxc-cli
Usage: ./src/cli/keepassxc-cli [options] command
KeePassXC command line interface.
Available commands:
add            Add a new entry to a database.
clip           Copy an entry's password to the clipboard.
edit           Edit an entry.
entropy-meter  Calculate password entropy.
extract        Extract and print the content of a database.
locate         Find entries quickly.
ls …
```

CLI : basic entry manipulation commands.

---

.travis.yml
src/core/Group.cpp

Fixes #940 
Manually + added unit tests on develop
The `resolveConflict` code has changed a lot in `develop`, and this bug is not on `develop`, as we already switched to `setGroup` instead of `addEntry`.

Fixes #940 : segfault when searching after merging

---

src/gui/DatabaseOpenWidget.cpp
src/gui/DatabaseOpenWidget.h
src/gui/DatabaseWidget.cpp
src/gui/UnlockDatabaseWidget.cpp
src/gui/UnlockDatabaseWidget.h

Fixes #944. Resets master key entry prior to showing the unlock dialog for merging and then after the merge is completed.
Not clearing the form can result in leaking the master key.
Manually and unit tests

Clear database open dialog before and after merging a database

---

src/gui/DatabaseTabWidget.cpp
src/keys/YkChallengeResponseKey.cpp
src/keys/drivers/YubiKey.cpp

* Fixed database not showing modified after failed save (auto save after change never marks dirty)
* Fixed Yubikey not being redetected after replug (fixes #712)
* Fixed single shot challenge resulting in failed saves (bumped it to try twice, results in 90% success rate) (fixes #531)
Manually using a Yubikey Neo

Correct multiple issues with Yubikey integration

---

src/core/Group.cpp

Fixes #965. Maintain entry history when merging databases.

Keep entry history when merging databases

---

src/cli/CMakeLists.txt

Installation of unofficial Arch Linux user (AUR) package ```keepassxc-git fails:
```
error: failed to commit transaction (conflicting files)
keepassxc-git: /usr/local/share/man exists in filesystem
Errors occurred, no packages were upgraded.
```
Hard-coded install path from #888 breaks things. Arch Linux discourages packages to install files to /usr/local.
Apply the patch and rebuild the package. The man page is installed to /usr/share/man/man1/keepassxc-cli.1.gz if CMAKE_INSTALL_PREFIX is /usr.
N/A. Build fix only.
-  All new and existing tests passed. **[REQUIRED]**
With ASAN, 5 tests fail as there are …
```

Use CMake's variable instead of hardcoded path to install man pages

---

src/gui/CloneDialog.cpp
src/gui/csvImport/CsvImportWizard.cpp

Just a small cleanup.
1. Don't use the _emit_ keyword with normal functions
2. Don't treat the _emit_ keyword as a function call
Coding style.
Made a rebuild of the project, then run related tests and the keepassxc binary.

Use the emit keyword correctly

---

src/core/Database.cpp
src/core/EntryAttachments.cpp
src/core/EntryAttributes.cpp
src/format/KeePass2XmlWriter.cpp
src/gui/AboutDialog.cpp

1. Use the multi-arg version of QString::arg()
2. Don't create temporary containers
The first change avoids creating temporary QStrings (leading to unnecessary heap allocations) when using chained QString::arg() calls by using the multi-arg overload. Rationale: [https://github.com/KDE/clazy/blob/master/src/checks/level0/README-qstring-arg.md](https://github.com/KDE/clazy/blob/master/src/checks/level0/README-qstring-arg.md)
The second change does a similar thing with temporary containers.
Optimization.
Made a rebuild of the project, then run related tests and the keepassxc binary.
- ✅ All new and existing …

Prevent unnecessary memory allocations

---

src/gui/Application.cpp
src/gui/Application.h

* Fixes #893, if connection to the listen server fails three times, the lock file is removed and a new listen server is started.
I also took the opportunity to bring this code into alignment with the coding standards for variable naming.
This issue has been reported 4 times since release of 2.2.0.
Manually

Correct latent single instance lock file preventing launch

---

src/core/Metadata.cpp
src/core/Metadata.h
src/gui/EditWidgetIcons.cpp
src/gui/EditWidgetIcons.h

Provides multiple fixes to reported bugs against custom icon loading.
* Fixes #904, icons are saved at or below 128x128 resolution
* Fixes #403, crash occurs due to dialog displayed while not on GUI thread
* Fixes #232, icon hashes are calculated on database load and compared against new downloads
The way I implemented the unique icon hashing ensures that existing databases with multiple unique icons already are not impacted.
Manually with several websites.

Correct multiple issues with custom icons

---

src/core/Entry.cpp
src/core/Entry.h
src/gui/entry/EntryModel.cpp

Fixes #845. {PASSWORD} placeholders are turned into ***** before calling "resolve placeholders" to prevent spillage of passwords in the entry view table.
Maintains security of passwords.
Manually

Mask passwords in URL column in entry view table

---

src/gui/entry/EditEntryWidget.cpp
tests/gui/TestGui.cpp

Fixes #909. Password fields are checked prior to saving to prevent data loss.
_Note: Code is repeated due to the way the apply button works (directly calls the save function). This should be refactored in the future._
Manually and unit tests.

Check for mismatched passwords BEFORE saving to prevent data loss

---

snapcraft.yaml

Fixes #905. Adds snapd-xdg-open program within the snap to allow for URL opening using the CTRL+U shortcut and right-click context menu entry.
I added a [wiki page to document the snap gotchas](https://github.com/keepassxreboot/keepassxc/wiki/Snap-Tips).
Manually on Ubuntu 17.04

Added snapd-xdg-open to snap to enable URL loading

---

src/core/Entry.cpp
tests/TestEntry.cpp
tests/TestEntry.h

Fixes #1017 
Manually with debugger

Corrected issue where blank urls resulted in spurious returns to KeepassHTTP

---

src/gui/DatabaseTabWidget.cpp

Fix memory leak in DatabaseTabWidget::openDatabase function
1. Open first instance of KeePassXC 
2. Open database /tmp/test.kdbx 
3. Open second instance of KeePassXC 
4. Try open database /tmp/test.kdbx 
5. Сhoose "No" in the dialogue that appeared 
6. Close second instance of KeePassXC 
ASAN detect leak:
```
DatabaseTabWidget::openDatabase(QString const&, QString const&, QString const&) /home/frostasm/dev/qt/keepassxc/src/gui/DatabaseTabWidget.cpp:155
```

Fix memory leak in DatabaseTabWidget::openDatabase function

---

CMakeLists.txt

Partially revert #981 on macOS when building with app bundle.
Cmake was trying to install the cli manpage at `/man1` because when `WITH_APP_BUNDLE` is set, `include(GNUInstallDirs)` isn't called to define the default manpage path.
`man keepassxc-cli`

Fix macOS man path

---

src/core/Metadata.cpp

QByteArray only accepts char* and QImage::bits only outputs uchar*.... 
Warnings can lead to silent issues.

Fixed old-style-cast warning in custom icon hasher

---

src/core/Database.cpp
src/core/Metadata.cpp
src/core/Metadata.h
src/format/KeePass2XmlReader.cpp
src/format/KeePass2XmlWriter.cpp
tests/TestMerge.cpp
tests/TestMerge.h

Custom icons were not carried over when merging.
Also removed code related to `autoEnableVisualHiding`, since it's not used.
@droidmonkey I'd wait for the changes made in `2.2.1` to be carried over in `develop` before merging this. Do we have an ETA for that?
Fixes #971 
* Unit test
* Tested manually

Add custom icons when merging.

---

src/gui/DatabaseOpenWidget.cpp
src/gui/DatabaseOpenWidget.h
src/keys/drivers/YubiKey.cpp
src/keys/drivers/YubiKey.h

Fixes #1045 
The previous implementation bailed after finding the first slot that was configured for challenge/response. In order to overcome some threading interchanges and Yubikey limitations the implementation was expanded to be far more robust.
Also, yubikey signals are disconnected from all the unlock widgets when they are hidden. The previous behavior caused all created unlock widgets (about 4-5 per open database) to be updated when the yubikey was polled.
Manually with Yubikey Neo …

Both slots on Yubikey are now polled for challenge/response

---

.gitignore

Adds a new item to the `.gitignore` list so that `.DS_Store` files are ignored.
Currently, an ignore item for `.DS_Store` files created by Finder in Mac OS is missing from the list.
N/A.
N/A.
N/A.

Extend the .gitignore list

---

src/core/Database.cpp
src/core/Database.h
src/format/KeePass2Writer.cpp
src/format/KeePass2Writer.h

Fix: https://github.com/keepassxreboot/keepassxc/issues/1051

Fix: Regenerate transform seed and transform master key on save.

---

Dockerfile
release-tool

- PPA qt59 no longer exists for 14.04, see https://launchpad.net/~beineri
- On Ubuntu 16.04 host with docker 17.09.0-ce, I needed apparmor:unconfined to be able to use fuse - see https://github.com/moby/moby/issues/9448#issuecomment-289950103
This allows Docker builds to work correctly (for me).
I've tested this by creating my own appimage with `docker build -t keepassxc-build . && ./release-tool build --version 2.2.1 --no-source-tarball --plugins ''` (after commenting out the check for a clean git repo).
('REQUIRED' items talking about passing tests and ASAN were removed)

Fix builds in Docker

---

src/core/Entry.cpp
src/core/Entry.h
tests/TestEntry.cpp
tests/TestEntry.h

Implement recursive resolving for placeholders
From keepass [help](https://keepass.info/help/base/fieldrefs.html): 
> Referencing fields of other entries only works with standard fields, not with custom user strings. If you want to reference a custom user string, you need to place a redirection in a standard field of the entry with the custom string, using {S:<Name>}, and reference the standard field.
Currently KeePassXC does not support the described behavior.
URL placeholders: 
- {URL:RMVSCM}
- {URL:WITHOUTSCHEME} - analog for {URL:RMVSCM}
- {URL:SCM} 
- {URL:SCHEME}  - analog for {URL:SCM}
- {URL:HOST}
- {URL:PORT}
- {URL:PATH}
- {URL:QUERY}
- {URL:FRAGMENT} - new url placeholder
- {URL:USERINFO}
- {URL:USERNAME}
- {URL:PASSWORD}
Implement behavior similar to keepass2
With unit test, …

Implement recursive resolving for placeholders

---

src/gui/DatabaseTabWidget.cpp

Fixes #590 by passing the provided password (via stdin) to a database that was already opened due to "open previously open databases"
Manually

Unlock previously opened databases with --pw-stdin

---

README.md

Adding KeePassHTTP-Connector to the readme instead of PassIFox and ChromeIPass that aren't maintained anymore
Fix #998 

add KeePassHTTP-Connector

---

release-tool

Adds ability to use signtool program to sign windows binaries. Also added --ignore-repo option to the build function to allow building without being on a clean slate.
Full service signing on Windows.
Manually

Add signtool function (Windows Only) to release-tool script

---

src/gui/DatabaseWidget.cpp
src/gui/DatabaseWidget.h
src/gui/MainWindow.cpp
src/gui/MainWindow.h
src/gui/MessageWidget.cpp
src/gui/MessageWidget.h
src/http/OptionDialog.cpp

Add ability to hide inline message widget after a set period of time (#1006)
Done: 
- Add the auto hide functionality to the KMessageWidget class
- Add ability to change the auto-hide settings for inline messages via gui
Possible improvements:
- Display the time through which the message will be closed 
- Change the default setting (currently auto-hide disabled by default)
fix opened issue #1006 
Manually

Add auto hide functionality to inline message widget (#1006)

---

src/gui/DatabaseOpenWidget.cpp
src/gui/DatabaseOpenWidget.h

Second attempt to fix #741, after https://github.com/keepassxreboot/keepassxc/pull/744
Rebased on `2.2.2`.
Locally, by opening a database with a keyfile, and testing the error message when providing an invalid path.

Fix double warning display for database open

---

AppImage-Recipe.sh
Dockerfile
share/linux/org.keepassxc.desktop

Resolves #1034.
This patch migrates our Docker build system from Ubuntu 14.04 to CentOS, uses custom builds of libyubikey and libykpers-1 and adds the ability to call keepassxc-cli inside an AppImage by using a "cli" argument.
Previous AppImage releases were unable to detect a plugged-in YubiKey and were also unable to directly start keepassxc-cli.
In addition, Ubuntu 14.04 is EOL while CentOS 7, whose first release was also in 2014, is still supported until 2024. In addition to that, we needed a lot of PPAs, because many packages were quite outdated, including Qt itself. The new Dockerfile reduces the number of non-official dependencies (at least when this issue is closed: https://github.com/bugzy/keepassxc-rpm-spec/issues/6). With it comes a Qt downgrade to 5.6, but that is still newer …

Fix AppImage not detecting YubiKey and add support for keepassxc-cli to AppImages

---

Dockerfile

Shorten Dockerfile and reduce number of Copr repositories.
Our new CentOS 7 Dockerfile can be reduced even further by pulling cmake3, libyubikey and libykpers-1 from CentOS/Fedora EPEL. This reduces the number of required external repositories even further and we also don't need to build the YubiKey libs ourselves anymore.
AppImage build still working, YubiKey also detected successfully at runtime.

Reduce external dependencies and install YubiKey deps from EPEL

---

src/autotype/AutoType.cpp
src/gui/entry/AutoTypeAssociationsModel.cpp
src/gui/entry/AutoTypeAssociationsModel.h
src/gui/entry/EditEntryWidget.cpp
tests/TestAutoType.cpp

Allow to use entry placeholders in window association title
This feature useful when we need to match window by some specific data (which not convenient to use as the name or the url), for example ip-address or mac-address, etc.
Manually, with using windows that do not contain name or url but contain value from the entry attribute.
- My change may require a change to the documentation.

AutoType: resolve placeholders for title in window associations

---

AppImage-Recipe.sh
Dockerfile
src/gui/DatabaseOpenWidget.cpp
src/gui/DatabaseOpenWidget.h
src/gui/MainWindow.cpp

This patch resolves #1114 by reverting our AppImage build system back to Ubuntu 14.04, but with custom builds for libyubikey and libykpers-1. It also ships a required code fix to prevent the YubiKey from appearing twice in the menu (only happens when building with 14.04, newer Ubuntu versions are not affected, but it may also be a problem of a specific Qt version).
Additionally, this patch resolves #691 by restricting our global menu workaround to Qt versions older than 5.9.0.
Moving to CentOS solved a few problems. It cleaned up our Dockerfile and didn't necessarily require a newer Qt version and YubiKeys worked out of the box. Unfortunately, AppImages built with CentOS don't integrate with Ubuntu's global menu (at least not with the standard Qt 5.6) and don't run on older Ubuntu-based …

Move build system back to Trusty (with fixes)

---

src/gui/DatabaseTabWidget.cpp
src/gui/DatabaseTabWidget.h
src/gui/MainWindow.cpp
src/gui/MainWindow.ui

Fix #207 
- Remove view menu since it's useless 
- Disable save button if there isn't anything to save
Manually, make test and with Travis

Remove view menu and disable save button

---

src/gui/DatabaseWidget.cpp
src/gui/UnlockDatabaseDialog.h

Disable reload prompt when db is locked
This problem was raised in #1113 (but does not fix this particular issue)
We should not try reloading the database file when it is locked, as it will be reloaded anyway when the database will be unlocked.
Locally by reproducing the steps in the issue, with `touch path/to/db.kdbx` while it is locked.

Disable reload prompt when db is locked

---

src/core/ScreenLockListenerDBus.cpp

The current code does not work with XUbuntu 16.04, which uses
light-locker to lock the screen.
I am not using a screensaver, but I suspect the screensaver activation
may have been detected by the existing events, and using it could thus
mask the issue.

Detect session lock on Xfce/XUbuntu 16.04

---

src/gui/SettingsWidget.cpp
src/gui/SettingsWidgetSecurity.ui
src/gui/entry/EditEntryWidget.cpp
src/gui/entry/EditEntryWidget.h
src/gui/entry/EditEntryWidgetMain.ui

Finalization of #541 
All credit to @grim210 
I prefer the notes section to be fixed width (#540).  When searching for an issue on the issue tracker, I found #342, which seems like it would be easy to fix while I was working on my own issue.  Overall, it was a simple fix for both.
Commit 636b3a0 fixes the issue that I created: #540.
Commit b9531a7 fixes issue #342.
Tried on existing database (my personal one, a few years old), and on a fresh database that was created for the screenshots below.  Notes persisted through save.  Disabling the notes after writing them does not erase them.
Tested on Ubuntu MATE 16.04.2 amd64, with Qt 5.5.1.  All tests in the 'tests' directory were passed (except the YubiKey ones; I don't have one).  There were no apparent side effects during testing.
This is …

Make notes hidden by default

---

src/http/Service.cpp

Add support for placeholders on the KeePassHTTP custom fields (#1067)
Changes: 
- Function Entry::resolvePlaceholder recognize {TOTP} placeholder 
- KeepassHttpProtocol::Server::prepareEntry use Entry::resolveMultiplePlaceholders for resolving placeholders on custom fields 
fix opened issue #1067
Manually via chromeIPass extension

Add support for placeholders on the KeePassHTTP custom fields (#1067)

---

src/gui/MainWindow.cpp

I found one small bug. KeePassXC saves the geometry even when the main window is hidden. It creates a wrong behaviour on my DE (I use Mate). When the application starts (after the app was closed with an invisible main window), the main window opens in the upper left corner of the monitor. 
Fix wrong behaviour
Manually
**Steps to reproduce:**
- Run app
- Move window to center of monitor
- Go to Options
- Mark checkboxes "Show a system try icon" and "Hide window to system tray instead of app exit"
- Save changes
- Close main window (Alt+F4)
- Quit from app via system tray menu
- Run app
- The main window opens in the upper left corner of the monitor
**Expected Behavior:**
App appear at center of monitor
**Current Behavior:**
The main window opens in the upper left corner of the monitor …

Save the geometry of main window only if the window is visible

---

src/gui/DatabaseWidget.cpp
src/gui/DatabaseWidget.h
src/gui/DatabaseWidgetStateSync.cpp
src/gui/DatabaseWidgetStateSync.h
src/gui/DetailsWidget.ui

- Allow to change the height of the preview panel
- Set a constant offset for the text on the General tab (left side 20px)
Fixes #1135
Fixes #1158
Manually

Allow to change the height of the preview panel (fix #1135)

---

src/gui/DatabaseWidget.cpp
src/gui/DatabaseWidget.h
src/gui/csvImport/CsvImportWizard.cpp
src/gui/csvImport/CsvImportWizard.h
tests/gui/TestGui.cpp
tests/gui/TestGui.h

This PR add a GUI test for DB creation
It also fix CsvImportWizard to re-use the already running ChnageMasterKeyWidget instance
Currently we aren't testing the DB creation mechanism
Manually, with `make test` and Travis

Add test for DB creation, re-use ChnageMasterKeyWidget instance in CsvImportWizard

---

src/gui/entry/EditEntryWidget.cpp
src/gui/entry/EditEntryWidget.h
tests/gui/TestGui.cpp
tests/gui/TestGui.h

Fixes #1133 
Loss of data if user hits apply then cancel when editing a new entry.
Manually and with newly written test cases.

Fix apply button not saving new entries

---

src/core/EntryAttachments.cpp
src/core/EntryAttachments.h
src/gui/FileDialog.cpp
src/gui/FileDialog.h
src/gui/entry/EditEntryWidget.cpp
src/gui/entry/EditEntryWidget.h

All errors show at once
Supported actions:
- Insert 
- Remove 
- Open 
- Save 
To make working with attachments more user friendly
Manually.
Window with opening errors:  

Add support for working with multiple entry attachments at once

---

src/gui/entry/EditEntryWidgetMain.ui

Revert 5bc000c to fix the startup slowdown introduced at that commit.
For some reason, setting the font was increasing the start time from about 1 second to almost 5 seconds. I'm reverting this change until someone finds a better way to set the note field font without this side effect.
Related: #974

Fix startup delay

---

src/CMakeLists.txt
src/core/MacPasteboard.cpp
src/core/MacPasteboard.h
src/gui/Clipboard.cpp
src/gui/Clipboard.h

Close #1118, close #787, close #720, close #894
Remove unwanted UTF-8 BOM from clipboard strings and use the [org.nspasteboard.ConcealedType](http://nspasteboard.org/) pasteboard.
Manual tests using Apple's [Clipboard Viewer](https://developer.apple.com/library/content/samplecode/ClipboardViewer/Introduction/Intro.html) and testing apps that had problems with the UTF-8 BOM added by Qt (mainly Steam).

Improve macOS pasteboard handling

---

src/core/Entry.cpp
src/gui/DatabaseWidget.cpp
src/gui/DetailsWidget.cpp
src/gui/SetupTotpDialog.cpp
src/gui/SetupTotpDialog.h
src/gui/SetupTotpDialog.ui
src/gui/TotpDialog.cpp
src/totp/totp.cpp
src/totp/totp.h
tests/TestTotp.cpp
tests/TestTotp.h

Add initial Steam TOTP support
* Add the concept of custom TOTP encoders, each with potential for custom
code alphabet, length, step interval and code direction (i.e. reversed)
* Select custom encoder via overload of the digits field of a loaded entry
* Allow selection of custom encoders via the "TOTP Settings" field's
size, as currently done by KeeTrayTOTP for Steam. Use "S" for the
short name of the Steam custom encoder
* Allow selection of custom encoders via the "otp" field by appending
a "&encoder=<name>" field to the URL query. For example,
"&encoder=steam"
* Update TOTP set-up dialog to permit selection between (default,
steam, custom) settings.
Adds the ability to generate Steam Guard TOTP codes using the secret
associated with a Steam account.
Fixes #594
Unit tests added
Tested …

Add initial Steam TOTP support

---

src/core/Entry.cpp
src/gui/SetupTotpDialog.cpp
src/totp/totp.cpp
src/totp/totp.h
tests/TestTotp.cpp

Rename QTotp class name to Totp, as it has nothing to do with Qt.
Related: https://github.com/keepassxreboot/keepassxc/pull/1206#issuecomment-345872501

Rename QTotp class name to Totp

---

src/gui/MainWindow.ui

I added Alt+m shortcut (underlined letter in menu) for _Groups > Empty recycle bin_ menu which I implemented some time ago to be consistent with other menu items in the same group which all have underlined letters.
This is a small tweak for UI consistency.
This has been tested by visually looking at the application after the change and by actually using Alt+G,m shortcut to ensure the menu is really invoked.
This is how it looks now

Add menu shortcut for consistency

---

src/core/Group.cpp
src/core/Group.h
tests/TestGroup.cpp
tests/TestMerge.cpp
tests/TestMerge.h

This changes the merge function to match the groups using the UUIDs, the same way we match the entries. This allows us to do basic conflict resolution on the groups, so we can update the basic information such as the name and the location.
I also removed the `shallow` parameter to `Group::clone` in favor of `CloneFlags`, just like for `Entry::clone`.
I think the next step for the merge function would be to separate the change detection (new entries, new groups, entries or groups changed) and the actual modification of the destination database. This would allow us to fix a couple of issues with the merge function. For example, we could easily implement a dry-run functionality, and we could detect when the database was really modified by a merge operation. This would also allow us to do the …

Merge : Synchronising groups.

---

src/gui/DatabaseTabWidget.cpp
src/gui/DatabaseWidget.cpp

Fixes #1113 
We may want to add test cases for this, but I would defer to the refactor moving saving into the database class.
Databases can be corrupted if autoreload is triggered when the database is locked, reload not accepted, and then saved on exit. These fixes prevent unnecessary dialogs from popping up when databases are locked and also adds an interlock in the save function to prevent corruption.
Manually

Prevent database corruption when locked

---

src/gui/DatabaseOpenWidget.cpp
src/gui/FileDialog.cpp
src/gui/FileDialog.h
src/gui/SettingsWidget.cpp

Fix #1151 
Every successful open/save dialog in KeePassXC save the path in the `LastDir` configuration.
This is a useful feature if you have to open your DB or adding/saving attachment many times.
On the other hand, keeping the directory of the keyfile is not so nice if the user unset "Remember last keyfiles"
**Users should always make their keyfile unavailable to an attacker. 
Hiding the keyfile path is just security by obscurity**
---
Manually …

Forget keyfile path by honoring settings

---

tests/TestOpenSSHKey.cpp
tests/TestOpenSSHKey.h

OpenSSHKey test did not init Crypto and apparently worked by luck. It fails for me now without the required initialization.
OpenSSHKeyTest works again.

Add missing crypto init to OpenSSHKey test

---

src/gui/PasswordEdit.cpp

Resolves #1226 
The default monospace font on Windows is Courier New, which has a few very similar characters. This PR tries to use Consolas instead when KeePassXC is compiled for Windows. Other platforms are unchanged.
Courier New has very similar characters, e.g. I (lowercase L) and 1, which was a problem for the PasswordEdit field.
Compiled on Windows, correct Consolars font is shown.

Use Consolas on Windows for PasswordEdit

---

AppImage-Recipe.sh
Dockerfile

This patch resolves #1157 by embedding update information into the AppImage.
`./KeePassXC-*.AppImage` shows the correct update information according to the specification. The actual AppImageUpdate tool could not be tested, because it crashes.

Add AppImage update information

---

share/keepassxc.ini
src/core/Config.cpp
src/gui/MainWindow.cpp
src/gui/MainWindow.h

Remove the empty "show toolbar" item and the context menu from the toolbar since the option to toggle it was removed at #1116 and without the "View" menu the user can't show the toolbar again after hiding it using the context menu.
Before:

Remove empty context menu from toolbar

---

CMakeLists.txt
src/http/qhttp/http-parser/http_parser.c
src/sshagent/SSHAgent.cpp
src/sshagent/SSHAgent.h

This PR sets the compiler flag `-Werror` to treat all warnings as errors.
In addition, four thrown warnings were fixed, two of them inside third-party code (http_parser.c).
There is no reason why warnings should be tolerated. The code should compile without any warnings, but pull requests keep introducing them and sometimes they go unnoticed, because code is not compiled from scratch. This change will ensure that our CI system will catch any warnings and report an error.
Code compiles fine on my machine and also on CI.
- ✅ I have compiled and verified my …

Treat warning as errors

---

.travis.yml
src/crypto/SymmetricCipherGcrypt.cpp
src/format/KeePass2Repair.cpp
src/format/KeePass2Repair.h
src/gui/DatabaseRepairWidget.cpp
tests/TestCsvParser.cpp
tests/TestCsvParser.h
tests/TestGroup.cpp
tests/TestKeePass2Writer.cpp
tests/TestSymmetricCipher.cpp

Fixed memory leaks non-gui tests
Fixed 2 memory leaks in production code and a few in testcases. As a result `leak_check_at_exit` ASAN option does not need to turned off for non-gui tests.
Smart pointers should be used elsewhere for consistency, but the sooner this fixes are delivered, the lesser memory leaks are introduced.
Memory leaks are bugs in short, so motivation is pretty straightforward :)
No logic was altered, thus existing testcases are sufficient

memory leaks fixes in non-gui tests

---

src/cli/CMakeLists.txt
src/cli/Clip.cpp
src/cli/Command.cpp
src/cli/Estimate.cpp
src/cli/Estimate.h
src/cli/Extract.cpp
src/cli/List.cpp
src/cli/Locate.cpp
src/cli/Merge.cpp
src/cli/Utils.cpp
src/cli/keepassxc-cli.1

The `entropy-meter` CLI command was lagging behind the other commands in terms of style, interface and documentation.
* renamed `entropy-meter` to `estimate`, since all the other commands are verbs
* Used QCommandLineParser for the arguments
* Only allow 1 password (via stdin or CLI arg)
* `clang-format` the whole `cli` directory
* Updated the man page.
Locally
```
$ keepassxc-cli estimate
password
Pass 'password' 	Length 8	Entropy 1.000	Log10 0.301
$ keepassxc-cli estimate password
Pass 'password' 	Length 8	Entropy 1.000	Log10 0.301
$ keepassxc-cli estimate password -a
Pass 'password' 	Length 8	Entropy 1.000	Log10 0.301
Multi-word extra bits 0.0
Type: Dictionary       Length 8  Entropy  1.000 (0.30) password
$ keepassxc-cli estimate -a
password
Pass 'password' 	Length 8	Entropy 1.000 …
```

Rename EntropyMeter -> Estimate

---

share/linux/org.keepassxc.KeePassXC.desktop

As the .desktop file has no StartupWMClass, Gnome can't match the desktop file to the application running.
This causes for example to have a duplicate icon on the dash-to-doc taskbar.
Edit the desktop file, add the line, and add the icon to favourites.
Then start KeepassXC, and you'll notice there is no more duplicate icon.

Add WMClass to the desktop file to have proper linking to the desktop file

---

src/gui/PasswordGeneratorWidget.cpp
src/gui/PasswordGeneratorWidget.h

original PR by @pkill-9  #1044 
In the password generator (standalone, ie not when you're editing an entry) the ESC key is ignored, however in most other dialogs ESC is a shortcut to quit the dialog.
Fix #953 

Quit the password generator with ESC key

---

src/gui/PasswordGeneratorWidget.ui

Enable translations for 'Extended ASCII' button.
The label of that specific button is plaintext. It should be translated. Until now, only the tooltip (same text) was translated.
Tested in an environment configured with locale fr_FR. French text is displayed. Translations are already available in the .ts files.

Enable translations for 'Extended ASCII' button

---

src/cli/Estimate.cpp

Previously the `entropy-meter` was accepting multiple passwords on a single invocation. Now we only allow 1, so we don't need to output the password before outputing the entropy stats.
Following up on https://github.com/keepassxreboot/keepassxc/pull/1250
Locally

Removing password output from Estimate.

---

release-tool

This patch splits GPG signing and EXE/ELF code signing into two commands `gpgsign` and `appsign`. Additionally, it adds support for code signing on macOS using `codesign`.
ELF signatures using a valid Apple Developer ID are needed to get around GateKeeper and to keep things modular, it makes sense to split (platform-dependent) code signing and (platform-independent) GPG signing.
`appsign` command works as expected on macOS with my Apple Developer ID. I couldn't test the (mostly unchanged) Windows `signtool` implementation (@droidmonkey maybe you can test that). …

Separate code and GPG signing and add support for macOS codesign to release-tool

---

src/cli/Show.cpp
src/cli/Show.h
src/cli/keepassxc-cli.1

In order for scripting to be much simpler with `keepassxc-cli show`,
provide a simple --show-attribute API which effectively is just a CLI
interface for entry->attributes()->value(...). This allows for more
extensibility and prevents changes in our output formatting from
breaking existing users of keepassxc-cli (if they use --show-attribute).
Signed-off-by: Aleksa Sarai <cyphar@cyphar.com>
I've recently started scripting around `keepassxc-cli` and I wanted to be able to extract particular fields (especially custom attribute fields) and to avoid having to parse the (unstable) output format.
I tested this on my machine with my existing database. It suffers from #1260, but once #1280 is merged this could be rebased.
- ✅ I have …

cli: show: add --attributes flag

---

src/cli/Show.cpp
src/core/Database.cpp
src/http/AccessControlDialog.cpp
tests/TestEntry.cpp
tests/TestEntry.h

Previously, `keepassxc-cli show` would not resolve references. This
would make it quite hard to script around its output (since there's not
interface to resolve references manually either). Fix this by using
resolveMultiplePlaceholders as with all other users of ->password() and
related entry fields.
Fixes keepassxreboot/keepassxc#1260
Fixes keepassxreboot/keepassxc#1269
Fixes #1211
Signed-off-by: Aleksa Sarai <cyphar@cyphar.com>
I tested this on my own KeePassXC database on several different entries (included nested ones), and verified that entries which were references now resolved to the correct value and that non-reference values also are correctly handled.
- ✅ I have read the **CONTRIBUTING** …

keepassxc-cli show: resolve references in output

---

src/gui/DatabaseWidget.cpp

Discovered this while testing https://github.com/keepassxreboot/keepassxc/pull/1231
Locally
before:
after:

Add \n in merge request message.

---

src/gui/DetailsWidget.ui

This is a follow-up of #879 and #1135, which fixes a remaining layout issue in the preview panel.
I force font size 18 for all Qt applications (via LXQt's settings). This creates a difference for the URL label (font size 9) and other labels (font size 18)
Manually on Arch Linux. See screenshots below.
Before:
After:
- My change requires a change to the documentation and I have updated it accordingly.
- I have added tests to cover my changes.

Fix font size of URL label in the preview panel

---

Dockerfile
release-tool
share/translations/CMakeLists.txt
snapcraft.yaml
src/CMakeLists.txt
src/core/Translator.cpp
src/core/Translator.h
src/main.cpp

This is a work-in-progress PR which resolves #1093.
With this patch, we bundle qtbase translations with KeePassXC builds. For this I refactored the Translator class and added the needed CMake install commands for Windows, macOS and Linux (AppImage only, PPA and other builds should use the system's qt5-translations package).
KeePassXC didn't bundle qtbase translations, so standard buttons were left untranslated when qtbase translations didn't exist on the user's system at the same location as on the distributor's system (on Windows, even a different Msys2 install location was apparently enough to break translations).
Windows portable ZIP and installer ship qtbase_*.qm translations files now. I tested that those are loaded correctly by temporarily renaming my …

Fix missing qtbase translations

---

src/CMakeLists.txt
src/core/EntryAttachments.cpp
src/core/EntryAttachments.h
src/gui/DatabaseWidget.cpp
src/gui/DetailsWidget.cpp
src/gui/DetailsWidget.h
src/gui/DetailsWidget.ui
src/gui/entry/EditEntryWidget.cpp
src/gui/entry/EditEntryWidget.h
src/gui/entry/EditEntryWidgetAdvanced.ui
src/gui/entry/EntryAttachmentsModel.cpp
src/gui/entry/EntryAttachmentsModel.h
src/gui/entry/EntryAttachmentsWidget.cpp
src/gui/entry/EntryAttachmentsWidget.h
src/gui/entry/EntryAttachmentsWidget.ui
tests/TestEntryModel.cpp

Improve entry attachments view.
- Create separate widget to edit/view entry attachments - **EntryAttachmentsWidget**
- Add drag and drop support for attachments view in EntryAttachmentsWidget
- Use EntryAttachmentsWidget to display and edit  attachments in EditEntryWidget
- Add attachments tab to details view - use EntryAttachmentsWidget
- Allow to open attachments from details view
In my opinion, the tableview more user friendly than a listview.
Manually.
**EditEntryWidget** 
**Details view** …

Improve entry attachments view

---

tests/TestCsvParser.cpp

Enforces UTF-8 encoding when performing the Unicode test for the csv parser. Without setting this explicitly, the local environment (eg, MinGW) could incorrectly set this to ASCII causing the tests to fail.
Fixes #612.
Unit tests

Correct encoding ambiguity in CSV Parser unicode test

---

README.md

This is just a simple follow-up CI fix which replaces the now-obsolete Travis build icon with the new TeamCity build icon.
If you can think of anything else we forgot, please tell.
I added guest=1 to the URLs and tested them in incognito browser windows to make sure they are publicly reachable.

Replace Travis build icon with TeamCity build icon

---

src/keys/FileKey.cpp
src/keys/FileKey.h
tests/TestKeys.cpp
tests/TestKeys.h

Resolves #1325
This patch implements a stronger key file generator and adds API documentation for the FileKey class.
The old key file generator created an XML key file with a short embedded random secret instead of a longer purely binary random byte string. The original motivation behind this was probably to be compatible with KeePass 2 (which generates the same kind of key files, apparently even with only 16 byte), but since KeePass 2 also supports usage of arbitrary files as key files, there is no reason to continue generating this kind of key files.
The new implementation generates a 128-byte blob of completely random data and no wrapping XML. The byte stream was generated using libgcrypt's cryptographic RNG. With 128 byte, the key file contents are definitely larger than the resulting …

Generate random 128-byte stream instead of legacy XML format when creating key files

---

share/keepassxc.ini
src/core/Config.cpp
src/core/FilePath.cpp
src/core/FilePath.h
src/gui/MainWindow.cpp
src/gui/SettingsWidget.cpp
src/gui/SettingsWidgetGeneral.ui

- New option `DarkTrayIcon` added to `keepassxc.ini` file, `false` by default.
- File paths now have two additional fields: `applicationIconDark` and `trayIconUnlockedDark`, both refer to the bundled dark icon.
- 'Dark system tray icon' option added to Settings UI
Implements feature request #784.
Tested manually on macOS 10.13 and Ubuntu 17.04.
macOS screenshots attached.

Add dark tray icon parameter to settings.

---

src/gui/MainWindow.cpp
src/gui/MainWindow.ui

Adds a menu role of QAction::NoRole to the database settings action to prevent it from shadowing the application settings action that is automagically moved by MacOS. This fixes #1332 
The PR further removes the hardcoded roles in favor or placing them in the MainWindow.ui file
❌ Needs testing by a MacOS user

Prevent shadowing of application settings on MacOS

---

src/autotype/AutoType.cpp
src/autotype/AutoType.h
src/gui/DatabaseWidget.cpp
src/gui/entry/EditEntryWidget.cpp
tests/TestAutoType.cpp
tests/TestAutoType.h

Replace #552 all credits to @marcbone
Auto Type now shows a warning when you try to  repeat something too often.
Also you can now repeat your password and username
I'm new to all this open source, transifex,qt and c++ stuff. So dont spare with criticism but be nice.
I didnt know how to get the message-strings away from the code and had some problems with the tests, so it would be better if somebody looks over it. Sorry for that.
Large delays and large repetitions arent ignored anymore, instead you get a Messagebox asking you if you want to continue or abort.
Fixes #216 
I changed autoType command to repeat it 101 times and executed the autotype command.
Problem is, if you have multiple commands which are repeated very often (ex. {Password 101} {Username 101}) you get multiple …

Add warning on long Auto Type sequences

---

src/gui/Application.cpp
src/gui/Application.h
src/gui/MainWindow.cpp
src/gui/MainWindow.h
src/main.cpp
tests/gui/TestGui.cpp
tests/gui/TestGui.h

- Implement drag&drop support in main form to open database files 
- Pass command line filenames to already running instance
To simplify the opening of files when one copy of the program is running (if was enabled the option "Start only a single instance of KeePassXC")
Manually on Linux OS
- ❌ My change requires a change to the documentation and I have updated it accordingly.
- ❌ I have added tests to cover my changes.

Pass command line filenames to already running instance

---

CMakeLists.txt

Fixes #1350 
Some distro (namely Gentoo) define _FORTIFY_SOURCE, 
so we need to undefine it before defining it again when compiling a binary
Manually 

undefine FORTIFY_SOURCE before trying to define it. In case it's already defined by the distro

---

src/gui/DatabaseTabWidget.cpp
src/gui/DatabaseTabWidget.h
src/gui/DatabaseWidget.cpp
src/gui/DatabaseWidget.h
src/gui/UnlockDatabaseDialog.cpp
src/gui/UnlockDatabaseDialog.h

Closes #1002 by completely removing the lock file.
This PR also addresses several issues with file handling and cleans up the code to be more streamlined. One major change includes removing a prompt when locking the databases that would never occur with these corrections in place.
First step to optimizing the saving of database files and also helps solve concurrent use issues reported.
Manually and with existing test cases. Future PR's will introduce testing with multiple clients open accessing the same database to ensure data integrity and accurate prompts.
- ✅ All new and …

Remove lock file and cleanup file handling

---

src/autotype/AutoType.cpp

Fix auto-type regression introduced at #1174 that causes the whole sequence to abort when using {delay=x} at the start.
Removed the check if the sequence is empty after the first `{}` tag since `{delay=x}` isn't added as an action at `createActionFromTemplate()` and the sequence syntax is already checked beforehand at `verifyAutoTypeSyntax()`.
Manual testing.

Fix auto-type regression introduced at #1174

---

src/browser/BrowserSettings.cpp

If "Update KeePassXC binary path automatically to native messaging scripts on startup" is not selected (default behavior), native messaging host JSON file contains wrong path " ". This is caused by two issues:
1. Custom proxy path is used even if "Use a custom proxy location if you installed a proxy manually." is not selected
2. BrowserSettings::customProxyLocation() has a wrong fallback
I'm testing this new feature :)
Manually with the just updated keepassxc-browser plugin (version 0.4.8) with Firefox Nightly 59.0a1. I tested two scenarios:
1. Default behavior
* Delete the [Browser] section from keepassxc_debug.ini
* Enable "Firefox" in "Supported browsers"
* Check ~/.mozilla/native-messaging-hosts/org.keepassxc.keepassxc_browser.json and see if it has the correct path
2. Edge case
* …

Improve proxy path handling for the browser plugin

---

src/CMakeLists.txt
src/proxy/CMakeLists.txt

Fixes for building with MacPorts
Fixes the makefiles for building keepassxc-proxy with Qt installed from MacPorts.
Manually.
- ❌ My change requires a change to the documentation and I have updated it accordingly.
- ❌ I have added tests to cover my changes.

Fix for building with MacPorts

---

src/browser/NativeMessagingHost.cpp

Fixes high CPU usage on Linux when stdin is not available.
Shut's down the QSocketNotifier if no data has been read.
Fixes https://github.com/keepassxreboot/keepassxc/issues/1365
Manually.

High CPU fix for Linux

---

src/gui/csvImport/CsvImportWidget.cpp

This PR adds support for importing last modified and created timestamps from CSV's exported from 1password. The user is able to map the correct columns in the CSV Import Widget and have these fields added to the new entries.
Implements feature request #1208. Currently only supports timestamps in Epoch time, since that's what 1password uses and what the ticket opener requested, although I think some good future work might be to add support for other formats from popular password managers (for instance, LastPass, bitwarden, etc. I'm not sure what format these packages use for their created and modified timestamps).
Tested locally on Arch Linux. Tested with malformed CSVs, CSV's with the fields in different orders, CSV's without the extra fields. Also tested with unit tests with …

Implement #1208: CSV Import Created and Modified Dates

---

src/cli/Extract.cpp
src/gui/ChangeMasterKeyWidget.cpp
src/gui/DatabaseOpenWidget.cpp
src/keys/FileKey.cpp
src/keys/FileKey.h
tests/TestKeys.cpp

This is a follow-up PR to #1326, which adds a warning when using legacy key file formats.
When we plan to deprecate old key file formats, we should tell users about it.
Manually and with additional unit tests.

Show warning for legacy keyfile usage

---

src/browser/BrowserService.cpp
src/browser/HostInstaller.cpp

This patch fixes the following browser integration problems:
- Remove unused chrome extension IDs (except the one of @varjolintu's store release which I left for now)
- add extension ID of the to-be official store release
- show a "key already exists" warning only if the key actually does exist in the database when pairing with the browser extension
- activate the key association dialog to bring it to the front (or at least indicate in the task bar, depending on OS window raising policy)
- also properly activate / restore a minimized main window when unlocking (now also works when minimized to tray)
Tested manually on Windows.
- ✅ My code follows the code style of this …

Fix browser integration quirks

---

CMakeLists.txt
src/CMakeLists.txt
src/browser/BrowserOptionDialog.cpp
src/browser/BrowserOptionDialog.h
src/browser/BrowserOptionDialog.ui
src/browser/BrowserSettings.h
src/config-keepassx.h.cmake
src/gui/AboutDialog.cpp
src/gui/EditWidgetIcons.cpp
src/gui/EditWidgetIcons.h
src/gui/KMessageWidget.cpp
src/gui/MainWindow.cpp
src/gui/MainWindow.h
src/gui/MainWindow.ui
src/gui/MessageWidget.cpp
src/gui/MessageWidget.h
src/gui/SettingsWidget.cpp
src/http/CMakeLists.txt
src/http/OptionDialog.cpp
src/http/OptionDialog.ui

This patch makes the following changes to the browser integration settings:
- Reword and reorder options to make them easier to understand and more consistent
- Move browser checkboxes to "General" tab to make them first-class options (will avoid user questions later why integration isn't working)
- Hide unimplemented settings
- Add "Browse..." button to proxy location setting
Furthermore, it deprecates KeePassHTTP and the WITH_XC_HTTP CMake flag and introduces a new WITH_XC_NETWORKING flag which separates general network access code from KeePassHTTP browser integration. Setting WITH_XC_HTTP implies WITH_XC_NETWORKING.
A CMake warning is issued when a user compiles KeePassXC with the deprecated WITH_XC_HTTP flag. Another (one-time) warning is shown to the user upon opening a database if …

Browser integration settings rework and KeePassHTTP deprecation

---

INSTALL.md
README.md
src/CMakeLists.txt
src/browser/BrowserAccessControlDialog.ui
src/browser/BrowserAction.cpp
src/browser/BrowserAction.h
src/browser/BrowserEntryConfig.cpp
src/browser/BrowserOptionDialog.ui
src/browser/BrowserService.cpp
src/browser/BrowserService.h
src/browser/NativeMessagingBase.cpp
src/browser/NativeMessagingHost.cpp

Multiple browser related fixes.
- Fixed new key association request popup displaying (didn't show up in the front)
- The main window is raised only when `triggerUnlock` parameter is `true` (before it was raised with every tab change if the database was locked)
- Renamed keepassxc-browser to KeePassXC-Browser in makefiles, dialogs and documents
- Added a new error `NO_LOGINS_FOUND` which is returned when there is no credentials present
- Added a missing incremented nonce to database hash response
- Fixed an error where QLocalServer was listening to an empty socket
- Error messages are returned with tr()
Manually.
- ✅ I have read the **CONTRIBUTING** …

Multiple browser related fixes

---

src/core/Config.cpp
src/gui/DatabaseWidget.cpp
src/gui/DatabaseWidget.h
src/gui/DatabaseWidgetStateSync.cpp
src/gui/DatabaseWidgetStateSync.h
src/gui/DetailsWidget.cpp
src/gui/entry/EntryModel.cpp
src/gui/entry/EntryModel.h
src/gui/entry/EntryView.cpp
src/gui/entry/EntryView.h
tests/TestEntryModel.cpp
tests/gui/TestGui.cpp

This improves and extends the entry view table,
- Adding additional colums _Password_, _Notes_, _Expires_, _Created_, _Modified_, _Accessed_ and _Attachments_ (addresses #129)
- Adding settings to display usernames/passwords hidden/visible
- Adding a context menu to customize view (toggle column visibility, resize and reset columns) (addresses #17, #129, #397)
- Adding a _'copy-on-doubleclick'_ feature for certain columns (addresses #360)
- Syncing view states when switching between multiple tabs
- Reading/writing last used view settings from/to config
bringing the entry view table in par with KeePassX 0.4.x and even beyond.
**NOTE:**
- KeePassXC's user configuration should be reset prior to testing this
- This is replaces my original pull request #849, providing a clean rewrite with …

Improve and extend entry view table

---

src/autotype/AutoTypeSelectDialog.cpp
src/autotype/AutoTypeSelectView.cpp
src/autotype/AutoTypeSelectView.h
src/gui/PasswordGeneratorWidget.cpp
src/gui/entry/EntryView.cpp

Quit autotype dialog with esc key
Fixes #907

Quit autotype dialog with esc key

---

src/core/Entry.cpp
src/core/Entry.h
src/gui/DetailsWidget.cpp
src/gui/DetailsWidget.h
src/gui/TotpDialog.cpp
src/gui/TotpDialog.h

This PR resolves resolves #1360
1. Fix crash when deleting TOTP entry
2. Fix memory leak when selecting TOTP entries
3. Fix TOTP update timeout on DetailsWidget
4. Fix TOTP settings attributes not being applied before first call to totpSeed()
1. maintained a TOTP update timer which wasn't deleted when the entry was deleted.
2. used to create a new QTimer instance every time a TOTP entry was selected without deleting the old one
3. was too fast by a factor of 100
4. caused TotpDialog to always use the standard settings on first invocation instead of the actual entry settings
Manually and by running existing unit tests. …

Fix multiple TOTP issues, resolves #1360

---

src/core/AutoTypeAssociations.cpp
src/core/AutoTypeAssociations.h
src/core/Entry.cpp
src/core/EntryAttachments.cpp
src/core/EntryAttachments.h
src/core/EntryAttributes.cpp
src/core/EntryAttributes.h
tests/TestEntry.cpp
tests/TestModified.cpp
tests/TestModified.h

Extended the calculation for the size of history items to match KeePass2
Small refactoring regarding readability in EntryAttachements. Fixed issue with AutoTypeAssociations which were not pushed to history.
Extended the calculation of the size for entries in the history to match the algorithm in KeePass2
Added calculation of the size of AutoTypeAssociations and Tags, includes the keys of EntryAttributes. Refactored EntryAttachements to match the general pattern for size calculation. AutoTypeAssociations are now copied to temp-history items to ensure that changes would be pushed to history correctly.
Please see #1387.
Changes tested due to unit tests
- ✅ My code follows the …

Add extend entry-size calculation (resolved #1387)

---

src/gui/DatabaseSettingsWidget.cpp
src/gui/DatabaseSettingsWidgetGeneral.ui

This patch adds a radio button group for choosing between GZip and no compression to the database settings.
There is not really a reason not to enable compression, but KeePass2 has a setting for this and KeePassXC used to just save with whatever compression setting the database was originally opened with. That way you probably wouldn't notice if compression is (accidentally?) turned off and even if you do, you couldn't change it without downloading KeePass2.
By saving and opening with and without compression in both KeePassXC and KeePass2.
- ✅ I …

Add compression options to database settings

---

src/gui/WelcomeWidget.cpp
src/gui/WelcomeWidget.ui

Resolves #1236.
The "Welcome to KeePassXC $VERSION" string on the WelcomeWidget wan't translatable in some languages.

Make 'Welcome to KeePassXC $VERSION' string properly translatable

---

src/core/Config.cpp
src/core/Database.cpp
src/core/Database.h
src/gui/DatabaseTabWidget.cpp
src/gui/DatabaseTabWidget.h
src/gui/SettingsWidget.cpp
src/gui/SettingsWidgetGeneral.ui
tests/gui/TestGui.cpp

* Added backup before save config setting
* Added non-atomic save config setting
* Adds prompt to fallback to non-atomic saves if saving fails 3 times:
* Updated basic settings to be in logical groups:
Fixes #197 and closes #1159 
The risk of data loss is minimal and better than not being able to save at all.
Manually and automatically

Correct saving files to DropBox/Drive/OneDrive

---

src/core/Entry.cpp
tests/TestTotp.cpp
tests/TestTotp.h

Resolves #1445 by wrapping TOTP setup into a transaction.
Setting up TOTP seeds for an entry did not add a history item.
Manually by adding TOTP seeds and with added unit tests.

Create history item when setting up a TOTP seed

---

CMakeLists.txt
cmake/FindYubiKey.cmake

Mainly for mingw, ensure the yubikey libraries are consistently chosen as dynamic or static by appending .dll / .so to the find_library call. Also bumping the minimum c version to c99 to allow for inline.
Some issues I came across while testing.
manually.

Minor cmake updates

---

src/gui/entry/EditEntryWidget.cpp
src/gui/entry/EditEntryWidget.h

When selecting an attachment or browsing for a file to use as the key, change the radio button selection automatically.
I found myself expecting this to happen and it being quite annoying when it didn't.
Manually.

SSH Agent: Always use freshly selected key

---

share/translations/keepassx_en.ts
src/core/Config.cpp
src/core/Config.h
src/gui/DatabaseSettingsWidget.cpp
src/gui/DatabaseSettingsWidget.h
src/gui/DatabaseSettingsWidgetEncryption.ui
src/gui/DatabaseTabWidget.h
src/gui/DatabaseWidget.cpp
src/gui/DatabaseWidgetStateSync.cpp
src/gui/DatabaseWidgetStateSync.h
src/gui/entry/EntryView.cpp
src/gui/entry/EntryView.h

This patch fixes various not explicitly user-defined settings (e.g. opened databases, window geometry, entry view columns) etc. not being persisted reliably on application exit.
Persistence of non-user-defined settings relied on destructors of various QObjects/QWidgets being called after exiting the main event loop and closing the application. This is not guaranteed to happen and therefore many settings weren't synced to persistent storage. I changed the behavior to listen for `QCoreApplication::aboutToQuit()` instead, which is the officially recommended way of doing last-minute activities in Qt.
Actual user settings were not affected, because those are explicitly synced when leaving the settings dialog.
In addition, I snuck in a small translation fix for properly handling plurals in KDF …

Fix settings not being persisted on exit

---

src/CMakeLists.txt
src/core/EntryAttributes.cpp
src/core/EntryAttributes.h
src/core/Group.cpp
src/core/Group.h
src/gui/DatabaseWidget.cpp
src/gui/DatabaseWidget.h
src/gui/DetailsWidget.cpp
src/gui/DetailsWidget.h
src/gui/DetailsWidget.ui
src/gui/widgets/ElidedLabel.cpp
src/gui/widgets/ElidedLabel.h

Refactor details widget
The attempt to simplify the codebase :)
Manually
- ❌ My change requires a change to the documentation and I have updated it accordingly.
- ❌ I have added tests to cover my changes.

Refactor details widget

---

src/gui/entry/EditEntryWidget.cpp
src/sshagent/ASN1Key.cpp
src/sshagent/ASN1Key.h
src/sshagent/CMakeLists.txt
src/sshagent/OpenSSHKey.cpp
src/sshagent/OpenSSHKey.h
src/sshagent/SSHAgent.cpp
tests/TestOpenSSHKey.cpp

Adds support for plain DSA and RSA keys in the "regular" format people actually use.
Candidate for 2.3.0 as it will prevent some support noise.
Not too fond of the partial ASN.1 parser but it works well enough for these key types. Supporting encrypted keys would require importing even more code just for KDF so at this time I'm leaving it out. The integration of these keys into OpenSSHKey class is done in a way decryption is straightforward to add later.
The empty comment thing is so that the username field of an entry is used as it for these keys as the private key file does not contain a comment.
SSH Agent was first introduced supporting only the "new" private key file format which does support all existing key types but the file format is not used by default except for ED25519 keys. …

SSH Agent: Support old unencrypted DSA and RSA keys

---

src/browser/BrowserService.cpp

If we set the window flags after showing/activating the window the
window will not pop up.
Fixes: https://github.com/keepassxreboot/keepassxc/issues/1452

Fix keepass-browser based popups on tiling WMs

---

src/core/Config.cpp

Resolves #1455
Fixes a missing include on macOS.

Re-add QStandardPaths include to fix compilation error on macOS

---

src/CMakeLists.txt
src/autotype/AutoType.cpp
src/autotype/AutoType.h
src/autotype/AutoTypeAction.h
src/autotype/AutoTypeSelectDialog.cpp
src/autotype/AutoTypeSelectDialog.h
src/autotype/AutoTypeSelectView.cpp
src/core/AutoTypeMatch.cpp
src/core/AutoTypeMatch.h
src/core/Entry.cpp
src/core/Entry.h
src/core/Group.cpp
src/core/Group.h
src/gui/entry/AutoTypeMatchModel.cpp
src/gui/entry/AutoTypeMatchModel.h
src/gui/entry/AutoTypeMatchView.cpp
src/gui/entry/AutoTypeMatchView.h
src/gui/entry/EditEntryWidget.cpp
src/gui/entry/EditEntryWidgetAutoType.ui
tests/TestAutoType.cpp
tests/TestAutoType.h

This PR:
- adds support for multiple autotype sequences for a single entry (based from https://github.com/keepassx/keepassx/pull/132)
- fixes some bug with the effectiveAutoTypeSequence
- add tests for effectiveAutoTypeSequence
- refactor AutoType functions
- improved the AutoType Window Association UI/UX
Fixes #559 
Manually and with make tests

Add support for multiple autotype sequences for a single entry

---

src/autotype/AutoType.cpp
src/autotype/AutoType.h
src/autotype/AutoTypeSelectDialog.cpp
src/autotype/AutoTypeSelectDialog.h
src/gui/DatabaseTabWidget.cpp
src/gui/DatabaseTabWidget.h
src/gui/SettingsWidget.cpp
src/gui/SettingsWidgetSecurity.ui

When the main Database is locked and autotype is performed, KeePassXC asks the user to unlock the database and then perform autotype.
This PR add support for re-locking the unlocked DB if autotype is successful, also adding signals for unsuccessful autotype (maybe useful in the future).
Relock is performed only if autotype is successful so if it isn't the user doesn't have to unlock the DB again.
If this behavior isn't acceptable we can connect unsuccessful autotype signals.
The option for relocking after autotype is selectable in the Settings (disabled by default)
Fixes #152 
Manually and with make test …

Relock database after successful autotype

---

src/core/FilePath.cpp
src/core/PassphraseGenerator.cpp
src/core/PassphraseGenerator.h

This patch fixes a Windows regression introduced in 6723f42 and adds some other small code style fixes.
The use of QString in the static `DefaultSeparator` field lead to crashes on Windows, probably because the object wasn't fully initialized at the time it's used inside `PassphraseGenerator`'s initializer list.
This patch changes the QString to a raw `const char*` array.
KeePassXC and tests are not crashing anymore.

Fix Windows regression due to faulty static variable initialization

---

src/crypto/SymmetricCipher.cpp
src/crypto/SymmetricCipher.h
src/crypto/SymmetricCipherGcrypt.cpp
src/sshagent/OpenSSHKey.cpp
src/sshagent/OpenSSHKey.h
tests/TestOpenSSHKey.cpp
tests/TestOpenSSHKey.h
tests/TestSymmetricCipher.cpp
tests/TestSymmetricCipher.h

Candidate for 2.3.0 as it makes the agent feature pretty much feature complete when it comes to common existing keys.
Added required bits to existing OpenSSHKey implementation to decrypt this key type. Added tests for both AES-128-CBC and decrypting an RSA key with it.
Additionally fixed error message translation placeholders.
RSA keys generated with `ssh-keygen` use AES-128-CBC encryption with MD5 used to hash the passphrase (with salt). This is currently still the default for OpenSSH and most likely represents the majority of encrypted SSH keys.
New covering tests added, tested manually in the UI to verify. …

SSH Agent: Support AES-128-CBC encrypted keys

---

src/autotype/AutoType.cpp

This patch fixed Auto-Type error messages about unmatched entries not being raised to the foreground.
The error message that's shown when Auto-Type couldn't find a matching entry wasn't raised and activated explicitly and therefore more often than not totally invisible to the user. I sometimes noticed that I had a bunch of these hidden behind the KeePassXC main window task bar button.
This problem is especially apparent on Windows.
Tested Auto-Type on Windows, message box now comes to the foreground as expected.
- ✅ I have compiled and verified my code …

Fix Auto-Type message not raised when no matching entry was found

---

src/core/Entry.cpp
src/gui/entry/EditEntryWidget.cpp
tests/TestEntry.cpp

This is a 2.3.0 hotfix
Reference resolving in 2.2.4 is broken, you can't resolve a reference if it's in a main field (title, username, etc)
This also prevent recursive loop when resolving references (for example inserting `{TITLE}` in the title field) and fixes a bug in the EditEntry widget not saving AutotypeWindowAssociations.
The code for reference resolving is very repetitive a refactor need to take place in next version.
Manually

Fix resolving reference in entry field

---

src/gui/AboutDialog.ui

This patch enables word wrap for long lines on the About dialog and makes more text (everything except the names) translatable.
On platforms with a larger default font size than Windows, the About dialog was a bit too wide, because the KeePassX acknowledgement line didn't break.

Enable word wrap for long lines on About dialog

---

src/gui/DatabaseWidget.cpp
tests/gui/TestGui.cpp
tests/gui/TestGui.h

Fix issue in #1447 where the headline was showing the wrong path when a group was selected in the side bar.
Added a check in `DatabaseWidget::switchToEntryEdit(Entry* entry, bool create)` that sets the group in the headline to the current group if creating a entry. Otherwise the headline group is the parent group of the entry.
Using the example from the issue, previously the headline would show:
Bad  > Doggy
With this change, we now get:
Good > Doggy
Solves issue #1447. 
Manually. I had a look at the gui tests to try and add a test for this but I can't find a way to access the headline attribute to check it contains the correct values. If I've missed it and someone can point me in the right direction so I can add some tests that would be awesome.
- ✅ Bug fix (non-breaking change which …

Fix Issue #1447 where the wrong path was shown for view/edit when opening via search results

---

src/gui/AboutDialog.ui

This patch fixes a small regression introduced by #1492. 
The maintainer list height was being trimmed down on macOS because the last paragraph didn't have a fixed vertical size policy.
Manually.

Fix about dialog height on macOS

---

src/format/KdbxXmlReader.cpp
src/gui/entry/EditEntryWidget.cpp
src/gui/entry/EditEntryWidget.h
src/gui/entry/EditEntryWidgetAdvanced.ui
src/gui/entry/EntryModel.cpp
tests/gui/TestGui.cpp

Adds full support for displaying foreground and background colors to entry rows. Also centered the paperclip icon in the new extended columns view.
Compatibility with KeePass 2.x
Manually and with KeePass 2.x

Add support for foreground and background entry colors

---

src/gui/DatabaseWidget.cpp
src/gui/EditWidget.cpp
src/gui/PasswordGeneratorWidget.cpp
src/gui/PasswordGeneratorWidget.h
src/gui/entry/EditEntryWidget.cpp
src/gui/entry/EditEntryWidget.h

Adds a warning popup to the user if the password generator is open and the password differs from the one currently in the main password edit field. This change also adds feedback to the user when an entry is successfully updated.
Other changes include:
* Rename saveEntry to commitEntry to accurately capture its purpose
* Add message to user when commit is successful
* Made all inline messages in edit entry view 2 sec visibility
Fixes #870  and fixes #1363 
Manually and unit tests …

Prevent password loss when using generator

---

src/gui/SettingsWidget.cpp

Fix https://github.com/keepassxreboot/keepassxc/issues/1515#issuecomment-367936968
Manually

Enable focus outline for global auto-type shortcut on macOS

---

AppImage-Recipe.sh
release-tool

Fixes AppImage crashing on older systems, resolves #1522.
The runtime library search paths for libgcrypt and libgpg-error were wrong, so the versions from the host system were used, which doesn't work on Xenial or older.
Additionally, our custom libgpg-error was stripped from the AppImage by the blacklist function, so it couldn't be found even if the paths had been correct. This patch fixes both issues.
Ran AppImage on Ubuntu Trusty.

Fix libgcrypt and libgpg-errror paths in AppImage

---

src/gui/DatabaseWidget.cpp
src/gui/entry/EditEntryWidget.cpp

There was a crash that occurred when the history was truncated and an entry was committed. This became apparent when we started showing the entry save successful message. The root cause is a stale entry pointer that is stored in the history model, but not updated when the actual pointer is deleted.
Also remove the entry update message when you hit "OK"
Crashes are bad... and this one loses data!
Manually

Correct intermittent crash due to stale history items

---

CMakeLists.txt
share/translations/CMakeLists.txt
src/CMakeLists.txt
src/proxy/CMakeLists.txt

Fixes hard-coded Qt paths in proxy/CMakeLists.txt, resolves #1518 
The CMakeLists.txt file hard-coded paths to Qt libraries, which only worked with upstream Qt, but not with Homebrew Qt. This resulted in failure of the install_name_tool to change the Qt link library paths for keepassxc_proxy.
Compiled on macOS and keepassxc_proxy now correctly links to @executable_path/../* (tested with `otool -L`).

Don't hardcode install_name_tool change path

---

AppImage-Recipe.sh
src/browser/BrowserOptionDialog.cpp
src/browser/BrowserOptionDialog.ui
src/browser/HostInstaller.cpp

This patch enables proper interaction between KeePassXC-Browser and KeePassXC AppImages.
KeePassXC-Browser used to execute either the keepassxc_proxy or keepassxc binary directly from the AppImage mount path (depending on the user settings). This only works if the user has the correct version of all necessary libraries installed.
This patch changes the behaviour for AppImages so that the AppImage binary is launched by the browser. The AppImage distinguishes between regular calls and browser calls by checking if the `CHROME_WRAPPER` or `MOZ_LAUNCHED_CHILD` environment variables are set. In addition, a user can explicitly launch the proxy by starting the AppImage with a positional `proxy` parameter (unfortunately, that doesn't work with native messaging manifest files).
Furthermore, if …

Enable keepassxc_proxy for AppImage builds

---

src/gui/entry/EditEntryWidget.cpp
tests/gui/TestGui.cpp

Replaces newlines in entry title, username and URL with spaces when saving an entry. Resolves #1502 
Prevents awkward newlines in entry listings when copy-pasting data into KeePassXC.
Since the affected fields are single-line input fields and display newlines as spaces, they should also be saved as such. Only exception is the password field, here I skipped newline sanitization and retain the password as-is, so people don't lock themselves out of their services accidentally.
Manually and with added test cases. …

Strip newlines from title, username and URL when saving entries

---

AppImage-Recipe.sh
Dockerfile
ci/trusty/Dockerfile
src/CMakeLists.txt

1. Updates the library paths in our deployment and CI scripts (AppImage recipe and Dockerfiles) and adds libcurl-no-gcrypt as new dependency.
2. Bundles selected Qt plugins with the AppImage and Windows build (i.e., imageformats and platforminputcontexts), resolves #1195 and #1439
I updated the PPA packages to install into a common root under /opt/keepassxc-libs instead of each having an individual root under /opt. This makes everything more manageable, requires less custom build paths and keeps /opt cleaner. I also added a new (OpenSSL-flavoured) `libcurl-no-gcrypt` package to the Trusty PPA, because all three `libcurl4-*` flavours from the Ubuntu repo directly or indirectly pull in `libgcrypt11`, which conflicts with `libgcrypt20` when linked into the same binary (yes, even …

Update library paths in AppImage recipe and Dockerfiles

---

src/core/Database.cpp

Changes the regular expression for generating the backup file name when "Backup database before saving" is turned on to avoid double replacement.
Qt replaced all *possible* occurrences of the regular expression, resulting in a doubled file extension (.old.kdbx.old.kdbx). This patch changes the behavior to only add .old.kdbx. If a file already ends in .old.kdbx, the backup file is named .old.old.kdbx.
Manually.

Avoid double file extension replacement in backup filename

---

CMakeLists.txt
release-tool
src/proxy/CMakeLists.txt

Replaces the hardcoded path HINT for macdeployqt with  a dynamic one.
In #1529 I added a new `${Qt5_PREFIX}` CMake variable, which points to the Qt install location on Windows and macOS, which we can use here instead of hardcoding a path to /usr/local/opt.
Not at all, @varjolintu @weslly someone of you please test, I don't have a Mac here atm.

Don't hardcode HINTS to macdeployqt

---

src/core/Database.cpp

Resolves #1511 by using copy instead of rename for unsafe saves on Linux.
Our workaround for the original Qt bug, which we implemented unsafe saves for, got busted by yet another Qt bug, which makes unsave saves with rename fail. See See https://bugreports.qt.io/browse/QTBUG-64008
Manually on an affected machine.

Use copy instead of rename for unsafe saving on Linux

---

src/CMakeLists.txt
src/gui/EditWidgetIcons.cpp

Follow-up PR on #1534, which adds missing Windows platform style plugins and CA bundles.
When no /mingw64 environment was available on the target system, KeePassXC started with Windows 95 classic look due to missing platform styles. I don't know why we didn't have this problem before, but maybe something changed with Qt 5.10.
With this patch I added the missing qwindowsvistastyle.dll and also the qdirect2d.dll platform plugin to the list of deployed plugins.
Another missing piece were CA bundles, without which cURL failed to verify TLS certificates. This was also added.
I renamed my /mingw64 root and started KeePassXC. Platform theme works ok and HTTPS downloads work as well. On the other hand, when run from within the build directory, where no ssl/certs/ca-bundles.crt deployment exists, …

Fix missing Qt platform styles and CA bundles in Windows release deployment

---

src/CMakeLists.txt

Without this patch I see:
````
[ 74%] Linking CXX executable keepassxc
../libkeepassx_core.a(ScreenLockListenerPrivate.cpp.o): In function `ScreenLockListenerPrivate::instance(QWidget*)':
/scratch/security/keepassxc/work/keepassxc-2.3.0/src/core/ScreenLockListenerPrivate.cpp:38: undefined reference to `ScreenLockListenerDBus::ScreenLockListenerDBus(QWidget*)'
[ 74%] Building CXX object src/autotype/xcb/CMakeFiles/keepassx-autotype-xcb.dir/keepassx-autotype-xcb_autogen/mocs_compilation.cpp.o
../libkeepassx_core.a(MainWindow.cpp.o): In function `MainWindow::MainWindow()':
/scratch/security/keepassxc/work/keepassxc-2.3.0/src/gui/MainWindow.cpp:174: undefined reference to `MainWindowAdaptor::MainWindowAdaptor(QObject*)'
--- src/cli/keepassxc-cli ---
...
libkeepassx_core.a(MainWindow.cpp.o): …
```

Fix build on NetBSD.

---

CMakeLists.txt

When checking out a tag, if you previously build a snapshot, the `KEEPASSXC_BUILD_TYPE` variable will be cached to `"Snapshot"`.
With this we explicitly force `"Release"` if the git repo is set to a tag by using the `OVERRIDE_VERSION` option
Manually

Release build when checking out a git-tag

---

src/format/KdbxXmlWriter.cpp
src/format/KeePass2Writer.cpp
src/format/KeePass2Writer.h
tests/TestKdbx4.cpp

Fixed KeePassXC incorrectly (unnecessarily) upgrading to KDBX 4 if CustomData are available on the meta data section.
Resolves #1563 , #1565 and #1584.
KDBX 4 upgrade should only be done for CustomData in entries or in the KDBX header, not in database meta data. Although an upgrade in itself is not a bad idea, it shouldn't be done automatically if it's not strictly needed.
I know I fixed this bug before and it must have been re-introduced somewhere along the way.
Manually and with updated upgrade tests. …

Don't upgrade to KDBX 4 when CustomData are present only in meta data section

---

src/core/MacPasteboard.h
src/gui/Clipboard.cpp
src/gui/Clipboard.h

Removes deletion of the MacPasteboard instance on exit, working around a crash due to a Qt bug. Resolves #1543.
Regression was introduced in 806248ebd
QMacPasteboardMime subclasses are registered and de-registered using ctors/dtors, but after deleting an instance, Qt keeps a dangling pointer, which it tries to delete again on program exit (https://bugreports.qt.io/browse/QTBUG-54832).
Since our MacPasteboard instance lives for the whole program duration, anyway, it's no big loss to simply not delete it and let Qt or, at the latest, the OS take care of it.
KeePassXC doesn't crash anymore when opening and locking a database and then exiting the program with Cmd+Q.
- ✅ My code …

Do not delete MacPasteboard instance on exit, resolves #1543

---

src/main.cpp

Fixes basic filename, --pw-stdin and --keyfile parameters being ignored.
Resolves #1358, resolves #1533, resolves #1600
Regression was introduced in 06518c5736
The line for processing basic command line parameters for the file to open, --pw-stdin, and --keyfile was removed. As a result, opening files via double click, or by specifying its name on the command line stopped working. So did specifying a keyfile or a password via STDIN. This patch restores the line.
Manually on Linux and Windows. Filenames (double-click open and explicit command line parameter), --pw-stdin and --keyfile work as expected.
If an instance is already running, the filename parameter is properly passed on to the running instance. …

Fix regression: basic filename, password and keyfile command line parameters being ignored

---

src/gui/DatabaseWidget.cpp

Resizes the details widget to its minimum size when no saved UI state is available.
Upon first start of KeePassXC, the details widget used to gobble up some 30 or 50% of the vertical screen space instead of just its minimum height. This patch resizes it down to its minimum size hint. If a saved UI state is available (i.e., if this is not the first start), it will override the size with whatever size the user has resized the widget to.
Manually on Windows by deleting the config file. …

Resize details widget to minimum by default

---

src/gui/entry/EditEntryWidget.cpp
src/gui/entry/EditEntryWidget.h
src/sshagent/OpenSSHKey.cpp
src/sshagent/SSHAgent.cpp

Fixes #1560
Multiple UI issues caused by not having public key available have been fixed as well. All old RSA keys are *always* decrypted for display now, there's no manual decrypt option available for such keys.
The changes also handle the edge case that should not happen that such key is loaded but not decrypted.
Tested all kinds of keys in all kinds of situations by hand in the UI and automatic add/removal. Could not find any issues so far.

SSH Agent: Fix handling of encrypted RSA keys

---

src/gui/CategoryListWidget.cpp

Fixes usage of possibly undefined value in a branch condition.
I found this bug with valgrind.
No more valgrind warnings about "Conditional jump or move depends on uninitialised value(s)".

Avoid conditional use of possibly uninitialized value in CategoryListWidgetDelegate

---

share/translations/keepassx_en.ts
src/core/Translator.cpp
src/format/KeePass2.cpp
src/gui/DatabaseSettingsWidget.cpp

Despite a previous fix, qtbase translations were not loaded in 2.3.0. This patch fixes this issue.
Also fixes cipher/KDF translations not being applied.
Qt standard widgets were not translated.
Manually, by selecting a language other than English.

Fix qtbase translations not being loaded (regression)

---

CMakeLists.txt
src/http/Server.cpp

Resolves #1558 by overwriting the KeePassHTTP password string without the use of memset() and enabling -Werror only for debug builds.
GCC 8 issued a warning about use of memset for non-trivial type QChar.
I don't have GCC 8, so I could only test with GCC 7.2 that everything continues to work.

Fix GCC 8 memset warning and set -Werror only for debug builds

---

src/autotype/AutoType.cpp
tests/TestAutoType.cpp

Fix #1546 
Extend the Autotype Syntax to Custom Fields/Attributes
Manually and with tests

Fix autotype syntax to support custom attributes

---

src/format/KdbxReader.cpp

Building with -flto caught the fact that we were ignoring the return
value of readMagicNumbers(), which potentially left the value of 'sig2'
uninitialized.

KdbxReader::readDatabase: abort if reading magic numbers fails

---

src/core/Entry.cpp

Currently, when a field value contains a reference plus other things, then:
* Auto-type is broken with that field
* References to this field are not properly resolved
This commit fixes both issues.
When editing database entries, one can use placeholders such as `{USERNAME}`, `{PASSWORD}`, `{URL:HOST}` (these will typically be used in auto-type patterns), but also reference placeholders like [`{REF:x@y:zzzz}`](http://keepass.info/help/base/fieldrefs.html), that indicate to use a value from a given field in a given entry.
The function `resolvePlaceholderRecursive`, will attempt to replace a placeholder with the final value it points to. It calls itself if the resulting value consists of a placeholder, such as reference to reference is also supported. However when the resulting value …

Allow references to be part of a field

---

src/gui/EditWidgetIcons.cpp

Fixes hanging favicon downloads for some websites.
Resolves #1573 and resolves #1645
Some websites seem to accept a TCP connection, but send no HTTP response when no User-Agent header is set. Because we sent no User-Agent and only set a connect timeout, but not a total request timeout, the download hung infinitely.
This patch adds a generic "curl" User-Agent and sets an overall request timeout of 10 seconds.
I removed the `CURLOPT_SSL_VERIFYPEER` option, because `1L` is already [the default](https://curl.haxx.se/libcurl/c/CURLOPT_SSL_VERIFYPEER.html).
I tested it with the example URLs provided in the linked issue reports and could download the favicons successfully.
- ✅ My …

Add User-Agent header and set request timeout to avoid infinite download hangs

---

src/gui/MainWindow.cpp
src/gui/MainWindow.h
src/gui/entry/EditEntryWidget.cpp
src/sshagent/SSHAgent.cpp
src/sshagent/SSHAgent.h

Implements in-entry messages when using manual add/removal and messages on lock/unlock.
Error handling is currently silent and is a blocker for a user to figure out what's wrong. Considering this a UX bug.
Manually.

SSH Agent: Show error messages if there are problems with agent communication

---

src/format/KdbxXmlReader.cpp
src/format/KdbxXmlReader.h

When parsing KDBX XML, the KdbXmlReader now supports Protected="true" on all attributes where `readString` or `readBinary` is used.
I had a KDBX 3.1 file which contained Binary entries with Protected="true". This lead to KeePassXC mostly reading the file fine, but because of the differences in the state of the random stream all passwords and attached files were silently mangled.
I am not sure which application created those (KeePass2, KyPass or Keepass2Android), but KeePass2 seems to parse Protected="true" in a similar way in its `KdbxFile::ProcessNode` method. To solve this specific case, handling Protected="true" only on `<Binary>` elements would have sufficed, but this could have lead to additional bugs later on if any other element is ever protected. This could corrupt the database. …

KdbxXmlReader: Support Protected attribute on most nodes

---

src/gui/DatabaseWidget.cpp
src/gui/MainWindow.cpp

The 'text' property of the QAction gets mangled by KDE when it adds its own accelerator shortcuts. But the data property is ours. Use that for keying instead.
---
Fixes #1569. The "not a bug" tag on there is totally misleading. Even if KDE is mangling the text attribute we can avoid breaking users by not using the mutable "text" property for keying into the attributes map.
I doubt that the Qt designers ever intend you to *read* the value of the text property programatically and use that for keying. It's generally assumed that it can be mangled by localization (or KDE's default accelerators thing in this case).

attributes: unbreak copy-to-clipboard on KDE

---

src/browser/NativeMessagingHost.cpp
src/main.cpp
src/proxy/NativeMessagingHost.cpp

Fixes a freeze and high CPU usage when provided with invalid STDIN data and/or a wrong database filename.
Resolves #1620
Manually. The reproduction examples in #1620 don't freeze KeePassXC anymore.

Fix freeze and high CPU usage on invalid STDIN data

---

src/keys/CompositeKey.cpp
src/keys/CompositeKey.h

Fail with an error when challenge-response failed during key transformation instead of silently discarding the key component.
Resolves #1656.
Saving a KDBX 3.1 file failed with an error message when challenge-response failed (e.g. YubiKey wasn't inserted). KDBX 4 silently discarded the key component. This is a user error which we should prevent.
Saving a KDBX 4 file fails when I unplug my YubiKey.

Raise error if challenge-response failed during KDBX4 key transformation

---

src/CMakeLists.txt

Removes qsvg.dll from the list of installed Qt plugins on Windows.
Resolves #1602
The Windows distribution crashed on some systems when trying to load SVG icons. Without an installed Qt5Svg.dll, this plugin is useless anyway, so we may as well remove it for now.
For KeePassXC 2.4 we will move to windeployqt, which will hopefully fix this issue properly.
I could reproduce crashes after adding Qt5Svg.dll to my installation and removing qsvg.dll fixes them again. I could not test it without Qt5Svg.dll, because qsvg.dll isn't loaded on my system, when Qt5Svg.dll is missing. …

Remove qsvg imageformat plugin to prevent crash when trying to load SVG icons

---

tests/TestAutoType.cpp
tests/TestKdbx4.cpp
tests/TestKdbx4.h

This speeds up the slowest tests, AutoType and Kdbx4, by adjusting some parameters which should not influence the tested semantics.
Tests are slow. It's more fun to write code with faster test suites.
I ran tests on Debian GNU/Linux on an i7-6700K with ASAN on and off. The times went down from approximately 9.71s and 8.72s respectively to 4.38s and 3.08s for a `make test`. `TestKdbx4` is still slow (still lots of cryptography), but `TestAutoType` is almost negligible.
- Speed optimization

Test speedup

---

src/core/FilePath.cpp
src/core/FilePath.h
src/gui/MainWindow.cpp

Introduces a separate path for tray icons which are neither locked nor unlocked and uses that when setting the tray icon while always using the default icon as an application icon.
Closes #1556.
Built on Linux, ran tests. Checked title bar, about menu, application switcher and tray icon with option turned on and off in KDE. Not sure if all platforms support differing application and tray icons, but I think this should work on the most popular ones.

Fix dark tray icon option making all icons dark

---

src/main.cpp

Make `--pw-stdin` use `getPassword()` instead of `readLine()`
A minor change to use the `getPassword()` function from CLI.
I've also updated the translation files and I'd like a thumbs up on that.
Fixes #1673
Manual testing plus `make test`

Change `--pw-stdin` to use `getPassword()`

---

src/autotype/AutoType.cpp
src/autotype/AutoType.h

Fixes crash on Windows due to double mutex unlock. Resolves #1561.
On Windows, the rejected() slot of the Auto-Type selection dialog was called twice on screen lock, resulting in a double mutex unlock. I have no idea why it's doing that (perhaps a bug introduced in Qt 5.10), but this patch works around it by making sure the mutex is locked before we try to unlock it.
In addition, I added another mutex for the actual auto-typing (not just the dialog) to ensure we are never auto-typing two sequences at the same time (not that this was an issue, but when we're already at it...)
Manually on Windows. I could not reproduce the crash anymore after applying the patch.
- ✅ My code …

Fix inconsistent mutex unlocking due to double slot execution

---

src/gui/DatabaseOpenWidget.cpp

Fixes #1692
Always set the password to be hidden on unlock and force processing events to make that change is applied before blocking the UI thread.
Manually on Linux and Windows.

Always hide password on unlock

---

src/gui/entry/EditEntryWidget.cpp
src/sshagent/SSHAgent.cpp

gpg-agent doesn't understand how to handle comment strings that are zero-length. It correctly reads the length of the comment string, but then requests a read of 0 bytes, which stupidly returns an EOF error code:
```
$ gpg-error 67125247
67125247 = (4, 16383) = (GPG_ERR_SOURCE_GPGAGENT, GPG_ERR_EOF) = (GPG Agent, End of file)
```
I looked at ensuring the `m_comment` string is always at least length 1, but that turned out to be a much uglier change.
I'm not able to use the OpenSSH-provided ssh-agent, because most of my SSH keypairs are actually PGP keys stored on YubiKeys -- and those require gpg-agent to use. For the remainder of my on-disk PEM keys, I can load those into KeePassXC... But only if gpg-agent will accept the keys.
I found the issue by trying to add my SSH keypairs to …

OpenSSHKey: when writing to agent, ensure comment string is at least one byte

---

src/gui/entry/EditEntryWidget.cpp
src/gui/entry/EditEntryWidget.h

The list of available attachments for SSH agent is now updated
immediately when adding or removing file attachments.
When adding or removing attachments, the list of available attachments was previously only updated after hitting `Apply` or `OK`.
Closes #1668.
Built on Linux, ran tests and tried adding and removing files with previously empty and non-empty lists. Also checked if removing a selected file would lead to an error.

SSH Agent: Update available attachments immediately

---

src/sshagent/SSHAgent.cpp

This adds more helpful error messages when adding keys to an agent
fails.
With the generic error message it is unclear as to where the error is. This would probably happen alot to people using the popular PuTTY agent on Windows.
Closes #1667.
I compiled on Windows and Linux, ran the test suites and checked whether the messages where shown as expected.

SSH Agent: Helpful error message for adding keys

---

README.md

Fixes the KeePassXC-Browser Chrome Web Store URL from the front page README (develop branch).
- ✅ Documentation / README

Fix extension URL

---

src/gui/MainWindow.cpp
src/main.cpp
tests/gui/TestGui.cpp
tests/gui/TestGui.h

**Opening another PR since PR #1700 had the wrong source branch. Sorry for the annoyance...**
Fix/work around tray issues on some Linux systems such as Arch Linux, and Windows. Fixes all cases explained in issue #1595.
Basically there are two separate issues at play there:
* **The Linux issue:** Sometimes instead of restoring, the KeePassXC window just flickers when restoring the window from the tray. This mostly happens if both the "minimize to tray" and "minimize at startup" options are enabled, and only on the first restore, though sometimes it's enough to set the  "minimize to tray" option is enough and the flicker happens once per every restore, thus the tray having a flicker-restore-hide cycle instead of a restore-hide cycle. I'm not sure why it only happens on Arch but not on …

Fix problems with the hide/restore functionality on the tray icon (issue #1595) (redone)

---

src/browser/NativeMessagingBase.cpp

NativeMessagingBase::sendReply send incorrectly formatted payload back to keepassxc-browser extension when using some locales.
* Using length() on QString won't return correct size in bytes when string
contains UTF-8 chars.
This commit fix many bugs with keepassxc-browser when keepassxc locale is set to a language with chars represented by multiple bytes (UTF-8). 
For instance, error string "Aucun identifiant trouvé" ("No logins found" in french) cause keepassxc-browser extension to disconnect from database.
This fix solves my issues in keepassxc-browser (firefox / chromium tested), with keepassxc in french. …

Fix wrong reply size in NativeMessagingBase

---

src/sshagent/blf.h
src/sshagent/blowfish.c
src/sshagent/includes.h

Both `blf.h`and `blowfish.c` are restored to their current [**upstream's state**](https://github.com/openssh/openssh-portable/tree/58fd4c5c0140f6636227ca7acbb149ab0c2509b9/openbsd-compat), and a reduced `includes.h` is added, that also keeps the windows specific modifications formely contained in `blf.h`.
Musl-libc needs explicit inclusion of `<sys/types.h>`, so keepassxc couldn't be built.
In specific,  `u_int32_t` types were not declared.
I built `2.3.1` including this patch using Void Linux' build system [**xbps-src**](https://github.com/voidlinux/void-packages) against glibc and musl-libc, which works now.
Also see [**here**](https://github.com/voidlinux/void-packages/pull/12441). …

Keep blowfish code unmodified

---

src/browser/BrowserOptionDialog.cpp
src/browser/BrowserService.cpp
src/core/CsvParser.cpp
src/core/Database.cpp
src/core/Entry.cpp
src/core/Group.cpp
src/format/Kdbx3Reader.cpp
src/format/KdbxXmlReader.cpp
src/format/KeePass1Reader.cpp
src/gui/AboutDialog.cpp
src/gui/ChangeMasterKeyWidget.cpp
src/gui/DatabaseOpenWidget.cpp
src/gui/DatabaseRepairWidget.cpp
src/gui/DatabaseTabWidget.cpp
src/gui/DatabaseWidget.cpp
src/gui/DetailsWidget.cpp
src/gui/EditWidgetIcons.cpp
src/gui/MainWindow.cpp
src/gui/SearchWidget.cpp
src/gui/TotpDialog.cpp
src/gui/csvImport/CsvImportWidget.cpp
src/gui/csvImport/CsvParserModel.cpp
src/gui/entry/EditEntryWidget.cpp
src/gui/entry/EntryAttachmentsWidget.cpp

This contains multiple different changes to (hopefully) improve translation base strings.
- In file dialog filters, only translate the text describing the filter, not the whole filter setup (e.g. only `"Executable Files"` and `"All Files"` in `"Executable Files (*.exe);;All Files (*.*)"`)
- Fix the capitalization of some base strings to be more consistent with other base strings, as the capitalization difference doesn't seem to be semantically important
- Where trailing whitespace isn't relevant to the translation, remove it from the base strings; where it _is_, instead use positional arguments and request the whole fragment be translated (e.g. `"Unable to create key file: %1"`, not `"Unable to create key file: ".append(…)`)
- Reduce other concatenation of strings (e.g. now `"Expires in …

Improve translation base strings

---

src/gui/MainWindow.cpp

Ignoring closeEvent signals that the application doesn't want the widget to be closed. This may cause unwanted shutdown interruption. There's no difference between close() and hide() unless WA_DeleteOnClose is set, so it's better to just accept the event if we're hiding the window
afterwards anyway.
This change *should* fix the issue #856, however I can't test it on all platforms to vouch
Tested this on Plasma 5.11.5, it fixes the shutdown interruption
However, I can't test it on Windows or Mac to confirm that it truly fixes the issue everywhere
- ✅ I …

Do not ignore MainWindow closeEvent when closing to tray

---

src/gui/EditWidget.cpp
src/gui/EditWidget.h
src/gui/EditWidgetIcons.cpp
src/gui/EditWidgetIcons.h
src/gui/entry/EditEntryWidget.cpp
src/gui/entry/EditEntryWidget.h
src/gui/entry/EntryAttachmentsWidget.cpp
src/gui/entry/EntryAttachmentsWidget.h
tests/gui/TestGui.cpp

When the user clicks on the Apply button, it will get disabled. When changes are made, it's enabled again.
* Whenever the Apply button is pressed, and if the save was successful, then the Apply button is disabled.
* Each subwidget used by EditEntryWidget has now a signal called `widgetUpdated` that is emitted when the widgets' internal content changes. The EditEntryWidget subscribes to that signal to know when to enable the Apply button (by calling `entryUpdated()`).
* There are some views that are not isolated in their own widgets (`m_advancedUi`, for example) so in those cases I invoked `entryUpdated()` directly whenever I detected an update:
* some updates occur directly in a Qt widget like when editing the text of a QLineItem, so in that case I connected the widget's signals directly …

Grey out Apply button when there are no changes

---

src/browser/BrowserAction.cpp
src/browser/BrowserService.h
src/browser/NativeMessagingBase.h
src/browser/NativeMessagingHost.cpp
src/proxy/NativeMessagingHost.cpp

Increases the maximum buffer size of keepassxc-protocol and Unix Sockets to 1M. This is the maximum messaging size for a single message with native messaging.
Solves issues where the message size goes over the maximum default of Unix Socket buffer 8k bytes.
Manually.

Socket buffer fix

---

src/browser/NativeMessagingBase.cpp

Changes socket location in macOS from `/tmp/kpxc_server` to user's temporary dir.
Allows multiple users.
Solves https://github.com/keepassxreboot/keepassxc/issues/1745.
Manually.

Change socket location in macOS to temporary dir

---

src/gui/entry/EditEntryWidget.cpp

Fixes an error message and non-working functionality introduced by a
wrong slot referenced in PR #1679. Compare comments in PR.
Fixed reference.
The previous commit referred to a wrong slot and thus did not have any effect but producing an error. This probably happened because the wrong version was pushed into Git.
All tests have been repeated as for the original version, just this time pushed the correct version.

SSH Agent: Fix wrong slot reference

---

src/sshagent/OpenSSHKey.cpp
tests/TestOpenSSHKey.cpp
tests/TestOpenSSHKey.h

The code for parsing OpenSSH private key files is broken for aes-256-cbc and aes-256-ctr encrypted keys in PEM format.
... to correctly load encrypted SSH keys.
Not fully tested yet.

OpenSSHKey: correctly parse aes-256-cbc/ctr keys

---

src/CMakeLists.txt
src/gui/EditWidgetIcons.cpp
src/gui/EditWidgetIcons.h
src/main.cpp

This pull request improves the favicon fetching process.
Here is a summary of the changes:
* Eliminate dependency on libcurl. We already depend on Qt5Network, so why not use the HTTP fetching from there?
* Show a progress dialog when downloading the favicon. The main utility of this is giving the user the option to cancel a download attempt (e.g. if it's taking too long). If the user clicks "cancel", it will cancel the current download attempt and try the next fallback URL in the list.
* Try three different ways to obtain the favicon, in this order:
* Direct to fully-qualified domain name (e.g. `https://foo.bar.example.com/favicon.ico`)
* Direct to 2nd-level domain name (e.g. `https://example.com/favicon.ico`)
* Google lookup for 2nd-level domain name (if enabled in settings)
I changed …

favicon fetch improvements

---

src/core/Tools.cpp

Changing the order of the includes on Tools.cpp at #1191 broke compiling on macOS.
```
In file included from ~/Projects/keepassxc/src/core/Tools.cpp:50:
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/usr/include/sys/ptrace.h:99:38: error: unknown type name 'caddr_t'
int     ptrace(int _request, pid_t _pid, caddr_t _addr, int _data);
^
1 error generated.
make[2]: *** [src/CMakeFiles/autotype.dir/core/Tools.cpp.o] Error 1
make[1]: *** [src/CMakeFiles/autotype.dir/all] Error 2
```
Manually

Fix build error on macOS

---

src/proxy/CMakeLists.txt
src/proxy/NativeMessagingHost.cpp

Fixes Windows build of https://github.com/keepassxreboot/keepassxc/pull/1720.
Manually.

Fix Windows build with socket size

---

src/browser/BrowserService.cpp

When running Set up TOTP a additional KPH attribute for `{TOTP}` is created for browser integration if it doesn't already exist.
Fixes https://github.com/keepassxreboot/keepassxc/issues/1652.
Manually.

Pass TOTP with credential data to KeePassXC-Browser

---

src/browser/BrowserAction.cpp
src/browser/BrowserService.cpp
src/browser/BrowserService.h

Ignores non-connected databases if search from all databases option is enabled in Browser Integration settings.
Previously searching from all databases returned entries also from non-connected databases, which is not very secure. This change only searches from databases that are connected with the browser extension. KeePassXC-Browser side change is needed, although it can be merged beforehand.
KeePassXC-Browser side PR here: https://github.com/keepassxreboot/keepassxc-browser/pull/108.
Must be merged after https://github.com/keepassxreboot/keepassxc/pull/1497 is merged.
Manually. …

Ignore non-connected databases from search with Browser Integration

---

src/browser/BrowserService.cpp

When updating credentials from KeePassXC-Browser the QMessageBox is now brought to the front.
Previously the messagebox was visible behind the browser window.
Fixes https://github.com/keepassxreboot/keepassxc/issues/1829.
Manually.

Brings messagebox to the front when updating credentials from KeePassXC-Browser

---

src/browser/BrowserService.cpp
src/browser/BrowserService.h

If an unlock request has been sent by KeePassXC-Browser lower the KeePassXC main window after unlock.
Fixes https://github.com/keepassxreboot/keepassxc/issues/1715
Manually.

Lower after unlock request from KeePassXC-Browser

---

src/browser/BrowserOptionDialog.cpp
src/browser/BrowserService.cpp
src/browser/BrowserSettings.h

Returning only the best matched entries option hasn't worked properly. This fixes it and only returns entries with sort priority 100.
It's not perfect but a small improvement. If you can think anything that could improve this PR please let me know.
Fixes 
https://github.com/keepassxreboot/keepassxc-browser/issues/84
Fixes #1112
Manually.

Implement best matches only option with browser integration

---

src/autotype/AutoType.cpp
src/autotype/AutoTypePlatformPlugin.h
src/autotype/mac/AutoTypeMac.cpp
src/autotype/mac/AutoTypeMac.h
src/autotype/test/AutoTypeTest.cpp
src/autotype/test/AutoTypeTest.h
src/autotype/windows/AutoTypeWindows.cpp
src/autotype/windows/AutoTypeWindows.h
src/autotype/xcb/AutoTypeXCB.cpp
src/autotype/xcb/AutoTypeXCB.h
src/core/Config.cpp
src/gui/SettingsWidget.cpp
src/gui/SettingsWidgetGeneral.ui

Fixes #1864 
Add's a configuration option to set the global autotype start delay. Previously it was hardcoded at 500ms which might be too quick for some people to release the global shortcut keys prior to typing beginning.
Manually

Configurable global autotype start delay

---

src/gui/DetailsWidget.cpp
src/gui/entry/EntryModel.cpp

Fixes #1812 
Do not resolve placeholders in notes. This is not a desirable behavior since notes are meant to be explicit and should not interpret placeholders. Also prevents inadvertent spillage of passwords.
Manually

Remove resolving placeholders for notes

---

src/browser/NativeMessagingHost.cpp

QSocketNotifier can be nullptr and it's not checked. Applies to 2.3.2.
Fixes https://github.com/keepassxreboot/keepassxc/issues/1922.
Manually.

Fix possible crash with latest STDIN changes.

---

CMakeLists.txt

Only enable high entropy ASLR for 64-bit builds. High entropy is not supported for 32-bit.
Cannot build 32-bit binaries
Manually

Fix Windows 32-bit building with ASLR

---

src/browser/NativeMessagingBase.cpp

Changes socket location for Unix systems.
Returns XDG_RUNTIME_DIR or TempLocation correctly.
Previously the runtime path returned was never empty.
Manually.

Change Unix socket location

---

src/gui/entry/EditEntryWidget.cpp

Qt 5.11 cleans up the internal headers and so consumers could fail by missing includes.
The build is broken because of a missing include on Qt 5.11.
A log of the build is added as attachment here: https://bugs.gentoo.org/655844
Let's compile the project using Qt 5.11
Compilation works again.

fix missing include for Qt 5.11

---

src/gui/DatabaseTabWidget.cpp
src/gui/MainWindow.cpp

Fix #1875 
Disables the merge action when the database is locked. Also adds an interlock to prevent any calls to the merge function when the database is locked.
If you merge to a locked database, the master password is erased making it look like the database is corrupt.
Manually.
- ✅ My change requires a change to the …

Disable merge when database is locked

---

src/gui/EditWidgetIcons.cpp

Fix #1936 
Also removes some unnecessary code and changes the progress to a true percentage.
Crashes are bad, mm'kay.
Manually

Fix occasional crash when favicon progress dialog is closed

---

README.md

The link to "Note about KeePassHTTP was not working (using firefox 60)

update link in readme

---

src/browser/BrowserService.cpp

Fixes `Sort matching credentials by title`.
Previously sorting by title didn't sort usernames after the title sort, and the order was not reverse but mixed. The sort provided the following results:
```
c_username (title1)
z_username (title1)
a_username (title1)
z_username (title2)
c_username (title2)
a_username (title2)
...
```
After the fix:
```
a_username (title1)
c_username (title1)
z_username (title1)
a_username (title2)
c_username (title2)
z_username (title2)
```
If the titles are identical another compare is made based on the username.
Manually.
- ✅ …

Fix entry sorting by title

---

src/browser/BrowserService.cpp

Removes title matching with URL's.
URL's from KeePassXC-Browser shouldn't check entry title at all, only the entry URL. Without the fix wrong credentials can be returned to the extension.
If an entry title contains part of requested URL, the credentials are returned to KeePassXC-Browser.
For example:
- Credentials of entry with title "github.com" and URL "https://github.com/login" is returned correctly.
- Credentials of entry with title "github.com" and URL "https://www.example.com" is still returned.
Manually.
- ✅ I have compiled and verified my code …

Remove title matching

---

src/gui/EditWidget.cpp
src/gui/EditWidgetIcons.cpp
src/gui/EditWidgetIcons.h

Quick tweak to let users select multiple icons when adding favicons from the filesystem. Useful for testing too!

Allow multiple image selections when adding favicons

---

src/sshagent/ASN1Key.cpp
tests/TestOpenSSHKey.cpp
tests/TestOpenSSHKey.h

Hex string inside a QByteArray apparently can't be converted into binary array without converting it to a string first. It works but only sometimes.
The changes to gcrypt arguments and sizes should be reviewed carefully. I read the manual(s) back and forth but still feel a little uneasy but the way they were before seemed wrong.
Parsing of ASN1 keys had a flaw when converting gcrypt hex string output to QByteArray which happened only once in five times of key parsing.
This at least affects Windows users with Pageant. OpenSSH may tolerate inconsistencies in the private key better.
New test was added and manual tests were run on Linux and Windows with a bunch of different keys. …

SSH Agent: Fix invalid iqmp output for RSA keys

---

src/gui/DatabaseOpenWidget.cpp

Resolve #570 dilemma
Automatically check the password checkbox if no selection is made from user at all.
Basically validates the scenario of unlocking a DB locked with an empty password.
Coherence with the fact that a DB with empty password is legal.
Until now an error message is issued telling the user that the password is wrong (it isn't).
Manually.

Select password locking if an empty password is entered

---

src/main.cpp

Fix #1362 by checking if the version option is set when deciding whether to print the "Keepassxc is already running" error message.
Built locally and ran. Passes all unit tests.

Print version information with --version even if another instance is already running

---

src/gui/MainWindow.cpp
tests/gui/TestGui.cpp

Related to https://github.com/keepassxreboot/keepassxc/issues/1875
This patch disables the merge button when the current database is locked.
Attempting to merge the database when the db is locked can cause database corruption, as stated in https://github.com/keepassxreboot/keepassxc/issues/1875
Locally. Had a hard time writing unit tests for the GUI.

Disable merge button when db is locked.

---

src/browser/BrowserService.cpp

With this change, expired credentials are not returned to KeePassXC-Browser.
Fixes https://github.com/keepassxreboot/keepassxc/issues/2111.
Manually.

Deny expired credentials

---

src/sshagent/OpenSSHKey.cpp
tests/TestOpenSSHKey.cpp
tests/TestOpenSSHKey.h

The previous default was to expect passphrases to be ASCII or rather Latin-1. It would be reasonable to expect modern keys to use UTF-8 instead.
This is a non-breaking change if passphrases only use characters that fall within ASCII.
Fix #2102.
New test added, existing tests pass.

SSH Agent: Expect passphrases to be in UTF-8

---

src/core/Entry.cpp
src/core/Uuid.cpp
src/gui/DatabaseWidget.cpp
src/gui/DetailsWidget.cpp
src/gui/DetailsWidget.ui

Fixes #1424
Note: There is still bad behavior in the details view when you have a cmd:// url it will attempt to open a url that is embedded in the command. This is a holdover for icon downloading and can be corrected once icon downloading has the ability to specify arbitrary urls.
Manually

Show all url schemas in entry view

---

src/browser/BrowserService.cpp
src/browser/BrowserService.h

Handle URL port and scheme when requesting credentials.
Entries with different port or scheme in URL are ignored. If an entry has a `http` scheme, credentials are not received when accessing a site with `https`.
Fixes https://github.com/keepassxreboot/keepassxc-browser/issues/143.
Fixes https://github.com/keepassxreboot/keepassxc/issues/1467.
Manually.

Handle URL port and scheme when requesting credentials

---

src/browser/BrowserAction.cpp

When connecting first time from KeePassXC-Browser to multiple databases within the same session, the same public key is used as an identification key. This causes the connections to use identical keys.
This PR allows the use of a separate `idKey` when saving the connection to KeePassXC. To ensure backward compatibility, the current public key will be used instead.
Fixes using identical identification keys.
Related KeePassXC-Browser PR: https://github.com/keepassxreboot/keepassxc-browser/pull/258.
Manually. …

Allows a separate ID key for browser extension association

---

src/gui/EditWidget.cpp
src/gui/EditWidget.h
src/gui/EditWidgetIcons.cpp
src/gui/entry/EditEntryWidget.cpp
src/gui/group/EditGroupWidget.cpp
tests/gui/TestGui.cpp

Temporary workaround for #2191. The actual fix requires a refactor to how entries/groups are created and saved (ie, move that function away from DatabaseWidget class). 
Also fixes divide by zero error that can occur in the database icon download (found during testing of this issue).
If a user creates a new entry and only hits apply and then locks the database, the new entry is lost.
Corrected automatic tests and manually

Disable apply button to workaround data loss issue

---

src/gui/SettingsWidgetSecurity.ui

Allow users to increase the timeout for lockDatabaseIdle to 12 hours.
Increases the maximum lockDatabaseIdleSpinBox value to 43200 seconds.
See https://github.com/keepassxreboot/keepassxc/issues/1331
We are considering enforcing lockDatabaseIdle for all of our users. If this is the case, we want our users to be able to select a much longer maximum timeout.
Manually

allow 12 hour timeout for lockDatabaseIdle

---

src/browser/NativeMessagingBase.h
src/browser/NativeMessagingHost.cpp
src/browser/NativeMessagingHost.h
src/proxy/NativeMessagingHost.cpp
src/proxy/NativeMessagingHost.h

Fixes shutting down keepassxc-proxy properly with Chromium-based browsers under Windows. Previously a new process was always created and the old process remained open even if the browser was closed.
Manually.

Fix keepassxc-proxy shutdown with Chromium-based browsers under Windows

---

src/browser/BrowserOptionDialog.cpp
src/browser/BrowserOptionDialog.ui

Add browser extension links to browser integration settings page.
Previously information about the new browser extension existed only in the FAQ or in the GitHub page. This makes the need of a browser extension more clear to the users.
Fixes https://github.com/keepassxreboot/keepassxc/issues/2158.
Manually. Links open in the default browser.

Add browser extension links to settings page

---

src/gui/MainWindow.cpp

Warns users that crashes can occur if they are running KeePassXC on Qt 5.5. This will assist with reporting issues such as #335, #1254, and #1554.

Provide warning to users with Qt 5.5.x about potential crash

---

share/about-contributors.html
share/about.html
src/gui/AboutDialog.ui
src/gui/MainWindow.cpp
src/gui/MainWindow.h
src/gui/MainWindow.ui
src/gui/SearchWidget.ui

Provide some minor upgrades to the About Dialog and add the settings button to the toolbar.
* Added Patreon contributors
* Added real names to project maintainers
* Cleaned up layout
* Added settings button to main toolbar
* Fixed sizing of search bar
* Added "Donate" and "Report a Bug" actions to the help menu
I also added the basis html for the about dialog to the share folder. In the future I want to pull from these files during build time and inject into the code. Editing these boxes in Qt Designer is terrible and it adds a bunch of unnecessary HTML. …

Enhancements to About dialog and add settings button to toolbar

---

release-tool

Fixes the release-tool always building a Snap instead of an AppImage, even if the `--snapcraft` flag is not set.
Works on my system. ^^

Fix --snapcraft flag

---

src/browser/BrowserService.cpp

Fix Match URL scheme setting with browser integration.
Previously the setting didn't work and credentials were ignored if the scheme didn't match.
Fixes https://github.com/keepassxreboot/keepassxc/issues/2237.
Manually.

Fix Match URL scheme setting

---

CMakeLists.txt
share/translations/keepassx_en_US.ts
src/CMakeLists.txt
src/config-keepassx.h.cmake
src/core/Config.cpp
src/gui/AboutDialog.cpp
src/gui/DatabaseOpenWidget.cpp
src/gui/DatabaseOpenWidget.ui
src/gui/DatabaseWidget.cpp
src/gui/MainWindow.cpp
src/gui/MainWindow.h
src/gui/SettingsWidget.cpp
src/gui/SettingsWidgetSecurity.ui
src/keys/PasswordKey.cpp
src/keys/PasswordKey.h
src/touchid/TouchID.h
src/touchid/TouchID.mm

Unlock your database using TouchID on supported Macbook Pro models.
With quick unlock one can simply unlock the database using TouchID without having to enter your password again while the application is still running. #209 
- TouchID is a option that can be activated on the unlock screen
- TouchID is only used for **temporary quick unlock**
- Database has to be unlocked once after restart of the application in order to activate quick unlock using TouchID
- TouchID quick unlock **only replaces the password** part of the unlock process
- With quick unlock activated the password will be encrypted (AES 256) and then kept in memory
- The random encryption key (and IV) will be protected by the KeyChain using TouchID
- Next time you don't need to enter your password, just press "OK" to unlock …

Add support for quick unlock with TouchID on Macbook Pro

---

.gitignore
src/core/Group.cpp
src/core/Group.h

Hi.  A first small contribution. As I'm working my way through the codebase to learn it, I noticed an error pointed out by Sonar, and made a few adjustments which, to fix it and, I think, make the intention of the code a bit clearer (to me at least). If you think it's useful, I offer it.
Group.cpp had 
```
if (!groupPath.endsWith("/") && !groupPath.endsWith("/"))
```
which SonarCloud flagged (it clearly was not what was intended, though it would only in practice create an incorrect false positive if basePath were not normalized).
Reran tests, which continue to all pass. The resulting refactor is meant to have the same functionality. 
- ✅ Refactor (non-breaking changes which make code clearer,  more maintainable, or less risky) …

Fixes typo in Group::findGroupByPath found by sonarcloud

---

CMakeLists.txt

I was browsing the code base and I noticed that the `CMakeLists.txt` file in the project root contained a duplicate statement. More specifically, the `CMAKE_AUTOUIC` variable was set to `ON` at line 61, but was already set to `ON` down below at line 313, along with `CMAKE_AUTOMOC` and `CMAKE_AUTORCC`.
I cleared the CMake cache in CLion, performed a clean build and ran all the tests (GUI tests included).
- ✅ Code clean-up.

Remove duplicate statement from CMakeLists.txt

---

src/core/Config.cpp
src/gui/EditWidgetIcons.cpp
src/gui/SettingsWidget.cpp
src/gui/SettingsWidgetSecurity.ui

Modified the fallback HTTP request to use DuckDuckGo (which uses paths to specify the site whose favicon should be retrieved) instead of Google which used params to specify the target site).  Additionally, changed references to "Google" to "DuckDuckGo" in ui elements and variables.
Prior to my fix, when a fetch failed, it was being hidden (and not ever closed) immediately after failing, only to be unhidden by the timeout specified by `setMinimumDuration()` being reached.  In `EditWidgetIcons::fetchFinished()`, the error state of the fetch is established, so it seemed like the correct place to close the `UrlFetchProgressDialog`.  The only issue is that the progress widget is only ever bound to a variable locally in a different function.  The `EditWidgetIcons` object is the parent of the …

Replace Google with DuckDuckGo as the optional fallback favicon fetcher

---

src/gui/KMessageWidget.cpp
src/gui/LineEdit.cpp
src/gui/MainWindow.cpp
src/gui/entry/EditEntryWidget.cpp

KeepassXC tries to load the theme icon first and then falls back to the internal icon unless the check is explicitely disabled. Remove the check from most icons
Fixes #756
I just compiled and ran. One of the icons that doesn't have a system
icon is the copy URL icon. I suggest that we change it.
- ✅ Bug fix

Fix icons not using default theme

---

src/gui/PasswordGeneratorWidget.cpp
src/gui/PasswordGeneratorWidget.h
src/gui/entry/EditEntryWidget.cpp

Adds optional length parameter to `PasswordGeneratorWidget::reset()` (default=0), which when >0 sets the length SpinBox's value to the value passed in. The EditEntryWidget already called reset() when the password at a time when was known, so the current length was just added to this call (accounts for empty passwords correctly)
This seems like a clean approach to me, as the use of the default parameter keeps all previous usage the same, except when a value is passed in.  Another approach could be to add a public `PasswordGeneratorWidget::setLength()` function. If that is more desired, I would be happy to do that instead.
**Edit:** Additionally, I made the change discussed in [my comment below](https://github.com/keepassxreboot/keepassxc/pull/2318#issuecomment-423872469).  Now, if the …

Make password generator length use existing length if available

---

share/keepassxc.ini
src/core/Config.cpp
src/gui/ApplicationSettingsWidget.cpp
src/gui/ApplicationSettingsWidgetSecurity.ui
src/gui/entry/EntryModel.cpp

Add an option to show an empty password field when there's no password specified within an entry.
Fixes #2310.
Manually.

Add option to not show password placeholder when field is empty

---

src/cli/List.cpp
src/cli/List.h

In keepassxc-cli it's possible to list the elements in the database but there was no way to list them recursively, this pull request add's that option.
The functionality to recursively print the database was already in the codebase. This pull request only enables the functionality to be used by the end user.
Removes the need to use "extract" when doing simple scripting tasks. 
Tested it with several commands:
-  `keepasxc-cli ls database.kdbx`
Lists only the top elements in the database
-  `keepasxc-cli ls -R database.kdbx`
Lists everything from the top element of the database
-  `keepasxc-cli ls database.kdbx group`
Lists only the top elements of the specified group
-  `keepasxc-cli ls -R database.kdbx group`
Lists everything from the specified group down
-  `keepasxc-cli ls `
Shows a …

Add option to list elements recursively in the cli

---

src/browser/BrowserService.cpp
src/browser/BrowserService.h

Fix checking subdomains when retrieving credentials.
After title matching was removed with release 2.3.4 the subdomain handling broke. Base domain of the URL will be used for EntrySearcher instead of hostname.
With this fix:
- Entry URL `https://google.com`: matches `https://*.google.com`, does not match `http://*.google.com`
- Entry URL `google.com` with scheme matching off: matches `*://*.google.com`
- Entry URL `https://accounts.google.com`: matches `https://accounts.google.com`, does not match with `https://*.google.com`
- Entry URL `accounts.google.com` with scheme matching off: matches `*://accounts.google.com`
Fixes https://github.com/keepassxreboot/keepassxc-browser/issues/283.
Fixes #2291
~~~Depends on https://github.com/keepassxreboot/keepassxc/pull/2232.~~~
Manually, and with …

Fix checking subdomains

---

src/browser/BrowserAccessControlDialog.cpp
src/browser/BrowserAction.cpp
src/browser/BrowserEntrySaveDialog.cpp
src/browser/BrowserEntrySaveDialog.h
src/browser/BrowserEntrySaveDialog.ui
src/browser/BrowserService.cpp
src/browser/BrowserService.h
src/browser/CMakeLists.txt
src/gui/DatabaseTabWidget.cpp
src/gui/DatabaseTabWidget.h
src/gui/DatabaseWidget.cpp
src/gui/DatabaseWidget.h

When updating or creating credentials from KeePassXC-Browser an additional dialog is shown.
If the user has multiple open databases and credentials are saved or updated from KeePassXC-Browser, a popup dialog is displayed where the correct one must be choosed (or cancel the operation).
The current active database is selected by default.
Fixes https://github.com/keepassxreboot/keepassxc/issues/1791.
Manually. Because of the changed, I'll add some new tests for DatabaseTabWidget if necessary. …

Choose database for saving or updating entries from KeePassXC-Browser

---

snapcraft.yaml
src/core/Bootstrap.cpp
src/gui/ApplicationSettingsWidget.cpp
src/gui/ApplicationSettingsWidgetGeneral.ui
src/gui/DatabaseWidget.cpp
src/gui/EntryPreviewWidget.ui
src/gui/MainWindow.cpp
src/gui/MainWindow.h

* Fix MainWindow startup when minimize to tray was enabled
* Reduce duplicate code in DatabaseWidget.cpp
* Fix snapcraft build dependencies
* Add support for CTRL+TAB, CTRL+PGUP, CTRL+SHIFT+TAB, CTRL+PGDN to focus database tabs from any location
* Add CTRL+SHIFT+M shortcut to minimize to tray
* Allow minimize instead of app exit without tray icon
Resolves #1876 
Resolves #2008 
Resolves #2254 
Resolves #2280 (adds a guard to not minimize to tray if the tray is not enabled)
Resolves #1333 (TAB (group -> entry), SHIFT+TAB (entry -> group))
Resolves #1727 
Resolves #1595 
Resolves #795 
Manually on Windows and Linux …

Multiple fixes to MainWindow and some cleanup

---

src/gui/KMessageWidget.cpp
src/main.cpp

This enables coordinate system scaling for high-DPI displays, which enforces correct proportions even on small 4k displays. The icons are scaled up without interpolation, which makes them crisp, but a bit pixelated. A new scalable icon set will solve this problem, but is not scope of this patch.
Resolves #548, #1381, #1710, #1888
As a small extra cookie, I snuck in enforcement of our icon set for the message box close icon (which has displayed a weird box on my KDE system ever since #2317 was merged).
Icons were tiny, widgets had inhomogeneous proportions and windows were way too small as a result.
Tested on a 13.3" 4k Dell InfinityEdge display under Windows 10, works perfectly.
I also tested it in an Ubuntu 18.10 VM. It works in principle, but Gnome does not set all required properties. …

Enable high-DPI scaling to support 4k screens

---

src/browser/BrowserOptionDialog.cpp
src/browser/BrowserOptionDialog.ui
src/browser/BrowserSettings.cpp
src/browser/BrowserSettings.h
src/browser/HostInstaller.cpp
src/browser/HostInstaller.h

If keepassxc-proxy binary (default or custom location) is not found after support for some browser is enabled, a warning message will be shown in the Browser Integration settings tab. The path where keepassxc-proxy is loaded will be shown in the message. Hopefully this makes the troubleshooting easier.
The warning message should be as non-tech as possible, but still informative. Any suggestions are very welcome.
And because the class is quite hard to read, I also added some documentation to the functions.
This PR is still under `Needs Work` label because I haven't tested this with all platforms.
Adds more information about the native messaging host location during troubleshooting.
Manually.
- ✅ I have read the **CONTRIBUTING** …

Show a warning message when native messaging host is not found

---

COPYING
share/CMakeLists.txt
src/core/FilePath.cpp

Follow-up of https://github.com/keepassxreboot/keepassxc/pull/2113
I noticed that there are some empty directories (e.g., `/usr/share/icons/hicolor/scalable/apps`) in an installed copy.
* Run `make test` and check there svg files are installed
* Run `make icons` and check inkscape commands run fine
_NOT CHECKED_
* If SVG icons are actually loaded or not. I'm not sure how to tell SVG from PNG icons.
- I have compiled and verified my code with `-DWITH_ASAN=ON`. **[REQUIRED]** - I don't think this is necessary as there are no real code changes.
- My change …

Replace all .svgz in paths to .svg

---

src/crypto/kdf/AesKdf.h
src/crypto/kdf/Argon2Kdf.h
src/keys/CompositeKey.h

There was a parsing issue in Qt Creator and I solved it by removing a macro that is not part of the Qt public APIs.
The Q_REQUIRED_RESULT macro was appended to the `transform` method of the
`CompositeKey` class. However, this macro is not part of the Qt public API
and, as such, it may change overtime (even if it's unlikely).
Furthermore, it caused Qt Creator to error out because of a parsing
issue. Removing the macro immediately fixed it.
I'm a Qt Creator user and as soon as I open it up to inspect the code I get this warning straight away at the top of `main.cpp`.
```
Warning: The code model could not parse an included file, which might lead to incorrect code completion and highlighting, for example.
CompositeKey.h:42:62: error: 'nodiscard' attribute cannot be applied to types …
```

Remove macro that caused Qt Creator to error out

---

src/CMakeLists.txt
src/browser/BrowserAction.cpp
src/browser/BrowserAction.h
src/browser/BrowserEntryConfig.cpp
src/browser/BrowserOptionDialog.cpp
src/browser/BrowserOptionDialog.h
src/browser/BrowserOptionDialog.ui
src/browser/BrowserService.cpp
src/browser/BrowserService.h
src/browser/NativeMessagingHost.cpp
src/browser/NativeMessagingHost.h
src/gui/MainWindow.cpp
src/gui/dbsettings/DatabaseSettingsDialog.cpp
src/gui/dbsettings/DatabaseSettingsDialog.h
src/gui/dbsettings/DatabaseSettingsWidgetBrowser.cpp
src/gui/dbsettings/DatabaseSettingsWidgetBrowser.h
src/gui/dbsettings/DatabaseSettingsWidgetBrowser.ui

Browser connection keys and Allow/Deny rules are stored to custom data instead of attributes.
Fixes https://github.com/keepassxreboot/keepassxc-browser/issues/11.
Tested manually with the latest KeePassXC-Browser.

Use custom data to save any browser integration related data

---

src/autotype/AutoType.cpp
src/autotype/AutoTypePlatformPlugin.h
src/autotype/AutoTypeSelectDialog.cpp
src/autotype/test/AutoTypeTest.cpp
src/autotype/test/AutoTypeTest.h
src/browser/HostInstaller.cpp
src/browser/NativeMessagingBase.cpp
src/core/Bootstrap.cpp
src/core/Config.cpp
src/core/FilePath.cpp
src/core/Metadata.cpp
src/core/ScreenLockListenerPrivate.cpp
src/gui/Application.cpp
src/gui/Clipboard.cpp
src/gui/Clipboard.h
src/gui/DatabaseWidget.cpp
src/gui/DialogyWidget.cpp
src/gui/FileDialog.cpp
src/gui/KMessageWidget.cpp
src/gui/MainWindow.cpp
src/gui/MainWindow.h
src/gui/csvImport/CsvImportWidget.cpp
src/gui/csvImport/CsvImportWidget.h
src/gui/entry/AutoTypeMatchView.cpp
src/gui/entry/EntryView.cpp
src/main.cpp

Performing a dev build against the latest version of Qt fails because of some deprecated members.
As of Qt 5.10, two functions and one class that were used in the code are deprecated.
Since this project supports Qt version 5.2 and higher, I replaced the two functions marked as deprecated with their updated versions and wrapped the new code in a compile-time check which enables it only if the project is being compiled against Qt 5.10 and up.
In the CSV import utility, the `QSignalMapper` class was used, which is entirely deprecated now. In place of it, lambdas can be used, which are part of the C++11 standard so I don't think that compile-time checks are required here since it's the version that the project is using, looking at the CMake scripts.
I removed the usage of the aforementioned …

Replace deprecated parts of code

---

src/browser/BrowserService.cpp

Update the entry scheme excluder to use the same logic as the port match checking code: only check for a match if the entry url has a port defined.
I believe this should resolve this issue https://github.com/keepassxreboot/keepassxc-browser/issues/319
I launched the new version locally and verified that the browser extension can now find passwords for entries which don't have a scheme specified (with and w/o the match scheme preference enabled). Before this change all entries with urls like `example.com` would fail to match `https://example.com` and `http://example.com` which didn't seem like the right behavior.  …

Browser extension: only check for url scheme matches when an entry has a scheme

---

src/CMakeLists.txt
src/cli/Add.cpp
src/cli/Clip.cpp
src/cli/Diceware.cpp
src/cli/Edit.cpp
src/cli/Estimate.cpp
src/cli/Extract.cpp
src/cli/Generate.cpp
src/cli/List.cpp
src/cli/Locate.cpp
src/cli/Merge.cpp
src/cli/Remove.cpp
src/cli/Show.cpp
src/cli/TextStream.cpp
src/cli/TextStream.h
src/cli/Utils.cpp
src/cli/Utils.h
src/cli/keepassxc-cli.cpp
tests/TestCli.cpp

QTextStream uses the system default locale, but this breaks in various situations:
- It does not work on the native Windows shell (cmd.exe, Powershell), since the default Windows locale is Windows-1252, but the shell uses Windows-850.
- It also breaks on *nix systems where the locale is Latin1 or C, which is the case for most CI systems or build servers.
We allow overriding the detected codec by setting the ENCODING_OVERRIDE environment variable, but otherwise prefer Windows-850 on Windows and UTF-8 on any other system, even if LANG is set to something else.
This resolves #2413
Uni tests pass on Windows and unlocking a database with a non-ASCII password works as well.
- ✅ …

Fix stdin/stdout encoding on Windows.

---

src/cli/Clip.cpp
src/cli/Show.cpp
src/core/Group.cpp
src/core/Group.h
tests/TestGroup.cpp
tests/TestMerge.cpp

Resolves #2408
Just some cleanup and streamlining in the Group class. Eliminated function that had undetermined results based on heuristics of the input (Group::findEntry). Aligned Group::findEntryByPath with Group::findGroupByPath.
Eliminated unnecessary Q_ASSERTS and integrated the checks into the code function instead.
**Recommendation:** rename Group::children() to Group::groups(). Children overshadows QObject function AND it is the only place where the name children is used, otherwise we just call them groups...
**Recommendation 2:** Look for other places where QString::isNull() is used and evaluate whether it makes sense. This function is for legacy purposes only and QString::isEmpty() is preferred by the Qt Docs.
- ✅ Refactor of code …

Fix issues with group functions

---

src/CMakeLists.txt
src/core/OSEventFilter.cpp
src/core/OSEventFilter.h
src/core/ScreenLockListenerDBus.h
src/gui/Application.cpp
src/gui/Application.h

The `XcbEventFilter` and `WinEventFilter` classes have been extracted into a separate file and a single class.
The new file has then been added to the build chain.
The new class, called `OSEventFilter`, implements the inherited `nativeEventFilter()` method and a preprocessor condition picks the right test for the `if` statement.
Installing a native event filter has now become this:
```cpp
#if defined(Q_OS_WIN) || (defined(Q_OS_UNIX) && !defined(Q_OS_MACOS))
installNativeEventFilter(new OSEventFilter());
#endif
```
which is oblivious of the actual implementation. The new structure should make it easier to add new event filters for new platforms: you just add a new preprocessor case in the `nativeEventFilter()` implementation.
The `XcbEventFilter` and `WinEventFilter` classes had basically …

Extract the OS event filter implementation

---

src/gui/DatabaseOpenWidget.cpp
src/gui/PasswordEdit.cpp
src/gui/PasswordEdit.h

Introduce const function `bool isPasswordVisible()` to detect whether password is visible if not. Add an if-conditional checking if password is selected to be visible or not, and change state of password field depending on return value. 
Fixes #2344.
Manually.

Don't obscure password field after invalid password attempt if setting is off 

---

docs/QUICKSTART.md
src/browser/BrowserOptionDialog.cpp
src/browser/BrowserOptionDialog.ui
src/browser/BrowserSettings.cpp
src/browser/BrowserSettings.h
src/browser/HostInstaller.cpp
src/browser/HostInstaller.h

1. [Removed translations](https://github.com/keepassxreboot/keepassxc/pull/2387#issuecomment-430262919) as per [request](https://github.com/keepassxreboot/keepassxc/pull/2387#issuecomment-430198858) from @droidmonkey 
2. Added macOS support with help from @varjolintu - correct native-messaging-hosts string added. (Pending screenshots from the man himself for verification.) e98dfb4
3. Added missing m_ui component in BrowserOptionsDialog.cpp e98dfb4.
4. Reordered TOR_BROWSER_TARGET_DIR and others to be at the end of lists as per @varjolintu's request 69a81ec9f3d46bbec7f955f4d974929a3c5b3bfd.
5. Created issue #2392 for help debugging what's going on for the Windows build.
1. Add UI component to point to Tor Browser installation so this will work for portable installs.
2. Resolve #2392
3. Add …

Added Linux, MacOS support for Tor Browser.

---

src/gui/entry/EditEntryWidget.cpp

Changed single expiration preset "1 year" to "1 year(s)", "2 year(s)", "3 year(s)", analogous to "week(s)" and "month(s)". Because of the changed literal, translations changed too, and I only updated translations for English and Russian. Others are marked "unfinished". Which is why I consider this a breaking change so far. But perhaps this added flexibility is worth updating translations. Still, I see why these changes might be too much to fix a little inconvenience.
Personally I prefer setting 2 or even 3 year expiration for many less used and less valuable passwords because changing them yearly or renew expiration is too much of a hassle. And for that I have to manually edit date which is also not ideal. And I would assume, I'm not the only one.
It hasn't been tested. I am not a C++ …

Add more expiration presets

---

src/core/Database.cpp

This is what I understand from https://github.com/keepassxreboot/keepassxc/issues/1484.
It's true that we call it a `dbFile` in the code, so might as well talk about database files with the user, this can only be more explicit.
https://github.com/keepassxreboot/keepassxc/issues/1484
```
$ ./src/cli/keepassxc-cli show fdsfsdfd fdfdsf
Insert password to unlock fdsfsdfd: 
Database file fdsfsdfd does not exist.
```

Better error message for invalid db file

---

src/cli/List.cpp
src/cli/keepassxc-cli.1

Following up on https://github.com/keepassxreboot/keepassxc/pull/2345
The new option was missing from the man page.
Other (documentation)

Document list -R option.

---

src/CMakeLists.txt

This patch fixes a small regression introduced by #2433 that caused a missing header error when building with the YubiKey flag turned off.
Manually.

Fix compilation without YubiKey

---

tests/TestMerge.cpp
tests/TestMerge.h

Adding tests on the `modified` signal of the database when merging. This is to make sure that the modified signal is not emitted when nothing was performed during the merge operation.
The previous implementation of the `merge` function was always emitting the `modified` signal.
- ✅ other (new tests)

Adding tests for modified signal on merge.

---

src/browser/BrowserService.cpp
src/browser/BrowserService.h

Fix KeePassHTTP settings to custom data conversion.
In the first versions which included KeePassXC-Browser support the data attributes and entries were specified as `keepassxc-browser Settings`. This fix adds the old settings name to the list for attributes and keys that will be converted to the new implementation.
Instead of `toLower()` it was easier just to add a new static string for conversion (QMap doesn't support CaseInsensitive comparison, and you still would have to make a case sensitive selection of the attribute).
Fixes https://github.com/keepassxreboot/keepassxc/issues/2417.
Manually.
- ✅ All new …

Fix KeePassHTTP settings to custom data conversion

---

src/cli/Merge.cpp
tests/TestCli.cpp

Do not save the database when the merge operation did nothing. Also display a different message so that the user knows nothing had to be written.
Locally + unit tests.
```
$ stat --format="%y" ~/1.kdbx 
2018-11-09 18:25:30.118978803 -0500
$ ./src/cli/keepassxc-cli merge ~/1.kdbx ~/1.kdbx -s
Insert password to unlock /home/louib/1.kdbx: 
Merge entry1/entry1 with local on top/under Root
Merge entry2/entry2 with local on top/under Root
Database was not modified by merge operation.
$ stat --format="%y" ~/1.kdbx 
2018-11-09 18:25:30.118978803 -0500
```
- ✅ I …

CLI Merge: Only save database file when modified.

---

src/gui/ApplicationSettingsWidgetSecurity.ui
src/gui/DatabaseWidget.cpp
src/gui/DatabaseWidget.h
src/gui/EntryPreviewWidget.cpp
src/gui/EntryPreviewWidget.h
src/gui/EntryPreviewWidget.ui
src/gui/MainWindow.cpp
src/gui/MainWindow.h
src/gui/MainWindow.ui
src/gui/SearchWidget.cpp
src/gui/SearchWidget.ui
src/gui/entry/EntryModel.cpp
src/gui/entry/EntryModel.h
src/gui/entry/EntryView.cpp
src/gui/entry/EntryView.h
tests/gui/TestGui.cpp

* Cleanup entry change notification with entryview focus in/out
* Change Open URL shortcut to CTRL+SHIFT+U to conform with an "action"
including SHIFT
* Change Copy URL shortcut to CTRL+U to conform with "copy" without
SHIFT
* Entry specific toolbar and menu items are disabled unless the entry
row has focus (prevents unintended actions)
* Reword security setting for password visibility in entry edit view
* Shortcut to hide/unhide usernames (CTRL+SHIFT+B)
* Fix #1588 - show keyboard shortcuts in context menu
* Fix #2403 - Change auto-type shortcut to CTRL + SHIFT + V
* Fix #2096 - Add (CTRL+F) to search bar background
* Fix #2031 & Fix #2266 - shortcut to hide/unhide passwords (CTRL+SHIFT+C)
* Fix #2166 - Add reveal password button to entry preview
The previous way these interactions were …

Fix multiple issues with entry keyboard shortcuts

---

src/gui/DatabaseOpenWidget.cpp
src/gui/DatabaseWidget.cpp
src/gui/PasswordEdit.cpp
src/gui/PasswordEdit.h
src/gui/entry/EditEntryWidget.cpp
src/gui/entry/EditEntryWidget.h
src/sshagent/SSHAgent.cpp
src/sshagent/SSHAgent.h

Fixes bugs introduced by the refactoring of our database classes (#2491).
Resolves #2502 by making sure that password fields are cleared when they are hidden.
Resolves issues no. 1 and 3 of #2499 by fixing conditions and reworking connected signals and tracking of added keys in our SSH agent feature.

Fix bugs introduced by database refactor #2491

---

src/gui/TotpSetupDialog.cpp
src/gui/TotpSetupDialog.ui

Ability to set 7-digit TOTP codes from the UI
Support 7-digit TOTP codes through the UI as since things like Authy use them (and our existing way of generating TOTP codes works with the way they do it) - it'd be handy to have it in the UI rather than changing the 'TOTP Settings' attribute manually.
resolves #1762

Ability to set 7-digit TOTP codes from the UI

---

src/keys/YkChallengeResponseKey.cpp
src/keys/YkChallengeResponseKey.h
src/keys/drivers/YubiKey.cpp
src/keys/drivers/YubiKey.h

* Move mutex lock to right before challenge call and wait for up to 1 second for unlock
* Fix bug where ALREADY_RUNNING was interpreted as success and causing database corruption
Fix #2436 - prevent database corruption when autosave saves two yubikey enabled databases at the same time
Manually

Correct simultaneous saving with Yubikey

---

src/cli/Add.cpp
src/cli/Clip.cpp
src/cli/Command.cpp
src/cli/Command.h
src/cli/Edit.cpp
src/cli/Extract.cpp
src/cli/List.cpp
src/cli/Locate.cpp
src/cli/Merge.cpp
src/cli/Remove.cpp
src/cli/Show.cpp

Same option is defined in most of the CLI commands. Also, more global options might appear in the future (`--no--password`, `--silent`, `--yubikey`, for example).
unit tests.
- ✅ Refactoring

Global const for KeyFileOption (CLI)

---

src/streams/LayeredStream.cpp

`close()` is a virtual function. Since we are calling it from a destructor, make it clear that we are specifically calling the base class (`QIODevice`) implementation, as opposed to an implementation in any derived class.
[Found by lgtm.com](https://lgtm.com/projects/g/keepassxreboot/keepassxc/alerts) …

LayeredStream dtor: fully qualify 'close()' call

---

src/core/Entry.cpp
src/core/Entry.h

Most of the time, `m_tmpHistoryItem` should be null by the time an `Entry` is destroyed. However, if a caller ever calls `beginUpdate()` without later calling `endUpdate()` -- perhaps because an exception was throw in the meantime -- it may not be null.
This change avoids a memory leak in that case.
Found via https://lgtm.com/projects/g/keepassxreboot/keepassxc/alerts …

Make Entry::m_tmpHistoryItem a QScopedPointer

---

src/format/KeePass2Reader.cpp

[Bug found via lgtm.com](https://lgtm.com/projects/g/keepassxreboot/keepassxc/alerts).
Fix error message when attempting to open a KeePass 1 database.
While I was at it, I also introduced a dedicated error message for I/O errors when attempting to read the file signature (though this is secondary and doesn't matter much).
[NOTE]: # ( Please describe in detail how you …

KeePass2Reader: fix error message logic

---

src/browser/BrowserAction.cpp
src/browser/BrowserOptionDialog.cpp
src/browser/BrowserOptionDialog.ui
src/browser/BrowserService.cpp
src/browser/BrowserService.h
src/browser/BrowserSettings.cpp
src/browser/BrowserSettings.h

Handle credentials requests from HTTP Basic Auths.
KeePassXC will detect credential retrieval requests sent from HTTP Basic Auth dialogs. Requests from those dialogs will trigger permission popup every time even if the same URL has been previously denied.
Adds a global setting that can ignore asking HTTP Basic Auth credential permissions.
Related …

Handle credentials requests from HTTP Basic Auths separately

---

src/cli/CMakeLists.txt
src/cli/Command.cpp
src/cli/Create.cpp
src/cli/Create.h
src/cli/keepassxc-cli.1
tests/TestCli.cpp
tests/TestCli.h

Rebasing https://github.com/keepassxreboot/keepassxc/pull/2352
(credits to @vi-n)
- ✅ My change requires a change to the documentation, and I have updated it accordingly.
- ✅ I have added …

Add create command to keepassxc-cli

---

src/gui/WelcomeWidget.cpp
src/gui/WelcomeWidget.h

Override `keyPressEvent`on WelcomeWidget on OS X to `openDatabaseFromFile`.
I work with a few different password DBs. I like to use the keyboard heavily in KeePassXC. I can close an existing DB with Ctrl+W, but I have to use the mouse to open a recent one. Hitting Enter does not work on OS X. Details are below.
My C++ is extremely rusty, so any feedback would be appreciated.
`openDatabaseFromFile` is already invoked via the QListWidget::itemActivated signal, but this signal doesn't fire on OS X for Enter. QListWidget::itemActivated activates on an OS specific activation key. [1] On Windows/X11, this is Enter, which lets the user easily navigate with just the keyboard. On OS X, this is Ctrl+O, which is already bound to Open Database. This means that `itemActivated` cannot fire via the …

Allow Enter key to select recent DB on OS X

---

src/cli/CMakeLists.txt
src/proxy/CMakeLists.txt

Fixes necessary makefiles for keepassxc-cli and keepassxc-proxy. PR https://github.com/keepassxreboot/keepassxc/pull/2165 broke the behaviour and the files were not copied properly under `src/KeePassXC.app/Content/MacOS/` during the build. These files should be copied to the temporary .app for debugging purposes, so it is possible to inspect the application before final `make package`.
PR https://github.com/keepassxreboot/keepassxc/pull/2165 …

Fix macOS makefiles for cli and proxy
