keepassxreboot/keepassxc

- src/gui/entry/EditEntryWidget.cpp
When using the password generator inside the Edit Entry screen and clicking the 'Accept' button, a new password would briefly be shown before the password generator was hidden (even though the original generated password would be applied to the entry).
This issue was only visible when passwords were shown in plain text.
Note that this is purely a cosmetic issue.
See …
> Edit entry widget: password generator: fix flicker

- src/browser/BrowserService.cpp
- src/browser/BrowserService.h
- src/gui/macutils/AppKit.h
- src/gui/macutils/AppKitImpl.h
- src/gui/macutils/AppKitImpl.mm
- src/gui/macutils/MacUtils.cpp
- src/gui/macutils/MacUtils.h
Extends the https://github.com/keepassxreboot/keepassxc/pull/1904. Using `QWidget::isHidden()` does not return a correct value when KeePassXC is hidden (via Cmd+H) but not minimized. Instead, a native method is used to retrieve this state and to hide the window back to the previous state.
Fixes https://github.com/keepassxreboot/keepassxc/issues/2579.
[TIP]:  # ( We expect new …
> Fix native hiding of macOS windows

- src/core/Config.cpp
- src/gui/ApplicationSettingsWidget.cpp
- src/gui/ApplicationSettingsWidget.h
- src/gui/ApplicationSettingsWidgetGeneral.ui
- src/gui/MainWindow.cpp
- Add ability to change toolbar state and tool buttons style via application settings widget.
- Save/restore toolbar state on app start/finish.
- Resolves #2343.
Manually.
> Toolbar and tool buttons style.

- src/cli/Add.cpp
- src/cli/Clip.cpp
- src/cli/Diceware.cpp
- src/cli/Edit.cpp
- src/cli/Estimate.cpp
- src/cli/Extract.cpp
- src/cli/Generate.cpp
- src/cli/List.cpp
- src/cli/Locate.cpp
- src/cli/Merge.cpp
- src/cli/Remove.cpp
- src/cli/Show.cpp
Making sure we use stderr to output the help
message when there is an invalid number of
arguments, or when there's any error related
to the arguments.
Also, some input text stream where no longer in used, probably dating back to when the password prompt was not centralised in `Utils`.
I also used the `outputTextStream` naming, since I believe it's used in majority by the CLI commands.
Not sure if it's worth adding tests for that. @phoerious what do you think? …
> We should output to stderr on EXIT_FAILURE

- src/core/Tools.h
- src/gui/MainWindow.cpp
- src/main.cpp
Require the same version of Qt the app was compiled against (or higher).
Since the Qt framework is dynamically linked to the app, it may happen that the app is compiled against a version of Qt higher than the one it'll be running with.
Snippets of code that are added/selected _at compile time_, such as this:
```cpp
#if QT_VERSION >= QT_VERSION_CHECK(5, 6, 0)
QApplication::setAttribute(Qt::AA_EnableHighDpiScaling);
#endif
```
will break if the app is compiled against, say, Qt 5.11 and then run in an environment with Qt 5.2 (which is the minimum supported version according to the build instructions).
This patch stops the execution of the app right away if a situation like this occurs.
I simply ran all existing tests. …
> Prevent post-compilation Qt downgrades

- src/browser/BrowserAction.cpp
- src/browser/BrowserAction.h
Modify the error messages to be a little more clearer. Any suggestions are very welcome.
The previous error messages are not clear enough to describe the error situation.
Manually.
[NOTE]: # ( Please go over …
> Clearer default error messages

- src/crypto/kdf/Kdf.cpp
- src/crypto/kdf/Kdf.h
Provides support for undocumented feature in KDBX for seed sizes from 8 bytes to 32 bytes. Retains byte size on subsequent save. Fixes #2581.
It might be appropriate to issue a warning to upgrade the seed byte size to 32 bytes if the user wants to.
[TIP]:  # ( We expect new code to be covered by unit …
> Allow for KDF seeds between 8 and 32 bytes

- Dockerfile
- reorganized the libraries for better readability
- added logic to clean-up apt-cache after fetch in-order to shrink layer
size; in-line with Docker best practices
- run following against `develop` and against this patch:
```
docker build -t keepassxc_image .
docker image ls 
```
You should see a small reduction in image size.
> Refactoring of Dockerfile for Space Optimization

- src/browser/BrowserAction.cpp
- src/browser/BrowserAction.h
- src/browser/BrowserService.cpp
- src/browser/BrowserService.h
- src/core/Group.cpp
- src/core/Group.h
- src/core/Tools.cpp
- src/core/Tools.h
- tests/TestGroup.cpp
- tests/TestGroup.h
Allows KeePassXC to set the group when adding new credentials from KeePassXC-Browser. Groups inside Recycle Bin are ignored.
Related KeePassXC-Browser PR: https://github.com/keepassxreboot/keepassxc-browser/pull/396.
[TIP]:  # ( We expect new code to be covered by unit tests and documented …
> Select group when adding credentials from browser extension

- src/browser/BrowserService.cpp
- src/browser/BrowserService.h
- src/cli/Clip.cpp
- src/cli/Clip.h
- src/cli/Create.cpp
- src/cli/Create.h
- src/cli/Utils.cpp
- src/core/Config.cpp
- src/core/CustomData.cpp
- src/core/EntryAttachments.cpp
- src/core/EntryAttributes.cpp
- src/core/Merger.cpp
- src/format/CsvExporter.cpp
- src/format/CsvExporter.h
- src/format/KdbxXmlReader.cpp
- src/gui/DatabaseWidget.cpp
- src/gui/EditWidgetIcons.cpp
- src/gui/EditWidgetIcons.h
- src/gui/MessageBox.cpp
- src/gui/MessageBox.h
- src/gui/dbsettings/DatabaseSettingsDialog.cpp
- src/gui/dbsettings/DatabaseSettingsDialog.h
- src/gui/dbsettings/DatabaseSettingsWidget.cpp
- src/gui/group/EditGroupWidget.cpp
- src/gui/group/EditGroupWidget.h
- src/gui/group/GroupView.cpp
- src/gui/group/GroupView.h
- src/gui/wizard/NewDatabaseWizardPage.h
Just a few more performance improvements spotted thanks to Clang-Tidy and Clazy.
- **Use `QFileInfo`'s exists() static method**
[According to the docs](https://doc.qt.io/qt-5/qfileinfo.html#exists-1), this static method is faster than the instance method of the same class. I simply replaced it accordingly.
- **Replace `QMap` with `QHash` when the key is a pointer**:
In a map where the key is a pointer, hash-based lookups are faster than tree-based lookups, as you only have to compute the hash of a number which is an O(1) operation, as opposed to the O(log(n)) complexity of the Red-Black tree of `QMap`s.
- **Avoid copying `QSharedPointer`s when not needed**
Many `QSharedPointer`s were passed by value even though they did not modify the …
> Performance fixes

- src/core/Group.cpp
- tests/TestGroup.cpp
- tests/TestGroup.h
This PR contains two fixes.
- Make sure `Group::copyDataFrom` emits `groupDataChanged` and `groupModified` singals.
- Fix `Group::GroupData::equals` wrongly uses the result from `timeInfo.equals`
The `EditGroupWidget` modifies a temporary `Group` object, and use `copyDataFrom` to apply the changes to the actual object. However, if only data members were changed, no signals are emitted. Thus the database is not marked as modified and changes will be discarded silently if that's the only change.
While …
> Fix group signals

- src/cli/Extract.cpp
- src/core/Database.cpp
- src/core/Database.h
- src/format/Kdbx3Writer.cpp
- src/format/Kdbx3Writer.h
- src/format/Kdbx4Writer.cpp
- src/format/Kdbx4Writer.h
- src/format/KdbxReader.cpp
- src/format/KdbxReader.h
- src/format/KdbxWriter.cpp
- src/format/KdbxWriter.h
- src/format/KeePass2Reader.cpp
- src/format/KeePass2Reader.h
- src/format/KeePass2Writer.cpp
- src/format/KeePass2Writer.h
Previously, extracting the xml from a database was done with the
`saveXml` attribute in the `KeePass2Reader` class.
This had several unfortunate consequences:
* The `KdbxReader` class had to import the `KdbxXmlWriter` class
in order to perform the export (bad separation of concerns);
* The CLI database unlocking logic had to be duplicated only
for the `Extract` command;
* The `xmlData` had to be stored in the `KeePass2Reader` as
a temporary result.
* Lots of `setSaveXml` functions were implemented only
to trickle down this functionality.
Also, The naming of the `saveXml` variable was not really
helpful to understand it's role.
Overall, this change will make it easier to maintain and expand
the CLI database unlocking logic (for example, adding a `--no-password`
option as requested in …
> Refactoring database extraction

- src/cli/Merge.cpp
- tests/TestCli.cpp
Looks like the `-q` option was not implemented when different credentials are used in the merge command. Fixed that and added a unit test.
unit test.
- ✅ I …
> Fix quiet option for Merge (CLI)

- src/browser/NativeMessagingBase.h
- src/browser/NativeMessagingHost.h
- src/core/Entry.cpp
- src/core/OSEventFilter.cpp
- src/core/OSEventFilter.h
- src/crypto/kdf/Kdf.cpp
- src/crypto/ssh/BinaryStream.cpp
- src/crypto/ssh/BinaryStream.h
- src/gui/MainWindow.cpp
- src/keeshare/ShareObserver.cpp
- src/proxy/NativeMessagingHost.cpp
- src/proxy/NativeMessagingHost.h
- src/proxy/keepassxc-proxy.cpp
- src/streams/SymmetricCipherStream.cpp
- src/updatecheck/UpdateChecker.cpp
General quality of code improvements for 2.4.0. Also addressing a couple of issues:
* Gracefully close KeePassXC and KeePassXC-Browser when receiving end session notice on Windows
* Fix #2684 - entry references search the whole group tree instead of its current group on down
* Fix #2697 and fix #2699 …
> Code quality updates for 2.4.0

- src/core/Database.cpp
- src/core/Database.h
- src/gui/dbsettings/DatabaseSettingsWidgetEncryption.cpp
- src/gui/dbsettings/DatabaseSettingsWidgetMasterKey.cpp
This patch resolves #2704.
The database master key settings widget does not actually need to (re-)transform the master key, it only needs to update the Key object on the database. Transformation can be deferred until the Database is persisted to disk. This avoids delays and unnecessary user interaction with challenge-response dongles by eliminating redundant key transformations.
[NOTE]: # …
> Prevent unnecessary key transformations, resolves #2704

- src/browser/NativeMessagingBase.cpp
See #2721.
Should fix #2643 and #2721
I'm not able to test these changes but I believe they won't have any impact.
- :x: I have compiled and verified my code with `-DWITH_ASAN=ON`. **[REQUIRED]**
> fix(NativeMessagingBase): always close epoll/kqueue file descriptor

- src/core/EntryAttributes.cpp
- src/core/EntryAttributes.h
- src/core/EntrySearcher.cpp
- src/core/EntrySearcher.h
- src/core/FileWatcher.cpp
- src/gui/DatabaseOpenWidget.cpp
- src/gui/EditWidget.cpp
- src/gui/EditWidgetIcons.cpp
- src/gui/entry/EditEntryWidget.cpp
- tests/TestEntrySearcher.cpp
* Fixed unending timer in BulkFileWatcher causing high CPU usage after first save
* Fix multiple SIGNAL connections found with GammaRay
* Remove horizontal scrollbar from EditWidget due to ghosting (maybe Qt bug)
* Only search custom named attributes
* Search attribute values in addition to keys
* Optimize …
> More 2.4.0 Code Improvements

- src/keeshare/SettingsWidgetKeeShare.ui
Working on the Russian translation for KeePassXC 2.4.0 (which is about to be released) I noticed that SettingsWidgetKeeShare.ui lacks a colon after "Signer" (all other labels in the same group have it). So I have added it for consistency.
Before
After
Manual testing.
> Add missing colon to SettingsWidgetKeeShare.ui

- src/keeshare/group/EditGroupWidgetKeeShare.cpp
- src/keeshare/group/EditGroupWidgetKeeShare.h
- src/keeshare/group/EditGroupWidgetKeeShare.ui
Added a 'Clear' button to the group settings for sharing.
Fixes a part of #2657 (clear button)
Manual testing.
> Add clear functionality to group share settings

- src/browser/BrowserService.cpp
- src/browser/BrowserSettings.cpp
The following small fixes are made for Browser Integration:
- Default URL matching scheme changed from `http` to `https`
- Auto-updating native messaging manifest files is enabled by default
Fixes https://github.com/keepassxreboot/keepassxc/issues/2715.
Fixes https://github.com/keepassxreboot/keepassxc/issues/2706.
[TIP]:  # ( We expect new code to be covered by unit tests and …
> Small fixes for Browser Integration

- src/gui/DatabaseWidget.cpp
- src/gui/DatabaseWidget.h
- src/gui/SearchWidget.cpp
- src/keeshare/KeeShare.cpp
- src/keeshare/KeeShare.h
Added a sharing label to DatabaseWidget to indicate shared containers.
- ✅ Improved feature (non-breaking change which adds functionality)
To highlight that a group is shared, a label is shown with the synchronization method and the path to synchronize to. Improvement is part of #2657
Added a small comment which may allow next reader to see the connection between `DatabaseWidget` and `SearchWidget` using the `SignalMultiplexer`.
The label is only updated enter/leave of a group. It would be possible to observe the changes of the custom data if needed and wished for. 
Manually tested.
- ✅ I have compiled and …
> Add share indication label in group view

- src/gui/EditWidgetIcons.cpp
- src/gui/EditWidgetIcons.h
- src/gui/entry/EditEntryWidget.cpp
Fixes stuck "Download favicon" button on icon download attempts for IP
address hosts by skipping attempts to get 2nd level domain resources
(which resulted in calls to 0.0.0.<rightmost octet of original IP>).
Fixes some cases when DuckDuckGo fallback fails to find icon of >2-level
domains, by adding a request to a DDG URL based on entry's 2nd level
domain.
Repurposes EditWidgetIcons' private fetchCanceled slot (which as of #2439,
is unused by any code) into public abortRequests slot, which is
connected to the entry edit widget's accepted and rejected signals (in
other words, Ok or Cancel was pressed). …
> Remediate errors in various favicon fetch scenarios (#2779)

- src/browser/BrowserAction.cpp
- src/browser/BrowserAction.h
- src/browser/BrowserService.cpp
- src/browser/BrowserService.h
With https://github.com/keepassxreboot/keepassxc-browser/pull/396 default group for saving passwords can be specified. Any group name not found in the database will be automatically created when saving new credentials.
Manually. The tests will be included later in a separate browser tests PR.
[NOTE]: # ( to be sent back …
> Allow creating new groups with Browser Integration

- snapcraft.yaml
- src/browser/BrowserOptionDialog.cpp
- src/browser/BrowserService.cpp
- src/browser/NativeMessagingBase.cpp
- src/core/Database.cpp
- src/gui/dbsettings/DatabaseSettingsWidgetMasterKey.cpp
- src/gui/masterkey/PasswordEditWidget.cpp
- src/gui/masterkey/PasswordEditWidget.h
- utils/keepassxc-snap-helper.sh
* Fix #2609 - Database can be created without a password; a warning is shown
* Fix #2647 - Wording updated for question about "legacy" browser settings
* Fix #1598 - Utility script to install native messaging configuration when using snaps or flatpak. Re-enabled browser extension support while building a snap.
```make format``` will be run and merged right after this …
> Final PR for 2.4.0

- src/cli/CMakeLists.txt
There are other man implementations beside man-db so it is not even sure
that the "mandb" binary even exists on all unices. Other than that, usually
there's a cron job running "mandb" on a daily basis.
> src/cli/CMakeLists.txt: Don't call mandb

- snapcraft.yaml
One issue with Qt snaps is the default cursor theme, which is a fallback theme and quite ugly. I propose the following changes to the snapcraft.yaml file to use the system cursor theme when available. Please see the following thread on the snapcraft forum for more background info and limitations of this: https://forum.snapcraft.io/t/qt-apps-and-gtk-themes-an-investigation-with-partial-success/10513
[NOTE]: # ( If it fixes an open issue, please …
> Snap: improve cursor theme

- src/cli/keepassxc-cli.1
- src/cli/keepassxc-cli.cpp
- src/core/Tools.cpp
- src/core/Tools.h
- src/crypto/Crypto.cpp
- src/crypto/Crypto.h
- src/crypto/CryptoHash.cpp
- src/crypto/Random.cpp
- src/crypto/SymmetricCipherGcrypt.cpp
- src/gui/AboutDialog.cpp
- src/main.cpp
Adding debug info to CLI.
Adding debug info to the CLI and the general option
of the main Qt app. Also took time to:
* use `EXIT_SUCCESS`/`EXIT_FAILURE` constants
for main.cpp (this is what is used in `src/cli`);
* fixed `m_initalized` typo;
* added info on debugging mode being disabled
or not;
* regrouped Qt related stuff in the debug output.
- ✅ Refactor
```
$ ./src/cli/keepassxc-cli --debug-info
KeePassXC - Version 2.4.0-snapshot
Build Type: Snapshot
Revision: 39d77b7
Qt 5.9.5
Debugging mode is disabled.
Operating system: Ubuntu 18.04.2 LTS
CPU architecture: x86_64
Kernel: linux 4.15.0-45-generic
Enabled extensions:
- Auto-Type
Cryptographic libraries:
libgcrypt 1.8.1
```
[NOTE]: # ( Please go …
> Adding debug info to CLI.

- src/core/Bootstrap.cpp
- src/gui/ApplicationSettingsWidget.cpp
- src/gui/ApplicationSettingsWidget.h
- src/gui/ApplicationSettingsWidgetGeneral.ui
- src/gui/DatabaseTabWidget.cpp
- src/gui/DatabaseTabWidget.h
- src/gui/MainWindow.cpp
- src/gui/MainWindow.h
Fix saving order of open databases
* Order of previously open databases are preserved when closing the application
* The active database on closing remains active after startup
* Nested open previous databases and remember key files under the remember previously open databases setting
* Fix #1675
Use existing database open function on startup
* Fix #2828
[NOTE]: # ( …
> Fix Startup Issues

- src/gui/entry/EditEntryWidget.cpp
- src/gui/entry/EditEntryWidget.h
- src/gui/entry/EditEntryWidgetAutoType.ui
When adding custom Auto-Type sequences, I often find myself in a position where I can't remember the syntax exactly. This change adds a button next to the text edit field which opens the [Autotype Custom Sequence](https://github.com/keepassxreboot/keepassxc/wiki/Autotype-Custom-Sequence) wiki page in the default browser.
[NOTE]: # ( to be sent back to you for correction or …
> Add button to open Custom Auto-type sequence documentation

- src/core/Tools.cpp
- tests/TestTools.cpp
* Issue introduced in 558cb3d
* Corrects loading of legacy KeePass Key Files that included a '/' in their data section. Fix #2863 and Fix #2834
* Added base64 unit test for '+' and '/' characters
* Used test …
> Fix base64 check missing '/' as valid character

- src/keeshare/KeeShare.cpp
- src/keeshare/ShareObserver.cpp
- src/keeshare/group/EditGroupWidgetKeeShare.cpp
During the translation of KeePassXC to Spanish and Russian I've encountered the following string: "The container %1 imported and export by different groups." I believe it should be "The container %1 imported and export**ed** by different groups." This PR fixes the typo. If I'm mistaken, then just close it.
Manual testing (well I've just fixed the typo).
> Fix a typo in EditGroupWidgetKeeShare

- src/gui/MainWindow.cpp
This is useful when keepassxc is minimized/hidden to the tray, and all
the plumbing is already in place from the lock icon button in the main
window UI.
Add a shortcut to lock all databases to the tray icon's menu without having to
open the full GUI. This feature was shockingly trivial to add, thanks to the magic
of Qt.
(ignore the weird transparency, it doesn't look like that for real, only when taking a screenshot on my system)
* All functionality is pulled in through the Lock Databases menu bar button that's already in MainWindow
* I tested on Linux (Arch with Gnome 3.32 and the "Kstatusnotifieritem/appindicator support" Gnome shell extension)
* Databases can be locked whether the main window is open or closed (hidden to …
> add Lock Databases option to tray icon menu

- src/core/Database.cpp
- src/core/Database.h
- src/format/KdbxXmlReader.cpp
- src/gui/DatabaseOpenWidget.cpp
- src/gui/DatabaseTabWidget.cpp
- src/gui/dbsettings/DatabaseSettingsWidgetMasterKey.cpp
- src/gui/entry/EditEntryWidget.cpp
- src/gui/masterkey/KeyComponentWidget.cpp
- src/gui/masterkey/KeyComponentWidget.h
- src/gui/masterkey/PasswordEditWidget.cpp
- src/gui/masterkey/PasswordEditWidget.h
* Fix #2877 - password is unchecked by default
* Smarter activation of key components based on contents of text entry fields
* Prevent multiple copies of the same database from opening when the canonicalFileName != fileName
Ported fixes from #2805 
* When removing portions of the master key, the key is marked dirty for saving
* Properly clear password and other fields …
> Correct opening files from command line

- src/core/Database.cpp
- src/core/Database.h
- src/gui/DatabaseTabWidget.cpp
- src/gui/DatabaseWidget.cpp
- src/gui/DatabaseWidget.h
- src/gui/MessageWidget.cpp
- src/gui/MessageWidget.h
* Fix #2888
* Qt has an undocumented rename implementation for QTemporaryFile that does not fallback to the copy implementation. Forcing the use of QFile::rename(...) allows for this fallback and protects against cross-device link errors.
* Improve behaviors when the database fails to save properly.
* Mark database dirty if saving fails
* Restore database file from …
> Fix broken safe saves across file systems

- src/format/Kdbx3Reader.cpp
- src/format/Kdbx4Reader.cpp
- src/format/KeePass1Reader.cpp
- src/gui/ApplicationSettingsWidgetGeneral.ui
- src/gui/DatabaseOpenWidget.cpp
- src/gui/DatabaseWidget.cpp
- src/gui/EditWidget.cpp
- src/gui/EditWidget.h
- src/gui/SearchWidget.cpp
- src/gui/entry/EditEntryWidget.cpp
- src/gui/entry/EditEntryWidget.h
- src/gui/group/EditGroupWidget.cpp
- src/gui/group/EditGroupWidget.h
- tests/TestCli.cpp
- tests/gui/TestGui.cpp
Improved error messages when opening database
* Reduced wording and confusion
* Streamlined delivery format
* Fix #813
Add note to restart after changing language
* Fix #2713
Allow copying passwords directly from searching
* Reverts removal of previously implemented feature
* Fix #2630
Correct issues with apply button
* Don't show apply button when creating new …
> Minor fixes for 2.4.1

- README.md
- src/browser/BrowserOptionDialog.cpp
- src/browser/BrowserOptionDialog.ui
- src/browser/BrowserSettings.cpp
- src/browser/BrowserSettings.h
- src/browser/HostInstaller.cpp
- src/browser/HostInstaller.h
- utils/keepassxc-snap-helper.sh
Fixes #2414
* Ran unit tests and all 35 passed
* Tested with binary built from this branch:
* Manually uninstalled KPXC config JSON from Brave .config dir
* Started binary 
* Checked the new "Brave" box in KPXC settings (see screenshot above)
* Verified the config JSON was in Brave's `.config/NativeMessagingHosts` directory
* Verified password auto-fill works in Brave
- ✅ My change requires a change to the documentation, and I have updated it accordingly.
> Add integration with Brave browser (for Linux, OSX, and Windows)

- src/autotype/AutoType.cpp
- src/autotype/AutoTypePlatformPlugin.h
- src/autotype/mac/AutoTypeMac.cpp
- src/autotype/mac/AutoTypeMac.h
- src/autotype/test/AutoTypeTest.cpp
- src/autotype/test/AutoTypeTest.h
* Instead of choosing the last active window, always hide the current window (ie, KeePassXC)
* Fixes #2883
Tested on macOS
[NOTE]: # ( Again, remove any …
> Hide window when performing entry auto-type on macOS

- src/gui/entry/EditEntryWidget.cpp
- src/sshagent/SSHAgent.cpp
- src/sshagent/SSHAgent.h
* Keys that were previously added do not show an error message (they are most likely still in the agent)
* Shifted to using the KeeAgentSettings class to guide behavior of addIdentity function
* Fixes #2902 …
> Re-Add keys on database unlock

- src/keeshare/KeeShareSettings.cpp
Compilation with GCC 5 failed due to a missing `<functional>` include. This patch fixes builds for the Ubuntu 16.04 Xenial PPA.
Compiled in a clean Ubuntu 16.04 environment. …
> GCC 5 / Ubuntu Xenial compilation

- src/gui/entry/EntryModel.cpp
- src/gui/macutils/AppKit.h
- src/gui/macutils/AppKitImpl.h
- src/gui/macutils/AppKitImpl.mm
- src/gui/macutils/MacUtils.cpp
- src/gui/macutils/MacUtils.h
* Fix coloring of reference entries on MacOS dark mode
* Introduce macUtils()->isDarkMode() fuction
* Fixes #860
BEFORE:
AFTER:
Ran on a Mac …
> Fix referenced entry color on macOS dark mode

- src/core/Merger.cpp
- src/core/Metadata.cpp
- src/keeshare/ShareObserver.cpp
- tests/TestMerge.cpp
- tests/TestMerge.h
SharedObserver did not check for already added icons add during export
leading to duplicate icons in the target db. Error was described #2976.
The `ShareObserver` did not check, if a custom icon was already exported. Improved `Metadata::addCustomIcon` to prevent duplicate entries in `m_customIconsOrder` by removing potential duplicate ids first.
Added simple test for `Merger` to check behavior. Other behavior not automatically testable because of `Q_ASSERT`s.
Manually tested.
- ✅ I have added tests …
> Fix duplicate icon add in export

- src/gui/DatabaseWidget.cpp
- src/gui/DatabaseWidget.h
- src/gui/dbsettings/DatabaseSettingsWidgetMasterKey.cpp
Fix building when yubikey and keeshare flags are disabled
[NOTE]: # ( Pull Requests that don't fulfill all …
> Fix conditional build flags for yubikey and keeshare

- .github/CONTRIBUTING.md
Just a minor fix. Code snippets were marked as `c` and caused incorrect highlighting when displayed by GitHub (see the `class` sample snippet, where it's more evident).
> Fix syntax highlighting in CONTRIBUTING.md

- src/gui/SearchHelpWidget.ui
The hardcoded background color was breaking the native dark mode background on macOS.
Tested on Linux (ubuntu) and macOS, with and without dark mode. …
> Remove hardcoded background color from search help widget

- src/CMakeLists.txt
- src/autotype/AutoTypeFilterLineEdit.cpp
- src/autotype/AutoTypeFilterLineEdit.h
- src/autotype/AutoTypeSelectDialog.cpp
- src/autotype/AutoTypeSelectDialog.h
When you have a lot of Auto-Type matches for the same window title, some quick search is helpful.
The input field has default focus and up/down arrow keys are captured which move the selection in the list. To make this a bit better, it would work with multiple words split into separate filters that narrow down the list.
Note: This does not yet pass the code quality requirements. The existing view model filter is pulled with a `qobject_cast<>()` which may be a bit hacky.
Implements #2944.
[NOTE]: # ( Please describe in detail how …
> Add free text filter to Auto-Type dialog

- src/gui/TotpSetupDialog.cpp
- src/totp/totp.cpp
- src/totp/totp.h
- tests/TestTotp.cpp
This implements support for SHA-256 and SHA-512 hash algorithms when
generating TOTP codes. These algorithms are specified by RFC6238. The
implementation is compatible with Google's OTP URL format, as well as
with the KeeOTP plugin for KeePass.
The implementation is not wired into the GUI, as the main project
developer expressed strong negative sentiment about adding more
options there. It is possible to configure codes by putting the
appropriate string into the entry's otp property, or using another
program with a less opinionated UI and a compatible on-disk format.
Description above.
Fixes #873
Fixes #1566
Built modified binary. Launched with existing database file containing a mix of SHA1 and SHA512 TOTPs from KeeOTP. …
> Support for RFC-compliant TOTP hashes

- src/gui/MainWindow.cpp
The text for the action icons in toolbar was not readable in macOS, changed to white text color.
Local Release Build with Tests
> Fix toolbar text color on macOS when in dark mode

- src/gui/group/EditGroupWidget.cpp
In case of a modified group, pressing cancel in the confirmation dialog
of cancel led to discarding the changes instead of returning to the edit widget.
When *Cancel* is pressed while editing a group (with chances), the following confirmation dialog will discard the changes instead of returning to the edit widget when *Cancel* is pressed again.
Manually tested.
> Fix canceling cancel request in edited group

- src/core/Metadata.cpp
- src/gui/ApplicationSettingsWidgetSecurity.ui
- src/gui/EditWidgetIcons.cpp
Some systems provide a favicon.ico out-of-box  and set the correct icon via source code. Keepassxc will load the out-of-box icon and not a recognizable/brand icon. Only fix is by hand, because DuckDuckGo is only a fallback.
**This patch adds an option to prefer DuckDuckGo over direct Favicon download.**
(I tried to open an issue, but it got declined. Now i …
> Add option to prefer DuckDuckGo

- src/gui/entry/EditEntryWidget.cpp
* When selecting another attribute in the advanced tab, do not mark the entry as modified (nothing was changed)
* Also do not mark as modified when the notes checkbox is checked/unchecked (doesn't change entry)
* Fixes #3013
[NOTE]: # ( Pull Requests that …
> Don't mark entry edit as modified when attribute selection changes

- src/gui/DatabaseWidget.cpp
* This bug impacted unsafe saves
* When auto save after every change was enabled, an unsafe save to a location that has become unavailable (eg, dismount veracrypt drive), the database modified signal would continually activate a save action that failed. This caused an infinite loop.
* When auto-save on exit was enabled, the database tab and the application itself …
> Prevent infinite save loop when location is unavailable

- CMakeLists.txt
- cmake/CodeCoverage.cmake
- src/CMakeLists.txt
* Ensure Qt dlls find plugins in bundled directory
* Reduce complexity of deployment code
* Standardize use of CMAKE_BUILD_TYPE_LOWER for more robust comparisons
Fixes #3023
Fixes #1535 …
> Windows: use winqtdeploy instead of DeplyQt4 from CMake

- CMakeLists.txt
- INSTALL.md
- src/CMakeLists.txt
- src/browser/CMakeLists.txt
- src/cli/CMakeLists.txt
- src/core/Alloc.cpp
- src/keys/FileKey.cpp
- src/keys/FileKey.h
- src/keys/PasswordKey.cpp
- src/keys/PasswordKey.h
- src/keys/YkChallengeResponseKey.cpp
- src/keys/YkChallengeResponseKey.h
- src/proxy/CMakeLists.txt
- src/touchid/TouchID.mm
To reduce residual fragments of secret data in memory after
deallocation, this patch replaces the global delete operator with a
version that zeros out previously allocated memory. It makes use of
the new C++14 sized deallocation, but provides an unsized fallback
with platform-specific size deductions.
This change is only a minor mitigation and cannot protect against …
> Improve resilience against memory attacks

- src/cli/TextStream.cpp
Previously, we enforced code page 850 for all console input and output, which breaks with non-western scripts. Since more recent Windows shells are able to display Unicode properly, this patch now enforces UTF-8 and falls back to code page 850 only if UTF-8 is unsupported.
Non-Windows systems default to UTF-8, but can override the codec by setting the LANG environment variable to something other than C.
Resolves #3049. …
> Set console code page to CP_UTF8 on Windows if supported.

- INSTALL.md
- src/cli/Utils.cpp
- src/main.cpp
- utils/keepassxc-kdewallet
- utils/keepassxc-keychain
fixes #2914
support MacOS keychain
update INSTALL requirements
use [keepassxc-kdewallet](https://github.com/jkt628/keepassxc/blob/pw-stdin/utils/keepassxc-kdewallet) on Linux
use [keepassxc-keychain](https://github.com/jkt628/keepassxc/blob/pw-stdin/utils/keepassxc-keychain) on MacOS
observe different behavior between branches develop and pw-stdin.
- ✅ I have compiled and verified my code …
> multiple database with --pw-stdin

- src/browser/BrowserService.cpp
Ensures that popups are closed when database is closed when a popup is visible. Without the extra checks, KeePassXC will crash.
Fixes #3085.
Manually. …
> Close popups when database is locked

- cmake/FindQuaZip.cmake
- src/keeshare/ShareObserver.cpp
Finding libquazip failed on macOS due to path differences.
This patch also cleans up the find module's code, aligns it with the coding style of the other CMake files and removes clutter that is not needed for KeePassXC such as non-Msys builds on Windows.
CMake found QuaZip on macOS, Windows and Ubuntu.
KeeShare signature panel was available on macOS after compilation. …
> Fix QuaZip find module on macOS and clean up code.

- src/core/CustomData.cpp
- src/core/CustomData.h
- src/core/Merger.cpp
- tests/TestKdbx4.cpp
- tests/TestMerge.cpp
- tests/TestMerge.h
Merges the custom data from database metadata.
We store an extra key _LAST_MODIFIED (UTC Date/Time) and make comparisons based on that value. Lacking this key we assume the source DB is "newer".
If Source is Newer:
- New Key -> Add to Target
- Missing Key -> Delete from Target
- Existing Key -> Replace Value on Target
If Source is Older:
- Don't modify target data …
> Support Database Custom Data Merging

- src/browser/BrowserOptionDialog.cpp
- src/browser/BrowserOptionDialog.ui
- src/browser/BrowserService.cpp
- src/browser/BrowserSettings.cpp
- src/browser/BrowserSettings.h
Allows returning expired credentials to the browser extension.
Allowing to retrieve expired credentials should still be allowed if the user wants to. In the extension side these credentials are marked with an extra "[Expired]" text appended to the end of the entry title.
Browser side support PR is here: …
> Add option for returning expired credentials

- src/autotype/AutoType.cpp
- src/autotype/AutoType.h
- src/autotype/mac/CMakeLists.txt
- src/autotype/test/AutoTypeTest.cpp
- src/autotype/test/AutoTypeTest.h
- src/autotype/test/AutoTypeTestInterface.h
- src/gui/DatabaseTabWidget.cpp
- tests/TestAutoType.cpp
* Store the currently active window right when the global keyboard shortcut is triggered
* Eliminate unnecessary window raise/lower and delays on macOS
* Remove duplicate addition of macutils symbols from mac Auto-Type plugin
* Fixes #1216 and fixes #3068 and fixes #3003 and fixes #2547
[TIP]:  # ( …
> Fix global Auto-Type when database locked

- src/browser/BrowserService.cpp
- src/browser/BrowserService.h
Default browser password group is not created if the group is set to something else.
Fixes #3119.
A possible fix to the extension side is also needed because if Root group has not groups, the default group will be still generated.
[TIP]:  # ( We expect new code to be covered by unit tests and …
> Don't create default browser group

- src/browser/BrowserSettings.cpp
- src/cli/Diceware.cpp
- src/core/PassphraseGenerator.cpp
- src/core/PassphraseGenerator.h
- src/gui/PasswordGeneratorWidget.cpp
- src/gui/PasswordGeneratorWidget.ui
- tests/CMakeLists.txt
- tests/TestPassphraseGenerator.cpp
- tests/TestPassphraseGenerator.h
adds lower, upper, and title case options to passphrase (diceware) generation
Adds an option to have passphrases generated in lower, UPPER, or title case. Adds this option to the saved configuration.
No large changes, ads a small step in teh gerenation of passphrases that modifies the word selected form the word list based on desired capitalization
fixes #1933
Manual testing only. I ran the compiled executable and generated a new passphrase with the new options. The passphrases were all generated with the correct case based on the selected option. 
I opened the executable multiple time and the case option was saved between sessions.
Repeated all manual tests with the standalone password generator.
No major documentation …
> Add word case option to passphrase generator

- src/format/Kdbx4Reader.cpp
- src/format/Kdbx4Reader.h
* Fixes #3048
* Certain programs that read/write KDBX4 files do not consolidate duplicate attachments into a single binary. This is against the KDBX4 specification. This change ensures KeePassXC will at least read the database in its entirety and not lose information. Upon saving the database in KeePassXC, the duplicate attachment binaries will be reduced to single …
> Read all database attachments even if duplicated

- src/browser/BrowserAction.h
- src/browser/BrowserService.cpp
- src/browser/BrowserService.h
- tests/CMakeLists.txt
- tests/TestBrowser.cpp
- tests/TestBrowser.h
> Browser Integration tests

- src/crypto/kdf/Argon2Kdf.cpp
- src/gui/DatabaseWidget.cpp
- src/gui/MainWindow.cpp
- src/gui/MainWindow.h
- src/gui/entry/EditEntryWidget.cpp
- src/gui/entry/EntryView.cpp
- src/gui/group/GroupView.cpp
- src/gui/group/GroupView.h
- src/totp/totp.cpp
* Prevent context menu options from disabling with keyboard navigation
* Fixes #2838
* When navigating the entry context menu with up/down arrow the options would disable due to losing focus on the EntryView. This change preserves the "focus" during this event.
* Update Group in Preview Widget when focused
* Fixes #3129
* Also fix out of bounds access when no entries …
> Last minute fixes for 2.4.2

- INSTALL.md
- README.md
- docs/KEYBINDS.md
- Fixes #3175 
- Add docs/KEYBINDS.md
- Add reference to above file in README.md
- Fix a small error in INSTALL.md in section "Packaging", link to keepassxreboot/keepassxc-packaging
No code changes
[NOTE]: # ( Please go over …
> Add documentation for keyboard shortcuts 

- src/gui/ApplicationSettingsWidget.cpp
- src/gui/ApplicationSettingsWidgetGeneral.ui
- src/keeshare/ShareObserver.cpp
When using KeeShare, a lot of export and import notifications start showing up. The warnings and errors are important, but the success ones get on my nerve. Especially because the message slide in from the top, moving all my passwords down, making it hard to click the one I want. I propose a new option to shush the success notifications, disabled by default. I find this especially important when doing a demo of KeePassXC.
I will wait and see how the code review goes before looking into the translation tool.
Feature seems to work, and persists across restart.
Though I doubt it's my fault, the following tests FAILED:
1 - testgroup (Failed)
16 - testopvaultreader (Failed)
I built on on arch Linux with: cmake -DWITH_XC_ALL=ON …
> Settings option to shush success KeeShare notifications

- CMakeLists.txt
Install ccache with `sudo apt install ccache`.
About ccache: https://en.wikipedia.org/wiki/Ccache
Makes building a huge lot faster, especially after switching branches.
Nothing happens if ccache is not installed. if you don't like it, just `sudo
apt remove ccache` and all is as before.
Example: (measured on my laptop)
```
$ ccache -C # clear the cache
$ rm -fr build
$ cd build
$ cmake -DWITH_XC_ALL=ON -DCMAKE_BUILD_TYPE=Release ..
$ time make -j4
...
real	5m8,817s
user	16m47,107s
sys	1m38,808s
$ rm -fr ../build/*
$ cmake -DWITH_XC_ALL=ON -DCMAKE_BUILD_TYPE=Release ..
$ time make -j4
...
real	0m32,571s
user	1m0,253s
sys	0m24,069s
```
- ✅ Refactor (significant modification to existing code) - affects the build process only, not the …
> Compile with Compiler Cache (ccache) if it's installed

- snap/snapcraft.yaml
- src/proxy/CMakeLists.txt
* Fix missing library from snap release
* Fixes #3203 
* Fix linking libsodium in keepassxc-proxy under macOS
* Fixes #3209
Tested on snap release and macOS …
> Fix issues with 2.4.2 deployment

- src/gui/MainWindow.cpp
- src/gui/MainWindow.h
- src/gui/SearchWidget.cpp
* Entry menu now locks focus on entry when used from menubar
* When using keyboard navigation to select menubar menus, do not lose focus on selected entry
* Fixes #3246
* When the search text edit has focus, retain selected entry keyboard shortcuts and button pressing capability
* Fixes #3034
[TIP]: …
> Fix remaining issues with menu keyboard navigation

- .github/CONTRIBUTING.md
In the contributing document, I noticed that the 'Beginner issues' link points to a non-existing label. There is however an existing label called 'good first issue'. I fixed the link to point to the issues page with the correct filters set.
[TIP]:  # ( We expect new code to be covered by unit tests and documented with …
> Fix 'Beginner issues' link in the contributing document to use correct label

- src/gui/MainWindow.cpp
* KDE does not take focus from the current active window when the tray icon is clicked. This prevented toggling the window (always called bringToFront). Checking if the window is active corrects this issue.
* Fixes #3256 and Fixes #3214 
[TIP]:  # ( We expect new code to be covered by unit tests and …
> Fix clicking tray icon to toggle window on Linux

- src/gui/DatabaseWidget.cpp
Fix #3259 
Use [QUrl::fromUserInput](https://doc.qt.io/qt-5/qurl.html#fromUserInput) to parse a url with scheme, if one is not provided
Related to https://github.com/keepassxreboot/keepassxc/pull/3153
Signed-off-by: sohamg <sohamg2@gmail.com>
> Improve parsing of Urls in the Open Url feature

- src/browser/BrowserAction.cpp
- src/browser/BrowserAction.h
- src/browser/BrowserService.cpp
- src/browser/BrowserService.h
Adds support for returning a proper state based on the user interaction. These states are `success`, `error` and `canceled`. Previously even a canceled operation (when updating a credentials from the browser extension) returned only a message for a successful operation.
This is needed for the extension to identify a correct user interaction.
Related browser …
> Support returning a message for canceled operation

- src/cli/Add.cpp
- src/cli/Add.h
- src/cli/CMakeLists.txt
- src/cli/Clip.cpp
- src/cli/Clip.h
- src/cli/Command.cpp
- src/cli/Command.h
- src/cli/Create.cpp
- src/cli/DatabaseCommand.cpp
- src/cli/DatabaseCommand.h
- src/cli/Diceware.cpp
- src/cli/Diceware.h
- src/cli/Edit.cpp
- src/cli/Edit.h
- src/cli/Estimate.cpp
- src/cli/Estimate.h
- src/cli/Extract.cpp
- src/cli/Extract.h
- src/cli/Generate.cpp
- src/cli/Generate.h
- src/cli/List.cpp
- src/cli/List.h
- src/cli/Locate.cpp
- src/cli/Locate.h
- src/cli/Merge.cpp
- src/cli/Merge.h
- src/cli/Remove.cpp
- src/cli/Show.cpp
- src/cli/Show.h
- tests/TestCli.cpp
This PR cleans up the `Command` classes in the CLI, introducing a
`DatabaseCommand` class for the commands operating on a database,
and a `getCommandLineParser` command to centralize the arguments
parsing and validation.
The opening of the database based on the CLI arguments and options
is now centralized in `DatabaseCommand.execute`, making it easy to
add new database opening features (like YubiKey support for the CLI).
Also a couple of bugs fixed:
* `Create` was still using `stdout` for some error messages.
* `Diceware` and `Generate` were not validating that the word count was an integer.
* `Diceware` was also using `stdout` for some error messages.
@droidmonkey let me know what you think! I believe with this PR merged, adding new commands or new database opening features will be …
> ✨✨ CLI Command cleanup ✨✨

- release-tool
I've told some of your team members about that feature already, but it didn't make it into master yet, so I thought I'd show how it can be used.
appimagetool picks up a `$VERSION` environment variable and embeds that information into the AppImage in a way that allows desktop integration tools to display that in app launchers ("start menu" kind of things). That's *really* useful if you use more than one version, which might occur at updates, but is generally quite handy.
You could even get rid of the custom AppImage name picking, since appimagetool will also use `$VERSION` in the output filename, but that's for another day.
> Embed version information in AppImage

- src/browser/BrowserOptionDialog.ui
For user-facing UI elements, we use the following notation when
referring to the current, native browser:
'KeePassXC-Browser'.
This commit irons out the last remaining formatting inconsistency,
which presented itself in the Browser Options dialog in an obvious
way since, after being enabled, a second instance of the string would
appear in close proximity to the first. …
> simplify wording of enabling browser integration

- src/cli/Merge.cpp
- src/cli/Merge.h
- src/cli/keepassxc-cli.1
- src/core/Merger.cpp
- src/core/Merger.h
- src/gui/DatabaseWidget.cpp
- src/gui/MainWindow.cpp
- src/keeshare/ShareObserver.cpp
- tests/TestCli.cpp
@droidmonkey This PR is rebased on top of https://github.com/keepassxreboot/keepassxc/pull/3210.
This shows how options can be added to CLI commands once the cleanup is merged.
- ✅ Refactor
Two changes in fact: I added the `--dry-run` option and the list of changes detected by the merge operation to the output. In the future, I'd also like to ask the user for confirmation before merging, after displaying the changes.
```
$ keepassxc-cli merge -s --dry-run ~/test1.kdbx ~/test2.kdbx 
Insert password to unlock /home/louib/test1.kdbx: 
Creating missing entry2 [06009d6280a741f88c4da6e4415d0aa5]
Database was not modified by merge operation.
$ keepassxc-cli merge -s ~/test1.kdbx ~/test2.kdbx 
Insert …
```
> Add CLI --dry-run option for merge

- src/core/Group.cpp
- src/core/Group.h
- src/fdosecrets/objects/Collection.cpp
- src/gui/DatabaseWidget.cpp
- src/gui/EditWidgetIcons.cpp
- src/gui/EditWidgetIcons.h
- src/gui/EditWidgetIcons.ui
- src/gui/entry/EditEntryWidget.cpp
- src/gui/group/EditGroupWidget.cpp
- tests/TestGroup.cpp
- tests/TestGroup.h
Set an icon for a group and automatically use it for subgroups and 
subentries. 
Applying icons recursively can be helpful if the database owner follows a policy
in which entries always have the same icon as their parent group (which also is
the standard setting for new entries).
After reorganization of the database, the icons keep their old icon which was
the …
> Allow setting group icons to children groups/entries

- src/autotype/AutoTypeSelectDialog.cpp
- src/gui/entry/AutoTypeMatchView.cpp
- src/gui/entry/AutoTypeMatchView.h
Sometimes when using AutoType the sequence does not match for various reasons 
(e.g. different login masks for the same service), and it is annoying to open KeePassXC manually.
Therefore it would be useful to have copy & paste of usernames and passwords available from the
AutoType dialog. This pull request adds a simple right-click context menu with both options. When
either a username or password is copied by the user the dialog automatically closes.
I was not quite sure why both _AutoTypeSelectView_ **and** _AutoTypeMatchView_ exist, so I chose
to go with the latter and added the context menu there. I also don't know how to handle the translation strings - both of them already exist within the translation context of the …
> Add copy context-menu in AutoType dialog

- src/browser/BrowserAction.cpp
- src/browser/BrowserSettings.cpp
- src/browser/BrowserSettings.h
- src/core/PassphraseGenerator.cpp
- src/core/PassphraseGenerator.h
- src/core/PasswordGenerator.cpp
- src/core/PasswordGenerator.h
- src/gui/PasswordGeneratorWidget.cpp
Pass correct entropy amount to keepassxc-browser instead of amount of bits in password/passphrase.
Rename json key from "login" to "entropy" (keeping "login" key as well for backwards compatibility).
Also make some changes to entropy calculation methods:
- Rename PassphraseGenerator::calculateEntropy to getCurrentEntropy
- Rename PasswordGenerator::calculateEntropy to estimateEntropy
- Implement PasswordGenerator::getCurrentEntropy
Entropy was being calculated as the number of bits in the password, resulting in a notable overestimation for passwords and a ridiculous overestimation for passphrases. The calculation/estimation is now done with …
> Fix keepassxc-browser password entropy display

- src/gui/DatabaseWidget.cpp
- src/gui/EntryPreviewWidget.cpp
I'm using placeholders heavily, so I've run into two bugs when trying to migrate to keepassxc:
1. Double-click on the URL field in the entry table passes URL to the framework as-is, with placeholders in place (see DatabaseWidget::openUrlForEntry). This may lead to QUrl parser failure and empty QUrl, so nothing is opened at all. Using four slashes instead of two after the scheme (related to https://github.com/keepassxreboot/keepassxc/issues/3219 ?) kind of "fixes" it for the QUrl parser, but the resulting URL still has placeholders in place of actual data, so it's not a valid workaround.
2. Copying URL from EntryPreviewWidget by right-clicking URL and choosing "copy" results in the same error, copied URL has placeholders instead of actual data.
- ✅ Bug fix (non-breaking change which fixes …
> Fix resolving placeholders in urls

- src/keeshare/ShareObserver.cpp
- src/keeshare/ShareObserver.h
Introduce a path resolver to allow to specify shares relative to the database (#2799). 
`ShareObserver` now tracks the location of shares using their path translated relative to the share defining database. This means absolute paths (which are still default using the file dialog) will work, but manually defined share location using relatives path should work now to.
A second pr is #3029 which is based on these changes and improves the separation of concerns of the `ShareObserver`.
Manually tested.
> Enforce ShareObserver to resolve relative paths

- src/keeshare/CMakeLists.txt
- src/keeshare/KeeShare.cpp
- src/keeshare/KeeShare.h
- src/keeshare/ShareExport.cpp
- src/keeshare/ShareExport.h
- src/keeshare/ShareImport.cpp
- src/keeshare/ShareImport.h
- src/keeshare/ShareObserver.cpp
- src/keeshare/ShareObserver.h
Introduce a path resolver to allow to specify shares relative to the database (#2799). 
`ShareObserver` now tracks the location of shares using their path translated relative to the share defining database. This means absolute paths (which are still default using the file dialog) will work, but manually defined share location using relatives path should work now to.
Since `ShareObserver` exploded which made it hard do maintain, I splitted the functionality into `ShareImport` and `ShareExport`, both encapsulating their respective code parts which are just called from the `ShareObserver`.
To prevent "retranslation" the new …
> KeeShare - improve share observer code

- src/gui/DatabaseOpenWidget.cpp
- src/gui/DatabaseOpenWidget.h
- src/gui/DatabaseOpenWidget.ui
- src/gui/KeePass1OpenWidget.cpp
- src/gui/OpVaultOpenWidget.cpp
- src/gui/dbsettings/DatabaseSettingsWidgetMasterKey.cpp
- src/gui/masterkey/PasswordEditWidget.cpp
With this change we get rid of the confusing key component checkboxes. Now a component is either there or not (if left empty). There is no redundant distinction between "unset" and "emtpy" anymore.
For compatibility with older databases that have "empty" passwords, KeePassXC will ask if the user wants to retry with an empty password if unlocking failed and the password field was left blank.
Besides these functional changes, the widget's layout has been rearranged to be more compact, less stretched out (e.g. input fields do not fill the full window width anymore), and more user-friendly
by providing a help tooltip for the hardware key field and accessible descriptions for screen readers.
**Note:** I am not totally satisfied with the layout yet. For instance, I'd like to make the background …
> Redesign database unlock widget

- src/core/Config.cpp
- src/core/Database.cpp
- src/core/Database.h
- src/core/Entry.cpp
- src/core/Entry.h
- src/core/Group.cpp
- src/core/Group.h
- src/gui/entry/EditEntryWidget.cpp
- src/gui/entry/EditEntryWidget.h
- src/gui/entry/EditEntryWidgetMain.ui
- tests/TestGroup.cpp
- tests/TestGroup.h
- tests/gui/TestGui.cpp
Fixes #3126
Autocompletion of usernames. 
Each time the EditEntryWidget opens, a set of existing usernames in the database is retrieved. If the user begins to enter a username, suggestions based on this set are made.
In case of a really large database, the current implementation would lead to a longer loading time of the EditEntryWidget. In this case, the user …
> Autocomplete usernames on typing based on existing ones

- src/gui/DatabaseOpenWidget.cpp
Remove reference to DatabaseOpenWidget::checkChallengeResponse that was removed in commit #3287.
Successfully built KeePassXC with YubiKey disabled.
- ✅ I have compiled and verified my code ~with `-DWITH_ASAN=ON`~. (it doesn't seem like a one-line removal should require ASAN) **[REQUIRED]**
> Fix broken build with YubiKey disabled

- src/gui/DatabaseOpenWidget.cpp
- src/gui/entry/EditEntryWidget.cpp
- src/gui/entry/EditEntryWidget.h
Updating mingw-w64-x86_64-qt5 to version 5.12.4-2 caused EditEntryWidget to fail
building. Fixed that with proper includes. Also ran `make format` which revealed
one file in need of formatting.
Got a successful build.
- ✅ I have compiled and verified my code ~with `-DWITH_ASAN=ON`~. **[REQUIRED]**
> Fix build broken by Qt

- CHANGELOG
- src/cli/Analyze.cpp
- src/gui/EntryPreviewWidget.cpp
- src/gui/EntryPreviewWidget.h
- src/gui/EntryPreviewWidget.ui
Fixes #3322.
- Manual tests with the _Hide entry notes by default_ setting both disabled and enabled
- Also tested with the _Notes_ field …
> Move notes to General tab on Group Preview Panel

- CHANGELOG
- share/keepassxc.ini
- src/core/Config.cpp
- src/gui/ApplicationSettingsWidget.cpp
- src/gui/ApplicationSettingsWidgetGeneral.ui
- src/gui/EntryPreviewWidget.cpp
- src/gui/Font.cpp
- src/gui/Font.h
- src/gui/entry/EditEntryWidget.cpp
- src/gui/group/EditGroupWidget.cpp
Fixes https://github.com/keepassxreboot/keepassxc/issues/540
See https://github.com/keepassxreboot/keepassxc/issues/540#issuecomment-505585978
[TIP]:  # ( We expect new code to be covered by unit tests and documented with doc …
> Add monospaced font option for Notes field

- CHANGELOG
- src/gui/PasswordGeneratorWidget.cpp
- src/gui/PasswordGeneratorWidget.h
Fixes #3064
Fixes #2749 
This issue was introduced by https://github.com/keepassxreboot/keepassxc/pull/1841. I found three problems with the code:
- Even though the `generator/SpecialChars` setting was saved properly, it was never loaded.
- The `generator/AdvancedMode` setting was never saved.
- The code that initializes the password generation options uses the …
> FIX: Password generator skips special characters

- src/main.cpp
This PR fixes the way icons are scaled for displays with a scale level >1 according to the method described in https://andrewcrouthamel.wordpress.com/2018/10/03/making-plasma-superb-in-hidpi/. Before, icons displayed severe scaling artifacts (see screenshots below)
The top image is taken from this PR …
> Fix icon scaling for HiDPI displays

- src/CMakeLists.txt
- src/core/Group.cpp
- src/core/Group.h
- src/format/HtmlExporter.cpp
- src/format/HtmlExporter.h
- src/gui/DatabaseTabWidget.cpp
- src/gui/DatabaseTabWidget.h
- src/gui/MainWindow.cpp
- src/gui/MainWindow.ui
For users who want to back up their password database to paper, this feature
adds a "HTML Export" feature which creates a self-contained HTML with the
complete password database (all groups, all entries, all attributes, etc.), in
order to be printed using the web browser. I use to print using "4 pages per
sheet" mode which saves paper and is still not too small to be readable.
HTML Export is in menu "Database -> Export". This new menu also contains
"Export to CSV file" which existed before directly in the "Database" menu; I
moved it into the new "Database -> Export" menu for symmetry reasons
(since we already have "Database -> Import").
NOTE: Don't use this feature unless you trust your browser, printer driver, and printer. …
> HTML Export (aka Paper Backup)

- src/browser/BrowserOptionDialog.cpp
- src/browser/BrowserOptionDialog.ui
- src/browser/BrowserService.cpp
- src/browser/BrowserSettings.cpp
- src/browser/BrowserSettings.h
- src/gui/MessageBox.cpp
- src/gui/MessageBox.h
Add an extra option for not displaying legacy KeePassHTTP setting popup. This is an add to the previous PR #3327.
Also extends the `MessageBox` class to include an optional checkbox.
[TIP]:  # ( We expect new code to be covered …
> Add setting for not displaying KeePassHTTP migration popup

- src/autotype/mac/AutoTypeMac.cpp
- src/autotype/mac/AutoTypeMac.h
- src/autotype/mac/AutoTypeMacKeyCodes.h
- src/autotype/mac/CMakeLists.txt
- src/gui/macutils/AppKit.h
- src/gui/macutils/AppKitImpl.h
- src/gui/macutils/AppKitImpl.mm
- src/gui/macutils/MacUtils.cpp
- src/gui/macutils/MacUtils.h
* Fix #3310
* Replaces Carbon-based API for global hotkey handling with NSEvent
* Thanks to @rockihack for his code submission
Tested on Mojave
[NOTE]: …
> Remove Carbon from Mac Auto-Type

- src/gui/macutils/AppKitImpl.mm
This patch is inspired by a compatibility header in old WebKit. See
https://github.com/WebKit/webkit/blob/1262b1fbf85ae267aab0c946500527ef3b97bac8/Source/WTF/wtf/mac/AppKitCompatibilityDeclarations.h
Ref: https://github.com/keepassxreboot/keepassxc/issues/2899
N/A - build fixes
Add this patch to MacPorts and build it on different versions of Mac OS X/macOS systems.
For Mac OS X < 10.8, builds fail as GitHub requires TLS 1.2 but old systems do not support that.
Build log for 10.9: https://build.macports.org/builders/ports-10.9_x86_64-builder/builds/92138/steps/install-port/logs/stdio
For builders 10.10 and 10.11, KeePassXC is still in the queue.
For builders 10.12~10.14, KeePassXC is skipped as it already builds fine without this …
> Fix building on Mac OS X < 10.12

- src/gui/KMessageWidget.cpp
The newest update of Qt set the foreground() method of QPalette deprecated causing the build to fail. 
The Qt documentation advises to use windowText() instead [1].
[1] https://doc.qt.io/qt-5/qpalette.html#ColorRole-enum 
Trailing whitespaces were removed as a side effect.
``` …
```
> Replace deprecated foreground() by windowText()

- src/keys/YkChallengeResponseKey.cpp
- src/keys/drivers/YubiKey.cpp
- src/keys/drivers/YubiKey.h
This PR is for the better way I mentioned here - https://github.com/keepassxreboot/keepassxc/pull/2754#issuecomment-506768000
This adds support for OnlyKey, this requires yubikey-personalization library greater than 1.19.3. Good news, yubikey-personalization library v1.20.0 was just released today! The function yk_open_key_vid_pid was added to yubikey-personalization in version 1.20.0 
- ✅ …
> Adding OnlyKey support

- src/main.cpp
I use Wayland without an XWayland server. In such a case fallback to the Qt xcb plugin does not work, so I explicitly set QT_QPA_PLATFORM=wayland to use Qt's Wayland plugin. The Wayland warning no longer matters and floods the terminal (or log files).
Less warnings on Wayland:
```
$ keepassxc
qt.qpa.wayland: Wayland does not support QWindow::requestActivate()
qt.qpa.wayland: Wayland does not support QWindow::requestActivate()
QObject::startTimer: Timers cannot have negative intervals
```
Run KeePassXC on Wayfire 0.2 with `export QT_QPA_PLATFORM=wayland`. …
> Skip the Wayland warning if QT_QPA_PLATFORM already set

- src/core/Config.cpp
- src/gui/ApplicationSettingsWidget.cpp
- src/gui/ApplicationSettingsWidgetSecurity.ui
- src/gui/SearchWidget.cpp
Add setting to control search results timeout.
KeepassXC has a hard-coded 5 minute timeout when searching the database. This adds an option in security settings to control the timeout. (Resolves #3400)
Tested changing the timeout setting and observing results.
Forgive me if I missed something, this is my first pull request/open-source contribution. Edit: Oops, I think my branch name should've been feature/#3400 instead of hotfix. I'm not sure how the branch naming …
> Add setting for search results timeout (#3400)

- src/keys/drivers/YubiKeyStub.cpp
I noticed in #3416 that the build was broken when the YubiKey flag was disabled.
This PR fixes the issue.
@droidmonkey so we're always testing with YK enabled during CI? …
> 🛠 🛠 Repair build when YK disabled.

- src/core/Database.cpp
- src/gui/DatabaseWidget.cpp
* Fix #3407
* Read-only files now disable auto-save and show as modified correctly. This allows the GUI to prompt to "save-as" instead of silently discarding changes when the read-only database is locked or closed.
_Note: The assert changes in Database.cpp are never hit due to correct handling of files in DatabaseWidget.cpp. These are in place in case of future …
> Improve handling of read-only files

- src/core/Database.cpp
Symlinks and Windows shortcuts are now handled correctly when atomic save is disabled.
The `save` routine is passed the canonical path when a symlink or Windows shortcut is used as the database path. Previously it overwrote the symlink with a regular file. Fixes #3435.
I tested my changes manually by opening a symlink to a dummy database I created for the purpose.
I also ran all the existing tests to make sure nothing broke.
> Save to canonical path when dealing with symlinks

- src/gui/DatabaseTabWidget.cpp
- src/gui/DatabaseWidget.cpp
- src/gui/FileDialog.cpp
- src/gui/FileDialog.h
- src/keeshare/SettingsWidgetKeeShare.cpp
- src/keeshare/group/EditGroupWidgetKeeShare.cpp
This PR aims at the portions of code that handle picking files from the file systems.
It also improves the overall code style of those portions.
- **Convert UNIX paths to native paths**
This commit fixes #3454. On Windows, `QFileDialog`s return paths with a UNIX-style path separator whereas when a `.kdbx` file is double-clicked in Explorer, it is passed to the KeepassXC process with Windows-style path separators. This caused the same file to be registered as two different files by KeepassXC depending on whether it was opened from the context menu or the file explorer. `QDir::toNativeSeparators` will adjust the path separator depending on the platform.
- **Let the window focus …
> Improve path handling when picking files with file dialogs

- src/browser/BrowserAction.cpp
- src/browser/BrowserAction.h
If any legacy database hashes are identified, `get-databasehash` response is written with an additional `oldHash` value. The hash is updated in the extension to a new format.
Reason for this: database hashes used with the extension are calculated using root group UUID + recycle bin UUID, which causes problems if any recycle bin related changes are made in the …
> Update legacy database hashes automatically

- src/browser/BrowserAccessControlDialog.cpp
- src/browser/BrowserAccessControlDialog.h
- src/browser/BrowserService.cpp
- src/browser/BrowserService.h
Disables the remember checkbox when requesting access to credentials with HTTP Basic Auth. Because a global setting exists for showing the HTTP Basic Auth permissions, this checkbox actually does nothing. …
> Disable remember checkbox with Basic HTTP Auth

- CHANGELOG
- src/cli/Add.cpp
- src/cli/Edit.cpp
- src/cli/Generate.cpp
- src/cli/Generate.h
- src/cli/keepassxc-cli.1
- tests/TestCli.cpp
- tests/TestCli.h
Summary of changes:
* extract function for creating password generator from options into
`Generate` command. This function is now reused in `Add` and `Edit`
commands.
* Updated manpage with missing password generation options.
* Updated manpage with missing longer forms of password generation options.
* Added unit tests for new password generation options in `Add` and
`Edit`.
* Handle case when `-g` and `-p` options are used at the same time.
This PR adds password generation functionalities while reducing
code duplication, but at the cost of 2 small breaking changes:
* the password generation option for `Add` and `Edit` for specifying
password length is now `-L` instead of `-l`, to not clash with the
`-l --lower` option.
* the `-u` shorthand for the `--upper` option had to be renamed to …
> 💻💻 CLI password generation options cleanup

- src/core/Config.cpp
- src/gui/ApplicationSettingsWidget.cpp
- src/gui/ApplicationSettingsWidgetGeneral.ui
- src/gui/DatabaseWidget.cpp
Implements the feature request: Minimize after unlocking database (as separate option) #3118
Depending on a new Setting in the Config "MinimizeAfterUnlock" the Main window is minimized after unlocking the database. The already existing setting to minimize the main window after the application startup stays intact.
Fixes #3118 
Ran unit tests
Tested if the new functionality works and is saved/loaded by trying it out
With -DWITH_ASAN=OFF all tests are successful. With -DWITH_ASAN=ON several tests fail. The same tests also fail on master though so I guess this is a problem that existed before? I would be happy about feedback on this.
- ✅ My code follows the code style …
> Add option to minimize after database unlock

- src/core/EntrySearcher.cpp
- src/gui/SearchHelpWidget.ui
- tests/TestEntrySearcher.cpp
I find the advanced search feature useful, but it's not always fun to have to type `title:word user:name` to narrow to the wanted results.  It'd be nice if you could search by just typing `t:word u:name`.
This change allows `t:word` instead of `title:word` and `p:word` instead of `password:word`, and so on.  The rule is that an abbreviated name expands to the first field name that starts with it, with exceptions of `u:` expanding to `username:` instead of `url:` and `pw:` expanding to `password:`.
New test cases are added.
- ✅ I have compiled and …
> Allow abbreviation of search field names

- src/keeshare/ShareObserver.cpp
Connected ShareObserver to allow to import from a share before an export happens.
Fixes #3286 by correcting the order of import and exports handled during database changes and database saves.
The problem seems to be the order of slot calls for `Database::databaseModified()` and `Database::databaseSaved()`. The current solution is more or less a workaround. I think listening to the `Database::groupAdded()`. `Database::groupDataChanged()` and `Database::groupRemoved()` signals should be replaced by some proper ordering of the signal handlers for database slot calls.
Currently only manually tested - possibly we need a GUI-Test which exercises the save chain.
- ✅ My code …
> Connect ShareObserver to group signals

- docs/QUICKSTART.md
- src/gui/DatabaseTabWidget.cpp
- src/gui/DatabaseWidget.cpp
- src/gui/DatabaseWidget.h
Fixes #3495
Summary of changes:
* DatabaseWidget::processAutoOpen() looks for custom attribute KeyFile in
the AutoOpen's entry that should contain the path to a keyfile in the same
format as for the database file
* requestOpenDatabase and its call are updated to handle this extra parameter
auto opening db with or without keyfile works (only tested on linux)
> Support key files with Auto Open feature

- src/gui/SearchWidget.cpp
- src/gui/SearchWidget.h
* Search menu icon only allowed the search menu to show when the right third of the icon was clicked, this was a Qt limitation.
* Fixes #3538
[NOTE]: # ( to be sent back to …
> Always show search menu when icon clicked

- src/core/Merger.cpp
- tests/TestMerge.cpp
- tests/TestMerge.h
merge custom data only when new or changed. Also skipped the meta `LastModified` custom data.
This was causing merge operation to repeatedly detect changes, even when the data and custom data didn't change.
unit tests
- ✅ I have …
> Merge custom data only when necessary

- src/cli/Utils.cpp
- tests/TestCli.cpp
- tests/TestCli.h
Avoids prompting the user for a password if unlocking is likely to fail
due to some problem with the database file (i.e. not found, not a file,
not readable).
Ran tests, tested manually.
> Additional database file checks in cli/Utils.unlockDatabase

- CHANGELOG.md
- cmake/FindReadline.cmake
- src/browser/BrowserAction.cpp
- src/cli/Add.cpp
- src/cli/CMakeLists.txt
- src/cli/Close.cpp
- src/cli/Close.h
- src/cli/Command.cpp
- src/cli/Command.h
- src/cli/Create.cpp
- src/cli/DatabaseCommand.cpp
- src/cli/Exit.cpp
- src/cli/Exit.h
- src/cli/Export.cpp
- src/cli/Help.cpp
- src/cli/Help.h
- src/cli/Open.cpp
- src/cli/Open.h
- src/cli/Utils.cpp
- src/cli/Utils.h
- src/cli/keepassxc-cli.1
- src/cli/keepassxc-cli.cpp
- src/keys/YkChallengeResponseKeyCLI.h
- tests/TestCli.cpp
- tests/TestCli.h
- tests/TestMerge.cpp
- tests/gui/TestGuiBrowser.cpp
This change adds an interactive mode to `keepassxc-cli`. For example:
```
$ ./src/cli/keepassxc-cli open ~/Downloads/passwords.kdbx
Insert password to unlock /home/whoever/Downloads/passwords.kdbx: <password>
Downloads/passwords.kdbx> ls /
General/
Windows/
Network/
Internet/
eMail/
Homebanking/
Recycle Bin/
Banking/
Downloads/passwords.kdbx> ls /Internet
Facebook
Twitter
Downloads/passwords.kdbx> show /Internet/Facebook
Title: Facebook
...
```
This change adds the following command: `open`. If `open` is invoked, the `keepassxc-cli` program attempts to open the database, then drops into interactive mode.
Interactive mode uses readline (falls back to just reading stdin if readline is not available). Each user command causes …
> Add open command, interactive CLI session support

- src/gui/MainWindow.cpp
* Fix #3465 
Since Ctrl+C overrides the default application behavior of "Copy what is in focus" we cannot allow that to happen in the entry view. Doing do causes unintended consequences of copying values in the focused cell instead of always copying the password, even if blank. This change normalizes the behavior.
[NOTE]: # ( Please describe in detail how you tested …
> Copy password of selected entry even if empty

- src/gui/EntryPreviewWidget.cpp
- src/gui/EntryPreviewWidget.h
- src/gui/EntryPreviewWidget.ui
Fixes #3511 
This change adds support for hyperlinks in the notes field of the
EntryPreviewWidget. This is done by enabling the
`openExternalLinks` property of `QLabel`, and modifying the
value of the content of this field so that links are wrapped
with `<a>` tags.
Links are assumed to use the format: `protocol://path`, since
assumptions cannot/shoudn't be made about the specific format of
a link. The text of the label uses the modified notes value.
[TIP]:  # ( We expect new code to be covered by unit tests and documented with doc blocks! …
> Add hyperlinks to EntryPreviewWidget notes field

- src/core/Entry.cpp
- tests/TestEntry.cpp
Fixes #3592.
Previously, cloning an entry with history would not preserve the modification times of items in the cloned entry's history. This was due to the CloneResetTimeInfo flag being set implicitly by CloneDialog.cpp and consequently being passed to the clone function of each entry in the cloned entry's history. This is mitigated by explicitly clearing the flag when calling clone() on a history entry.
Moreover, cloning an entry with the Rename flag set would update the modification time even when CloneResetTimeInfo was not set. In contrast, this does not happen when the Rename flag was not set, hence i assumed this to be a bug.
Extended …
> Fix entry clone modification time update

- src/gui/MainWindow.cpp
I Just started using KeePassXC and like it a lot!
I only struggled with the "Toggle window" menu item in the tray. When I want to see the window I often have to click the menu item twice because it still is somewhat visible.
I found out the tray click action is disabled on Mac OS. I enabled it and now the window comes to front when I click the system tray icon.
- `make test`
- manual tests
> Bring window to front on Mac when clicking the system tray

- src/browser/HostInstaller.cpp
When updating KeePassXC portable, the Windows registry settings are pointing to the old location. The extra checking for existing registry folder is removed, and old values are always overridden.
Fixes #1817. …
> Fix setting and removing registy values for Browser Integration

- src/browser/BrowserService.cpp
- src/browser/BrowserService.h
- src/gui/entry/EditEntryWidget.cpp
- src/gui/entry/EditEntryWidget.h
- src/gui/entry/EditEntryWidgetBrowser.ui
Adds a new settings page "Browser Integration" when editing an entry.
The following options are added:
- Skip Auto-Submit for this entry
- Hide this entry from the browser extension
When **Skip Auto-Submit for this entry** is enabled, a new parameter `skipAutoSubmit` is returned with the credential.
In the future, other entry related Browser Integration …
> Add support for entry related settings with Browser Integration

- src/gui/PasswordEdit.cpp
Fixes regression introduced by 3b330ee2. The previous changes could add an invalid style sheet to PasswordEdit's QLineEdit.
- ✅ I have compiled and verified …
> Fix stylesheet warnings introduced by 3b330ee2

- src/main.cpp
(not sure what the appropriate type is)
This removes the unsetting of `XDG_SESSION_TYPE`, and thus restores QTs behaviour of choosing the platform backend according to OS and desktop used.
Rationale:
For one, the wayland backend of QT is quite stable nowadays, and with current QT, KPXC works fine under GNOME and sway (and probably KDE as well), file open …
> re-enable wayland

- src/CMakeLists.txt
- src/browser/BrowserOptionDialog.cpp
- src/browser/BrowserService.cpp
- src/browser/BrowserService.h
- src/core/Bootstrap.cpp
- src/core/Entry.cpp
- src/gui/dbsettings/DatabaseSettingsWidgetBrowser.cpp
- src/gui/entry/EditEntryWidget.cpp
- src/gui/entry/EditEntryWidget.h
- src/gui/entry/EditEntryWidgetBrowser.ui
- src/gui/entry/EntryURLModel.cpp
- src/gui/entry/EntryURLModel.h
- tests/CMakeLists.txt
- tests/TestBrowser.cpp
- tests/TestBrowser.h
- tests/TestCli.cpp
- tests/TestEntry.cpp
- tests/gui/TestGuiBrowser.cpp
- tests/gui/TestGuiBrowser.h
Adds support for multiple URL's per entry. The new Browser Integration entry settings page has a list view with any additional URL's. These URL's are added to the entry attributes with `KP2A_URL_<counter>`, which means those are directly compatible with Keepass2Android.
Please note that #3444 (Browser Integration releated entry settings) must be merged before …
> Add support for multiple URL's in entry

- src/autotype/AutoType.cpp
* Fix #3351
On macOS, entry specific Auto-Type (Cmd+Shift+V) now raises the last active window before lowering the KeePassXC window. This improves accuracy of the window that is actually typed into.
Tested on …
> Make macOS Auto-Type more robust

- src/core/Entry.cpp
- src/gui/TotpDialog.cpp
- src/gui/TotpExportSettingsDialog.cpp
- src/gui/TotpSetupDialog.cpp
- src/gui/TotpSetupDialog.ui
- src/gui/entry/EditEntryWidget.cpp
- src/totp/totp.cpp
- src/totp/totp.h
- tests/TestTotp.cpp
* Fix #3142 - Warn user when entering invalid TOTP secret key.
* Fix #773 - The TOTP dialog now listens for the copy shortcut without having to press the Copy button.
* Add ability to choose hash algorithm from the TOTP setup dialog
* Add upgrade to "otp" attribute when custom attributes are chosen to prevent …
> TOTP Setup Fixes

- src/gui/dbsettings/DatabaseSettingsWidget.cpp
- src/gui/dbsettings/DatabaseSettingsWidget.h
- src/gui/masterkey/KeyFileEditWidget.cpp
- src/gui/masterkey/KeyFileEditWidget.h
- src/gui/masterkey/KeyFileEditWidget.ui
When adding a keyfile, the selected file is checked:
- if it is a `*.kdbx` file, the user is warned that the file is not appropriate, but can ignore the warning. Maybe some users decided to give their keyfiles a kbdx extension and want to continue with this in the future.
- if it is the current database file, an error is shown. The database would be corrupted if it was used.
Strictly speaking, the change could be considered to be a breaking change. The user cannot pick the database as its own …
> Ask user before allowing kdbx files as key files

- src/core/Database.cpp
- src/core/Group.cpp
- src/core/Group.h
- src/gui/dbsettings/DatabaseSettingsWidgetGeneral.cpp
- tests/TestGroup.cpp
- Fix issue [#3365](https://github.com/keepassxreboot/keepassxc/issues/3365).
- Makes it possible to empty the recycle bin if "Use recycle bin" is disabled in "Database settings".
Manually emptied recycle bin when "Use recycle bin" is enabled/disabled in Ubuntu 18.04.3 LTS, MacOS Mojave v10.14.6.
> Ask to delete recycle bin when disabled in database settings

- src/cli/Add.cpp
- src/cli/AddGroup.cpp
- src/cli/Create.cpp
- src/cli/Edit.cpp
- src/cli/Import.cpp
- src/cli/Merge.cpp
- src/cli/Move.cpp
- src/cli/Remove.cpp
- src/cli/RemoveGroup.cpp
- src/core/Database.cpp
- src/core/Database.h
- src/core/FileWatcher.cpp
- src/core/FileWatcher.h
- src/gui/DatabaseTabWidget.cpp
- src/gui/DatabaseWidget.cpp
- src/gui/DatabaseWidget.h
- tests/CMakeLists.txt
- tests/TestCli.cpp
- tests/TestCli.h
- tests/TestDatabase.cpp
- tests/TestDatabase.h
- tests/gui/TestGui.cpp
- tests/gui/TestGui.h
- tests/util/TemporaryFile.cpp
- tests/util/TemporaryFile.h
**Cleanup Database Save Functions**
* Make a clear distinction between saving to the existing file path and saving to a new file path
* Use proper save function calls in CLI
**Move FileWatcher into database class**
* Fix #3506
* Fix #2389
* Fix #2536
* Fix #2230
Every database that has been opened now …
> Detect database file changes using hash

- src/cli/Utils.cpp
Fixes an unused variable error when building with `-Werror=unused-parameter`.
> Fix unused variable error when building without WITH_XC_YUBIKEY.

- src/browser/BrowserService.cpp
- src/browser/BrowserService.h
When requesting access to a credential, the `submitUrl` received from the extension is not shown at all. At worst cases the …
> Browser access control dialog shows submitUrl when found

- src/browser/BrowserService.cpp
When extension associates KeePassXC with a database, a popup window is shown. The text is not informative and haven't been updated for a while. The fix shows the database name in the popup.
Fixes #838.
Fixes #3626.
[TIP]:  # ( We …
> Show database name when doing association

- src/cli/DatabaseCommand.cpp
Fixes the following warning when opening a database with `keepassxc-cli` when `WITH_XC_YUBIKEY` is not set:
```
QCommandLineParser: option not defined: "y"
```
Tested manually.
> Don't show a warning when opening a database without WITH_XC_YUBIKEY.

- src/core/Group.cpp
- src/core/Group.h
- src/gui/DatabaseWidget.cpp
* Fix #3651
* Correct data loss when the database reloads due to a file change while creating a new entry. The issue occurred due to the "new parent group" pointer being invalid after the database is reloaded following merge.
* Also fix re-selecting entries following database file reload. If the entry was moved out of the current group it would result in an assert …
> Prevent new entry loss on database file reload

- src/gui/EntryPreviewWidget.cpp
- src/gui/EntryPreviewWidget.h
if KeePassXC is compiled with WITH_XC_KEESHARE=OFF, the "Share" tab of
the EntryPreviewWidget for groups is removed from the GUI completely.
closes #3619.
The EntryPreviewWidget for groups should not display the "Shared" tab at all, if compiled with WITH_XC_KEESHARE=OFF.
With KeeShare enabled:
With KeeShare disabled and without this change:
With KeeShare disabled and with this change:
Manually, see screenshots.
> no "Share" tab without WITH_XC_KEESHARE

- src/core/Alloc.cpp
- src/keeshare/ShareExport.cpp
* Add a missing include in src/core/Alloc.cpp
On Mac OS X 10.11 with Xcode 8.2.1, building fails with
```
/opt/local/var/macports/build/_opt_bblocal_var_buildworker_ports_build_ports_security_KeePassXC/KeePassXC-devel/work/keepassxc-f726d7501ff7e8a66ae974719042f23010716595/src/core/Alloc.cpp:44:10: error: no type named 'free' in namespace 'std'
std::free(ptr);
~~~~~^ …
```
> Fix building on Mac OS X 10.11 or older

- src/gui/DatabaseOpenWidget.cpp
The OpenDatabaseWidget has two labels that should not be visible when compiled without yubikey support.
Before:
After:
Manually, see screenshots.
- ✅ I have compiled and verified my code with `-DWITH_ASAN=ON` (8807 bytes leaked in 127 allocation with and without my change -- no difference :stuck_out_tongue:).
> Hide yubikey gui labels if compiled without WITH_XC_YUBIKEY

- src/core/OSEventFilter.cpp
- src/gui/MainWindow.cpp
- src/gui/MainWindow.h
Force app exit if session manager signals a shutdown. Resolves #3410.
Additionally, "fix" main window toggling behaviour when clicking the tray icon while the window is visible, but not in focus (e.g. hidden by other windows). On platforms other than Windows, the window is now brought to the front if it does not already have focus or is toggled otherwise.
Since I cannot reliably reproduce shutdown issues on Linux, I could not really test if …
> Force app exit if session manager signals a shutdown.

- src/gui/dbsettings/DatabaseSettingsWidgetEncryption.cpp
* Fix #3550
* Default memory reduced to 64 MiB (from 128 MiB) and parallelism reduced to 2 threads. This allows for desktop and mobile device compatibility.
[NOTE]: # ( to be …
> Reduce default Argon2 memory and thread settings

- src/core/Database.cpp
- src/core/FileWatcher.cpp
- src/core/FileWatcher.h
* Fix #3699
Reduce file watch hashing of open database files from every second to every 30 seconds. Additionally, only hash the first 1024 bytes of the database file. This is valid since most of the header and the entire encrypted portion are changed significantly on every save. …
> Significantly reduce impact of FileWatcher hashing

- share/docs/man/keepassxc-cli.1
- src/cli/Show.cpp
- src/cli/Show.h
- tests/TestCli.cpp
Realized this might be a problem while using the interactive session with `open`.
Added an option to reveal the protected fields, but otherwise I'd say it's better not to display it by default.
existing and new unit tests.
- …
> CLI: do not display protected fields by default.

- CMakeLists.txt
- src/core/Alloc.cpp
One some operating systems  malloc(3) is not in malloc.h nor in
malloc_np.h, instead it is in stdlib.h.
In addition, not all systems support malloc_usable_size(3). You could
argue it's not safe.
This patch tries to be portable and it fix the build on OpenBSD.
> Check include malloc.h and malloc_usable_size(3)

- src/main.cpp
This is required to show the keepassxc icon on Wayland windows in a
Plasma Wayland session.
kwin_wayland fetches application icons from .desktop files and it
expects the desktop filename to be set on the QGuiApplication instance.
Without this, kwin sets a generic Wayland icon as fallback.
Start keepassxc on a Plasma Wayland session with/without this patch and check its window icon.
> Show application icon in Plasma Wayland sessions

- src/gui/DatabaseOpenWidget.cpp
- src/gui/DatabaseOpenWidget.h
- src/gui/DatabaseOpenWidget.ui
The new unlock dialogue seems to confuse users as to what the purpose of the key file is. This
patch changes the generic "Select file..." affordance to the more explicit "Select key file (if any)..."
and prevents the user from using the KDBX file as a key file (since that would never work anyway).
The change breaks existing translations on purpose (instead of simply …
> Make the purpose of the key file field clearer

- src/core/EntrySearcher.cpp
- src/core/EntrySearcher.h
- src/fdosecrets/objects/Collection.cpp
- src/fdosecrets/objects/Collection.h
- src/fdosecrets/objects/Item.cpp
- src/fdosecrets/objects/Item.h
- tests/TestEntrySearcher.cpp
- tests/TestFdoSecrets.cpp
- tests/TestFdoSecrets.h
To properly fix #3729, we need a way to pass arbitrary terms to the entry searcher, bypassing the limitation of the search term minilanguage. I also removed `QSharedPointer` usage in search terms. These are not shared in multiple places and there's no benefit using `QSharedPointer` over using struct value …
> Add functions to EntrySearcher accepting crazy terms for internal code use

- src/main.cpp
This is just a cosmetic change. On KDE Plasma, the title of the tray icon is set by either the name of the binary, or by calling `setApplicationName()`. So having it properly stylized looks better. See #3564
Before (first system tray item):
After (first system tray item):
[NOTE]: # ( to be sent back to you for …
> Properly stylize the application name

- src/core/Global.h
- src/gui/DatabaseOpenWidget.cpp
- src/gui/DatabaseTabWidget.cpp
- src/gui/DatabaseWidget.cpp
- src/gui/TotpSetupDialog.cpp
- tests/gui/TestGui.cpp
* Fix #3735 - Don't focus on OpenDatabaseWidget fields that are not visible; ensures password field is focused after database lock.
* Fix #3487 - Password input is selected after failed unlock.
* Fix #1938 - Password input is focused after toggling visibility using the keyboard
* Fix #3713 - DatabaseWidget starts in locked mode instead of view mode fixing tab names on …
> Multiple minor fixes to functionality

- src/core/Database.cpp
- src/core/Database.h
- src/gui/DatabaseWidget.cpp
- src/keys/PasswordKey.cpp
- src/keys/PasswordKey.h
This patch improves KeePassXC's memory hygiene. It consists of two changes:
**1) Ensure database contents are released right away.**
When we lock a database, we reset the database pointer to free its resources. Since various other widgets besides the DatabaseWidget hold references to the shared pointer object, …
> Improve memory hygiene

- src/gui/DatabaseOpenDialog.cpp
Fixes the default shrink-wrap and wonky upscaling behaviour of the DatabaseUnlockDialog window (must be a regression of something).
The explicit minimum width of 700 is because the minimum content size hints are not working properly. The widgets remain usable at the default window size, but are a bit too small to my taste (somebody please fix Qt layouting).
[TIP]:  # …
> Fix DatabaseUnlockDialog window sizing.

- src/gui/EntryPreviewWidget.cpp
- src/gui/EntryPreviewWidget.h
- src/gui/EntryPreviewWidget.ui
* Fix #3701 - replace QLabel with QTextEdit to enable scrolling of notes
* Notes are plain text. They will remain as plain text and hyperlinks will not be enabled in the notes. Until the notes editor is moved to a rich text / html editor this will remain the case.
* Convert username and password fields in preview pane to QLineEdit's to allow for full copying and …
> Correct formatting of preview widget fields

- release-tool
- share/macosx/keepassxc.entitlements
The release-tool had bugs on macOS which I always needed to hotfix while building releases. This PR finally fixes those once and for all. The main issues were an outdated target platform, a non-working sandbox entitlement configuration, and a wrong path to the entitlements file in the codesign command.
In …
> Fix release-tool on macOS and add notarisation

- src/totp/totp.cpp
Allows for proper export of TOTP settings via QR code
Fixes https://github.com/keepassxreboot/keepassxc/issues/3255
> Properly encode trailing equal signs for base32 encoded TOTP

- src/browser/BrowserService.cpp
- src/browser/BrowserService.h
- tests/TestBrowser.cpp
- tests/TestBrowser.h
Ignores junk URL's, and fixes port matching. Also renames some functions and variables.
If scheme matching is enabled, entry URL's without a scheme will fallback to `https`.
Fixes #3751.
Manually. Previously …
> Fix URL matching with Browser Integration

- src/cli/Analyze.cpp
Adding a new line after the message "Evaluating database entries against HIBP file, this will take a while..." helps to separate a report and the comment.
The output of the analyze command looks like
> % keepassxc-cli analyze db.kdbx --hibp  pwned-passwords-sha1-ordered-by-count-v5.txt
> Enter password to unlock db.kdbx: 
> Evaluating database entries against HIBP file, this will take a while...Password for '<1>' has been leaked 1161 times!
> Password for '<2>' has been leaked 891 times!
> Password for '<3>' has been leaked 27 times!
The comment "take a while..." and the first line of the report are molded together.
- …
> Add a new line after in Analyze command

- src/browser/BrowserService.cpp
- src/browser/BrowserService.h
- tests/TestBrowser.cpp
- tests/TestBrowser.h
Fix for subdomain matching with Browser Integration. The previous fix handled the matching mostly based on the domain, and entry URL's with different subdomains were returned.
The behaviour is now following:
- `https://accounts.example.com` entry URL is only matched with  `https://accounts.example.com` or any subdomain under it.
- `https://example.com` entry URL is …
> Fix subdomain matching

- src/fdosecrets/objects/Collection.h
- src/fdosecrets/objects/Service.cpp
While reproducing #3861, I found this crash. This may or may not be the crash reported in the issue.
When the user enabling the Secret Service Integration plugin, the plugin tries to create a `default` alias for the currently opened database. But if the database is not exposed, the creation will fail. The code didn't handle this.
[NOTE]: # ( Please describe in detail …
> FdoSecrets: fix crash when enabling the plugin on a non-exposed database

- src/cli/Analyze.cpp
- src/gui/MainWindow.cpp
The standalone mode on the password generator was set before the widget was made visible. The `showEvent` of `PasswordGeneratorWidget` resets its state and thus disables standalone mode.
Fixes https://github.com/keepassxreboot/keepassxc/issues/953
[TIP]:  # ( We expect new code to be covered by unit …
> Correctly initialize standalone PW generator mode

- src/cli/keepassxc-cli.cpp
When quitting interactive mode, a pointer is still left on the database object due to https://github.com/keepassxreboot/keepassxc/blob/develop/src/cli/keepassxc-cli.cpp#L168. We should release all resources of the database before exiting interactive mode.
Fixes https://github.com/keepassxreboot/keepassxc/issues/3880
[NOTE]: # ( Please describe in detail how you tested …
> Release database before exiting CLI interactive mode

- src/browser/BrowserOptionDialog.cpp
- src/browser/BrowserOptionDialog.ui
Fixes https://github.com/keepassxreboot/keepassxc/issues/3707
* Manual testing, although I was unable to test on all platforms
- ✅ I have read the **CONTRIBUTING** …
> Only show warning about snap browsers on Linux

- src/gui/DatabaseOpenWidget.cpp
- src/gui/DatabaseOpenWidget.ui
Disable the DB open form while loading the DB to prevent multiple Enter/OK button events 
Fixes https://github.com/keepassxreboot/keepassxc/issues/3872
* Manual testing …
> Disable DB open form while loading DB

- src/core/Database.cpp
- src/core/Database.h
- src/core/FileWatcher.cpp
- src/core/FileWatcher.h
- src/gui/DatabaseWidget.cpp
- src/gui/DatabaseWidget.h
- src/gui/widgets/ElidedLabel.cpp
* Mark the database as clean after fully completing the file save operation INSTEAD of when merely writing the database to a file.
* Stop the modified timer when marking the database as clean, this prevents latent erroneous modified signals from being emitted.
* Do not restart the modified timer after a new change is detected while it is still running.
* Fix #3933 and …
> Correct multiple issues with database saving

- src/CMakeLists.txt
- src/core/Tools.cpp
- src/core/Tools.h
- src/gui/URLEdit.cpp
- src/gui/URLEdit.h
- src/gui/entry/EditEntryWidget.cpp
- src/gui/entry/EditEntryWidgetMain.ui
- src/gui/entry/EntryURLModel.cpp
- src/gui/entry/EntryURLModel.h
- tests/TestBrowser.cpp
- tests/TestBrowser.h
Shows a warning when editing entry if the URL field has an invalid value.
Also works with Additional URL's page, although the background color only changes after editing.
Valid URL:
Invalid URL:
Invalid URL in Additional URL's page: …
> Show UI warning for invalid URL's

- src/gui/SearchWidget.cpp
- tests/TestGroup.cpp
- tests/TestOpVaultReader.cpp
This makes the tests run successfully with asan (AddressSanitizer).
The GUI tests still have a bunch of leaks, some from library code, and
some that look real but which I didn't manage to figure out so far.
N/A
[TIP]:  # ( We expect …
> Fix memory leaks (mostly) in tests

- src/gui/macutils/AppKitImpl.mm
This commit reverts #3357.
The previous PR is for the new symbol NSEventMaskKeyDown, which is
introduced in #3347. In #3794, #3347 is reverted, so the workaround
in #3357 is no longer needed. Furthermore, it causes build failures
on 10.11 (#3932) as the header file for type NSEventMask is removed
in #3794, too.
Note that this is not a complete fix. A complete patch can be found
at [1]. In MacPorts, the OS version for building a package is the same
as the OS that installs it, so #ifdef can be used to replace @available.
However, this is not always the case for other cases (e.g., official
KeePassXC builds for macOS), so I didn't include the full patch in this PR.
Here the latter language feature @available is not available until Xcode …
> Partial fix for building on Mac OS X < 10.12

- src/cli/keepassxc-cli.cpp
> Fix crash upon exiting interactive mode if there is no current database.

- src/browser/BrowserAction.cpp
- src/browser/BrowserService.cpp
- src/browser/BrowserService.h
- src/core/Global.h
- src/gui/entry/EditEntryWidget.cpp
- src/gui/entry/EditEntryWidgetBrowser.ui
- tests/TestBrowser.cpp
Adds a new option to use entry only with HTTP Basic Auth. If an entry uses additional URL's, the option will be enabled for them also.
Fixes #3925.
[TIP]:  # ( We expect new code to be covered by unit tests and documented with …
> Add option to use entry only for HTTP Basic Auth

- share/docs/man/keepassxc-cli.1
- src/cli/Merge.cpp
- tests/CMakeLists.txt
- tests/TestCli.cpp
- tests/TestCli.h
Rename 'k' to 'f' because 'k' is already used to specify the key for the
target database of the merge
rebuild and merged two databases with different keys using keepassxc-cli
- ✅ My change requires a change to the documentation, and I have updated it accordingly.
> Fix keyfile from/to parameter collision

- COPYING
- share/icons/application/scalable/actions/object-locked.svg
- share/icons/application/scalable/actions/object-unlocked.svg
- src/fdosecrets/CMakeLists.txt
- src/fdosecrets/FdoSecretsPlugin.cpp
- src/fdosecrets/FdoSecretsPlugin.h
- src/fdosecrets/objects/Collection.cpp
- src/fdosecrets/objects/DBusReturn.h
- src/fdosecrets/objects/Service.cpp
- src/fdosecrets/widgets/SettingsModels.cpp
- src/fdosecrets/widgets/SettingsModels.h
- src/fdosecrets/widgets/SettingsWidgetFdoSecrets.cpp
- src/fdosecrets/widgets/SettingsWidgetFdoSecrets.h
- src/fdosecrets/widgets/SettingsWidgetFdoSecrets.ui
This PR contains multiple fixes and refactor. I just think they're not worth separate PRs. But @droidmonkey, if you prefer, I can also do that.
- UI improvements (mostly refactor)
- Use proper models for database and session in the settings page
- Fix button text (unlock/lock) not changed according to the database locking status
- Fix button icons not present on icon themes other than …
> Cumulative updates to secret service integration

- src/fdosecrets/objects/Collection.cpp
When using `secret-tool` or any other client to search the database via secret service API, KeePassXC will return all exposed entries if the searching terms contain only `Password`.
Example: `secret-tool search --all Password abc`
The intended behavior is to not allow searching by password at all. Because the terms are passed in clear text which is insecure. In the …
> Secret Service Integration: fix all exposed entries are returned if search with empty terms

- src/fdosecrets/objects/Collection.cpp
- tests/TestFdoSecrets.cpp
- tests/TestFdoSecrets.h
When constructing search terms for EntrySearcher, the attribute value should be escaped before passing to `Tools::convertToRegex`, otherwise special attribute value won't be searched.
This fixes #3955, because Evolution sets attribute `e-source-uid` to something like `OAuth::[user.name@gmail.com]`. …
> FdoSecrets: fix searching of entries with special characters in attributes

- src/fdosecrets/objects/Collection.cpp
- src/fdosecrets/objects/Collection.h
- src/fdosecrets/objects/Prompt.cpp
- src/fdosecrets/objects/Prompt.h
- src/fdosecrets/objects/Service.cpp
- src/fdosecrets/objects/Service.h
- src/gui/DatabaseOpenDialog.cpp
- src/gui/DatabaseOpenDialog.h
- src/gui/DatabaseTabWidget.cpp
- src/gui/DatabaseTabWidget.h
The `DatabaseTabWidget::unlockDatabaseInDialog` returns before the dialog is completed by the user. Previously the completed signal is emitted on DBus right after the method returns. This causes issues for clients using this signal assuming the database is already unlocked.
[TIP]:  # ( We expect new …
> FdoSecrets: only emit completed signal when the action actually finishes

- CMakeLists.txt
- src/browser/BrowserOptionDialog.cpp
- src/format/OpVaultReaderSections.cpp
- src/gui/DatabaseWidget.cpp
- src/gui/Font.cpp
- src/gui/TotpDialog.cpp
- src/gui/masterkey/PasswordEditWidget.cpp
- tests/gui/TestGui.cpp
Last bit of 2.5.2 bug fixes:
* Fix compiler issues with Qt 5.14
* Remove deprecation warnings when not doing a DEV_BUILD. Qt 5.14 introduced several deprecation flags on basic function calls in QList and QSet that would require several #pragma ignores. Assuming this was in preparation to Qt 6.0.
* Remove unnecessary assert in PasswordEditWidget that was hit in macOS …
> Last round of fixes for 2.5.2

- CMakeLists.txt
This causes build failures in Gentoo because we don't allow access to
ccache files if ccache is not enabled for build.
Fix this by adding a WITH_CCACHE cmake option and change behavior so that
cmake fails if WITH_CCACHE is enabled but ccache program cannot be found.
Gentoo-bug: https://bugs.gentoo.org/704560
Signed-off-by: Lars Wendler <polynomial-c@gentoo.org> …
> CMakeLists.txt: Do not unconditionally use ccache

- src/core/FileWatcher.cpp
* Fixes #4118
Tested by disabling the file watcher and renaming the database file so it cannot be opened by the hashing routine. Upon renaming back to normal no merge request was provided. …
> Prevent unnecessary merge requests on intermittent network shares

- src/core/Database.cpp
- tests/CMakeLists.txt
- tests/TestKdbx3.cpp
- tests/TestKdbx4.cpp
- tests/TestKdbx4.h
- tests/TestKeePass2Format.cpp
- tests/TestKeePass2Format.h
The challenge-response key buffer is explicitly cleared before the key transformation if no such key is configured to ensure one is never injected into the hash even if the database had a challenge-response key previously.
This patch also adds extensive tests for verifying that a key change will not add any expired key material to the hash.
Fixes #4146
Fixes #4041 …
> Ensure challenge-response key buffer is properly cleared.

- src/browser/BrowserService.cpp
Add's an empty path to URL's when needed. Otherwise URL's `https://example.com`  and `https://example.com/` will have a different sorting priority which causes the latter one to be choosed when "Return only best-matching credentials" is enabled.
Fixes #4109.
Manually.
[NOTE]: # ( Again, remove any lines which …
> Add empty path to URL when needed

- src/gui/DatabaseWidget.cpp
- src/gui/EntryPreviewWidget.cpp
- src/gui/EntryPreviewWidget.h
- tests/gui/TestGui.cpp
* Fix #4093 - The first entry in the list is selected after deleting an entry
* Prevents crashes due to dangling pointers held by the Entry Preview Widget when entries were deleted.
Tested numerous …
> Prevent crash when all entries are deleted from a group

- src/gui/Clipboard.cpp
- src/gui/Clipboard.h
* Prefer clearing clipboard by explicitly setting the clipboard
to an empty string. Qt's QClipboard::clear() method is unreliable
under X11 environment.
* Fixes #4126
Tested on Gnome and Windows 10.
Needs to …
> Fix clearing clipboad on Gnome

- src/browser/BrowserService.cpp
- tests/TestBrowser.cpp
Adds base domain matching when handling URL matches. This prevents invalid matches to appear. In this case, for example an entry with `https://hub.com` would be returned for `https://github.com`.
Fixes #4170. …
> Fix base domain matching

- src/browser/NativeMessagingBase.cpp
* Fix #4079 - proxy host would get stuck trying to read characters from stdin. Switch to "readsome" which does not block if there are not enough characters to read. Added a longer delay to slow the checking loop down.
This may also address #4140, but that needs to be tested.
[TIP]:  # ( We expect new …
> Prevent proxy host from blocking application shutdown

- src/cli/keepassxc-cli.cpp
Also not sure why `qCritical` was used instead of an `stderr` output
stream. Added translation on the invalid command string.
Tested locally. `showHelp` will log to `stdout` whatever the status code we pass, so doing the logging to `stderr` directly.
- ✅ My code follows the code style of this …
> Use stderr for help text on error.

- src/core/ScreenLockListenerDBus.cpp
- src/core/ScreenLockListenerDBus.h
Issue #3339 shows issues with some screen locker setups where the database is not locked. The ObjectPath of the `org.freedesktop.login1.Session` object is created from `$XDG_SESSION_ID`, which does not necessarily correspond to the correct path. With this PR, the ObjectPath is retrieved with a call to `org.freedesktop.login1.Manager.GetSession` (introduced in systemd/systemd@bef422ae1e7cbe77ad72dcbfe44798b0fe5e2931, systemd v30).
Fixes #3339 …
> Retrieve login1 session object from manager

- share/docs/man/keepassxc-cli.1
- share/docs/man/keepassxc.1
- Fix lacking commas between short and long option names (e.g. `-l` and `--lower`) in the generate options section of CLI man page, and fix a typo in groff command.
- Changed command and option names in man page to bold. Because it's easier to understand than if it's not bold. …
> Fix CLI man page and change both man pages

- src/core/Compare.cpp
- src/core/Compare.h
- src/core/Entry.cpp
- src/core/Entry.h
- src/core/Metadata.cpp
- src/core/Metadata.h
- src/format/KdbxXmlReader.cpp
- src/format/KdbxXmlReader.h
- src/format/KdbxXmlWriter.cpp
- src/format/KdbxXmlWriter.h
- src/gui/entry/EditEntryWidget.cpp
- src/gui/entry/EntryModel.cpp
- src/gui/entry/EntryModel.h
- tests/TestKeePass2Format.cpp
- tests/TestModified.cpp
- tests/gui/TestGui.cpp
Opening this one as a draft PR since it's not ready to be merged, but I'd like some early review. This is a first step to remove the `Qt:Widgets` dependency for the core modules (and thus the CLI). Basically instead of storing `QColor`s in the entries, we store the RGB `QString` and convert it to `QColor` in the gui code only. After `QColor` I think the only Widgets module remaining in the core module is `QImage`, but I'm not 100% sure.
https://github.com/keepassxreboot/keepassxc/issues/1714
Unit tests and manual testing. Let me know if you'd like new unit tests. …
> Removing QColor (from Qt::Widgets) from core modules.

- src/cli/Show.cpp
We never show the attribute name on `showTotp`, so I removed the if clause.
> Small cleanup in cli/Show.cpp

- src/gui/entry/EditEntryWidget.cpp
- src/gui/entry/EditEntryWidget.h
- src/sshagent/KeeAgentSettings.cpp
- src/sshagent/KeeAgentSettings.h
- src/sshagent/SSHAgent.cpp
- Remove duplicate code to load a key (EditEntryWidget & SSHAgent)
- Refactor all key loading and saving to KeeAgentSettings
- Depend only on Entry to allow future CLI expansion
For future expansion and code duplication avoidance the KeeAgentSettings class has been made a complete pivot between an Entry and OpenSSHKey. It can load/save a key from an Entry without depending on GUI classes and configure OpenSSHKey. SSHAgent and EditEntryWidget have been updated to use this new style.
Future implementations may include context menu and hotkey based key management, cli support, global key management …
> SSH Agent: Refactor entry and agent key management

- src/gui/MainWindow.cpp
- src/gui/MainWindow.h
1-9 goes to 1-9 tab; 0 - goes to the last one
Please read Testing strategy, thanks!
In browsers we could not only use CTRL + PgDn/PgUp and CTRL (+ SHIFT) + TAB to switch tabs.
There is also ALT + <Number> which have various types of work. 1-9 operates on tabs from 1st to 9th one, and (on Chrome?) the 0 goes to last one.
On the another similar to KPXC application found this kind of feature. ;)
N/A
This is WIP, I wonder if this code could be (bc of less complexity) or should change to functor or some Signal mapper.
- ✅ I have compiled and verified …
> Enable browser-like DbTab experience (Alt + Nums)

- utils/keepassxc-cr-recovery/.gitignore
- utils/keepassxc-cr-recovery/README.md
- utils/keepassxc-cr-recovery/go.mod
- utils/keepassxc-cr-recovery/go.sum
- utils/keepassxc-cr-recovery/main.go
- ✅ tool in the utils directory
This adds a small command line tool to the utils folder (as requested in https://github.com/keepassxreboot/keepassxc/issues/1734#issuecomment-572032911) which will help with regaining access to a challenge-response protected database in case of a lost yubikey.
It will generate a keyfile based on your database and the original challenge-response secret (this needs to be saved upon initial configuration of the yubikey) which then can be used to unlock the database.
> Add challenge-response recovery tool

- src/core/Tools.cpp
- src/core/Tools.h
- src/sshagent/KeeAgentSettings.cpp
- src/sshagent/KeeAgentSettings.h
- tests/TestTools.cpp
- tests/TestTools.h
People usually want their SSH key file path to be relative to `$HOME` which helps transferring database between multiple systems with different local users. Automatic path pickup will use an absolute path but you can manually change it to use a tilde or any combination of environment variables.
For example the following key file paths work on Linux/Mac/BSD:
- `~/.ssh/id_rsa`
- `$HOME/.ssh/id_rsa`
Following hypothetical path should work on Windows:
- `%HOMEDRIVE%%HOMEPATH%\.ssh\id_rsa`
This work has been kindly supported by my employer, Vincit.
Fixes #3523
[TIP]:  # ( We expect new code to be covered by …
> Implement SSH key file path env substitution

- src/sshagent/AgentSettingsWidget.cpp
- src/sshagent/AgentSettingsWidget.ui
- src/sshagent/SSHAgent.cpp
- src/sshagent/SSHAgent.h
In issue #3683 and many others, the agent socket path environment variable is either missing or wrong in KeePassXC. Added a view to current effective environment variable and an override field to set a static path if so desired.
This work has been kindly supported by my employer, Vincit.
Fixes #3795
Manual testing on Linux. Manual testing of agent connection test on …
> SSH Agent: Add SSH_AUTH_SOCK override and connection test

- share/docs/man/keepassxc-cli.1
- src/cli/Create.cpp
- src/cli/Create.h
- src/crypto/kdf/Kdf.h
- src/gui/dbsettings/DatabaseSettingsWidgetEncryption.cpp
- src/gui/dbsettings/DatabaseSettingsWidgetEncryption.h
- src/gui/dbsettings/DatabaseSettingsWidgetEncryption.ui
- tests/TestCli.cpp
Added an option to set the target decryption time on database creation
for the CLI create command. This required some refactoring, in
particular the extraction of the min, max and defaut decryption times in
the `Kdf` module. Some work was done to allow changing those constant
only in the `Kdf` module, should we ever want to change them.
Manual testing and new unit tests for the CLI option. I also tested when changing the defaults and everything works great as long as the values in MS are multiple of the slider's increment value (100). …
> CLI: set decryption time on create.

- src/cli/Create.cpp
Fixes a name mismatch introduced in
b78ca924fdf2b6d5937d87bab65104cba629382f.
Currently, `db-create` is the correct invocation but `create` appears in all the runtime-generated documentation.
Tested manually. Unfortunately there are no tests that actually run the keepassxc-cli binary and simulate user input. Such a test would have caught this issue. …
> Use db-create as Create::name

- src/core/FilePath.cpp
- src/core/FilePath.h
- src/fdosecrets/widgets/SettingsModels.cpp
- src/fdosecrets/widgets/SettingsWidgetFdoSecrets.cpp
- src/gui/KMessageWidget.cpp
- src/gui/LineEdit.cpp
- src/gui/masterkey/PasswordEditWidget.cpp
- src/keeshare/group/EditGroupWidgetKeeShare.cpp
- utils/makeicons.sh
In fact, it removes functionality.
As requested in https://github.com/keepassxreboot/keepassxc/issues/475#issuecomment-573335843. With the Material Design icons (#475), any other icons brought in through the system icon theme will look inconsistent.
[NOTE]: # ( Please describe in detail how you …
> Ignore system icon theme, always use our own icons

- src/browser/BrowserAccessControlDialog.cpp
- src/browser/BrowserAccessControlDialog.h
- src/browser/BrowserAccessControlDialog.ui
- src/browser/BrowserService.cpp
- src/browser/BrowserService.h
Improves the confirm access dialog when requesting credentials from KeePassXC-Browser.
When confirm access dialog is displayed it's possible to select one or more credentials which are allowed or denied. All credentials are selected by default. Only the selected credentials are affected with the remember checkbox. Permissions to non-selected credentials will remain the same.
Previously you could select one credential from the popup but the selection didn't actually do anything. All credentials were still allowed or denied.
Manually.
- ✅ I have …
> Improve confirm access dialog for browser plugin

- src/cli/Export.cpp
- src/cli/TextStream.cpp
- src/cli/TextStream.h
Fix encoding problem when exporting the database into XML format.
Fixes https://github.com/keepassxreboot/keepassxc/issues/3900
Root case explained here: https://stackoverflow.com/questions/40318671/streaming-utf-8-literals-into-qtextstream
**Disclaimer**: I do not consider my change a proper fix. It works (correct XML is outputted), but I suspect the proper fix would …
> Wrap XML data into QString to fix encoding

- src/gui/MainWindow.cpp
- src/gui/MainWindow.h
Changes the browser-type tab switching from ⌥Alt+num to the standard ⌘Command+num with macOS.
Also changes using 0 to 9 with all OS's. 9 always goes to the last tab, which is also a standard behavior with browsers.
[NOTE]: # ( Pull Requests that don't …
> Fix browser-like DbTab experience with macOS and Windows

- INSTALL.md
Hi, I have noticed a slight ambiguity with the build instructions in INSTALL.md.  I had thought that the "directory-where-sources-live" was implying the src/ folder within the git folder, but it seems to be the root git folder.
I have just changed directory-where-sources-live to git-project-directory (I think this makes it more clear).
> Distinguish meaning of src directory and git root directory

- src/core/IconDownloader.cpp
Adds a missing check for icon downloading. When editing an entry and using the Icon Download button with an invalid URL, the URL list for icon download is empty, and it's never checked.
Fixes https://github.com/keepassxreboot/keepassxc/issues/4352.
[TIP]:  # ( We expect new code to be covered by unit …
> Icon downloader button crash fix

- src/gui/DatabaseWidget.cpp
Prior to when a database is saved after an edit, the Group and Entry Views are disabled which causes a loss in keyboard focus. This change sets the focus to Entry View after the views are re-enabled.
Fixes #4157 
All unit tests as well as manual testing.
- ✅ My code follows …
> Return keyboard focus after saving database edits

- src/core/Clock.cpp
- src/core/Clock.h
- src/gui/DatabaseWidget.cpp
- src/gui/MainWindow.cpp
- src/gui/MainWindow.h
- src/gui/TotpDialog.cpp
- src/gui/TotpExportSettingsDialog.cpp
* Bug with window both minimized and hidden is reported in XFCE/LXDE - that is X11 desktops. You can run a X11 desktop on any platform - X11 is portable. Detect running X11 rather than the OS.
* Sometimes the main window hides just after clicking the tray icon to show it.
Add a timer to not hide window immediately after it is shown.
* The workaround for window hiding after shown breaks Windows tests for some reason. Don't apply it on windows. 
* The main window fails to minimize in X11 in some WMs that don't support minimization (in olden days some WMs did not support minimization but minimized windows were simply lost). There is an option for hiding the window in tray instead of minimizing. Honor it. …
> Fix window hiding right after being shown on X11, fix window not minimizing in X11

- src/gui/group/GroupModel.cpp
Previous behavior: When only one database is open there is no display showing the opened database path and filename.
With this change, mousing over the root group entry will now display the database file path.
Fixes #4038 …
> Display database path in root group tooltip

- src/browser/BrowserService.cpp
So it can be displayed in the autocomplete list when more than one login matches. 
For users that use groups and have similar names for multiple logins but they are organized in different groups.
Fixes https://github.com/keepassxreboot/keepassxc-browser/issues/466 together with https://github.com/keepassxreboot/keepassxc-browser/pull/739
Create multiple entries for the same URL in different groups.
Use the browser extension with the changes from https://github.com/keepassxreboot/keepassxc-browser/pull/739.
I also tested edge cases
* Older KeepassXC version without this change: Browser extension still works
* All entries being in the same group
I am not sure if the group can be null. Is it safe like this? At least I wasn't able …
> Add the name of the group to the results for browser extensions

- src/gui/DatabaseWidget.cpp
- src/gui/DatabaseWidget.h
- src/gui/MainWindow.cpp
Don't take the focus into account when setting certain menuitem's enabled / disabled state.
Fixes https://github.com/keepassxreboot/keepassxc/issues/3770
I did not see any need to have the `hasFocus` condition. Without it, the application behaves intuitively: toolbar buttons are only disabled if an entry is visually unselected.
[NOTE]: # ( Please describe in detail …
> Ignore focus when checking toolbar state

- src/fdosecrets/widgets/DatabaseSettingsWidgetFdoSecrets.ui
- src/fdosecrets/widgets/SettingsWidgetFdoSecrets.cpp
- src/fdosecrets/widgets/SettingsWidgetFdoSecrets.h
- src/fdosecrets/widgets/SettingsWidgetFdoSecrets.ui
Reworks the settings page logic so that the page is only enabled if there is indeed a service instance. Fixes the crash reported in #4311.
To avoid confusion, the page now displays a message prompting the user to save before they can edit the rest part. A new message widget is used because this prompt can appear at the same time with an existing service warning.
Fixes …
> FdoSecrets: fix crash when editing settings before service is enabled

- src/sshagent/AgentSettingsWidget.cpp
- src/sshagent/SSHAgent.cpp
- src/sshagent/SSHAgent.h
- tests/CMakeLists.txt
- tests/TestSSHAgent.cpp
- tests/TestSSHAgent.h
By depending on OpenSSH `ssh-agent` we can implement proper `SSHAgent` integration testing. These tests will not be supported on Windows but they should provide full coverage excluding a few Windows specific Pageant bits.
This depends on cleanups in #4256.
- ✅ All new and …
> Implement SSH Agent integration tests

- CHANGELOG.md
- share/docs/man/keepassxc-cli.1
- src/cli/Create.cpp
- src/cli/Create.h
- src/cli/Import.cpp
- src/cli/Utils.cpp
- src/cli/Utils.h
- tests/TestCli.cpp
Fixes https://github.com/keepassxreboot/keepassxc/issues/4307
This makes sure that there's no clash between the database opening options (`--no-password` and `--key-file`) and the database creation/modification options, which start by `--set`. The main consequence is that setting the password on creation must be done explicitly, but I feel like it's ok to be explicit when creating the  db. 
unit tests.
[NOTE]: # ( Again, remove any lines …
> CLI: Cleanup create options

- src/autotype/AutoType.cpp
- src/core/Entry.cpp
- src/core/Entry.h
This PR adds support for AutoType DateTime placeholders, in the same way KeePass2 has it.
https://keepass.info/help/base/placeholders.html
PS: This is my first contribution to a C++ project in general and KeePassXC specifically :)
I used DateTime placeholders in KeePass2 all the time, but switched to KeePassXC. So i added the following AutoType placeholders.
Placeholder | Is Replaced By
-- | --
{DT_SIMPLE} | Current local date/time as a simple, sortable string. For example, for 2012-07-25 17:05:34 the value is 20120725170534.
{DT_YEAR} | Year component of the current local date/time.
{DT_MONTH} | Month component of the current local date/time.
{DT_DAY} | Day component of the current local date/time.
{DT_HOUR} | Hour component …
> Add DateTime placeholders to AutoType feature

- src/sshagent/KeeAgentSettings.cpp
- src/sshagent/KeeAgentSettings.h
Since #3833 was merged, `KeeAgentSettings` was not properly initialized and caused random _KeeAgent.settings_ attachments on every new entry.
Luckily @droidmonkey picked this up before even before any pre-release was made.
Quick testing by hand.
- ✅ My code follows the code …
> Add back missing initializers to KeeAgentSettings

- src/gui/entry/EntryModel.cpp
- Notes are hidden in preview panel when set to mask on default, but not in the entry view. This checks if notes are set to be hidden and masks them in the entry view if so.
- Fixes #4412 
Unit and manual testing
> Hide notes in entry view when hidden in preview panel

- src/gui/reports/ReportsWidgetHibp.cpp
- src/gui/reports/ReportsWidgetHibp.h
- src/gui/reports/ReportsWidgetHibp.ui
* Show horizontal header in results table
* Correctly handle the case when there are no entries to analyze
* Make countToText static
[NOTE]: # ( to be sent back to you for …
> Fix issues with HIBP report

- docs/KEYBINDS.md
- src/gui/DatabaseWidget.cpp
- src/gui/DatabaseWidget.h
- src/gui/MainWindow.cpp
- src/gui/MainWindow.h
- src/gui/MainWindow.ui
- src/gui/entry/EditEntryWidget.cpp
- src/sshagent/KeeAgentSettings.cpp
- src/sshagent/KeeAgentSettings.h
- src/sshagent/SSHAgent.cpp
- src/sshagent/SSHAgent.h
Allow controlling entry SSH Agent integration with hotkeys (Ctrl-H and Ctrl-Shift-H) and via context menu.
Fixes #1815.
Manually on Linux.
[NOTE]: # ( Again, …
> SSH Agent: Entry context menu control

- src/cli/Utils.cpp
- tests/TestCli.cpp
This fix allows copying passwords on Wayland, where xclip does not work. I've also slightly changed the code so that other clipboard tools could be easily added in the future.  #3812 
> On Unix, copy to clipboard using wl-clipboard if xclip is not available

- src/core/FileWatcher.cpp
* When FileWatcher::stop() is called, also stop the timer that checks the file checksum every 30 seconds.
> Stop file checksum compare when stop is called

- src/gui/MainWindow.cpp
- src/gui/MainWindow.h
Fixes separator being visible despite multiple tabs being active when KeePassXC started hidden in the tray.
Tabbar hidden as expected when starting in the tray with multiple tabs open. Also tested all other combinations of tabs being visible or not and different stacked widget pages.
> Fix tabbar separator visibility

- src/core/Entry.cpp
- src/core/Entry.h
- src/gui/entry/EntryModel.cpp
- src/gui/entry/EntryModel.h
- src/gui/entry/EntryView.cpp
- tests/TestEntryModel.cpp
Adds a size column to the entry view that displays the size of each entry in KiB
Closes #4101
Unit and Manual Testing
- ✅ I have modified tests to cover my changes.
> Add "Size" column to entry view

- src/gui/styles/base/BaseStyle.cpp
Menu spacing looked fine on most platforms and on high-DPI Windows, but was very crammed on low-DPI Windows.
Before:
After:
Tested on low- and high-DPI Windows and on Linux with KDE Plasma desktop.  1.0/4.0 is too much on all platforms except low-DPI Windows, whereas 1.0/6.0 and smaller is too little. 1.0/5.0 looks decent everywhere, probably due to rounding errors. …
> Fix menu menu spacing on low-DPI Windows

- share/windows/KPXC_ExitDlg.wxs
- share/windows/KPXC_InstallDir.wxs
- share/windows/KPXC_InstallDirDlg.wxs
- share/windows/wix-template.xml
- src/CMakeLists.txt
- src/gui/ApplicationSettingsWidget.cpp
- src/gui/ApplicationSettingsWidgetGeneral.ui
- src/gui/osutils/OSUtilsBase.h
- src/gui/osutils/macutils/MacUtils.cpp
- src/gui/osutils/macutils/MacUtils.h
- src/gui/osutils/nixutils/NixUtils.cpp
- src/gui/osutils/nixutils/NixUtils.h
- src/gui/osutils/winutils/WinUtils.cpp
- src/gui/osutils/winutils/WinUtils.h
- src/main.cpp
Adds autostart option on all platforms.
Works on all platforms, but macOS is a bit special. It doesn't show up in the user's login items, since we'd have to write a separate helper app for that whose only responsibility is to launch KeePassXC.
Fixes #1218
.desktop file is created at correct location and settings widget responds to its presence. Windows works perfectly, macOS works okay-ish (not user editable, because we are not using …
> Add option to launch KeePassXC at system startup

- tests/TestCli.cpp
The CLI clip test fails very often on the Linux CI, most likely due to timing issues. Propagating the clipboard contents from KeePassXC to xclip, then to the X server, and back to KeePassXC may take a while, particularly if the build agent doesn't have exclusive access to the host CPU (the CI Kubernetes cluster shares resources with other jobs).
CLI tests pass locally, let's see what the CI has to say.
[NOTE]: # ( Please remove all …
> Make CLI clip test more reliable

- snap/snapcraft.yaml
Fixes #4663 by adding xclip into the snap and adding the x11 plug to keepass.cli
Used snapcraft on my machine with my changes and it solved the issue:
- Ran `snapcraft`
- Installed with ` sudo snap install --dangerous <pat_to_snap`
- Tested with `keepass.cli clip <db_path> <entry_path>`
> Add xclip into snap

- src/core/Bootstrap.cpp
This option didn't work properly when "Hide window to system tray when minimised" was also enabled.
I don't see a particular reason why Windows shouldn't be calling hideWindow() like all other platforms. hideWindow() takes care of choosing the correct minimisation mode based on the user's settings.
Tested different combinations of tray and minimise settings, worked flawlessly. …
> Fix "Minimise at startup" on Windows

- src/core/Database.cpp
- src/core/FileWatcher.cpp
- src/core/FileWatcher.h
- src/gui/FileDialog.cpp
- src/gui/FileDialog.h
- src/keeshare/KeeShare.cpp
- src/keeshare/ShareObserver.cpp
- src/keeshare/ShareObserver.h
- src/keeshare/group/EditGroupWidgetKeeShare.cpp
- src/keeshare/group/EditGroupWidgetKeeShare.h
* Fix #3790, shares now use the standard FileWatcher class to detect remote file changes using checksums and file system triggers.
* Fix #3895, macOS file selection no longer hangs the app.
* Restore saving of KeeShare settings accidentally removed by 596d2cf
Tested on Windows and Linux using SMB shares to ensure changes were detected. Tested on macOS for file open dialogs.
- ✅ …
> Fix various issues with KeeShare

- src/cli/Add.cpp
- src/cli/AddGroup.cpp
- src/cli/Analyze.cpp
- src/cli/Clip.cpp
- src/cli/Command.cpp
- src/cli/Create.cpp
- src/cli/DatabaseCommand.cpp
- src/cli/Diceware.cpp
- src/cli/Edit.cpp
- src/cli/Estimate.cpp
- src/cli/Export.cpp
- src/cli/Generate.cpp
- src/cli/Help.cpp
- src/cli/Import.cpp
- src/cli/Info.cpp
- src/cli/List.cpp
- src/cli/Locate.cpp
- src/cli/Merge.cpp
- src/cli/Move.cpp
- src/cli/Remove.cpp
- src/cli/RemoveGroup.cpp
- src/cli/Show.cpp
- src/cli/Utils.cpp
- src/cli/Utils.h
- src/cli/keepassxc-cli.cpp
- src/format/KdbxWriter.h
- src/keys/YkChallengeResponseKeyCLI.cpp
- src/keys/YkChallengeResponseKeyCLI.h
- tests/TestCli.cpp
- tests/TestCli.h
* Use stderr for password prompts (from @pluvano)
* Fixes #3398
* Convert to QTextStream for all CLI IO and greatly improve CLI tests
* Completely overhaul CLI tests to be much more streamlined and easy to read. Removed unnecessary code blocks by using existing functions.
Significantly improved reliability of CLI tests
- ✅ …
> CLI: Use stderr for password prompts and improve tests

- src/core/EntrySearcher.cpp
- src/core/EntrySearcher.h
- src/gui/SearchHelpWidget.ui
- tests/TestEntrySearcher.cpp
- tests/TestEntrySearcher.h
Count results of search with generic and specific group search term
Fixes #3482
> Add group search

- src/gui/DatabaseWidget.cpp
- src/gui/DatabaseWidget.h
- src/gui/EntryPreviewWidget.cpp
- src/gui/EntryPreviewWidget.ui
- src/gui/MainWindow.cpp
- src/gui/MainWindow.h
- src/gui/MainWindow.ui
- src/gui/SearchWidget.cpp
- src/gui/group/GroupView.cpp
- src/gui/group/GroupView.h
- tests/gui/TestGui.cpp
* Override Qt's default [broken] behavior of handling Tab/Shift+Tab to navigate around the MainWindow. Completely fixes trapped focus.
* Improve handling of search results when navigating the UI.
* Fix selecting first entry after ending a search.
* Add keyboard shortcuts to directly focus on search (F1), Group List (F2), and Entry List (F3)
* Fixes #2878
* Fixes #4636
* Fixes #4221 
None
[TIP]:  # ( We expect new code to be covered by unit tests and documented …
> Fix changing focus around the main window using tab

- src/core/Database.cpp
This removes read-only mode.
The underlying motivation is #803 (and maybe #1937), where a qt bug triggers keepassxc to always open in read-only mode on some filesystems. I am also guessing that read-only mode is vestigial, and may be removed to work around the bug.
As I explained [my comment on the issue](https://github.com/keepassxreboot/keepassxc/issues/803#issuecomment-605207384), read-only mode seems to not be fully functional. I can't find any documentation on read-only mode or its place in the vision of multi-user / multi-client support in KeePassXC; my inference is that read-only mode is part of an old "office-style" mandatory explicit locking mechanism, and KeeShare is the new mechanism.
If I got the vision wrong, please let …
> Deactivate read-only mode autodetection. Fixes #803.

- src/browser/BrowserSettings.cpp
- src/browser/BrowserSettings.h
- src/browser/BrowserSettingsWidget.cpp
- src/browser/BrowserSettingsWidget.ui
- src/browser/NativeMessageInstaller.cpp
- src/core/Config.cpp
- src/core/Config.h
- src/gui/dbsettings/DatabaseSettingsWidgetBrowser.cpp
- src/gui/dbsettings/DatabaseSettingsWidgetBrowser.h
Allows editing the browser extension connection keys. Both key and identifier value can be changed. Editing "Created" timestamp is not allowed.
Editing works using double click on the mouse. A keyboard shortcut could be also added if needed.
Also adds an option to use a custom extension ID with debug builds.
Fixes #3819.
[NOTE]: # ( Please describe in detail …
> Allow manual editing of browser extension connection keys & add option for custom extension ID

- src/browser/BrowserService.cpp
- src/browser/BrowserService.h
Changes made:
- When "Search from all databases" is enabled, access control dialog is not executed when switching between open databases. Switching from locked to to open again, the dialog will be shown.
- Do not hide the application main window when switching databases when the access control dialog is visible. Switching to another tab rejects the dialog.
Fixes #4639.
Manually.
[NOTE]: # ( Please remove all lines which don't apply. …
> Fix annoyances with access control dialog

- src/core/Config.cpp
- src/core/Config.h
- src/gui/DatabaseWidgetStateSync.cpp
Changes the behavior of the "Hide Passwords" setting in entry view so it no longer persists across runs.
It is easy to accidentally activate the keyboard shortcut for this setting without an obvious way to change it back (see #4378). Since it's possible for a user to unintentionally switch to less secure behavior, either the switch should be temporary or it should be harder to accidentally trigger (remove the keyboard shortcut). Making it temporary is probably the less disruptive change between those options.
[TIP]:  # ( We …
> Make 'show/hide passwords' toggle temporary

- src/browser/BrowserService.cpp
- src/browser/BrowserService.h
- src/gui/DatabaseTabWidget.cpp
- src/gui/DatabaseTabWidget.h
- src/gui/MainWindow.cpp
Instead of rising the KeePassXC window to the front, a separate unlock dialog is used.
Manually. …
> Use unlock dialog when unlocking a database from browser extension

- src/gui/entry/EditEntryWidget.cpp
- src/sshagent/KeeAgentSettings.cpp
- src/sshagent/KeeAgentSettings.h
Entry attachments are updated only after apply and the refactored agent code depended on Entry. This fix introduces the least amount of dependencies to KeeAgentSettings while keeping the functionality identical.
Fixes regression since #3833 was merged
[TIP]:  # ( We expect new code to be covered by …
> SSH Agent: Fix attachment data not updating before apply

- src/gui/DatabaseWidget.cpp
- src/gui/entry/EditEntryWidget.cpp
- src/sshagent/SSHAgent.cpp
- src/sshagent/SSHAgent.h
- tests/TestSSHAgent.cpp
- tests/TestSSHAgent.h
We did not track which database "owned" what key so when any database is closed/locked all keys that had remove-on-lock set were cleared from the agent.
This change adds database UUID tracking when adding keys and outright refuses to add the same key from two different databases for simplicity. Null QUuid can be and is used for testing.
Signals and slots had to be refactored to use the `databaseLockRequested` signal to detect a lock request as `databaseLocked` was emitted after the Database object was cleared from data which also changed the UUID.
Additionally const'd some SSHAgent arguments.
[NOTE]: # …
> SSH Agent: Track which database owns a key for remove-on-lock

- src/core/Bootstrap.cpp
Qt uses "MS Shell Dlg 2" as the default font, which resolves to Tahoma and not Segoe UI, which is the actual Windows 10 default font.
Before:
After:
I checked the exact pixel dimensions of the font at various font scaling settings. The application still doesn't react immediately when you change the "Make text bigger" setting, but at least it does react at all now …
> Use Segoe UI font on Windows.

- src/core/Entry.cpp
- src/core/Entry.h
- src/gui/DatabaseWidget.cpp
Add placeholder `{DB_DIR}` for the url of the autoopen functionality
Adding placeholder for the url of the autoopen functionality would it make easier to sync a database with a child database on multiple devices via file sharing services.
e.g. `{DB_DIR}/passwords.kdbx`
Currently relative paths and absolute paths work in KeepassXC (https://github.com/keepassxreboot/keepassxc/pull/1053).
But relative paths do not work in Keepass2 or other clients i.e Keepass2Android, whereas path placeholders work in those clients.
Keepass placeholders:
https://keepass.info/help/base/placeholders.html
Fixes #3863 
created databases linked them to the parent database, using different url styles (relative path, `file:///`, and with `{DB_DIR}`) …
> Add DB_DIR placeholder for autoopen urls

- src/gui/DatabaseWidget.cpp
Fix a bug where trying to 'save as' with an invalid file name and then
cancelling would cause the application to continue trying to use the
invalid path.
The 'save as' method changes the database path to the user's input before attempting to save, but didn't change the path back if the save fails. Future saves would fail because they would attempt to use the invalid …
> Reset database path after failed 'save as'

- src/gui/entry/EntryAttachmentsWidget.cpp
- src/gui/entry/EntryAttachmentsWidget.h
The EntryAttachmentsWidget is changed such that a warning is issued to the user if he uploads one or more attachments that have size > 5MB. Added a function to EntryAttachmentsWidget.cpp that does the checking and issues warning.
Closes #3782
**User tries to upload three files where two of them are >5MB.**
**User is issued a warning that two of them are large files.**
**The files are added to the widget.**
All previous test pass.
> Issue a warning before adding large attachments

- src/gui/DatabaseTabWidget.cpp
`count()` will change if some tabs without a file were closed because of locking. So `numLocked` will be different from `count()`. I found this while working on some gui tests, which marks every tab clean and close them all.
The fix is to simply save the count at the beginning.
* create a new database
* mark it as clean
* call `lockDatabases`
It should return `true` rather than `false`.
[NOTE]: # ( Please remove all lines which don't …
> Fix DatabaseTabWidget::lockDatabases returns false even when all tabs are locked

- src/gui/MainWindow.cpp
- src/gui/MainWindow.h
- src/gui/osutils/macutils/AppKit.h
- src/gui/osutils/macutils/AppKitImpl.h
- src/gui/osutils/macutils/AppKitImpl.mm
- src/gui/osutils/macutils/MacUtils.cpp
- src/gui/osutils/macutils/MacUtils.h
Transforms application into a UIElement agent app when minimize to tray is enabled and the window is hidden. This hides the dock icon and removes the application from the Cmd+Tab listing. The changes work well together with macOS's inbuilt hide feature.
Also fixes the buggy tray icon context menu trigger behaviour. macOS triggers the tray context menu also on normal left click, which causes the window to toggle at the same time as the menu. To fix this, window toggling has been disabled altogether on macOS and users will be shown only the context menu from now on.
Fixes #1334
[NOTE]: # ( …
> Hide window and dock icon on macOS when tray enabled

- src/core/EntrySearcher.cpp
- src/core/EntrySearcher.h
- src/fdosecrets/FdoSecretsPlugin.cpp
- src/fdosecrets/objects/Collection.cpp
- src/fdosecrets/objects/Collection.h
- src/fdosecrets/objects/DBusObject.h
- src/fdosecrets/objects/DBusTypes.cpp
- src/fdosecrets/objects/Item.cpp
- src/fdosecrets/objects/Item.h
- src/fdosecrets/objects/Prompt.cpp
- src/fdosecrets/objects/Prompt.h
- src/fdosecrets/objects/Session.cpp
- src/fdosecrets/objects/SessionCipher.cpp
- src/fdosecrets/objects/SessionCipher.h
- src/fdosecrets/widgets/SettingsModels.cpp
- src/gui/DatabaseTabWidget.cpp
- src/gui/DatabaseTabWidget.h
- tests/CMakeLists.txt
- tests/TestEntrySearcher.cpp
- tests/TestEntrySearcher.h
- tests/data/dbus/interfaces/org.freedesktop.Secret.Collection.xml
- tests/data/dbus/interfaces/org.freedesktop.Secret.Item.xml
- tests/data/dbus/interfaces/org.freedesktop.Secret.Prompt.xml
- tests/data/dbus/interfaces/org.freedesktop.Secret.Service.xml
- tests/data/dbus/interfaces/org.freedesktop.Secret.Session.xml
- tests/data/dbus/session.conf
- tests/gui/CMakeLists.txt
- tests/gui/TestGuiFdoSecrets.cpp
- tests/gui/TestGuiFdoSecrets.h
This adds proper unit tests to the secret service integration plugin. The tests cover most exposed API and some regression tests for previously fixed issues.
The first commit adds all test cases. The whole test is added as a GUI test because currently the plugin still depends on `DatabaseWidget`. Other …
> FdoSecrets: Add unit tests for secret service integration

- tests/TestOpVaultReader.cpp
Just a simple lost pointer in a test case.
I think the `QScopedPointer` in `OpVaultReader::readDatabase` gave a false sense of security.
`valgrind build/tests/testopvaultreader` no longer shows leaked memory
> Fix memory leak in test

- src/core/Resources.cpp
- src/core/Resources.h
- src/gui/ApplicationSettingsWidget.cpp
The tray icon appearance setting is null by default, since we do not
want to include OSUtils into Config. As a result, we must take special
care to preselect the correct combo box entry on the settings page.
> Fix loading of tray icon appearance setting

- src/gui/WelcomeWidget.cpp
- src/gui/WelcomeWidget.h
While a database in the "Recent databases" on the welcome screen is selected, pressing the "Delete" key will now cause that database to be removed from the recent databases list.
Fixes #4710 
Additionally, this fixes a segfault that occurs when a user presses Enter while the "Recent databases" widget is in focus but no database is selected.
I did some manual tests.  
I'm new to this so let me know if/how I should implement tests.
> Cleanup welcome screen recent databases view

- src/gui/DatabaseOpenWidget.cpp
- src/gui/DatabaseOpenWidget.h
- src/gui/DatabaseOpenWidget.ui
- src/gui/KeePass1OpenWidget.cpp
* Only clear password field when switching tabs or minimizing. This prevents the setting "Remember Key Files and Hardware Keys" from being useless with multiple databases.
* Convert key file field to Line Edit, simplifies usage. Fix clear field button as well.
* Removed need for clearForms to check if the database is being opened (was a solution to tab switching while unlocking, no longer a problem).
Tested multiple ways manually. …
> Fix minor UX issues with DB Open Widget

- src/core/Database.cpp
- src/keys/FileKey.cpp
- tests/gui/TestGuiFdoSecrets.cpp
* Saving a database in unsafe mode retains the existing permissions on the kdbx file
* New databases (save as, save backup, new database) and new key files are saved with 0600 permissions (user read/write), fixes #2575
Tested on all platforms, these changes really only apply to *nix systems. Windows by default inherits folder permissions and changes to permissions on individual files is ignored by Qt.
[NOTE]: # ( Please remove all …
> Fix permissions changing on database save

- CMakeLists.txt
Adds ability to list what languages a compiler flag should be used for; defaults to "C CXX".
Bumps required cmake to 3.3 for IN_LIST (released July 2015, so should be a safe assumption)
- See also #4807 for origin
- I didn't see anywhere else in the repo that mentioned the explicit `cmake` version; there may be other locations.
- If `cmake` bump unacceptable, there are workarounds
Tested locally with `gcc` and `clang` on Fedora 32 and `gcc` on MSYS2/x86/Win10
> Reduce compiler flag warnings depending on language

- src/core/Config.cpp
* Use the native application name for the config folder versus the camel-case name defined later
* Fixes #4835
> On case-sensitive OS, force use of lowercase config directory

- src/fdosecrets/FdoSecretsPlugin.cpp
FdoSecretsPlugin is added to m_extraPages in ApplicationSettingsWidget
via addSettingsPage(). m_extraPages holds QSharedPointer's to added
pages, so those pages are freed when ApplicationSettingsWidget is freed.
If FdoSecretsPlugin also declares tabWidget as parent, double deletion
will occur and may cause crashes:
```
==1472== Invalid read of size 8
==1472==    at 0x1CCF38: QtSharedPointer::CustomDeleter<ISettingsPage, QtSharedPointer::NormalDeleter>::execute() (qsharedpointer_impl.h:186)
==1472==    by 0x1CCCEC: QtSharedPointer::ExternalRefCountWithCustomDeleter<ISettingsPage, QtSharedPointer::NormalDeleter>::deleter(QtSharedPointer::ExternalRefCountData*) (qsharedpointer_impl.h:204)
==1472==    by 0x18F6F4: QtSharedPointer::ExternalRefCountData::destroy() (qsharedpointer_impl.h:148) …
```
> FdoSecrets: fix double deletion

- src/fdosecrets/FdoSecretsPlugin.cpp
- src/fdosecrets/FdoSecretsPlugin.h
- tests/gui/TestGuiFdoSecrets.cpp
* Prevent double free due to QObject cleanup happening before/after the ExtraPage  storing the QSharedPointer to FdoSecretsPlugin is deleted.
* Fixes #4877
> FDO Secrets: Fix double free on exit

- src/browser/BrowserHost.cpp
- src/proxy/CMakeLists.txt
- src/proxy/NativeMessagingProxy.cpp
With the new browser integration refactor adjusting the send buffer size was removed. This causes large messages to be dropped.
Manually. For testing this you need a database with a lot of groups (30-40) which causes the reply for `get-database-groups` request being quite large. Without the higher buffer setting the message never leaves the Unix socket, or the proxy.
This can be easily tested when saving new credentials with option …
> Fix adjusting send buffer size

- src/main.cpp
[FIX] --pw-stdin throws errors: QTextStream: No device on debian sid
`$ echo foo|keepassxc --pw-stdin --keyfile bar.key baz.kdbx`
`Database password: QTextStream: No device`
`QTextStream: No device`
After changing --pw-stdin does not throw errors any more and the password is used. 
> Fix --pw-stdin by initializing text streams

- src/gui/MainWindow.cpp
* Fix #4768
* MainWindow::updateTrayIcon() is called in MainWindow::applySettingsChanges() earlier in construction. Calling this function twice in a row causes issues with startup times on Linux.
> Remove redundant call to update tray icon during startup

- src/gui/MainWindow.cpp
* Fixes #4885
After the Config changes we were checking `Config::Security_ResetTouchIdTimeout` instead of `Config::Security_ResetTouchId` to determine if the timeout value should be honored.
> Fix Touch ID timeout not being set correctly

- src/main.cpp
> Call `QGuiApplication::setHighDpiScaleFactorRoundingPolicy` to fix #2815

- src/autotype/AutoType.cpp
- src/autotype/AutoType.h
- src/browser/BrowserService.cpp
- src/browser/BrowserService.h
Hides the KeePassXC main window properly when unlocking a database, showing Access Confirm dialog or saving new credentials.
Fixes #4904.
Manually.
> Hide window after unlock dialog

- src/keys/drivers/YubiKey.cpp
Yubikey code was checking the slot number based on the yubikey key number instead of the slot loop number. This PR fixes that typo so that if a single yubikey is plugged in, slot 2 will still be checked (and if a second yubikey is plugged in, then its slot 1 will be checked) which is not currently happening.
Fixes #4987 
> Fix slot detection when first YubiKey is configured on slot 2

- src/core/Resources.cpp
qt5ct randomly resets the active Qt icon theme to "", resulting in empty or wrong icons.
See https://sourceforge.net/p/qt5ct/tickets/80/
Fixes #4963 
Icons are no longer missing when `QT_QPA_PLATFORMTHEME=qt5ct` is set.
> Reset icon theme name before calling QIcon::fromTheme().

- share/linux/org.keepassxc.KeePassXC.appdata.xml
It is usable by both Gnome Software, KDE Discover and web frontends,
such as Flathub which now enforces OARS.
By using OARS 1.0 all distributions should be supported. Version 1.1
should work almost everywhere, but there are a few notable distributions
that still lack GNOME Software >= 3.27.3.
In this case it should not matter, because the OARS data is the same for
both versions (nothing 1.1 specific is used).
You can generate and verify these changes using:
https://odrs.gnome.org/oars
`appstream-util validate share/linux/org.keepassxc.KeePassXC.appdata.xml`
> Add OARS metadata

- share/linux/org.keepassxc.KeePassXC.appdata.xml
Update url filenames to reflect updates at keepassxc.org. This is however not sufficient because it only satisfies `appstream-util validate-relax`. At least Flathub now enforces `appstream-util validate` which is stricter:
```
• attribute-invalid     : <screenshot> width (580) too small [https://keepassxc.org/images/screenshots/thumbs/welcome_screen.png] minimum is 624px
• attribute-invalid     : <screenshot> width (580) too small [https://keepassxc.org/images/screenshots/thumbs/edit_entry.png] minimum is 624px
• attribute-invalid     : <screenshot> width (622) too small [https://keepassxc.org/images/screenshots/thumbs/edit_entry_icons.png] minimum is 624px
• attribute-invalid     : <screenshot> width (580) too small [https://keepassxc.org/images/screenshots/thumbs/database_view.png] …
```
> Partially fix appdata screenshots

- src/core/Tools.cpp
- tests/TestTools.cpp
Fixes #5008 partly. We can safely assume `~` means some sort of home directory on any platform.
Updated tests.
> Substitute tilde with USERPROFILE on Windows

- src/sshagent/SSHAgent.cpp
The new stricter tracking of who owns a key triggered #5016 as the database uuid changes if you *close* it and re-open rather than lock and unlock. This only happens for keys that don't have remove-on-lock set.
I don't recall why we kept a known key in-memory after locking or closing databases in the first place. The snippet that this PR removes was originally introduced way back in 2018 by 785a64cc3b3123541657831e615b0e97d3341ca5.
Fixes #5016.
Manually on Linux.
> SSH Agent: Always forget all keys on lock

- src/core/Entry.cpp
- src/totp/totp.cpp
* Fix #5105 - prevent divide-by-zero segfault due to invalid TOTP settings
* Clear TOTP settings if attributes are removed
> Fix crash if TOTP digits exceeds 10

- docs/CMakeLists.txt
When using `cmake -GNinja` the build fails with
```
ninja: error: '/usr/ports/security/keepassxc/work/keepassxc-2.6.0/docs/man/*', needed by 'docs/keepassxc.1', missing and no known rule to make it
```
> Unbreak build with Ninja

- src/cli/Info.cpp
> Fix 'db-info' command name to show it right in 'help'

- src/browser/BrowserService.cpp
- src/browser/BrowserService.h
- tests/TestBrowser.cpp
- tests/TestBrowser.h
When _Return only best-matching credentials_ is enabled matching is also done based to subdomain and URL path.
This requires https://github.com/keepassxreboot/keepassxc-browser/pull/904 for full support so let's include this to 2.6.1 so the extension can be upgraded before the release. Otherwise the best-matching feature will not work properly.
Fixes https://github.com/keepassxreboot/keepassxc/issues/4734.
Fixes https://github.com/keepassxreboot/keepassxc/issues/4754.
[TIP]:  # ( We expect new code to be covered by unit …
> Adjust matching with best-matching credentials enabled

- src/autotype/AutoType.cpp
- src/autotype/AutoType.h
- src/gui/DatabaseWidget.cpp
- src/gui/DatabaseWidget.h
- src/gui/MainWindow.cpp
- src/gui/MainWindow.ui
**Add option to Auto-Type just the username/password**
Fixes #4444
Some websites these days do not present both the "username" and the "password"
input box on the same webpage (e.g. Google, Amazon). So no custom sequence is
possible to enter both the said attributes in one go.
So, two new context menu actions have been added:
1. To perform the Auto-Type-ing of just the username
2. To perform the Auto-Type-ing of just the password
These context menu actions are analogous to "Copy username" and "Copy
password", except it avoids sending all characters via clipboard.
It "partially fixes" #3630, which is about the ability to perform Auto-Type-ing
of any arbitrary attribute. This PR gives the ability for just the two most
important attributes: the username and the password, for now.
The …
> Add option to auto-type just the username/password

- src/gui/entry/EntryAttachmentsWidget.cpp
- src/gui/entry/EntryAttachmentsWidget.h
Buttons Save and Open are now always visible.
User needs to save and open attachment in read-only mode using buttons.
Fixes #2039
Please check how it looks with dummy database
View and check attachment panel in read-only mode and edit mode.
> Open and save attachment in readonly mode

- src/gui/Application.cpp
- src/gui/URLEdit.cpp
- src/gui/URLEdit.h
- src/gui/entry/EntryURLModel.cpp
- src/gui/styles/base/basestyle.qss
- src/gui/styles/dark/darkstyle.qss
- src/gui/styles/light/lightstyle.qss
* Support mouse hover color change for QPushButtons.
* Fix #5040 - don't enforce standard palette when in classic theme mode
> Minor theme fixes

- src/gui/Clipboard.cpp
Clipboard is cleared on lock only when the clipboard timer is active. This will ensure the clipboard is always cleared on database lock
Closes #5020 
Unit and manual testing
> Clear clipboard on database lock

- src/gui/Application.cpp
- src/gui/osutils/winutils/WinUtils.cpp
- src/gui/osutils/winutils/WinUtils.h
The light and dark theme don't respond to Windows's high contrast accessibility mode, so when the theme is set to "auto", we
default to "classic" instead of "light".
Fixes #5044 
Set theme to auto and enabled high contrast mode in the Windows settings.
> Switch to classic if theme set to auto and high contast mode is on

- src/gui/PasswordGeneratorWidget.cpp
- src/gui/PasswordGeneratorWidget.h
- src/gui/PasswordGeneratorWidget.ui
- src/gui/styles/base/basestyle.qss
* Fix #5098 - Ensure advanced mode settings are saved distinctly from simple mode settings
* Make selected character groups pop out in the UI
* Improve layout of character options
> Improve Password Generator Widget UI/UX

- src/gui/CategoryListWidget.cpp
I've tested a321471 and PR #5185 doesn't fix the problem with clipped labels of category widget ~on systems with HiDPI displays~. This PR should fix the issue.
Fixes #5164
I've tested it only under Arch Linux though and only with 2 devices (17" HD+ and 15" FHD).
- ✅ Bug fix (non-breaking change that fixes an …
> Fix clipped labels when Light/Dark theme is used

- src/browser/BrowserAccessControlDialog.cpp
- src/browser/BrowserAccessControlDialog.h
- src/browser/BrowserService.cpp
* Prevents dialog from growing in width if there is a really long url requesting access.
**BEFORE:**
**AFTER:**
> Only display domain name in browser access confirm dialog

- src/gui/entry/EditEntryWidget.cpp
Update "Open Auto-Type help webpage" URL to the actual documentation site.
Probably not necessary just for an updated URL.
> Update "Open Auto-Type help webpage" URL

- src/gui/Application.cpp
- src/gui/DatabaseWidget.cpp
- src/gui/styles/base/basestyle.qss
- src/gui/styles/base/classicstyle.qss
- src/gui/styles/styles.qrc
Proposed fix for: #5049
The idea here would be to adjust the search-banner theme just after search input and before actually displaying it, however I would be curious to hear your thoughts on this approach.
(also on possible refactoring of the CSS code)
Moreover I couldn't find the matching RGB-code for the blue-style in the classic theme,
so this would still be needed to be set for the correct values.
Finally, there is still the default call of "m_searchingLabel->setStyleSheet(.." in
the constructor which begs the question of how to initialize the values here.
Set theme to the available, auto/dark/light/classic and type text into the search bar.
- ✅ My code follows the code …
> Fix "Search Results" banner improperly themed

- src/core/DatabaseIcons.cpp
- src/core/Metadata.cpp
- src/core/Resources.cpp
* Fixes #5240
* Limit size of icons being loaded to prevent excessive memory usage in some cases
* Fix loading database icons, previous method would just overwrite the same pixmap and not actually provide caching.
There is no difference in icon quality after these changes.
- ✅ Bug fix (non-breaking change that …
> Fix excessive memory usage by icons

- docs/topics/KeyboardShortcuts.adoc
- src/gui/DatabaseWidget.cpp
- src/gui/DatabaseWidget.h
- src/gui/MainWindow.cpp
- src/gui/MainWindow.h
- src/gui/SearchWidget.h
- tests/gui/TestGui.cpp
* Fixes #5037
* F1 focuses group view, if already focused it opens the focused group for editing
* F2 focuses entry view, if already focused it opens the focused entry for editing
* F3 focuses search
* Documentation updated for keyboard shortcuts
> Change actions for F1-F2-F3  keys

- src/autotype/AutoType.cpp
- src/core/Config.cpp
- src/core/Config.h
- src/gui/ApplicationSettingsWidget.cpp
- src/gui/ApplicationSettingsWidgetGeneral.ui
Fixes #1855
A new checkbox is introduced in the Settings -> General -> Auto-Type - section 
named 'Hide expired entries on selecting multiple for global Auto-Type'.
When checked, on hitting the autoType-hotkey and entering the selection screen of multiple entries for  the autoType feature, expired entries will not be shown to the user. 
If unchecked both expired and valid entries will be shown.
Considering unit-testing, would you like to have a test which ensures the removal of expired entries in the internal matchList ?
(match URL & Entry Title on global AutoType checkboxes were enabled)
Multiple entries with the same title were created and some were set to expired. 
The total count of the valid/expired entries was recorded and compared to the count
if valid/expired items in the …
> Add show/hide expired entries on global AutoType

- src/gui/entry/EditEntryWidget.cpp
There is no harm to deleting an empty URL from the browser integration
URL list when the user never set a value. It's a bit annoying, actually.
I kind of dislike inverting the control flow, but didn't see a better way.
There are no tests for deleting URLs yet. I would add it, but haven't yet spent the time to find out how to handle the `MessageBox`.
> Ergonomics: Don't ask when removing an empty URL

- src/gui/DatabaseOpenDialog.cpp
Currently the Open Dialog does not behave like a dialog. In Unix it
means that the EWHM hints are not set correctly therefore the window
manager doesn't properly set the floating window style.
It should also allow removing Mac/Windows/Unix custom conditional code.
> The Database Open Dialog should use the window flag QT::Dialog

- src/core/Entry.cpp
- src/core/Entry.h
- src/format/CsvExporter.cpp
- src/gui/csvImport/CsvImportWidget.cpp
- src/gui/csvImport/CsvImportWidget.ui
- tests/TestCli.cpp
- tests/TestCsvExporter.cpp
* Fixes #3541
* CSV export now includes TOTP settings, Entry Icon (database icon number only), Modified Time, and Created Time.
* CSV import properly understands time in ISO 8601 format and Unix Timestamp.
* CSV import will set the TOTP settings and entry icon based on the chosen column.
Tested importing an export and it worked great.
[NOTE]: # ( Please remove all …
> Improve CSV export and import capability

- src/gui/entry/EntryView.cpp
- src/gui/entry/EntryView.h
* Work around Qt bug that causes isSectionHidden to return false after restoring state due to the section actually only being set to 0 width.
* Fixes #5317
Tested multiple time when opening/closing the application and hiding showing the columns.
> Fix Paperclip and Totp columns not saving state

- src/browser/BrowserService.cpp
- src/browser/BrowserService.h
- tests/TestBrowser.cpp
- tests/TestBrowser.h
This is my second take on implementing https://github.com/keepassxreboot/keepassxc-browser/issues/533 .
The idea is to add custom handling for URLs that start with `keepassxc://`. If a search URL matches `keepassxc://by-uuid/<uuid>` and an entry with that UUID exists, it will be returned.
This concept could be extended to search for entries using other attributes or more complex search queries, but I don't plan on doing that.
Successful dogfooding for multiple months (:
> Browser service search for entries by UUID

- src/cli/keepassxc-cli.cpp
Proposed fix for #5367
After investigating with AddressSanitizer it seems that 
the ~Database destructor is called twice, since the QSharedPointer
variable cmd->currentDatabase & currentDatabase is initialized to
the the same address.
**also** fixed a issue with the cli unkown command output, since
in case of a wrong command only a "\n" character is appended to the
Utils::STDERR textstream but not flushed & printed. 
Upon exitting the shell the stream is flushed and if a bunch of unkown
commands are entered all of them are subsequently printed.
With endl the newline char is appended and the error-message is flushed,
printed and the shell continues.
1. Open a .kdbx database file with the keepassxc-cli open cmd
2. Enter any valid command as defined in the namespace commands
3. Exit the …
> Fix heap-use-after-free & error-msg output in keepassxc-cli

- src/gui/DatabaseWidget.cpp
* Fix case where only exclusions are entered (eg, !COMPUTER1, !COMPUTER2) which should allow opening the database on every other computer name.
> Fix AutoOpen IfDevice matching, again

- src/browser/BrowserAction.cpp
- src/browser/BrowserService.cpp
- src/browser/BrowserService.h
- tests/TestBrowser.cpp
- tests/TestBrowser.h
It was still broken. And actually the change for passing a full URL from the extension fixed the issue without any extra handling in the BrowserService.cpp.
Fixes #5299.
Added some more tests, and tested it also manually. Double verification will be needed. This should be the final fix for this. Really.
> Fix Best-Matching ..again

- src/gui/MainWindow.cpp
Change <kbd>Ctrl+Tab</kbd> (well, it was actually <kbd>Cmd+Tab</kbd>, but that is the macOS task switcher) shortcut to <kbd>Alt+Tab</kbd>. <kbd>Ctrl+Tab</kbd> does not work unfortunately, see https://bugreports.qt.io/browse/QTBUG-8596 and https://stackoverflow.com/questions/20694919/c-qt-osx-qtmetaqtkey-tab-shortcut-bind.
I also changed Ctrl+PageDown for consistency, but I can change that back. I can also change the variable name. I wanted to quickly create this PR with the gist of the proposed change in order to get feedback.
It appears that there is some kind of workaround that Chrome utilizes (https://bugreports.qt.io/browse/QTBUG-8596?focusedCommentId=321526&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-321526). But I have not idea if it is feasible …
> Use Alt+Tab on macOS to switch between databases

- src/gui/reports/ReportsWidgetHealthcheck.cpp
- src/gui/reports/ReportsWidgetHibp.cpp
Fixed columns sorting in HealthCheck and HIBP widgets in database report (#4976).
I'm not a Qt developer, but I wanted to try to contribute anyway; so if this PR does not reflect the programming patterns of this project, please feel free to reject it.
Since in both widgets the columns need to be sorted in a particular way (eg in HIBP widget the exposed password numbers are displayed as words but they must be sorted as digits), in this PR I suggest to apply Qt::UserRole as SortRole to the tables. In this way, each field has two values: a textual one which is displayed to the user and one set …
> Fix sorting of database report columns

- docs/man/keepassxc-cli.1.adoc
- src/cli/Add.cpp
- src/cli/Add.h
- src/cli/Edit.cpp
- tests/TestCli.cpp
Was working on exporting my data from Bitwarden where I use notes to KeePass and noticed the keepassxc-cli was missing notes as an option for adding and editing records. Looked easy enough to plug in so figured I would give it a go. Hopefully it is to taste!
Manual testing performed with existing and newly created databases through the develop branch version. Changes show to be reflected correctly in the databases.
> Add a -n (--notes) option to keepassxc-cli `add` and `edit` commands

- src/gui/PasswordGeneratorWidget.cpp
- src/gui/PasswordGeneratorWidget.h
- src/gui/PasswordGeneratorWidget.ui
Fixes #5396 
A new information field is added to the passphrase generator view
and depicts the number of characters in the generated passphrase. 
Considering the UI-Implementation I'd be happy to hear improvement suggestions
since I'm still a Qt novice.
In the current implementation a character is only counted if it is a number or letter.
So e.g. whitespace or special characters like '&' are not counted. (see attached screenshot)
If this is not the desired behaviour, I'll change it according to the discussion.
> Add display number of characters in passphrases

- src/gui/EditWidget.cpp
- src/gui/entry/EditEntryWidget.cpp
- src/gui/entry/EditEntryWidget.h
- src/gui/entry/EditEntryWidgetMain.ui
- src/gui/group/EditGroupWidget.cpp
- src/gui/group/EditGroupWidget.h
- src/gui/group/EditGroupWidgetMain.ui
- src/gui/styles/base/basestyle.qss
* Fixes #5321 - Text alignment in the general tab of the entry and group edit views is fixed
* Fixes #5300 - Errant scrollbar in the general tab is fixed
* Fixes #4852 - Tabbing into notes field works as expected. To tab out, currently only Shift+Tab works.
**BEFORE:**
**AFTER:**
Tested on Windows and Ubuntu 16.04
[NOTE]: # ( Please remove all lines which don't apply. …
> Fix layout and alignment of Entry and Group edit views

- docs/styles/dark.css
- docs/topics/DownloadInstall.adoc
- docs/topics/UserInterface.adoc
- src/core/Config.cpp
- src/core/Config.h
- src/gui/MainWindow.cpp
- src/main.cpp
* Fix #5313, allow specifying local config path using environment variable and command line flag
* Add command line flag `--localconfig <path>` to specify a file path to use for the local configuration settings.
* Add environment variable support to set config files paths: `KPXC_CONFIG` and `KPXC_CONFIG_LOCAL` to override default locations.
* Reorder startup sequence to load specified config files earlier to allow for theme settings and other early options to be picked up.
* Removed old command line option `--pw`, no longer used.
* Attempt a fix of application not closing when last window is gone. Only set `QApplication::setQuitOnLastWindowClosed(true)` when tray icon is enabled instead of always.
Replacement for #5325 
[NOTE]: # ( Describe your changes in detail, why is this change …
> Cleanup config initialization, add local config options

- src/cli/keepassxc-cli.cpp
Upon playing around with the `import` and `db-create` commands in the cli,
I stumbled over another heap-use-after-free crash after the database has been created.
The crash can be reproduced with compiling the project with the cmake flag `-DWITH_ASAN=ON`
and using the cli `db-create` command: e.g. `./keepassxc-cli db-create -k ~/exampleKeyFile ~/exampleDB`
The design problem is described in #5166 and the trouble starts right after the initialization of `currentDatabase`
in https://github.com/keepassxreboot/keepassxc/blob/develop/src/cli/Create.cpp#L164
I am aware of this PR #5212 which would address this issue already, however since I'm not sure
about the status, I wanted to **propose** a quick hotfix. 
If the other PR will get merged soon, feel free to close this PR.
cheers!
@phoerious …
> Hotfix heapUseAfterFree in db-create command

- src/browser/BrowserService.cpp
KeePassHTTP Settings moved to recycle bin still shows a warning dialog for KeePassHTTP migration on every database unlock.
Fixes #5297.
Manually.
> Ignore recycle bin on KeePassHTTP migration

- docs/man/keepassxc-cli.1.adoc
- src/cli/Analyze.cpp
- src/cli/Analyze.h
- src/core/HibpOffline.cpp
- src/core/HibpOffline.h
* Closes #5447
* Add option `--okon <okon-cli path>` to trigger the use of the okon cli tool to process a database's entries. When using this option the `-H, --hibp` option must point to a post-processed okon file instead of the standard HIBP text file.
* Updated documentation
- ✅ New feature (change that adds …
> CLI: Add support for okon in offline HIBP checks

- src/core/AsyncTask.h
- src/core/FileWatcher.cpp
- src/gui/FileDialog.cpp
* Fixes #5295
* Introduce a callback approach to AsyncTask instead of entering multiple QEventLoop in the stack. This has additional benefits including not returning to the original stack location and potentially operating on deleted objects (use after free).
* Revert FileDialog filter mods for macOS
Tested on Windows and macOS Catalina
- ✅ Bug fix (non-breaking change that …
> Fix FileDialog closing randomly on macOS

- src/gui/MainWindow.cpp
* Fixes #5378
* Add Key to SSH Agent is Ctrl + H on all platforms
* Remove Key from SSH Agent is Ctrl + Shift + H on all platforms
> Fix SSH Add/Remove Key Shortcut on macOS

- src/browser/BrowserService.cpp
- src/browser/BrowserService.h
- src/gui/entry/EditEntryWidget.cpp
- src/gui/entry/EditEntryWidgetBrowser.ui
I added this feature since there is a real use-case for me and therefore maybe others as well. 
I work in different environments - from some I need to supply basic-auth credentials when accessing certain websites in addition to the webpage credentials. I usually have two distinct entries for the site in question. However if one has to supply http basic-auth credentials one still has two entries and keepassxc-browser doesnt know which one to choose although only one of those entries is applicable for basic-auth which is slowing down my process.. The added feature enables the user - in addition to the already present option to mark entries as ONLY_HTTP_AUTH - to mark an entry with the opposite attribute - NO_HTTP_AUTH...
Tested on my actual setup.. Only the correct login for the use-case …
> Add feature to ignore entries for HTTP-Auth Logins

- src/gui/PasswordEdit.cpp
* Fix #5543 - Only check caps lock state when key is pressed/released or widget is focused.
The previous implementation called a repaint() during a QEvent which causes an infinite recursion in some cases. We also checked the state of caps lock on EVERY event, which is incredibly wasteful.
- ✅ Bug fix …
> Fix crash when toggling capslock rapidly

- src/core/Config.cpp
- src/core/Config.h
- src/gui/DatabaseWidget.cpp
- src/gui/DatabaseWidget.h
- src/gui/DatabaseWidgetStateSync.cpp
- src/gui/DatabaseWidgetStateSync.h
- src/gui/MainWindow.cpp
- src/gui/MainWindow.h
- src/gui/MainWindow.ui
- src/gui/entry/EditEntryWidget.cpp
- src/gui/entry/EntryModel.cpp
- src/gui/entry/EntryModel.h
- src/gui/entry/EntryView.cpp
- src/gui/entry/EntryView.h
- src/keeshare/ShareObserver.cpp
- utils/keepassxc-snap-helper.sh
* Closes #4151 - implement windows always on top in view menu
* Fixes #4982 - Move hide usernames/passwords into view menu (cleans up code a bunch!)
* Fixes #4463 - Mask password placeholder in command execution dialog
* Fix #4083 - move auto-type checks early in the commit process to prevent half-saving an entry if there is a bail-out.
* Fix #4182 - prevent setting modified by just viewing auto-type window associations
* Fix #4895 - when KeeShare imports a database it performs a merge operation. If that share was deleted from another identical database (ie, same base group UUID), then the …
> Final push for 2.6.2

- src/core/Entry.cpp
- src/core/Entry.h
- src/core/Group.cpp
- src/core/Group.h
- src/gui/group/GroupModel.cpp
* Fixes #5262
* Always reset the UUID on groups and entries moved or copied between databases. This prevents data loss when the group/entry is moved back to the original database.
> Prevent data loss when drag/drop between databases

- src/browser/BrowserService.cpp
- src/core/Entry.cpp
- src/core/Entry.h
- tests/TestBrowser.cpp
- tests/TestBrowser.h
This PR adds the option to use the URL scheme to search for an entry by path. Hence, tools implementing the keepassxc-browser API can use a credential's path to request a specific credential.
The code currently reuses the strategy implemented by @piegamesde in https://github.com/keepassxreboot/keepassxc/pull/4763.
- Unit tests.
> Add search 'by-path' url for browser

- src/gui/dbsettings/DatabaseSettingsDialog.cpp
- src/gui/dbsettings/DatabaseSettingsWidgetDatabaseKey.cpp
- src/gui/wizard/NewDatabaseWizardPage.cpp
- src/gui/wizard/NewDatabaseWizardPage.ui
- src/gui/wizard/NewDatabaseWizardPageDatabaseKey.cpp
- src/gui/wizard/NewDatabaseWizardPageDatabaseKey.h
* Fix #5440
This was unreasonably difficult to fix, mainly because of the way Qt styles and sizes scrollareas. I dialed everything in so that the new database wizard is consistent in size and doesn't cause scrunched display. I pulled the styling trick to remove the QScrollArea backgrounds (yes plural) from https://stackoverflow.com/a/16482646.
Tested on Linux and …
> Place database credentials widget in scroll area

- src/fdosecrets/FdoSecretsPlugin.cpp
- src/fdosecrets/FdoSecretsPlugin.h
- src/fdosecrets/objects/Collection.cpp
- src/fdosecrets/objects/Collection.h
- src/fdosecrets/objects/DBusObject.cpp
- src/fdosecrets/objects/DBusObject.h
- src/fdosecrets/objects/DBusTypes.h
- src/fdosecrets/objects/Item.cpp
- src/fdosecrets/objects/Item.h
- src/fdosecrets/objects/Prompt.cpp
- src/fdosecrets/objects/Prompt.h
- src/fdosecrets/objects/Service.cpp
- src/fdosecrets/objects/Service.h
- src/fdosecrets/objects/Session.cpp
- src/fdosecrets/objects/Session.h
- src/fdosecrets/objects/adaptors/CollectionAdaptor.cpp
- src/fdosecrets/objects/adaptors/DBusAdaptor.h
- src/fdosecrets/objects/adaptors/PromptAdaptor.cpp
- src/fdosecrets/objects/adaptors/ServiceAdaptor.cpp
- tests/gui/TestGuiFdoSecrets.cpp
- tests/gui/TestGuiFdoSecrets.h
Fixes #5279. Aside from typos and formatting fixing, this does the following
- Correctly propagate error message to the UI rather than ignoring them
- Simplify the internal states of `Collection`, so it's less likely to be left in an inconsistent state
- Handle corner cases when registering Collection on DBus
* Previously `QFileInfo::baseName` was used to derive the name, but this can be empty if there are leading dots in the filename, causing #5279. `QFileInfo::completeBaseName` is used instead.
* Although unlikely, if two open databases have the same filename (but on different paths), the …
> Secret Service: cleanup and fix crash

- src/gui/osutils/winutils/WinUtils.cpp
Attaches a console to enable printing debug output on Windows (e.g. with QDebug).
The console is attached the moment WinUtils is instantiated for the first time.
> Attach console in debug mode on Windows

- src/crypto/kdf/Argon2Kdf.cpp
- src/crypto/kdf/Argon2Kdf.h
- src/format/KeePass2.cpp
- src/format/KeePass2.h
- src/format/OpVaultReader.cpp
- src/gui/dbsettings/DatabaseSettingsWidgetEncryption.cpp
- tests/TestKdbx4.cpp
- tests/TestKeePass2Format.cpp
- tests/gui/TestGui.cpp
After some discussion in #4317 as to which KDF may become the future default or at least a new option and @DReichl's eagerness to implement Argon2id right away, I have now added it to our code base as a selectable KDF.
If Argon2id lands in KeePass2 rather soon, we can backport this to 2.6, since the surface for potential breakage is very small. I did not touch any of the KDBX4 defaults, so that remains Argon2d for now.
The implementation uses libargon2 for the time begin, since that requires the least amount of code changes. In the future, we may switch to libsodium if we decide we no longer need Argon2d (or if some other miracle happens).
The new KDF UUID is `9e298b19-56db-4773-b23d-fc3ec6f0a1e6`.
[TIP]:  # ( We expect …
> Add Argon2id KDF

- src/gui/PasswordGeneratorWidget.ui
A feature of keepassxc, that I used, was to generate long passwords e.g. of 255 characters.
This feature was broken lately.
Not completely sure if this fix will just work like that, but it seemed worth a shot to me.
> Fix regression: Remove length limit on password

- src/core/Database.cpp
- src/core/Database.h
`Database` may be accessed from a different thread in `Database::saveAs`, where the `m_modifiedTimer` is stopped during the saving. The solution is simply to post the timer stop call to the timer thread's event loop. Before this, the timer is not actually stopped, so I guess this has caused some unnecessary saves.
This was mentioned in #5370, but closed as a minor defect. Today the warning becomes annoying enough for me when working on the codebase and I happen to have a debug build of Qt to track this down. …
> Fix the warning about QTimer cannot be stopped from another thread

- src/cli/Import.cpp
- src/crypto/kdf/Argon2Kdf.cpp
- src/crypto/kdf/Argon2Kdf.h
- src/format/KeePass2.cpp
- src/format/KeePass2.h
- src/format/OpVaultReader.cpp
- src/gui/dbsettings/DatabaseSettingsWidgetEncryption.cpp
- tests/TestKdbx4.cpp
- tests/TestKeePass2Format.cpp
- tests/gui/TestGui.cpp
Backport of #5726 (Argon2id support).
> Add Argon2id KDF (backport)

- CODE-OF-CONDUCT.md
- README.md
KeePassXC is a growing project with an increasing number of contributors. Although, we haven't really needed it so far, in order to avoid potential future conflict and also considering eligibility for individual fund grants, I propose adding a code of conduct based on the template from https://www.contributor-covenant.org/.
Please discuss.
My take: The paragraph about sexualised language (not to be confused with sexist language, which is absolutely not okay) is perhaps a bit prude, and could be removed. But I have no major objections against leaving it in there. I can totally identify with the rest of the document.
> Add code of conduct

- docs/topics/BrowserPlugin.adoc
- src/browser/BrowserService.cpp
- src/core/Entry.cpp
- src/core/Entry.h
- src/format/CsvExporter.cpp
- src/gui/csvImport/CsvImportWidget.cpp
- src/gui/csvImport/CsvImportWidget.ui
- tests/TestCli.cpp
- tests/TestCsvExporter.cpp
* Backport #5346 - Improve CSV Import/Export
* Backport #5653 - Fix crash in browser integration with multiple similar entries
* Backport #5692 - Document how to use browser extension on Edge in managed mode
> Backport several PR's into 2.6.3

- src/gui/osutils/nixutils/NixUtils.cpp
* Fix #5691 - add a 2 second delay to startup on Linux to allow for tray initialization and Auto-Type shortcut registration
> Add delay to login startup on Linux

- src/gui/DatabaseOpenWidget.cpp
- src/gui/DatabaseOpenWidget.ui
> Hide keyfile path by default

- src/gui/DatabaseWidget.cpp
Fixes #5548
1.) Open up a .kdbx file with KeePassXC
2.) Select sub-group and subGroup-entry
3.) Lock the database
4.) Unlock it again and verify the selection.
> Fix re-select previously selected entry on database unlock

- src/core/Config.cpp
- src/core/Config.h
- src/gui/ApplicationSettingsWidget.cpp
- src/gui/ApplicationSettingsWidgetSecurity.ui
- src/gui/DatabaseWidget.cpp
Fixes #5232 
If this feature is considered, a new checkbox is introduced in the settings -> security -> convenience - section. 
When checked, the confirmation dialog before entries are moved/deleted will not appear and the entry/entries
will be moved to recycle bin or deleted.
Deleted entry / entries with & without checkbox checked.
> Add 'delete entry without confirm' functionality

- src/core/Config.cpp
- src/core/Config.h
- src/gui/ApplicationSettingsWidget.cpp
- src/gui/ApplicationSettingsWidgetSecurity.ui
- src/gui/DatabaseWidget.cpp
- tests/gui/TestGui.cpp
Fixes #5232 
and this time, testgui will be fixed too !
"If this feature is considered, a new checkbox is introduced in the settings -> security -> convenience - section.
When checked, the confirmation dialog before entries are moved/deleted will not appear and the entry/entries
will be directly moved to recycle bin without confirmation dialog".
Deleted entry / entries with & without checkbox checked.
> Redo 'delete entries no confirm' functionality & unit-tests

- src/browser/BrowserService.cpp
- src/gui/DatabaseWidget.cpp
- src/gui/MainWindow.cpp
- src/gui/TotpDialog.cpp
- src/gui/TotpExportSettingsDialog.cpp
* Fixes #5719, Fixes #5744
Moves detection of blocking modal dialog into Database Widget allowing other databases to lock. Only conditions that would cause a lock to block at this point are editing an entry/group with unsaved changes and unsaved database changes. These conditions will be addressed in 2.7.0 with a setting such as "Always save database on lock request".
Tested manually
[NOTE]: # ( Please remove all lines which don't …
> Fix closing modal dialogs on database lock

- src/gui/EntryPreviewWidget.cpp
- src/gui/EntryPreviewWidget.ui
- tests/gui/TestGui.cpp
- tests/gui/TestGui.h
This pull request attempts to fixes #5450. The point is to allow the user of the program to view an entry's autotype sequence in the preview pane instead of performing the whole "right click on entry -> edit entry -> select autotype tab on the side menu -> check autotype sequence"  to do the same.
Originally the Autotype tab in the preview pane is enabled only if there are actual window associations. Meaning, if a custom sequence is set, but not used for any window association, the tab would remain disabled. With the change in this PR, the tab would be disabled only if the entry has autotype …
> Display default autotype sequence on entry preview pane

- src/gui/entry/EditEntryWidget.cpp
- src/keeshare/ShareObserver.cpp
- src/keeshare/ShareObserver.h
* Hack for #5722 until a refactor of KeeShare, Merger, and EditEntryWidget can be performed. This hack should only ever be triggered on the rare occurrence of two people editing the same entry at the same time.  The end result is potential data loss, but the current result is a hard crash. Unfortunately the way everything is interfaced currently doesn't afford any solution without a major refactor.
* Additionally add a short delay before actually reloading a share to prevent read/write locks from preventing proper import. This delay also prevents conflicting saves between the main database and the KeeShare database. This should eventually be moved into the FileObserver itself to smooth out all merge operations once the above refactor occurs.
Side note: KeeShare operates independently of …
> Prevent crash when KeeShare merges an entry that is in edit mode

- src/gui/MainWindow.cpp
- src/gui/MainWindow.h
Uses Qt 5.15's new QWindow::startSystemMove() to implement empty-area drag, which allows the user to click and drag any empty area on the menubar, toolbar, or tabbar to move the window around.
This was part of another futile attempt at implementing properly style CSDs on Windows. This time, I tested this new Qt feature for it: https://www.qt.io/blog/custom-window-decorations
Turns out, the feature is pretty useless for the thing it was designed for (https://bugreports.qt.io/browse/QTBUG-84466), but we can use it to implement empty-area drag without any custom window moving logic.
> Implement empty-area drag.

- src/gui/reports/ReportsWidgetStatistics.cpp
The average password length shown in the Statistics report is now computed based on the total number of passwords. Previously, it was erroneously computed based on the number of unique passwords.
Also, round average password length to the nearest integer instead of truncating to the floor.
Fixes #5134.
n/a
Tested manually with the test database as described in #5134.
> Fix average password length in the Statistics report

- src/gui/DatabaseOpenDialog.cpp
Always activate DatabaseOpenDialog on Windows.
Fixes #5390
> Always activate DatabaseOpenDialog on Windows

- src/gui/osutils/nixutils/NixUtils.cpp
It had "Version=1.0true", which seems wrong
With patched KeePassXC, disabling and enabling "Automatically launch KeePassXC at system startup" brings the correct desktop file.
Before this patch:
```
[Desktop Entry]
Name=KeePassXC
GenericName=Password Manager
Exec=/usr/bin/keepassxc
TryExec=/usr/bin/keepassxc
Icon=keepassxc
StartupWMClass=keepassxc
StartupNotify=true
Terminal=false
Type=Application
Version=1.0true
Categories=Utility;Security;Qt;
MimeType=application/x-keepass2;
X-GNOME-Autostart-enabled=true
```
With this patch:
```
[Desktop Entry]
Name=KeePassXC
GenericName=Password Manager
Exec=/usr/bin/keepassxc
TryExec=/usr/bin/keepassxc
Icon=keepassxc
StartupWMClass=keepassxc
StartupNotify=true
Terminal=false
Type=Application
Version=1.0
Categories=Utility;Security;Qt; …
```
> Fix autostart .desktop file

- src/crypto/kdf/Argon2Kdf.cpp
- src/crypto/kdf/Argon2Kdf.h
Argon2Kdf was using a wrong UUID internally for the id variant, resulting in the incorrect dropdown entry being selected in the database encryption settings.
Reading and writing databases was not affected.
Fixes #5922
> Fix Argon2id UUID mixup

- release-tool
- src/core/PasswordHealth.cpp
- src/gui/styles/base/BaseStyle.cpp
Also add ability to set the timestamp server by command line switch.
Second commit: backport ignoring format changes when using newer versions of clang-format
> Update timestamp server for appsign

- src/gui/osutils/nixutils/NixUtils.cpp
This pull request fixes #5050.
The method QApplication::applicationFilePath returns a temporary executable path for AppImage, resulting in a non working autostart of KeePassXC with AppImage. The environment variable **APPIMAGE**, provided by the the AppImage returns the path to the AppImage file, which must be used to get autostart on startup of KeePassXC with AppImage working.
1. Remove autostart entry under ./config/autostart/
2. Start patched KeePassXC AppImage
3. Enable **automatically launch KeePassXC at system startup**
4. Check autostart entry under ./config/autostart/
5. Reboot system
6. Check if KeePassXC AppImage starts automatically
> Automatic launch at system startup for distribution AppImage

- docs/topics/DatabaseOperations.adoc
I've added a subsection to the _Database Operations_ section explaining how to generate the HMAC key and write it to a YubiKey so one has a) a backup and b) the option to have more than one YubiKey for using the optional Challenge-Response feature of KeePassXC.
PS: I just noticed that my editor removed spaces at the end of line. If this is an issue I'll take care of this in future.
[TIP]:  # ( We expect new code to be covered by unit tests and documented with …
> Add subsection for "backing up" YubiKey HMAC key. Concerns #465

- src/gui/PasswordGeneratorWidget.ui
Reverts changes from #5748 and increases the limit from 128 characters to 999 characters when setting the length using the spinbox text entry.
> Set maximum password length to 999 characters when using spinbox text entry

- src/gui/MainWindow.cpp
Change logic in click handler in eventFilter so that startSystemMove() is only called when there is no menubar action under the mouse cursor (i.e., when a blank area of the menubar is clicked).
Fixes #5925
Tested on Arch Linux with Qt 5.15.2
> Fix menubar click-to-move window with Qt 5.15

- src/gui/DatabaseWidget.cpp
- src/gui/MainWindow.cpp
- src/sshagent/SSHAgent.cpp
- src/sshagent/SSHAgent.h
* Fix #5928 - SSH Agent keys are properly removed on database lock. Also fixes crash when keys are still loaded on application close.
* Remove dependency on DatabaseWidget within SSH Agent.
Tested on Winodws with Pageant.
> Fix unloading ssh keys on database lock

- src/gui/MainWindow.cpp
* Close #5780 - Show window title as system tray icon tooltip
* Fix #5943 - Try to show system tray icon up to 5 times, waiting 5 seconds between attempts, if the system tray is not available. This works around observed startup issues on Linux.
* Change function of "isTrayIconEnabled()" to return true if the tray icon is created and visible. This may correct some long standing bugs with the window hiding forever unexpectedly.
[TIP]:  # ( We expect new code to …
> Correct issues with system tray icon

- src/gui/MainWindow.cpp
> Auto-close About Dialog before locking databases

- release-tool
Changes:
- Set correct target architecture when building on ARM64.
- Split signing and notarization into separate commands. This eases the  workflow when notarization fails because changes to Apple's ToS have  not yet been accepted on iTunes Connect.
- Sign all binaries and frameworks individually instead of using --deep. This is the correct way of signing apps and it avoids weird problems during signature verification.
- Fix signing of AppDirs, which was supposed to work, but never did.
The updated release-tool itself is targeted towards 2.7.0, but nothing stops us from using it to build 2.6.4 binaries for Apple Silicon with it already (resolves #4934).
- ✅ New feature (change …
> Prepare release-tool for Apple Silicon builds

- src/gui/Icons.cpp
This PR fixes adaptive icon being drawn incorrectly on Windows. The change was introduced in PR #5851.
See [5851](https://github.com/keepassxreboot/keepassxc/pull/5851#discussion_r562263044) for more info.
*Note: Fix was tested only on Windows, if it causes problems on other platform I'll scope it to Windows platform only.*
> Fix adaptive icon painting

- src/gui/EntryPreviewWidget.cpp
- src/gui/Icons.cpp
- src/gui/Icons.h
- src/gui/PasswordEdit.cpp
Some widgets such as QTableView do not call QIconEngine::pixmap(), but do
the drawing immediately through QIconEngine::paint(). This breaks alpha
blending for recolouring, since the underlying image canvas is not
necessarily transparent and also not anchored at (0, 0). This results in
a black box of the size of the icon bounding box.
Icon recolouring is now always done on a temporary QImage with
transparent background and only the finished end result is composed onto
the original canvas.
Fixes #6006
> Fix icon alpha blending in QTableView

- .gitattributes
- src/core/Resources.cpp
- src/core/Resources.h
- src/gui/Application.cpp
- src/gui/ApplicationSettingsWidget.cpp
- src/gui/EntryPreviewWidget.cpp
- src/gui/MainWindow.cpp
- src/gui/PasswordEdit.cpp
- src/gui/osutils/OSUtilsBase.h
- src/gui/osutils/macutils/AppKit.h
- src/gui/osutils/macutils/AppKitImpl.h
- src/gui/osutils/macutils/AppKitImpl.mm
- src/gui/osutils/macutils/MacUtils.cpp
- src/gui/osutils/macutils/MacUtils.h
- src/gui/osutils/nixutils/NixUtils.cpp
- src/gui/osutils/nixutils/NixUtils.h
- src/gui/osutils/winutils/WinUtils.cpp
- src/gui/osutils/winutils/WinUtils.h
- src/gui/styles/base/BaseStyle.cpp
- src/gui/styles/base/BaseStyle.h
- src/gui/styles/dark/DarkStyle.cpp
- src/gui/styles/light/LightStyle.cpp
The UX on macOS with a dynamic system theme is horrible without proper support for live theme switching in KeePassXC, so I decided to backport the following changes:
- Live theme switching on macOS and Windows (#5851)
- Adaptive icon painting resolution fix (#5989)
- Alpha blending fix for QTableView (#6033)
The last two are fixups for regressions introduced by the first patch.
I backported all the changes in Icon.cpp to Resources.cpp, since that incurs the least amount of changes overall. I did not want to backport the whole refactoring of moving icon handling out of Resources.cpp (this will create conflicts on merge back into develop, but they can easily be resolved by discarding everything from master).
- ✅ Bug fix (non-breaking …
> Backport live theme switching

- src/gui/osutils/OSUtilsBase.cpp
- src/gui/osutils/OSUtilsBase.h
- src/gui/osutils/macutils/AppKit.h
- src/gui/osutils/macutils/AppKitImpl.h
- src/gui/osutils/macutils/AppKitImpl.mm
- src/gui/osutils/macutils/MacUtils.cpp
- src/gui/osutils/macutils/MacUtils.h
- src/gui/osutils/nixutils/NixUtils.h
- src/gui/osutils/winutils/WinUtils.cpp
- src/gui/osutils/winutils/WinUtils.h
- src/main.cpp
On Windows this PR makes KeePassXC main window and all it's child windows invisible for screen recording and screen shooting.
This is done by capturing native events `WM_NCCREATE` & `WM_ENTERIDLE`, and set `WDA_EXCLUDEFROMCAPTURE` display affinity flag via [SetWindowDisplayAffinity](https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-setwindowdisplayaffinity) to the window in action or modal dialog. If for any reason the screen capturing of an app is desired i.e. demonstration, app should be run with `--allow-screencapture` argument. ~~When screen capturing for the app is enabled a persistent warning is displayed to the user, and title bar text of every displayed window is modified to contain text `[Screen Capture Allowed]`. The title bar text is also modified to contain …
> Prevent screen capture on Windows

- CMakeLists.txt
- src/CMakeLists.txt
- src/autotype/mac/CMakeLists.txt
- src/cli/CMakeLists.txt
- src/proxy/CMakeLists.txt
Since Homebrew moved all its stuff to /opt/homebrew, our hard-coded install_name_tool patch magic stopped working. This patch uses macdeployqt for all executables to prevent this kind of behaviour.
Fixes #6042
I still cannot get it to build properly with XCode's standard CMake (missing paths and such), but using Homebrew's own CMake, everything works fine and both keepassxc-cli and keepassxc-proxy have proper relocatable rpaths.
> Use macdeployqt for all executables

- src/gui/group/EditGroupWidget.cpp
Save method includes apply entry, clearing und emitting editing changes (true) like the normal way of saving entries.
This pull request fixes issue #6091.
See video expected behavior in issue #6091.
1. Groups / New Group...
2. Type Name XYZ
3. Press Cancel
4. Press Save
5. Look for newly created group on the left side
6. Doing (2-6) the same with a existing group entry
> use save method if new (and existing) created group entry has unsaved changes

- src/main.cpp
Fixes #6169. This seems safe.
Starting KeePassXC. Segfaults without this.
> Initialize Application before parser arguments

- src/core/PasswordGenerator.cpp
- tests/TestPasswordGenerator.cpp
* Fix #6075
This change add 6/G and 8/B as additional look-alike characters to be excluded upon user request. 
This feature was requested in issue #6075. 
The existing unit tests were updated to cover the additional look-alike characters.
> Exclude additional lookalike characters (6G8B)

- src/keeshare/ShareExport.cpp
- src/keeshare/ShareImport.cpp
Fixes #6081 
The crash arises if the specified exported file path is missing either one of the 
allowed file endings ".kdbx" or "kdbx.share".
In the KeeShare settings of the group the yellow warning ("your keepassXC version does not support sharing this container type. Supported extensions are: kdbx, kdbx.share") is correctly shown, however
the user is still able to progress the control flow via "ok" or "apply" button
and trigger the QASSERT in ShareExport.cpp which crashes the application.
The default file extension ".kdbx" is appended if the user omits it. Export then runs through.
> Add file extension if user omitted (Keeshare)

- src/gui/IconDownloader.cpp
- src/gui/IconDownloader.h
- tests/CMakeLists.txt
- tests/TestIconDownloader.cpp
- tests/TestIconDownloader.h
Fixes #5001 and #2843.
The favicon download URL was constructed from scheme and host only. This is fixed by simply replacing the path of the original URL with "/favicon.ico", thus keeping scheme, host, auth and port intact.
**Further modification**: URL's with a non-http schema are now rejected. (See #2843)
Tested URLs mentioned in #5001 and several well-known domains.
- ✅ Breaking change (causes existing functionality to change)
> Fix favicon download from URL with non-standard port.

- src/autotype/xcb/AutoTypeXCB.cpp
- src/autotype/xcb/AutoTypeXCB.h
* Fix #5958 - Modal dialogs do not have WM_STATE set even though they are a valid top-level window with a valid name. In this case, we need to poll for WM_TRANSIENT_FOR which returns the top level window the dialog is a child of.
Tested on XFCE
> Auto-Type: Allow selection of modal dialogs on X11

- src/core/Config.cpp
- src/core/Config.h
- src/gui/MainWindow.cpp
Regarding this issue #6231, I agree that the nature of the "Always on Top" option is to be persisted like in KeePass.
However, in order to keep the current functionality intact, and let the user decide how it will work, I made a pull request with an additional option in:
Settings -> General (Basic Settings) -> User Interface: "Force Always on Top to be persisted". Note that this option only allows persistance of the existing "Always on Top" in View submenu.
This gives the ability to the user to persist the "Always on Top" setting on "View" menu. 
Additional Settings in .ini
- "Always on Top" -> "GUI_AlwaysOnTop"
- "Force Always on Top to be persisted" -> "GUI_PersistAlwaysOnTop"
- Open the application with both settings false (default). Close the application. Re-open it. It works as in …
> Force Always on Top to be persisted

- src/gui/osutils/nixutils/NixUtils.cpp
This extends the feature for GNOME and KDE in https://github.com/keepassxreboot/keepassxc/pull/5724 to also include LXQt. The key `X-LXQt-Need-Tray` is not documented, though. It is seen in the source code https://github.com/lxqt/lxqt-session/blob/0.16.0/lxqt-session/src/lxqtmodman.cpp#L111.
This feature can also be added manually from the `lxqt-config-session` program, or by modifying the file `~/.config/autostart/org.keepassxc.KeePassXC.desktop` directly. However, changes are lost with Tools -> Settings -> OK.
---
N/A
Regenerate the autostart desktop file via settings, logout LXQt and login. The KeePassXC tray icon is always visible. Before this change, the tray icon may be lost if KeePassXC is run before the system tray plugin on the panel is available.
- ✅ New feature (change that …
> Make KeePassXC start after the system tray is available on LXQt

- src/gui/csvImport/CsvImportWidget.cpp
I had some extracted secrets from another TOTP app in CSV format and they didn't import.
That was because they were stored as bare TOTP secrets instead of otpauth url format.
This was an easy enough fix for me so I took the liberty to implement it.
Fixes #6167
So... Yeah...
I didn't find any test of the CSV importing wizard, so I don't know where to add a test if I really should.
However, the fix is trivial enough (and can't cause data loss) so it may be OK as it is. Just tell me.
I did test manually however and the TOTP seems to correctly generate
> Allow CSV import of bare TOTP secrets

- README.md
Adding badges for the 2 matrix channels, so that it's easier to find them.
> Add matrix channel badges

- src/autotype/AutoType.cpp
- src/autotype/AutoTypeAction.cpp
- src/autotype/AutoTypeAction.h
- src/autotype/mac/AutoTypeMac.cpp
- src/autotype/mac/AutoTypeMac.h
- src/autotype/test/AutoTypeTest.cpp
- src/autotype/test/AutoTypeTest.h
- src/autotype/windows/AutoTypeWindows.cpp
- src/autotype/windows/AutoTypeWindows.h
- src/autotype/xcb/AutoTypeXCB.cpp
- src/autotype/xcb/AutoTypeXCB.h
AutoTypeActions are required to return a result object with information if they can be retried or not. An error string is also provided to show a user friendly message why said action did not succeed if even after retries it keeps failing.
This is a prerequisite for waiting for modifier keys to be released on X11 and can be used to add friendly error messages to any executor.
We want to merge this before #6351 so it can be refactored to make use of the retry logic here.
Only X11 is actually implemented and others are just stubbed in.
Manually.
> Auto-Type: Allow actions to fail and be retried

- src/gui/Clipboard.cpp
- src/gui/Clipboard.h
- src/gui/MainWindow.cpp
- src/gui/MainWindow.h
- src/gui/styles/base/basestyle.qss
- src/gui/styles/dark/DarkStyle.cpp
- src/gui/styles/light/LightStyle.cpp
Double-clicking to copy a password in the list is my most-used interaction with the application. Recently, I found myself clicking 3-4 times "just to be sure" because there is no visual indication that the password was actually copied. This PR now adds a progress bar and timer message to the status bar.
Closes #1843
Manual - clicked the item and watched the progress …
> Show countdown for clipboard clearing

- src/browser/BrowserService.cpp
- src/browser/BrowserSettings.cpp
- src/browser/BrowserSettings.h
- src/browser/BrowserSettingsWidget.cpp
- src/browser/BrowserSettingsWidget.ui
- src/core/Config.cpp
- src/core/Config.h
- tests/TestBrowser.cpp
- tests/TestBrowser.h
Remove credential sorting from KeePassXC. There's no need to keep this logic inside the main application.
It is now done in the extension instead: https://github.com/keepassxreboot/keepassxc-browser/pull/1280.
Manually. Some tests had to be removed and altered because the only sorting is now based on the URL priority check.
- ✅ Breaking change (causes existing functionality to …
> Remove credential sorting from Browser Integration

- src/autotype/AutoType.cpp
- src/autotype/AutoTypeMatchView.cpp
- src/autotype/AutoTypeMatchView.h
- src/autotype/AutoTypeSelectDialog.cpp
- src/autotype/AutoTypeSelectDialog.ui
- Change Auto-Type dialog radios to a single checkbox, Ctrl-F shortcut to toggle on/off.
- Don't automatically select first item if we are doing global search and the query is empty
These improve UX.
`Filter or Search...` has been updated to plain `Search...`
Manually on linux. Focus works correctly.
- ✅ Breaking change (causes existing functionality to change)
> Auto-Type: Shortcut to search all entries, checkbox, default selection

- src/autotype/xcb/AutoTypeXCB.cpp
Releasing lock modifiers during Auto Type does not work reliably on X11 and can cause some modifiers to get stuck and more precisely layout switching can get stuck.
Instead of trying to find out what modifiers to release we can be dumb and just abort when the user is holding modifiers that may affect the typing sequence.
With #6357 merged we return a retry request if modifiers are held.
Fixes #6350 and #1915 after #6357 is merged and this is rebased on top of it.
See #6350 
> Auto-Type: Abort keystroke if modifiers held on X11

- src/format/OpVaultReader.h
- src/format/OpVaultReaderSections.cpp
- tests/TestOpVaultReader.cpp
* Fix #6303 - the text attribute in 1Password contains the actual text seen in 1Password whereas the name attribute may contain a ref pointer and not a name.
Tested using our test data.
> OPVault: Use Text instead of Name for attribute names

- src/gui/Font.cpp
* Fix #6286
**BEFORE:**
**AFTER:**
Tested on Windows 10 using system level font scaling of 150%
> Use application font size when setting default or monospace fonts

- src/gui/entry/EditEntryWidget.cpp
- src/sshagent/KeeAgentSettings.cpp
- src/sshagent/KeeAgentSettings.h
This slightly breaks the encapsulation of KeeAgentSettings now depending on SSHAgent for the global configuration option but it's not too bad.
This has a minor header include conflict with #6209 and can wait for it to be merged first.
I will do a class forwards declaration cleanup later for all SSH Agent stuff so this continues the tradition of including the classes for now.
Closes #5225
[TIP]:  # ( We expect new code to be covered by unit tests and documented …
> SSH Agent: Allow using database path to resolve keys

- src/autotype/AutoTypeMatchView.cpp
- src/autotype/AutoTypeMatchView.h
- src/autotype/AutoTypeSelectDialog.cpp
- src/autotype/AutoTypeSelectDialog.h
The original issue was likely related to subtle keyboard focus issues in the old dialog but since we explicitly focus in the new input field we can capture these keys in addition to arrows to emulate paging consistently on all platforms. We can't capture Home/End keys because it would conflict with line editing.
Number 5 was chosen by fair dice roll.
Fixes #4530
Manually on Linux.
> Auto-Type: PageUp/PageDown scrolling for entries

- src/gui/entry/EntryView.cpp
This allows to show/hide the group column both in normal and search
mode, finding a compromise for issue #6163
Search view:
Main view:
Should not affect current status of testing
> Allow the Group column to be toggled for entry view. Fixes #6163

- docs/topics/PasswordGenerator.adoc
- src/gui/PasswordGeneratorWidget.cpp
- src/gui/PasswordGeneratorWidget.ui
add the shortcut CTRL+Enter as an option (on top of the current CTRL+S)
to close the Password Generator widget and apply the changes.
Closes #6111 
Assuming desired backwards compatibility and keeping the CTRL+S shortcut
Checklist:
How can I test this? @droidmonkey @phoerious 
> Add CTRL+Enter to apply password generator changes

- src/gui/databasekey/KeyFileEditWidget.cpp
- src/gui/databasekey/KeyFileEditWidget.ui
- tests/gui/TestGui.cpp
The current text and the three buttons available are confusing.
It is unclear whether one should Browse current master key file
or type in a new-one and click Generate ... Make it clear what
happens.
Ideally, the "Key File" could be replaced with "Master Key File"
and the path on the "Browse" line should show in grey path to the
current keyfile. …
> Improve description text when changing Key File credential

- src/gui/EntryPreviewWidget.cpp
Fixes Issue #6461
Entries without notes were not clearing the notes field in the entry preview widget. I'm not clearing them either, but making the field invisible (it will get overwritten by next entry with notes).
(gif)
Manual testing
> fix showing any notes in an entry without notes (Fixes #6461)

- src/gui/entry/EntryAttachmentsWidget.cpp
I sometimes want to export an SSH key from a database and use it without having KeePassXC running (I mostly use the SSH agent integration, but in certain cases I want the key outside of the database).
But what happens in that case is that I get this warning:
```
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@         WARNING: UNPROTECTED PRIVATE KEY FILE!          @
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
```
So I run `chmod 600` on the file and then continue on with my day.
But I think it would be appropriate if KeePassXC did this for me. After all, you may have things more sensitive than an SSH key and it is best if KeePassXC does whatever it can to keep those things private.
I wanted `file.setPermissions` to be run before `file.write` so that the …
> Set permissions of saved attachments to be private to the current user

- src/CMakeLists.txt
- src/gui/DatabaseWidget.cpp
- src/gui/MainWindow.cpp
- src/gui/MainWindow.h
- src/gui/MainWindow.ui
- src/gui/SearchWidget.cpp
- src/gui/SearchWidget.h
- src/gui/widgets/KPToolBar.cpp
- src/gui/widgets/KPToolBar.h
Always show the search bar when the search keyboard shortcut is pressed. If the toolbar is in overflow, the toolbar will be expanded automatically and search focused. If the toolbar is hidden it will be shown and expanded if necessary. When searching is canceled or the down arrow is pressed (to select the first entry) the toolbar will be set back to it's previous configuration.
* Fix #505
> Show search bar when toolbar is hidden or overflow

- src/gui/DatabaseWidget.cpp
The MinimizeAfterUnlock setting added in #3439 closes the main window
after unlock. However, when the unlock is triggered through
KeePassXC-Browser, a password dialog is shown on top of the main window
and the main window remains open after the unlock. This is fixed
in this commit.
Tested only locally on macOS.
> MinimizeAfterUnlock also when unlocking through browser

- src/gui/Application.cpp
- src/gui/Application.h
- src/main.cpp
Closes/Fixes #6126
This adds a command line option `--lock` which locks all open databases in the running instance. This also makes some minor changes to the codebase ~~(e.g. changing `bool sendFileNamesToRunningInstance(const QStringList& fileNames)` to `bool sendToRunningInstance(quint32 id, const QStringList& fileNames)` for more flexibility in future)~~, as well as some comments to explain what appears to be going on in otherwise-confusing code. Some of these comments are TODOs, particularly one that urges the use of an enum going forward per droidmonkey's idea.
I loaded up one real database and one dummy database, then ran `keepassxc --lock`. As expected, both locked. I also made sure sending files to open works as usual.
- ✅ …
> Add command line option to lock open databases

- src/gui/EntryPreviewWidget.cpp
- src/gui/EntryPreviewWidget.ui
addresses Issue #1930
Working prototype. 
TODO:
Manual testing
> add a button to reveal protected attributes in entry view (addresses Issue #1930)

- src/CMakeLists.txt
- src/gui/DatabaseWidget.cpp
- src/gui/DatabaseWidget.h
- src/gui/GuiTools.cpp
- src/gui/GuiTools.h
- src/gui/reports/ReportsWidgetHealthcheck.cpp
- src/gui/reports/ReportsWidgetHealthcheck.h
- src/gui/reports/ReportsWidgetHealthcheck.ui
- src/gui/reports/ReportsWidgetHibp.cpp
- src/gui/reports/ReportsWidgetHibp.h
- src/gui/reports/ReportsWidgetHibp.ui
Addresses Issue #4986
Ideally we would be able to select multiple entries and delete them at once, but it would require deeper changes in the widget. This is a start.
> Add a context menu entry to delete entries from health check reports

- src/gui/osutils/macutils/AppKitImpl.mm
- src/gui/osutils/macutils/MacUtils.cpp
* Fix #6234 - properly set NSApplication activation policies when the window is hidden and shown
Tested on macOS
> Correct macOS window activation from hidden state

- src/gui/osutils/macutils/AppKitImpl.mm
Even though #6575 apparently passed the CI, it broke compilation on my Mac machines, because `NSApp` wasn't declared.
> Fix compilation on macOS

- src/gui/Application.cpp
- tests/TestKeys.cpp
- tests/gui/TestGui.cpp
- tests/gui/TestGui.h
* Fixes #1932 - See https://gcc.gnu.org/bugzilla/show_bug.cgi?id=66425#c29
Adding a negation before the function call allows the (void) syntax to work properly.
Tested on linux build
> Resolve compiler warnings for unused return values

- src/core/Config.cpp
- src/core/Config.h
- src/sshagent/AgentSettingsWidget.cpp
- src/sshagent/AgentSettingsWidget.ui
- src/sshagent/SSHAgent.cpp
- src/sshagent/SSHAgent.h
OpenSSH is already supported in Windows 10. In some situations, I really need to use both Pageant and OpenSSH agent at the same time. Therefore, I have modified the SSH Agent setting which is able to choice to use both agent simultaneously. As the result, the SSH key can be added/ removed from both agent by KeePassXC.
- Choose "use Pageant", lock and unlock database, …
> Add a SSH agent option to use both Pageant and OpenSSH agent simultaneously in Windows

- src/browser/BrowserService.cpp
- src/gui/DatabaseOpenDialog.cpp
- src/gui/DatabaseOpenDialog.h
- src/gui/DatabaseTabWidget.cpp
- src/gui/DatabaseTabWidget.h
- src/gui/DatabaseWidget.cpp
- src/gui/DatabaseWidget.h
When showing the database unlock dialog from browser or auto-type and
there's more than one open database, add tabs to the unlock dialog so
that the user can choose which database to unlock.
This implements part of #2322 and improves the UX when working with
multiple databases after version 2.6 switched to using the dialog for
browser unlock.
Make the DatabaseOpenDialog window Application-Modal so that it blocks
input to the main UI when the dialog is open. This reduces corner cases
by avoiding the possibility of databases getting closed or unlocked
behind the open dialog.
See https://github.com/keepassxreboot/keepassxc/pull/5427#issuecomment-692983371
All current tests pass; I'm not sure if or how to add a GUI test for this functionality. When building with asan, I can't find any new …
> Allow selecting any open database in unlock dialog

- src/gui/PasswordGeneratorWidget.cpp
The HEX button automatically unselects `selectBoxLower` therefore there is no need to also add `ghijklmnopqrstuvwxyz` in the excluded characters text field. This is not really a bug, just a small thing I noticed while exploring the generator options. 
I have not tested it yet. I tried running it in VSC and I couldn't figure out how to setup and build the project to …
> Removed unnecessary characters from HEX excluded chars

- src/main.cpp
This works:
```
$ keepassxc test1.kdbx test2.kdbx --pw-stdin
Database password: <manual input 1234>
Database password: <manual input 4321>
```
But this doesn't (only `test1.kdbx` is unlocked):
```
$ printf '%s\n' 1234 4321 | keepassxc test1.kdbx test2.kdbx --pw-stdin
Database password:
Database password:
```
The problem is that `Utils::setDefaultTextStreams()` is called multiple times when unlocking multiple databases with `--pw-stdin`, which appears to break the pipe. Simply call it once to avoid the problem.
Fixes: #5012 (as far as I can tell by simulating the script in Linux)
Before the fix:
After the fix:
Tested manually on Linux. The code change is trivial as well:
* In case only one database is unlocked, the same calls are done, just slightly reordered.
* In case multiple databases …
> Fix unlocking multiple databases with pw-stdin when input is a pipe

- share/translations/keepassxc_en.ts
- src/core/Config.cpp
- src/core/Config.h
- src/sshagent/ASN1Key.cpp
- src/sshagent/AgentSettingsWidget.cpp
- src/sshagent/AgentSettingsWidget.ui
- src/sshagent/OpenSSHKey.cpp
- src/sshagent/OpenSSHKey.h
- src/sshagent/SSHAgent.cpp
- src/sshagent/SSHAgent.h
- tests/TestOpenSSHKey.cpp
- tests/TestOpenSSHKey.h
Finally closes #4334 :sweat_smile: 
Shout-out to @yubico for sending me keys with up-to-date firmware to properly test this!
Manual tests with Yubikeys on Linux. Automated tests for the in-wire format.
This needs to be tested by people with Yubikeys other than me before merging.
> SSH Agent: Add support for OpenSSH 8.2 FIDO/U2F keys

- share/translations/keepassxc_en.ts
- src/gui/EditWidgetIcons.cpp
- src/gui/EditWidgetIcons.h
- src/gui/EditWidgetIcons.ui
Previously, it was a bit cumbersome to get a favicon from a URL that you did not already have from an entry. You would need to temporarily create an entry and download the favicon with the URL before discarding it. 
To make this easier, I took the "download favicon" button on the Icon selection page that previously would appear if the URL field was filled into the entry, and converted it so that it is always visible and provides a dialog popup that allows the user to download favicons. This also makes it so that you can download icons that may not already be in your icon list when editing a group.
Tested manually on Linux. I reused the existing favicon download implementation, so the code change just involved creating a new Dialog and altering some connection endpoints. I confirmed that …
> Add favicon url download dialog

- share/translations/keepassxc_en.ts
- src/core/Config.cpp
- src/core/Config.h
- src/gui/dbsettings/DatabaseSettingsDialog.cpp
- src/gui/dbsettings/DatabaseSettingsDialog.h
- src/gui/dbsettings/DatabaseSettingsDialog.ui
- src/gui/dbsettings/DatabaseSettingsWidgetBrowser.h
- src/gui/dbsettings/DatabaseSettingsWidgetDatabaseKey.h
- src/gui/dbsettings/DatabaseSettingsWidgetEncryption.cpp
- src/gui/dbsettings/DatabaseSettingsWidgetEncryption.h
- src/gui/dbsettings/DatabaseSettingsWidgetEncryption.ui
- src/gui/dbsettings/DatabaseSettingsWidgetGeneral.h
- src/gui/dbsettings/DatabaseSettingsWidgetMaintenance.h
- src/gui/dbsettings/DatabaseSettingsWidgetMetaDataSimple.h
- src/gui/settings/SettingsWidget.cpp
- src/gui/settings/SettingsWidget.h
- src/gui/wizard/NewDatabaseWizardPage.cpp
- src/gui/wizard/NewDatabaseWizardPage.h
- src/gui/wizard/NewDatabaseWizardPage.ui
- tests/gui/TestGui.cpp
- tests/gui/TestGuiBrowser.cpp
Current implementation has it disabled instead of hidden. Fixes #6190
In addition, it moves the checkbox into the only tab that has use for it, the Security->Encryption settings tab.
The scrolling bar is not working (yet)
Went to each tab and checked every configuration
> only display advanced settings checkbox on tabs that have them (partially fixes #6190)

- src/gui/entry/EditEntryWidget.cpp
- src/gui/entry/EntryHistoryModel.cpp
Fixes #9936
Current deleteIndex() will not remove correspond entry in `m_historyModifications`, then this issue appears.
And the current showing logic of history tab is curious. when we perform a modification to an entry and commit it(i.e. click `OK` or `Apply`). The History Tab will not be showed automatically. we need to reopen the EditEntryWidget. I'm not sure about whether it's a bug, but it's a very small code midification, I bundle it to the related bug fix. Discussions are welcomed.
[NOTE]: # ( Please describe in detail …
> Fix issue about removing entry from history and improve logic of history tab showing
