README.md
Just a small change to the README file to get started.
=> Update link to new upstream repository for pull requests

src/core/Config.cpp, src/core/Database.cpp, src/core/Database.h, src/gui/DatabaseOpenWidget.cpp, src/gui/DatabaseOpenWidget.h, src/gui/DatabaseTabWidget.cpp, src/gui/DatabaseTabWidget.h, src/gui/DatabaseWidget.cpp, src/gui/DatabaseWidget.h, src/gui/MainWindow.cpp, src/gui/SettingsWidget.cpp, src/gui/SettingsWidgetGeneral.ui
Merged from https://github.com/daniellandau/keepassx/commit/ce4abdc0ef92e3fa2c0054c5c181b7b0575bbcba
Issue #22
=> Detect background changes to database file.

.github/CONTRIBUTING.md, .github/ISSUE_TEMPLATE.md, .github/PULL_REQUEST_TEMPLATE.md, README.md
**This PR needs a Review from the Team for approving the Contributing Policy**
- Fix The first part of the README
- Add ISSUE_TEMPLATE and PULL_REQUEST_TEMPLATE
- Add CONTRIBUTING (**need to add C Styleguide**)
State in the README the new feature from KeePassX.
With Template is easier to write Issue and PR.
In the README we refer to a CONTRIBUTING file that is missing.
=> [RFC] DOC: fix README, add ISSUE and PR template, add CONTRIBUTING

README.md
For new GitHub users, it's not clear where the issues section is.
Added a link to issues in the README.
My friend is helping me create a pull request.  I did not know where issues were.
Renders good on GitHub.
N/A
=> Added issues link to issues

.github/CONTRIBUTING.md
Add to the CONTRIBUTING.md file the Branch Strategy as stated in #24 
- :white_check_mark: New feature (non-breaking change which adds functionality)
- :white_check_mark: I have updated the documentation accordingly.
- :negative_squared_cross_mark: I have added tests to cover my changes.
=> Update CONTRIBUTING.md with Branch Strategy

src/autotype/AutoType.cpp, src/autotype/AutoType.h
See #76 
See #76 
Manually
- :heavy_minus_sign: Bug fix (non-breaking change which fixes an issue)
- :white_check_mark: New feature (non-breaking change which adds functionality)
- :heavy_minus_sign: Breaking change (fix or feature that would cause existing functionality to change)
- :negative_squared_cross_mark: I have added tests to cover my changes.
=> Add delay feature to autotype

src/gui/DatabaseOpenWidget.cpp, src/gui/DatabaseOpenWidget.h, src/gui/MainWindow.cpp, src/gui/MainWindow.h, src/main.cpp
Force focus on password field, resolves #116 
Also remove redudant code for minimizing to tray
- :white_check_mark: Bug fix (non-breaking change which fixes an issue)
- :negative_squared_cross_mark: I have added …
=> Force focus on password field, resolves #116

src/gui/DatabaseWidget.cpp, src/gui/DatabaseWidget.h, src/gui/SearchWidget.cpp, src/gui/SearchWidget.h, tests/gui/TestGui.cpp
Enhances the search feature by scoping the current search by the selected group. Selecting another group changes the search focus instead of closing out the search.
Closes #16 
Implemented additional tests for group search and case sensitive search.
- :heavy_minus_sign: Bug fix (non-breaking change which fixes an issue)
- :white_check_mark: New feature (non-breaking change which adds functionality)
- :heavy_minus_sign: Breaking change (fix or feature that would cause existing functionality to change)
- :heavy_minus_sign: My change requires a change to the documentation. …
=> Search scopes to currently selected group

src/core/SignalMultiplexer.cpp, src/format/KeePass2Reader.cpp, src/format/KeePass2Reader.h, src/format/KeePass2XmlReader.cpp, src/gui/entry/EditEntryWidget.cpp, src/gui/entry/EditEntryWidgetMain.ui, tests/gui/TestGui.cpp
This is the continuation of pull request #158 which adds four missing commits.
Code still compiles and runs.
=> KeePassX PR Migration: #191 Spelling (missing commits)

.travis.yml
Changed Travis to build both Release and Debug configurations using clang and gcc.
=> Travis builds release and debug using clang and gcc

src/gui/EditWidgetIcons.cpp
Fixes #225
There was already verifications for the presence `m_database` in the other functions of this class, but this one was missing.
Unit tests + manual tests
@droidmonkey I know you don't like early returns, but I felt like this one was appropriate :)
=> Fixes #225 : downloading favicon crash

snapcraft.yaml
Fixed a typo in the `snapcraft.yaml` file
=> Typo is snap description.

release-tool
This PR puts the finishing touches to the release-tool for OS X.
Fixes any known remaining issues on OS X.
I also added a fix for all platforms to the changelog parsing. The changelog is now parsed before switching to the target branch (used to be the other way round and resulted in the current changelog not being added to the merge commit message).
The release-tool used to be incompatible with OS X. It can now be used for building the OS X release.
Terminal color codes have also been fixed, no more terminal ASCII gibberish.
I used it to build the 2.1.1 DMG on OS X 10.12 Sierra.
I didn't test merging and signing completely, but I assume those parts work properly too, since they don't contain any OS X-specific code. Also we don't have any dedicated Mac developers who would need that …
=> Fix release-tool for OS X

src/gui/WelcomeWidget.ui
recentListWidget in the welcome screen is too long 
=> Fix recentListWidget size

src/gui/MainWindow.cpp
Revert new entry shortcut to `CTRL+N` and new database shortcut to `CTRL+SHIFT+N`
=> Revert new entry shortcut

src/gui/DatabaseTabWidget.cpp
Resolves #202
This PR fixes the utterly confusing dialog that comes up when opening a database which is already locked by another instance.
Not only made the previous phrasing of the question no sense at all, it also couldn't be answered by Yes or No which were the only possible answers.
This is what is looks like now:
=> Fix impossible dialog by providing a proper question with approriate answers

src/http/Protocol.cpp, src/http/qhttp/http-parser/http_parser.h, src/http/qhttp/private/httpreader.hxx, src/http/qhttp/private/qhttpclient_private.hpp, src/http/qhttp/private/qhttpserver_private.hpp, src/http/qhttp/private/qhttpserverconnection_private.hpp, src/http/qhttp/qhttpabstracts.cpp
This PR only fixes compiler warnings generated by the new QHttp library code. No functionality has been changed.
=> Fix compiler warnings in QHttp library

README.md
Minor update of the README file.
=> Update README to reflect current text from our website

src/zxcvbn/zxcvbn.cpp
pull request for stack buffer overflow fix for release branch, related to:
https://github.com/keepassxreboot/keepassxc/pull/363
=> Fix stack buffer overflow in zxcvbn / release branch

CMakeLists.txt
Enable Data Execution Prevention (DEP) and Address Layout Randomization (ASLR) on windows.
DEP and ASLR are simple exploit mitigation technologies. DEP is currently not enforced and ASLR is not enabled at all.
https://www.microsoft.com/security/sir/strategy/default.aspx#!section_3_3
https://blogs.technet.microsoft.com/srd/2010/12/08/on-the-effectiveness-of-dep-and-aslr/
Windows 7 + ProcessExplorer
=> Enable DEP and ASLR.

CMakeLists.txt
=> Enable -fstack-protector-strong flag only for GCC >= 4.9 and Clang

README.md
* Update feature description of Yubikey according to https://github.com/keepassxreboot/keepassxreboot.github.io/pull/8#issuecomment-286398903
* Add build instructions for Yubikey
Precise and thorough documentation 
Update Documentation
=> Update feature description and build instructions for Yubikey

src/core/Entry.cpp, src/gui/DatabaseWidget.cpp, src/gui/entry/EntryModel.cpp, tests/gui/TestGui.cpp, tests/gui/TestGui.h
The multiple placeholder regex was incorrect. 
Every time multiple placeholder was called no placeholder was resolved.
Fixed #402 to resolve multiple placeholder instead of single when copying entry attributes (and custom attributes as well)
Fixed also the EntryModel that was resolving only single placeholders
Manually and with `make test`
=> Fix regex for placeholders and add regression test

src/gui/MainWindow.cpp, src/gui/MainWindow.h, src/gui/WelcomeWidget.cpp, src/gui/WelcomeWidget.h, src/gui/WelcomeWidget.ui
In welcome window there is no button for the CSV import feature so I added it at the bottom of the pile.
It seems also that this feature has been missing from #292 last commit so I started from clear.
Manual tests ( with ASAN of course :smiley: )
=> Adds a button for CSV import option

Dockerfile
Simple update to the Dockerfile to support yubikey builds and remove libmicrohttpd
Enable use for new container based CI services
=> Updated Dockerfile to meet new library requirements

src/gui/MainWindow.cpp, src/gui/WelcomeWidget.cpp, src/gui/WelcomeWidget.h
Small fixes in the Welcome Screen.
When in Welcome screen and Recent Databases is cleared from the menu refresh the list.
Use the ItemActivated event to catch both double clicks and Enter keypress
Manually
=> Fix RecentDatabases

README.md
- ✅ I have read the **CONTRIBUTING** document. 
@droidmonkey this time the logo is not too big
=> Updating readme with logo

CMakeLists.txt
Allows proper debugging using GDB on Windows.
Manually with both Debug and RelWithDebInfo builds
=> Disable DEP and ASLR for Debug builds

snapcraft.yaml
Simple fix to add autotype to snapcraft. 
Manually on ubuntu 16.10
=> Add autotype plugin to snapcraft build

src/gui/CloneDialog.ui
closes #493 
Fix clone dialog layout.
=> Fix clone dialog layout

src/gui/CloneDialog.ui
=> Remove maximum size from label in clone dialog

src/gui/CloneDialog.cpp
Set fixed size for entry clone dialog while also adapting for different font DPI and translations with bigger texts.
=> Set fixed size for entry clone dialog

src/gui/MainWindow.ui
Add menu accelerators for the "Database" and "Tools" Menus.
Fixes #447.
Built & ran the app. Used the new accelerators with Alt-D and Alt-T.
=> Fix #447 - Menu Accelerators for Database & Tools

src/autotype/mac/AutoTypeMac.cpp
=> Fix OSX El Capitan compilation issue

.gitignore, CMakeLists.txt, cmake/FindLibMicroHTTPD.cmake, src/CMakeLists.txt, src/http/CMakeLists.txt
Cleanup of CMake files in preparation for v2.2.0. This PR closes #331 with exception to "moving files to correct locations". I am deferring that part to v2.3.0 and will open a new issue for it. This also adds minimal support for using visual studio code.
=> Cleanup CMake files

utils/fix_mac.sh
fix #567 
Signed-off-by: Robert van Bregt <robert@robertvanbregt.nl>
Fix #567 
#567
=> add fix for mac qt build environment

src/cli/CMakeLists.txt, src/cli/Clip.cpp, src/cli/Clip.h, src/cli/Extract.cpp, src/cli/List.cpp, src/cli/Merge.cpp, src/cli/Show.cpp, src/cli/keepassxc-cli.cpp, src/core/Database.cpp, src/core/Group.cpp, src/core/Group.h, src/core/Uuid.cpp, src/core/Uuid.h, tests/TestGroup.cpp, tests/TestGroup.h
Adding a command to the CLI interface to copy a password to the clipboard.
Unit tests + local testing.
=> Feature : clip command

src/core/Group.cpp, tests/TestGroup.cpp
Allow finding an entry only by title.
unit tests + show command.
=> Find entry by title.

src/cli/Merge.cpp, src/core/Database.cpp
Now that it's available, I'd rather enter my password in this prompt than on stdin.
unit tests + all 4 combinations of the `-g` and `-s` options.
=> Add the GUI prompt option to the merge command.

src/core/ScreenLockListenerWin.cpp
Self documenting. This error was introduced in 533136fb.
=> Fixed variable naming error that prevented compiling on Windows

release-tool, snapcraft.yaml
This PR updates the release tool and snapcraft.yaml file in preparation for the v2.2.0 release. The release tool has gained the following skills:
- Check for lupdate-qt5
- Check snapcraft.yaml for the release version number
- Check CMakeLists.txt for the new way release numbers are stored
- Added a command ```check``` that does a dry-run to make sure everything is good before you actually commit to changing anything. Refactored code to make this simple.
Manually. Recommend further testing other commands to ensure no regressions (merge, build, sign).
- ✅ I …
=> Update release tool and snapcraft.yaml

src/cli/List.cpp
It's already possible to use the GUI prompt for other CLI commands, adding it for this one as well.
Unit tests + manual tests
=> Adding gui prompt to List command.

src/main.cpp
Simple fix to disable Single Instance when debugging.
=> Allow multiple instances when debugging

src/gui/DatabaseWidget.cpp
=> Change text color of search label

src/gui/AboutDialog.cpp, src/gui/AboutDialog.ui
Adds a contributors tab to the about dialog that is populated with the top code contributors and translators. Also did some cleanup of the about dialog itself. Implements #376. 
Manually
=> Added contributors to about dialog

src/cli/Clip.cpp, src/cli/Extract.cpp, src/cli/List.cpp, src/cli/Merge.cpp, src/cli/Show.cpp
Forgot these in the last PR (https://github.com/keepassxreboot/keepassxc/pull/650)
Manually
- ✅ Bug fix 
=> Failure exit code when showing help

CMakeLists.txt, Dockerfile, release-tool
This PR
* removes any checks from the build command of the release tool except the check for a clean working tree
* makes CMake 3.1 the minimum required version
* updates the Docker file to use a not-so-ancient CMake version and Qt 5.9
=> Fix release building and require CMake 3.1+

src/gui/MainWindow.cpp, src/gui/SettingsWidget.cpp, src/gui/SettingsWidget.h
=> Fix apply button on settings window

src/gui/MainWindow.cpp, src/gui/SettingsWidget.cpp, src/gui/SettingsWidget.h
=> Fix apply button on settings window (repost)

src/gui/EditWidget.cpp, src/gui/entry/EditEntryWidget.cpp
=> Fix edit entry header entity encoding

.github/ISSUE_TEMPLATE.md
With the 2.2.0 release, we have a new "About" dialog with a copy&paste template of debug info. This patch updates the issue template to ask for that debug info.
=> Update issue template to ask for debug info from new About dialog

.github/CONTRIBUTING.md
Removed outdated information from CONTRIBUTING.md
Removed references to Google Groups in CONTRIBUTING.md, as Google Groups is no longer used for discussions.
No sense having outdated information posted publicly.
I ran it through spell check twice
=> :memo: Remove reference to Google Groups from CONTRIBUTING.md

src/gui/AboutDialog.ui
Fixes various aspects of the About dialog:
- Fix minimum (and default) dialog size to always fit content, so maintainer names are completely visible
- Split "Project Maintainers: &lt;list of maintainers&gt;" into two labels, one translatable, one untranslatable
- Strip unnecessary HTML from other labels
- Remove explicit coloring from links
- Make contributors untranslatable *
- Replace contributor's QTextEdit with QLabel inside a QScrollView to avoid automatic HTML expansion by the Qt designer **
- Make dialog heading a little smaller and remove "v" in front of the version name
Dialog minimum size was a fixed value and not determined based on its contents, causing parts not being visible on KDE.
\* The contributors list contains English strings which might be worth translating, but that …
=> Fix minimum About dialog size and clean up HTML tag soup

INSTALL.md
Fix url to build environment instructions and format better.
The urls to the "Build Environment" instructions were incorrect. 
Manually verified the urls by copying them, and clicking on them. Verified formatting by using the github preview pane. 
- Documentation
=> Fix url to build environment instructions

src/gui/AboutDialog.ui
Cherry-pick of https://github.com/keepassxreboot/keepassxc/pull/810 to release/2.2.1 branch.
=> Let Qt figure out geometry of the about window.  Closes: #780.

src/cli/Extract.cpp
Continuation of #816, support --key-file in `keepassxc-cli extract`
All other database manipulation sub-commands in CLI supports ```--key-file```. I want extract to be among them.
I use extract from time to time. This may help #544, too.
Only manually tested. I need to run tests on different platforms later.
```
$ ./src/cli/keepassxc-cli extract -k ~/does_not_exist ~/foo.kdbx             
Failed to load file key /home/yen/does_not_exist: No such file or directory
$ ./src/cli/keepassxc-cli extract -k ~/var/cdic2 ~/Dropbox/document/keepass/main2.kdbx
Insert the database password
> 
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<KeePassFile>
</KeePassFile>
``` …
=> Support --key-file in `keepassxc-cli extract`

src/cli/Extract.cpp
- Unit tests
- Locally
@yan12125 FYI
=> Normalizing translated messages in Extract.

src/cli/CMakeLists.txt, src/cli/Command.cpp, src/cli/Locate.cpp, src/cli/Locate.h, src/core/Group.cpp, src/core/Group.h, tests/TestGroup.cpp, tests/TestGroup.h
This PR adds a locate command to the CLI
- Added unit tests for the new `core` function.
- Manually by using `keepassxc-cli` 
```
$ ./src/cli/keepassxc-cli
Usage: ./src/cli/keepassxc-cli [options] command
KeePassXC command line interface.
Available commands:
clip           Copy an entry's password to the clipboard.
entropy-meter  Calculate password entropy.
extract        Extract and print the content of a database.
locate         Find entries quickly.
ls             List database entries.
merge          Merge two databases.
show           Show an entry's information.
Options:
-h, --help     Displays this help.
-v, --version  Displays version information.
Arguments:
command        Name of the command to execute.
$ ./src/cli/keepassxc-cli locate
Usage: ./src/cli/keepassxc-cli locate …
```
=> Adding Locate command.

src/core/Entry.cpp, src/core/Entry.h, src/http/Server.cpp
non-user-facing trivial source comment fixes
=> misc. typo fixes

src/cli/CMakeLists.txt, src/cli/keepassxc-cli.1
#681
- installed the cli on mac and linux, verified that the manpage was accessible.
@magkopian FYI
=> Adding manpage for keepassxc-cli

src/crypto/SymmetricCipher.h, src/crypto/SymmetricCipherBackend.h, src/crypto/SymmetricCipherGcrypt.h, src/format/KeePass2RandomStream.h
Fix: https://github.com/keepassxreboot/keepassxc/issues/908
=> Fix build on mac os with qt 5.9.1

.clang-format
Updating `.clang-format` according to the style of the project.
Even though it's not performed automatically during CI, I use it locally before submitting a PR.
Would be nice to add it to the checks performed during CI, but that would require reformatting the whole codebase, which I'm not sure is a good idea.
- ✅ maintenance.
=> Updating .clang-format

INSTALL.md
Fix a small typo in Install.md
"document a the following link" -> "document at the following link"
Documentation should as much as possible free of errors.
The markdown syntax is still correct.
I'm not sure it can be considered a bug
[ci skip]
=> Typo fix in Install.md

.travis.yml
upporting the Travis Fix from `release/2.2.1` branch. 
Cherry-picking shouldn't have any conflict later
=> Fixing travis build

src/core/Config.cpp, src/gui/SettingsWidget.cpp
* Fixes #916.
* Clear LastDatabases and LastKeyFiles settings variables if disabled in the settings widget.
Manually and unit tests.
=> Set "Don't modify on non-data changes" to true by default

src/gui/SettingsWidget.cpp
The google fallback option was loaded in the wrong checkbox
Fixes #1028 
Manually
=> Fix GoogleFallback/Screnlock settings

.github/CONTRIBUTING.md
Remove the section about emoji in commit messages from the style guide.
It's unnecessary, rather confusing and we don't even do it ourselves.
- ✅ Documentation change
=> Remove emoji in commit messages from style guide

tests/TestMerge.cpp
Hold over from 2.2.1 feature. Add's tests for the transfer of entry history after a merge.
=> Added tests for retention of entry history after merge

src/gui/DetailsWidget.cpp
Fix #1143 
Regression in commit eb6582266533a979a753327b7f222867b7d146c3
Hide the DetailsView if there are no entry instead of crashing
Manually
=> Prevent crash with empty database

COPYING
Already in line 46~48 :)
I find this by an accident 😆 
N/A
N/A
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to change)
=> COPYING: remove a duplicated entry

src/gui/DetailsWidget.cpp, src/gui/DetailsWidget.h, src/gui/DetailsWidget.ui
This is a hot fix for #1156.
Please see #1156 for specifics of the bug here fixed.
Manually on macOS.
N/A.
=> Fix TOTP Segfault in DetailsWidget #1156

src/autotype/AutoType.cpp, src/autotype/AutoType.h, src/gui/DatabaseWidget.cpp
=> Focus database unlock dialog on macOS

src/http/Service.cpp
i18n fixes in Service.cpp, solving #874
=> I18n fixes in Service.cpp

src/core/Database.cpp, src/core/Database.h, src/core/Entry.cpp, src/core/Entry.h, src/core/EntryAttachments.cpp, src/core/EntryAttributes.cpp, src/core/EntryAttributes.h, tests/TestEntry.cpp, tests/TestEntry.h
Implement search for reference placeholder based on fields other than ID
fix #1040 
fix #1137 - turned off the warnings in the release mode
with unit tests
- My change requires a change to the documentation and I have updated it accordingly.
=> Implement search for reference placeholder based on fields other than ID

share/linux/org.keepassxc.KeePassXC.appdata.xml
Signed-off-by: Germano Massullo <germano.massullo@gmail.com>
=> Fixed typo in XML tag

src/CMakeLists.txt, src/gui/Font.cpp, src/gui/Font.h, src/gui/PasswordEdit.cpp, src/gui/entry/EditEntryWidget.cpp, src/gui/entry/EditEntryWidgetSSHAgent.ui
Fixes #1200. Includes only UI changes.
- ✅ Bug fix (non-breaking change which fixes an issue))
=> SSH Agent: Split private key selection

snapcraft.yaml
* Removed snapd-xdg-open support; built into snapd
* Updated desktop-qt5 stage packages
The website FAQ has already been updated to remove the snapd-xdg-open workaround.
Fixes #1011 and fixes #1292 
Manually
=> Updated snapcraft build file

CMakeLists.txt
cmake_minimum_required() must be used before project(), otherwise it has no effect on internal cmake code that runs when project() is invoked. In particular CMP0025 does not default to NEW and CMake does not detect Clang features on macOS, which is necessary to compile the project with the upstream (non Apple) compiler.
The requirement that cmake_minimum_required() should precede project() is documented here: https://cmake.org/cmake/help/v3.10/command/cmake_minimum_required.html
@ariutta attempted to work around it at https://github.com/ariutta/nixpkgs/blob/6113b56902a09aa88312752b6276bd046777829e/pkgs/applications/misc/keepassx/community.nix#L44
The proposed patch was applied at https://github.com/NixOS/nixpkgs/blob/b693f989f65d55d2213c52b716cf26fe60e40ad0/pkgs/applications/misc/keepassx/ …
=> Fix use of cmake_minimum_required

ci/trusty/Dockerfile, src/gui/entry/EditEntryWidget.cpp, src/gui/entry/EntryAttachmentsWidget.cpp, src/gui/entry/EntryAttachmentsWidget.h
This PR adds a Dockerfile (based on #1209) for running CI on TeamCity.
This branch is mostly a preflight check, please do not merge yet. I tested TeamCity with my personal KeePassXC fork, now lets see how it performs with the real repository.
=> Add TeamCity integration

.travis.yml, src/gui/entry/EntryAttachmentsWidget.cpp
Last merge causes build failures.
Unit and manual.
=> Correct regression to ssh-agent from entry attachment refactor

src/CMakeLists.txt, src/core/ScreenLockListenerPrivate.cpp, src/gui/MainWindow.cpp, src/main.cpp
Replacement for #1025
Since GitHub closed the original PR while force-pushing the rebased and updated branch and doesn't let me reopen, this PR replaces #1025.
The original PR was already reviewed, I added a new commit to address my own change requests.
- ✅ New feature (non-breaking change which adds functionality)\
=> Enable OpenBSD support

README.md
Fixes internal link to "Note about KeePassHTTP" section in the README.
Good to have working links in documentation, even if it only takes users down a few paragraphs.
I actually wasn't able to test this but I think I got the syntax right!
=> Fixes internal link in README

src/sshagent/AgentSettingsWidget.cpp, src/sshagent/AgentSettingsWidget.h, src/sshagent/CMakeLists.txt
This PR fixes #1238 and TeamCity builds
Manually + TeamCity
=> Fix sshagent autouic

src/gui/DatabaseWidget.cpp
This PR adds some small changes, based on input from PR #1167's code review.
Address a minor issue with the use of Q_ASSERT in some guard conditions.
Locally on macOS and by running unit tests.
- ❌  My change requires a change to the documentation and I have updated it accordingly.
- ❌  I have added tests to cover my changes.
=> Refactor src/DatabaseWidget.cpp

src/format/Kdbx4Writer.cpp, src/format/Kdbx4Writer.h
Corrects attachments not being saved when KDBX 4 format is used.
MAJOR BUG!
Manually and with KeePass 2
=> Correct missing attachments in KDBX 4 write

src/gui/DatabaseWidget.cpp, src/gui/MainWindow.cpp
On searching mode, New Entry icon is always enabled, when clicked it will create a new entry using the search text as Title
Fixes #895 
Manually and guitests
=> Create new entry while searching

src/sshagent/SSHAgent.cpp
Fixes #1396.
Ignore Recycle Bin when searching for SSH keys.
=> Ignore SSH keys in Recycle Bin, fixes #1396

COPYING, src/gui/AboutDialog.ui
Updates the list of contributors on the About dialog.
Many new code contributions and translations require many new names on the About dialog.
I added all translators for all languages which are complete to at least 40% and are therefore shipped in KeePassXC.
I removed debfx from the maintainers list and added a special thanks note instead.
=> Update list of contributors

release-tool
Fixes the release-tool's build steps on macOS.
With updated Xcode, the release tool wasn't able to compile without errors anymore. Also some of the CMake flags didn't make sense anymore.
Successfully build 2.3.0-beta1 DMG.
=> Fix macOS build

Dockerfile
Update Qt PPA version in deployment Dockerfile.
=> Update PPA Qt version

cmake/FindArgon2.cmake, snapcraft.yaml
* Properly rename argon2 symbols on Win32 builds
* Force snapcraft builds to be release builds
Manually
=> Correct compile time issues with 2.3.0

src/core/Entry.cpp, tests/TestEntry.cpp
Added test to #1649 
Also I've added a fallback in `resolvePlaceholderRecursive` for finalizing the fix for the above PR.
`resolvePlaceholderRecursive` is the function we use almost everywhere in the code assuming only 1 placeholder can be in a field. 
Turns out this is not the case so in this PR I kept the `placeholderType` as function defined over single placeholders strings and I've added a fallback in the case the placeholder is multiple(single+extra text) or not present at all. 
Then `resolveMultiplePlaceholderRecursive` will take care to check if there are multiple placeholders or if it's just a text string.
Reference and Placeholders support was added without proper tests cases and as we developed it we found new type of references, new usage and new constrain for them.
The result …
=> Add test case for recursive placeholders

CMakeLists.txt
Inspired by #1739 
Increase security on Windows
Built and used ProcessHacker to verify
=> Enable high entropy ASLR for Windows builds

snapcraft.yaml
Snaps have to be build on Trusty (still!) and there are packages that do not exist in the Trusty package manager. Using the PPA in a Docker container solves this problem.
=> Update snapcraft to use ppa packages

ci/snapcraft/Dockerfile, release-tool, snapcraft.yaml
Use a custom Docker image (ci/snapcraft/DockerImage) to build snaps. Added a --snapcraft flag to the release-tool build command.
=> Build snaps using custom Docker image

src/core/Tools.cpp, src/core/Tools.h, tests/CMakeLists.txt, tests/TestKeys.cpp, tests/TestModified.cpp, tests/TestTools.cpp, tests/TestTools.h
Clean up and test 3 methods from Tools
Tools::humanReadableFileSize
Tools::isHex
Tools::isBase64
- ✅ improved UT coverage
=> improved unit test coverage in Tools

.gitignore, cmake/CodeCoverage.cmake, sonar-project.properties
Adds support for SonarCloud. Currently pushing analysis results to https://sonarcloud.io/dashboard?id=keepassxc
=> Add support for SonarCloud analysis

src/gui/csvImport/CsvImportWidget.cpp, src/gui/csvImport/CsvImportWidget.h
Add tab delimiter in CSV import.
Closes #1798
Manually created a tab delimited CSV file, imported successfully.
=> Add tab delimiter in CSV import.

src/gui/entry/EditEntryWidget.cpp, src/sshagent/OpenSSHKey.cpp, src/sshagent/OpenSSHKey.h, tests/TestOpenSSHKey.cpp
Fixes #2050 
Existing tests pass and visual test.
=> SSH Agent: Show MD5 fingerprint of keys

src/cli/keepassxc-cli.1
=> Corrects ordering of command/opts in cli manpage

src/autotype/xcb/keysymmap.py
Some Python code improvements - each commit contains the necessary description
Just wanted to contribute to achive better Python code (speed, robustness, etc...)
Improved Python code corresponding to PEP's - commits have links to sources
=> Some Python code improvements

src/core/Entry.cpp, tests/TestEntry.cpp
Fix #2304.
I added a couple of test cases for both Unix and Windows file paths.
=> Add support for opening file:// urls

src/cli/keepassxc-cli.1
Updating the man page `AUTHOR` section to credit all the KeePassXC contributors.
- ✅ Other (documentation/credits)
=> Updating man page authorship

.github/CONTRIBUTING.md, .github/ISSUE_TEMPLATE.md, .github/PULL_REQUEST_TEMPLATE.md
Removes HTML comments in favor of markdown "comments" of the form:
```[NOTE]: # ( ..... )```
This will help with non-web views that actually render HTML comments as plain text (Fasthub, GitKraken Glo, etc.)
Streamlined the PR template a little and updated the wording of the contributing document.
Avoiding doing school work :grin:
=> Update Github templates

src/gui/DatabaseWidget.cpp, src/gui/DatabaseWidget.h, src/gui/entry/EntryView.cpp, src/gui/entry/EntryView.h, src/gui/group/GroupView.cpp, src/gui/group/GroupView.h, tests/gui/TestGui.cpp
* Align entryview selection change signals with groupview
* Eliminate redundent and confusing signals/slots
* Correct group selection canceling search
Issue reported in #2499.
GUI tests were updated for …
=> Correct refactor issues with entry selection and search

src/core/Config.cpp, src/gui/ApplicationSettingsWidget.cpp, src/gui/ApplicationSettingsWidget.h, src/gui/DatabaseTabWidget.cpp, src/gui/DatabaseWidget.cpp, src/gui/DatabaseWidget.h, tests/gui/TestGui.cpp
* Standardize use of DatabaseWidget::save() function
* Close new database tabs that are "discarded"
* Fixes #2604, autoSaveOnExit setting not working due to poor handling of checkboxes
* Fixes #2604, autoSaveAfterEveryChange was not implemented after database refactoring
[TIP]:  # ( We expect new …
=> Fix crash when canceling save of new database

src/main.cpp
* Wayland theme is buggy yet enforced by default on Qt 5.11+ on Gnome desktop environment
* Resolves #2006
N/A
Pending: haven't tested, need …
=> Prevent use of wayland theme on Linux

README.md
Updating README after KeePassHTTP deprecation.
Documentation
=> Update README after KeePassHTTP deprecation.

src/keeshare/ShareObserver.cpp
Extended the error messages in ShareObserver for to provide more error information. Fixed a small issure where the error message was checked before writing.
Fixes error message part of #2657 
Code compiles ;)
=> Improve messages and fix issue in ShareObserver

src/keys/drivers/YubiKey.cpp
Fix #2643 and #2721.
I used `lsof` and `strace` as described in #2721.
=> fix(YubiKey): call `yk_release` on errors

docs/QUICKSTART.md
As title says, fixed a small typo in QUICKSTART.md.
I've read [CONTRIBUTING.md](https://github.com/keepassxreboot/keepassxc/blob/develop/.github/CONTRIBUTING.md) but it doesn't contain any guidance on updating the docs so please let me know if you would prefer me to do anything different now or in the future.
- ✅ My change requires a change to the documentation, and I have updated it accordingly.
=> Fix typo in QUICKSTART.md

src/gui/DatabaseWidget.cpp
/var/tmp/portage/app-admin/keepassxc-2.4.0/work/keepassxc-2.4.0/src/gui/DatabaseWidget.cpp: In member function ‘void DatabaseWidget::search(const QString&)’:
/var/tmp/portage/app-admin/keepassxc-2.4.0/work/keepassxc-2.4.0/src/gui/DatabaseWidget.cpp:1115:5: error: ‘m_shareLabel’ was not declared in this scope
m_shareLabel->setVisible(false);
^~~~~~~~~~~~
/var/tmp/portage/app-admin/keepassxc-2.4.0/work/keepassxc-2.4.0/src/gui/DatabaseWidget.cpp:1115:5: note: suggested alternative: ‘m_searchingLabel’
m_shareLabel->setVisible(false);
^~~~~~~~~~~~
m_searchingLabel
- ✅ Refactor (significant modification to …
=> src/gui/DatabaseWidget.cpp: Build fails without WITH_XC_KEESHARE

src/gui/masterkey/PasswordEditWidget.cpp
Checks if the password field is in edit mode prior to determining if the fields are empty. Further protection needs to be incorporated because the UI is not fully initialized which can lead to nullptr access issues such as this. There are no nullptr guards in public functions that may not be full initialized.
Fix #2834  …
=> Prevent crash when editing master key

src/sshagent/SSHAgent.cpp
* Don't remove keys on app exit that would not be removed due to database locking.
* Restores behavior from 2.3.4
* Fixes #2980 
Tested on Windows using Pageant …
=> Only remove keys on exit if they would remove on lock

src/gui/ApplicationSettingsWidget.cpp
Remove the non-functional apply button from the application settings. …
=> Remove apply button from application settings

src/cli/Add.cpp, src/cli/Clip.cpp, src/cli/Create.cpp, src/cli/Diceware.cpp, src/cli/Edit.cpp, src/cli/Estimate.cpp, src/cli/Extract.cpp, src/cli/Generate.cpp, src/cli/List.cpp, src/cli/Locate.cpp, src/cli/Merge.cpp, src/cli/Remove.cpp, src/cli/Show.cpp
* Prevents keepassxc-cli.exe -> keepassxc-cli show.exe
* Fixes #3032 …
=> Correct CLI help messages on Windows

src/gui/DialogyWidget.cpp, src/gui/entry/EditEntryWidget.cpp
* Remove specific action from EditEntryWidget
* Implement key handling at the lowest level
* Fix #3036
[NOTE]: # ( to be sent back to you for correction or will be rejected. …
=> Support Ctrl+Enter shortcut on all dialogs with QPushButtonBox

src/core/Translator.cpp, src/core/Translator.h
* Uses built-in facilities of Qt to traverse QLocale::uilanguages() to find a valid "most preferred" language
* Still respect user's choice in the application settings
* Fixes #3030 
Tested on Windows with …
=> Use QLocale for translation search instead of custom method

snapcraft.yaml
This fixes issue #3027 which is caused by a missing plug to allow the snap to query the locking status of the session. See discussion in PR #3028 for additional info.
Tested on Ubuntu 18.04. Manually locking …
=> Snap: fix session database locking

src/CMakeLists.txt, src/gui/DatabaseTabWidget.cpp, src/gui/macutils/AppKit.h, src/gui/macutils/AppKitImpl.h, src/gui/macutils/AppKitImpl.mm, src/gui/macutils/MacUtils.cpp, src/gui/macutils/MacUtils.h
Locks all databases when switching user in macOS.
Fixes #2642.
Tested manually with quick user switching. …
=> Lock database on switching user in macOS

src/gui/MainWindow.cpp, src/gui/MainWindow.h, tests/gui/TestGui.cpp
* Support double click on tray icon to always toggle window to/from tray
* Single click on tray icon will bring window to front if in background, otherwise window is toggled
* Fixes #2956
Tested on Windows, …
=> Robust processing of tray icon triggers

src/gui/DatabaseWidget.cpp, src/gui/EntryPreviewWidget.cpp, src/gui/EntryPreviewWidget.h
Let the OS handle how to open the url.
Changed the openUrl() function to use a QUrl object, which has the appropriate scheme set.
Fixes #2427
Fixes #2395 
Manually tested with ssh:// and https:// URLs on Linux  …
=> Fix opening url's with non-http schemes

src/browser/NativeMessagingBase.cpp, src/gui/entry/EntryAttachmentsWidget.cpp
* Fix native messaging to use user-specific common folder
* Open attachments in snap data folder
* Fixes #2283 
Tested on snap build in Ubuntu
[NOTE]: # …
=> Use Snap-Specific directories

docs/QUICKSTART.md
* unified the 2 guides (Quickstart & KeeShare) a bit
* use "international" mozilla-link
* removed wrong and/or superfluous newlines & spaces
* some other minor polish & cleanup
for example _highlighting_ is still **not** unified!
=> revised this resp. these two guides

src/gui/ApplicationSettingsWidget.cpp, src/gui/ApplicationSettingsWidgetGeneral.ui, src/gui/dbsettings/DatabaseSettingsDialog.cpp, src/keeshare/SettingsWidgetKeeShare.cpp, src/keeshare/SettingsWidgetKeeShare.ui, src/keeshare/ShareObserver.cpp
* Moved KeeShare Quiet Success message setting to the KeeShare portion of the application settings
* Removed an assert that caused the application to crash in debugging when a share file could not be found
* Corrected database settings security icon
[NOTE]: …
=> KeeShare settings fixes

CHANGELOG, src/gui/EntryPreviewWidget.cpp, src/gui/EntryPreviewWidget.h, src/gui/EntryPreviewWidget.ui
Fixes #1564. Please see the issue discussion for more details about the context. 
Changes in this PR:
- UI refactor on the _General_ tab
- Moved the _Notes_ section to the _General_ tab
- Merged the _Attributes_ and _Attachments_ tabs together into a new _Advanced_ tab
- Changed the panel title format …
=> Rework the Entry Preview panel

share/keepassxc.ini, src/core/Config.cpp, src/gui/ApplicationSettingsWidget.cpp, src/gui/ApplicationSettingsWidgetGeneral.ui, src/gui/DatabaseWidget.cpp
New Feature: Add a "Minimize on Open URL" option
=> Add MinimizeOnOpenURL feature

src/gui/DatabaseOpenWidget.cpp
Fixes #3033. 
- Manual test
[NOTE]: # ( Pull Requests that don't fulfill all [REQUIRED] …
=> Fix password visibility button state on database open

src/browser/BrowserService.cpp
Does not display the data migration prompt when Browser Integration is disabled.
Fixes #3327.
Manually. …
=> Prompt to migrate KeePassHTTP settings only if Browser Integration is enabled

src/cli/Add.cpp, src/cli/Add.h, src/cli/Clip.cpp, src/cli/Clip.h, src/cli/Command.cpp, src/cli/Create.cpp, src/cli/Create.h, src/cli/Diceware.cpp, src/cli/Diceware.h, src/cli/Edit.cpp, src/cli/Edit.h, src/cli/Estimate.cpp, src/cli/Estimate.h, src/cli/Extract.cpp, src/cli/Extract.h, src/cli/Generate.cpp, src/cli/Generate.h, src/cli/List.cpp, src/cli/List.h, src/cli/Locate.cpp, src/cli/Locate.h, src/cli/Merge.cpp, src/cli/Merge.h, src/cli/Remove.cpp, src/cli/Remove.h, src/cli/Show.cpp, src/cli/Show.h
- ✅ Minor cleanup
* empty destructors are replaced with default destructors
* a few loop variables made into const references to avoid copies
* add missing `override` spec for some `Command::execute` methods
Ran unit tests
=> A handful of cleanups in keepassxc-cli

src/cli/Utils.cpp
=> Fix leak in keepassxc-cli Clip command

README.md, docs/KEYBINDS.md, src/gui/EntryPreviewWidget.cpp, src/gui/MainWindow.cpp, src/gui/MainWindow.h, src/gui/MainWindow.ui, src/keys/drivers/YubiKeyStub.cpp
- Fix #3376 
Use Font::fixedFont() for password preview
- #3378 (temporarily)
Added a menu entry in the Help menu which opens [the KEYBINDS document](https://github.com/keepassxreboot/keepassxc/blob/develop/docs/KEYBINDS.md)
- #3360 partially
Added a mention of the CLI to the README.
Manual
[NOTE]: # ( to be sent …
=> Fix password preview font, add some documentation

README.md
✅ Documentation (non-code change)
=> Point readme to the new changelog

src/browser/BrowserOptionDialog.cpp
So the page will be showed in other languages.
[NOTE]: # ( …
=> Remove en-US/

CHANGELOG.md, src/cli/AddGroup.cpp, src/cli/AddGroup.h, src/cli/CMakeLists.txt, src/cli/Command.cpp, src/cli/Move.cpp, src/cli/Move.h, src/cli/RemoveGroup.cpp, src/cli/RemoveGroup.h, src/cli/keepassxc-cli.1, tests/TestCli.cpp, tests/TestCli.h
This PR adds group manipulation commands (mkdir, mv and rmdir).
See  https://github.com/keepassxreboot/keepassxc/issues/2703
unit tests + local testing. …
=> CLI: Group commands

src/gui/DatabaseOpenWidget.ui, src/gui/EditWidgetIcons.ui, src/gui/entry/EditEntryWidgetMain.ui
* Fix #3514 
- ✅ My code follows the code style of this …
=> Add missing tooltips to buttons

src/browser/BrowserOptionDialog.ui, src/browser/BrowserService.cpp
In certain situations a non-connected database leaked credentials to the extensions.
Fixes #3477 
Manually. Steps to reproduce before the fix:
1. Open a connected database.
2. Switch tab to non-open …
=> Fix getting credentials from non-connected database

share/linux/org.keepassxc.KeePassXC.desktop
=> Add danish translation

share/macosx/keepassxc.entitlements, src/cli/CMakeLists.txt, src/gui/macutils/AppKitImpl.mm
* Fix #3609 - Request screen reader permission by faking a 1px screenshot. Thanks to MacPass for this idea.
* Fix #3578 - Remove duplicate sandbox entitlement
* Fix #3270 - Use executable path reference for libquazip
[TIP]:  # ( We expect new code to be covered by unit tests and documented with doc …
=> Request screen reader permission for AutoType

COPYING
=> Update copyright year to 2019

src/gui/dbsettings/DatabaseSettingsWidgetStatistics.cpp
Fixes zxcvbn out-of-tree includes. Resolves #3658.
=> Fix zxcvbn include for out-of-tree compilation, resolves #3658

README.md, share/docs/man/keepassxc-cli.1, share/docs/man/keepassxc.1, src/CMakeLists.txt, src/cli/CMakeLists.txt
Last-minute change that adds a keepassxc man page and moves the keepassxc-cli man page to share/docs/man. The latter change was done to avoid having multiple places where we have man pages and to avoid mixing code and documentation. Man pages in other languages may be added to that location in the future.
[NOTE]: # ( Again, remove …
=> Add keepassxc man page and move cli man page to share folder

src/gui/AboutDialog.cpp, utils/transifex_translators.py
Add Patreon supporters and Translators to about dialog.
- …
=> Update About Dialog contributors and translators

src/gui/MainWindow.cpp, src/gui/MainWindow.h
* Fix #3670
* Obtain context focus lock when showing new context menus
Tested manually …
=> Additional fixes for entry context menu

INSTALL.md
Fix broken link "Building Environment on MacOS".
=> INSTALL.md: Fix broken link for MacOS

src/cli/Clip.cpp, src/cli/Import.cpp, src/cli/List.cpp, src/cli/Locate.cpp, src/core/IconDownloader.cpp, src/format/OpVaultReader.cpp, tests/TestCsvParser.cpp, tests/TestEntryModel.cpp, tests/TestGroup.cpp
Some cppcheck and clang-tidy fixies (and a bit from me)
By existing tests
- ✅ My change requires a change to the documentation, and I have updated it …
=> Fix some static analyser fixies

src/core/Tools.cpp, src/fdosecrets/objects/Service.cpp, src/fdosecrets/objects/SessionCipher.cpp, src/fdosecrets/objects/SessionCipher.h
A few fixes for the Secret Service Integration plugin, including the fix for #3667.
- Run unit tests
- Manually test the situation in #3667 doesn't happen again …
=> Secret Service Integration Fixes

src/gui/dbsettings/DatabaseSettingsWidgetStatistics.cpp, src/gui/dbsettings/DatabaseSettingsWidgetStatistics.h, src/gui/dbsettings/DatabaseSettingsWidgetStatistics.ui
* Fix #3766 - move database statistics processing into async task and only perform the calculation when the statistics tab is activated.
Tested with a static 10 second delay to simulate long calculations. …
=> Improve UX of database statistics page

src/core/FileWatcher.cpp
Self explanatory
- ✅ My code follows …
=> Perform file hash checks asynchronously

src/gui/widgets/ElidedLabel.cpp
Fixes https://github.com/keepassxreboot/keepassxc/issues/3905
* Manual testing
[NOTE]: …
=> HTML encode url in ElidedLabel

.github/ISSUE_TEMPLATE/release-preview-bug-report.md, docs/KEYBINDS.md, docs/QUICKSTART.md, src/fdosecrets/README.md
Fix some typos.
N/A
N/A
[NOTE]: # ( Pull Requests …
=> Fix typos in various .md files

INSTALL.md
The link was broken. I've changed it to link to a similar wiki page.
I've changed the wording, since it would be incorrect to claim that it is the "online version of this document"; and linking to the doc itself would seem a little pointless.
Anyway, there's a bigger issue here, which is that there is a lot of duplication between `INSTALL.md` and the `Building-KeePassXC` wiki page. …
=> INSTALL.md: fix broken wiki link

src/fdosecrets/objects/Collection.cpp, src/fdosecrets/widgets/DatabaseSettingsWidgetFdoSecrets.cpp
Fix #3861
When the exposed group was moved to the recycle bin, it is still incorrectly exposed to DBus. While there are some checks in place skipping entries/groups in the recycle bin, they are not thorough, thus causing the crash in #3861.
[TIP]:  # ( We expect new code to be covered by unit tests …
=> FdoSecrets: handle the exposed group being moved to recycle bin

src/browser/BrowserService.cpp
Removes an extra if condition that could cause all additional URL's not to return.
Fixes #4031.
Manually. …
=> Remove extra check for additional URLs

CMakeLists.txt
It appears that the FeatureSummary module is not included automatically on all 
Resolves #4024 
Resolves #3000
[NOTE]: # ( to be sent back to you for correction or will be …
=> Move FeatureSummary include to top of CMakeLists

release-tool
Don't use SHA-1 for code signing digest on Windows. Prefer SHA-256.
Tested on Windows with release-tool …
=> Use SHA256 Digest for Code Signing on Windows

src/autotype/AutoType.cpp
* Check that entry's group is not nullptr
* Fixes #3967
Tested manually
[NOTE]: # ( Pull …
=> Prevent crash if Auto-Type performed on new entry

src/autotype/AutoType.cpp
Backport of #4132.
* Check that entry's group is not nullptr
* Fixes #3967 …
=> Backport: Prevent crash if Auto-Type performed on new entry

src/core/Tools.cpp
* Due to the complexity of cmd:// type url's, avoid trying to parse them for validity once the initial scheme is entered.
* Fixes #4138
[NOTE]: # ( to be sent back to you for …
=> Don't mark cmd:// urls as invalid

README.md, src/browser/BrowserOptionDialog.cpp, src/browser/BrowserOptionDialog.ui, src/browser/BrowserSettings.cpp, src/browser/BrowserSettings.h, src/browser/HostInstaller.cpp, src/browser/HostInstaller.h
All paths used must be verified after the stable version of Edge is released. This PR is WIP until then.
https://microsoftedge.microsoft.com/addons/detail/pdffhmdngciaglkoonimfcmckehcpafo
Manually. …
=> Add integration with Edge browser (Chromium-based)

release-tool
`release-tool appimage` did not exit with an error if an intermediary build step failed. …
=> Exit with error code if AppImage creation fails midair

src/format/HtmlExporter.cpp
Fix closing tag typo:  
`</t>`  => `</th>`
=> Fix closing tag typo

README.md
It's a convention that the first text block after the title is the
general description of the project, so we don't need the explicit
section there.
=> Remove extraneous readme section

README.md
=> Adding release badge to README.

src/browser/BrowserOptionDialog.ui, src/cli/Export.cpp, src/cli/Import.cpp, src/fdosecrets/widgets/DatabaseSettingsWidgetFdoSecrets.cpp, src/fdosecrets/widgets/DatabaseSettingsWidgetFdoSecrets.ui, src/fdosecrets/widgets/SettingsWidgetFdoSecrets.ui, src/gui/ApplicationSettingsWidgetGeneral.ui, src/gui/EditWidgetIcons.ui, src/gui/PasswordGeneratorWidget.ui, src/gui/dbsettings/DatabaseSettingsWidgetBrowser.ui, src/gui/dbsettings/DatabaseSettingsWidgetGeneral.ui, src/gui/entry/EditEntryWidget.cpp, src/gui/entry/EditEntryWidgetAutoType.ui, src/gui/group/EditGroupWidgetMain.ui, src/gui/wizard/NewDatabaseWizardPage.ui, src/keeshare/group/EditGroupWidgetKeeShare.ui
Removes unnecessary &amp; from strings in settings widgets. These cause confusion and complicate translation. They are unnecessary as all dialogs allow efficient tabbing between elements.
Also add colons after several settings with input boxes and remove a hard stop. …
=> Cleanup UI files

src/fdosecrets/FdoSecretsPlugin.cpp, src/fdosecrets/FdoSecretsPlugin.h, src/fdosecrets/objects/Service.cpp, src/fdosecrets/widgets/SettingsWidgetFdoSecrets.cpp, src/fdosecrets/widgets/SettingsWidgetFdoSecrets.h, src/fdosecrets/widgets/SettingsWidgetFdoSecrets.ui
Check and show PID and executable for the existing secret service process. This should make it easier for users to debug if another service is running. See screenshots.
[TIP]:  # ( We expect new code to be covered by unit tests …
=> FdoSecrets: check and show PID and executable for existing secret service process

src/autotype/xcb/AutoTypeXCB.cpp, src/core/ScreenLockListenerWin.h, src/gui/EditWidgetIcons.cpp, src/gui/MainWindow.cpp, src/gui/MessageBox.cpp, tests/TestSymmetricCipher.cpp
Mostly style issues.
I used the following tools to find most of these:
- lgtm.com
- clang-tidy
- cpplint
- cppcheck
N/A
[NOTE]: # ( Please go …
=> Code Style: Fixes for minor issues found by static analysis

src/browser/BrowserService.cpp
When using Additional URL's from the same domain as entry URL, duplicate credentials are returned. An extra check is added that no duplicate entries will be returned to the browser extension.
Manually. See …
=> Do not add duplicate entries

src/gui/DatabaseWidget.cpp, src/gui/EditWidget.cpp, src/gui/MainWindow.cpp, src/gui/entry/EditEntryWidget.cpp, src/gui/entry/EditEntryWidget.h, src/sshagent/AgentSettingsWidget.cpp, src/sshagent/AgentSettingsWidget.ui, src/sshagent/SSHAgent.cpp, src/sshagent/SSHAgent.h
After refactors this was rather trivial. When integration is disabled all remove-on-lock keys are removed from the agent as a safety measure.
This PR includes a hefty cleanup of the SSHAgent singleton and configuration management.
Fixes #1196 and an …
=> SSH Agent: Allow toggling integration on and off without restart

src/gui/SearchWidget.cpp, src/gui/SearchWidget.h
* Reset clear timer when manipulating the entry view and opening/closing entries
* Only start the clear timer if there is an active search …
=> Fix clearing search field when using application

src/core/Bootstrap.cpp, src/core/FilePath.cpp
* System icons are no longer used eliminating the need to differentiate behavior for the snap package on Linux.
[NOTE]: # ( to be sent back to you for correction or will be …
=> Fix compile errors when building snap package

src/gui/SearchHelpWidget.ui, src/gui/SearchWidget.cpp, src/gui/widgets/PopupHelpWidget.cpp, src/gui/widgets/PopupHelpWidget.h
* Clean up parent alignment code
* Don't hide widget if it currently has focus
* Use Qt::Tool window type on macOS as well. This prevents the popup help from hiding to the background if the main window has focus.
* Fixes #2814
[TIP]:  # ( We expect new code to be covered by unit tests and documented …
=> Fix issues with PopupHelpWidget on Linux and macOS

src/browser/BrowserService.cpp, src/core/CustomData.cpp, src/core/CustomData.h, src/gui/dbsettings/DatabaseSettingsWidgetBrowser.cpp
Adds "Created" column with a timestamp to Browser Integration page at Database Settings.
Fixes #4340.
Manually.
[NOTE]: # ( Please go …
=> Add Created column to Browser Integration at Database Settings

src/browser/BrowserSettings.cpp, src/browser/BrowserSettings.h, src/core/PasswordGenerator.cpp, src/core/PasswordGenerator.h, src/gui/PasswordGeneratorWidget.cpp, src/gui/PasswordGeneratorWidget.ui, tests/TestPasswordGenerator.cpp, tests/TestPasswordGenerator.h
See issue #3271 for a motivation of this feature.
This patch adds an additional text input to the advanced view of the password
generator.  All characters of this input field (if not empty) will be added as
another group to the password generator.  The characters from the excluded field
have precedence over the characters from this new field, meaning any character
added to both fields will *not* appear in any generated password.  As the
characters from this new field will be added as their own group to the password
generator, checking the 'Pick characters from every group' checkbox will
force at least character to be chosen from the new input field.
The `PasswordGenerator` class has also been changed so that the `isValid` …
=> Allow defining additional characters for the password generator

src/gui/entry/EditEntryWidget.cpp
* Fixes #3940
[TIP]:  # ( We expect new code to be covered …
=> Set expiration time to Now when enabling entry expiration

src/crypto/kdf/Kdf.cpp
* Prevent using double memory when benchmarking Argon2 performance.
* Improve benchmark results by not overusing CPU and memory simultaneously. Parallel benchmarks were causing artificially strained calculations resulting in a lower than desired number of rounds.
Thanks to @Piraty for pointing this out!! …
=> Perform one KDF benchmark at a time

COPYING
=> Update copyright year to 2020

src/CMakeLists.txt
* Replace find_library with find_file. CMake likely changed behavior of find_library to exclude dll files.
* Fixes #4523 
Tested on Windows with mingw64 and mingw32. …
=> Fix install of libssl and libcrypto on Windows build

src/gui/MessageWidget.cpp, src/gui/MessageWidget.h, src/keeshare/group/EditGroupWidgetKeeShare.cpp
* Allows for persistent messages that can change text without disturbing the user interface
* Immediate improvement to KeeShare group edit window
[NOTE]: # ( to be sent back …
=> Ability to disable animation of message widget

src/browser/BrowserService.cpp
When converting KeePassHTTP settings to KeePassXC-Browser's settings, the old settings are put to the Recycle Bin instead of deleting it directly. It allows the user the keep both settings in the database at the same time, if wished so.
Fixes #4528.
[TIP]:  # ( We expect new code to be covered by …
=> Recycle KeePassHTTP settings

.github/ISSUE_TEMPLATE/bug-report.md, .github/ISSUE_TEMPLATE/feature-request.md, .github/ISSUE_TEMPLATE/release-preview-bug-report.md, .github/PULL_REQUEST_TEMPLATE.md
Made substantive updates to the issue and pull request templates. Removed unnecessary and often misused sections. 
I removed the checklist section from the pull request template because it really didn't mean anything to anyone. Our robust CI captures the vast majority of issues now and a checklist never stopped anyone from submitting a half-baked PR.
=> Update Issue and Pull Request templates

src/gui/entry/EditEntryWidgetMain.ui
Adds a placeholder text to the URL input field in the entry editor, for non-technical users who don't know what a URL is.
Fixes #3830 …
=> Set URL placeholder text to https://example.com

tests/gui/TestGui.cpp, tests/gui/TestGui.h
=> Make GUI tests more robust for CI

src/browser/BrowserShared.cpp
* Prefer hardcoded string, we never want this server name to change due to arbitrary reasons.
Tested windows, linux
=> Fix browser socket path for proxy and app

src/browser/BrowserService.cpp, src/browser/BrowserService.h, src/core/CustomData.cpp, src/core/CustomData.h, src/core/Merger.cpp, src/gui/dbsettings/DatabaseSettingsWidgetBrowser.cpp
When importing data from another database via merge, do not delete any old keys from the destination.
Fixes #4077.
Fixes #4684.
=> Fix merging browser keys

src/core/Config.cpp, src/core/Config.h, src/gui/MainWindow.cpp, src/gui/MainWindow.ui
Add button to hide pre-release warning for this release.
=> Add button to hide pre-release warning for this release.

src/browser/BrowserSettings.cpp, src/browser/BrowserSettings.h, src/browser/BrowserSettingsWidget.cpp, src/browser/BrowserSettingsWidget.h, src/browser/BrowserSettingsWidget.ui, src/browser/BrowserShared.h, src/browser/NativeMessageInstaller.cpp, src/core/Config.cpp, src/core/Config.h
Adds a custom browser option for Browser Integration. The manifest.json base can be choosed between Firefox or Chromium based browser.
Windows is not supported.
Fixes #1594.
Manually.
[NOTE]: # ( …
=> Add custom browser option

src/gui/DatabaseWidget.cpp, src/gui/entry/EditEntryWidget.cpp, src/gui/entry/EditEntryWidget.h, src/sshagent/KeeAgentSettings.cpp, src/sshagent/KeeAgentSettings.h
Fixes #4594
Fixes #4020 
Manual clicking in the UI. Seems to work as intended.
=> SSH Agent: Reset settings when KeeAgent.settings is removed

src/CMakeLists.txt
Small bugfix. Looks like a copy paste error for the error handling 5 lines above.
Simply review should be enough.
=> Check correct CMake flag.

src/browser/BrowserService.cpp
=> Remove connection to non-existent signal

src/gui/reports/ReportsWidgetHealthcheck.cpp, src/gui/reports/ReportsWidgetHealthcheck.h, src/gui/reports/ReportsWidgetHibp.cpp, src/gui/reports/ReportsWidgetHibp.h
=> Fix activating entries in database reports when sorted

src/browser/BrowserService.cpp
=> Browser: Check for expired entry prior to custom data

src/gui/MainWindow.ui
45848c3f611b88015c8227be197baac07a284b3d is the first bad commit
Looks like failed conflict resolution. This is between 2.5.4 and 2.6.0 so it has not slipped to a final release yet.
Manual shortcut testing on Linux.
=> SSH Agent: Fix regression in context menu hotkeys

src/core/Config.cpp, src/core/Config.h, src/core/DatabaseIcons.cpp, src/core/DatabaseIcons.h, src/core/Global.h, src/core/Metadata.cpp, src/gui/Application.cpp, src/gui/Application.h, src/gui/ApplicationSettingsWidget.cpp, src/gui/ApplicationSettingsWidget.h, src/gui/ApplicationSettingsWidgetGeneral.ui, src/gui/EntryPreviewWidget.cpp, src/gui/MainWindow.cpp, src/gui/MainWindow.h, src/gui/MainWindow.ui, src/gui/SearchWidget.ui, src/main.cpp
**Introduce View Menu**
* Move user interface settings from the settings widget into the view menu.
* Add auto-restart prompt to make theme changes easy
**Introduce Compact Mode**
* Added to the new view menu, show entry/group icons at 16px and reduce toolbar icons to 22px. 
* Fix search widget being too large vertically (removed padding)
Tested on all three platforms …
=> Introduce View Menu and Compact Mode

share/windows/wix-template.xml, src/gui/osutils/winutils/WinUtils.cpp
Previous implementation broke auto-start after settings were changed (Press OK in settings) due to backwards slashes in the registry.
=> Fix auto-start settings on Windows

src/gui/csvImport/CsvImportWidget.cpp, src/gui/csvImport/CsvImportWidget.h, src/gui/csvImport/CsvImportWidget.ui
The original layout of CSV Import broke when the window was resized.
ORIGINAL:
NEW:
=> Fix layout of CSV Import Widget

src/gui/ApplicationSettingsWidget.cpp, src/gui/MainWindow.cpp
* Fixes #4959
* Ask to restart when changing languages in application settings.
=> Improve restart requests

src/gui/DatabaseWidget.cpp
=> Prevent crash if focus widget gets deleted during saving

src/core/PasswordHealth.cpp
=> Skip referenced passwords in Health check report

src/gui/PasswordEdit.cpp
=> PasswordEdit use CTRL modifier on all platforms

src/core/Translator.cpp
=> Add Qt translation dir for RPM packaging

src/core/ScreenLockListenerDBus.cpp
=> Add support for the Xfce screensaver

docs/man/keepassxc-cli.1.adoc, docs/man/keepassxc.1.adoc, docs/man/section-copyright.adoc, docs/man/section-notes.adoc, docs/man/section-reporting-bugs.adoc
Make the following changes:
1. Add reporting bugs section to CLI man page.
2. Add notes section (links to resources related to the project).
3. Add copyright section.
4. Change author section to only info of original author, because it's clear from copyright section that these man pages are maintained by the KeePassXC Team.
5. Add copyright notice as comment.
6. Change the order of sections based on [man-pages(7)](https://man7.org/linux/man-pages/man7/man-pages.7.html). …
=> Improve man pages with useful links and copyright

src/gui/ApplicationSettingsWidget.cpp
=> Fix removing open databases setting

src/browser/BrowserAction.cpp, src/browser/BrowserAction.h, src/browser/BrowserService.cpp, src/browser/BrowserService.h
Add support for a new command for retrieving the current TOTP value.
Manually using https://github.com/keepassxreboot/keepassxc-browser/pull/961.
=> Add command for retrieving the current TOTP

src/gui/styles/base/basestyle.qss, src/gui/styles/dark/darkstyle.qss, src/gui/styles/light/lightstyle.qss
Use the proper hover color when an icon is checked.
=> Improve button hover effect for checked buttons

docs/styles/dark.css, docs/topics/KeyboardShortcuts.adoc
Fixes #4408
Sorry that it took so long to update the PR
=> Add note for macOS Keyboard shortcuts

src/format/HtmlExporter.cpp
The previous version left a lot of white space to the right of the table, meaning that more pages needed to be printed for a paper backup. The table has been reorganized. HTML Backup for the demo.kdbx database is now down from 6 to 3 pages.
Before:
After:
Tested manually with demo.kdbx and my personal database.
- …
=> HTML Export: Don't waste horizontal space

src/gui/DatabaseTabWidget.cpp
* Fixes #4069 and closes #5002
=> Fix opening opvault on macos

src/gui/PasswordGeneratorWidget.cpp
=> Use selected settings in password generator on load

src/core/Tools.cpp, tests/TestBrowser.cpp
=> Don't mark URL references as invalid URL

src/gui/entry/EntryView.cpp
=> Restore natural sort on application load

src/gui/EntryPreviewWidget.cpp
=> Enforce fixed password font in preview widget

src/browser/BrowserShared.cpp
=> Add username to browser named pipe on Windows

docs/topics/ImportExport.adoc
Add a section to the "Exporting Databases" chapter of the user guide that briefly explains how to create a paper backup using HTML export. Points to the upcoming blog article for details.
WIP because the exact URL of the blog article is still missing.
n/a
n/a
=> Describe HTML export/paper backups in the user manual

src/gui/DatabaseWidget.cpp
* Fixes #5093
Tested using artificially short search clear timeout and an empty group.
=> Force set entry preview after search ends

src/browser/BrowserService.cpp
=> Use strict check for std::sort to prevent recursion

docs/topics/BrowserPlugin.adoc
Add documentation for system administrators to setup support for KeePassXC extension in a managed Microsoft Edge.
Addresses #5253 
=> Document support for managed Microsoft Edge

src/gui/PasswordGeneratorWidget.cpp
=> Properly save Password Generator settings

src/gui/MainWindow.cpp
* Fix #5794 - Don't show "Download All Favicons" in group menu
* Don't show offline documentation links if built documentation is disabled
=> Hide actions when features are disabled

CODE-OF-CONDUCT.md
=> CODE-OF-CONDUCT.md: fix typo

src/gui/entry/EditEntryWidget.cpp, src/gui/styles/base/BaseStyle.cpp, src/gui/styles/base/classicstyle.qss
=> Remove offset on username field in classic theme

src/gui/Clipboard.cpp
Fix #2358 
Tested on Windows 10
=>  Prevent clipboard history and cloud sync on Windows

src/core/Entry.cpp, src/core/Entry.h, src/core/Group.cpp, src/core/Group.h, src/gui/group/GroupModel.cpp, tests/gui/TestGui.cpp
* Fix #5809
Added test case to check history is copied
=> Copy history when drag/drop entries and groups

src/crypto/Crypto.cpp, src/gui/AboutDialog.cpp
=> Patron Names and Debug Info

snap/snapcraft.yaml
* Fix #5877, greatly improve startup time of snap package
=> Set Snap compression to lzo

src/gui/MainWindow.cpp
* Fix #3944
- ✅ Breaking change (causes existing functionality to change)
=> Ensure app exiting flag is set on logoff/shutdown

share/windows/wix-template.xml
Allows setting properties when configuring unattended installs with MSI. For example:
```
msiexec /qn /i KeePassXC-2.7.0-Win64.msi AUTOSTARTPROGRAM=0 LAUNCHAPPONEXIT=0
```
Thanks to @BDaddyG for pointing this out!
Tested using new msi package.
=> Allow setting MSI properties in unattended install

src/gui/MainWindow.ui
Open to any feedback. I was just experimenting, read through the QT docs and this worked for me locally.
- ✅ Bug fix (non-breaking change that fixes an issue) issue 6130
=> Update MainWindow minimum size to enable smaller verticle space

share/windows/wix-template.xml, src/core/PasswordGenerator.cpp, src/gui/MainWindow.ui, src/gui/PasswordGeneratorWidget.ui, tests/TestPasswordGenerator.cpp
* Allow setting MSI properties in unattended install
* Update MainWindow minimum size to enable smaller verticle space (#6149)
* Exclude additional lookalike characters (6G8B)
=> Handful of backports for 2.6.5

src/keys/drivers/YubiKeyStub.cpp
Build with stub YubiKey was borked with the Botan merge.
=> Update YubiKey stub implementation for Botan

.github/pull.yml
see: https://github.com/wei/pull#introduction
=> added pull.yml to automatically update forks

docs/topics/DatabaseOperations.adoc
How to search for an attribute name or value is not clear, either in the user interface or the user manual. The example added to the search queries table illustrates the syntax (attr:[searchstring]) and clarifies search behavior (both attr name and values are searched).
=> Docs: example for how to search using attributes

src/autotype/AutoType.cpp
=> Auto-Type: Increase max inter-type delay to 500 ms

src/gui/reports/ReportsWidgetHealthcheck.cpp, src/gui/reports/ReportsWidgetHibp.cpp
Addresses issue #5678
Don't know how to screenshot with the cursor appearing
Manual testing
=> Allow resizing of reports table columns

src/autotype/AutoTypeSelectDialog.cpp
* Fix #3882
Also add nullptr checks for extra safety.
=> Auto-Type: Resolve username/password when copying to clipboard

src/core/Database.cpp
=> Fix unreachable setting of file permissions

src/gui/reports/ReportsWidgetHealthcheck.cpp, src/gui/reports/ReportsWidgetHealthcheck.ui
Addresses Issue #5032. 
Manual testing
=> Add a checkbox to health report allowing to exclude expired entries

src/core/Database.cpp
* Fix #6028
* This feature will only be available on Qt 5.10 or newer deployments
=> Retain file creation time when saving database

src/gui/SearchWidget.cpp
* Fixes #6600 - error exists only on master branch due to poor cherrypick merge
Tested on Linux and macOS where it was failing before.
=> Fix focusing search using Ctrl + F

src/gui/TotpSetupDialog.cpp
=> Trim TOTP key input of whitespace prior to processing

tests/TestDatabase.cpp
=> Improve testdatabase performance

share/linux/org.keepassxc.KeePassXC.desktop.in
Keyword taken from Github topics
Add keywords as specified here: https://webcache.googleusercontent.com/search?q=cache:https://specifications.freedesktop.org/desktop-entry-spec/desktop-entry-spec-latest.html
These are also used by Flathub, KDE Discover and Gnome Software
As an example, check the Ghidra .desktop file and Flathub page: …
=> Add keywords to .desktop file
